import { Advantage } from '../models/advantage.model';

// â”€â”€â”€ Vorteile (Advantages) â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
// Source: DSA 5 Regelwerk (pages 163â€“170) + noted expansion books
// Parameterized advantages (Begabung, Herausragender Sinn, etc.) use a base entry.
// Specific instances use naming: {baseName}_{qualifier} (e.g. begabung_singen).
// Cost is per level for leveled advantages (lvl/maxLvl).
export const ADVANTAGE: Advantage[] = [
  // â”€â”€ Regelwerk S. 163 â”€â”€
  {
    name: 'adel',
    label: 'Adel I-III',
    cost: 5,
    lvl: 1,
    maxLvl: 3,
    prerequisite: [],
    sources: [{ book: 'Regelwerk', page: 163 }],
    url: 'https://dsa.ulisses-regelwiki.de/vorteil.html?vorteil=Adel+I-III',
  },
  {
    name: 'altersresistenz',
    label: 'Altersresistenz (*)',
    cost: 5,
    prerequisite: [{ name: 'schnelleAlterung', required: false }],
    sources: [{ book: 'Regelwerk', page: 163 }],
    url: 'https://dsa.ulisses-regelwiki.de/vorteil.html?vorteil=Altersresistenz+%28%2A%29',
  },
  {
    name: 'angenehmerGeruch',
    label: 'Angenehmer Geruch',
    cost: 6,
    prerequisite: [],
    sources: [{ book: 'Regelwerk', page: 163 }],
    url: 'https://dsa.ulisses-regelwiki.de/vorteil.html?vorteil=Angenehmer+Geruch',
  },
  // Begabung: cost varies by skill category A/B/C/D = 6/12/18/24 AP
  // Specific instances: begabung_singen, begabung_klettern, etc.
  {
    name: 'begabung',
    label: 'Begabung',
    cost: 6,
    prerequisite: [{ name: 'unfahig', required: false }],
    sources: [{ book: 'Regelwerk', page: 163 }],
    url: 'https://dsa.ulisses-regelwiki.de/vorteil.html?vorteil=Begabung',
  },
  {
    name: 'beidhandig',
    label: 'Beidhändig',
    cost: 15,
    prerequisite: [],
    sources: [{ book: 'Regelwerk', page: 164 }],
    url: 'https://dsa.ulisses-regelwiki.de/vorteil.html?vorteil=Beidh%C3%A4ndig',
  },
  // â”€â”€ Regelwerk S. 164 â”€â”€
  {
    name: 'dunkelsicht',
    label: 'Dunkelsicht I-II (*)',
    cost: 10,
    lvl: 1,
    maxLvl: 2,
    prerequisite: [{ name: 'nachtblind', required: false }],
    sources: [{ book: 'Regelwerk', page: 164 }],
    url: 'https://dsa.ulisses-regelwiki.de/vorteil.html?vorteil=Dunkelsicht+I-II+%28%2A%29',
  },
  {
    name: 'eisenaffineAura',
    label: 'Eisenaffine Aura',
    cost: 15,
    prerequisite: [{ name: 'zauberer', required: true }],
    sources: [{ book: 'Regelwerk', page: 164 }],
    url: 'https://dsa.ulisses-regelwiki.de/vorteil.html?vorteil=Eisenaffine+Aura',
  },
  {
    name: 'entfernungssinn',
    label: 'Entfernungssinn',
    cost: 10,
    prerequisite: [
      { name: 'blind', required: false },
      { name: 'eingeschrankterSinn_sicht', required: false },
      { name: 'farbenblind', required: false },
      { name: 'verstummelt_einaugig', required: false },
    ],
    sources: [{ book: 'Regelwerk', page: 164 }],
    url: 'https://dsa.ulisses-regelwiki.de/vorteil.html?vorteil=Entfernungssinn',
  },
  // â”€â”€ Regelwerk S. 165 â”€â”€
  {
    name: 'flink',
    label: 'Flink',
    cost: 8,
    prerequisite: [
      { name: 'behabig', required: false },
      { name: 'fettleibig', required: false },
      { name: 'verstummelt_einbeinig', required: false },
    ],
    sources: [{ book: 'Regelwerk', page: 165 }],
    url: 'https://dsa.ulisses-regelwiki.de/vorteil.html?vorteil=Flink',
  },
  {
    name: 'geweihter',
    label: 'Geweihter',
    cost: 25,
    prerequisite: [],
    sources: [{ book: 'Regelwerk', page: 165 }],
    url: 'https://dsa.ulisses-regelwiki.de/vorteil.html?vorteil=Geweihter',
  },
  {
    name: 'giftresistenz',
    label: 'Giftresistenz I-II',
    cost: 10,
    lvl: 1,
    maxLvl: 2,
    prerequisite: [{ name: 'giftanfallig', required: false }],
    sources: [{ book: 'Regelwerk', page: 165 }],
    url: 'https://dsa.ulisses-regelwiki.de/vorteil.html?vorteil=Giftresistenz+I-II',
  },
  {
    name: 'gluck',
    label: 'Glück I-III',
    cost: 30,
    lvl: 1,
    maxLvl: 3,
    prerequisite: [{ name: 'pech', required: false }],
    sources: [{ book: 'Regelwerk', page: 165 }],
    url: 'https://dsa.ulisses-regelwiki.de/vorteil.html?vorteil=Gl%C3%BCck+I-III',
  },
  {
    name: 'gutaussehend',
    label: 'Gutaussehend I-II',
    cost: 20,
    lvl: 1,
    maxLvl: 2,
    prerequisite: [{ name: 'hasslich', required: false }],
    sources: [{ book: 'Regelwerk', page: 165 }],
    url: 'https://dsa.ulisses-regelwiki.de/vorteil.html?vorteil=Gutaussehend+I-II',
  },
  // â”€â”€ Regelwerk S. 166 â”€â”€
  // Herausragender Sinn: Sicht/Gehör=12, Geruch&Geschmack=6, Tastsinn=2
  // Instances: herausragenderSinn_sicht, herausragenderSinn_gehor, etc.
  {
    name: 'herausragenderSinn',
    label: 'Herausragender Sinn',
    cost: 12,
    prerequisite: [
      { name: 'eingeschrankterSinn', required: false },
      { name: 'blind', required: false },
      { name: 'taub', required: false },
    ],
    sources: [{ book: 'Regelwerk', page: 166 }],
    url: 'https://dsa.ulisses-regelwiki.de/vorteil.html?vorteil=Herausragender+Sinn',
  },
  // Herausragende Fertigkeit: A/B/C/D = 2/4/6/8 AP, max 4 talents
  {
    name: 'herausragendeFertigkeit',
    label: 'Herausragende Fertigkeit',
    cost: 2,
    prerequisite: [{ name: 'unfahig', required: false }],
    sources: [{ book: 'Regelwerk', page: 166 }],
    url: 'https://dsa.ulisses-regelwiki.de/vorteil.html?vorteil=Herausragende+Fertigkeit',
  },
  // Herausragende Kampftechnik: B/C/D = 8/12/16 AP, max 2
  {
    name: 'herausragendeKampftechnik',
    label: 'Herausragende Kampftechnik',
    cost: 8,
    prerequisite: [],
    sources: [{ book: 'Regelwerk', page: 166 }],
    url: 'https://dsa.ulisses-regelwiki.de/vorteil.html?vorteil=Herausragende+Kampftechnik',
  },
  {
    name: 'hitzeresistenz',
    label: 'Hitzeresistenz',
    cost: 5,
    prerequisite: [{ name: 'hitzeempfindlich', required: false }],
    sources: [{ book: 'Regelwerk', page: 166 }],
    url: 'https://dsa.ulisses-regelwiki.de/vorteil.html?vorteil=Hitzeresistenz',
  },
  {
    name: 'hoheAstralkraft',
    label: 'Hohe Astralkraft I-VII',
    cost: 6,
    lvl: 1,
    maxLvl: 7,
    prerequisite: [
      { name: 'zauberer', required: true },
      { name: 'niedrigeAstralkraft', required: false },
    ],
    sources: [{ book: 'Regelwerk', page: 166 }],
    url: 'https://dsa.ulisses-regelwiki.de/vorteil.html?vorteil=Hohe+Astralkraft+I-VII',
  },
  {
    name: 'hoheKarmalkraft',
    label: 'Hohe Karmalkraft I-VII',
    cost: 6,
    lvl: 1,
    maxLvl: 7,
    prerequisite: [
      { name: 'geweihter', required: true },
      { name: 'niedrigeKarmalkraft', required: false },
    ],
    sources: [{ book: 'Regelwerk', page: 166 }],
    url: 'https://dsa.ulisses-regelwiki.de/vorteil.html?vorteil=Hohe+Karmalkraft+I-VII',
  },
  {
    name: 'hoheLebenskraft',
    label: 'Hohe Lebenskraft I-VII',
    cost: 6,
    lvl: 1,
    maxLvl: 7,
    prerequisite: [{ name: 'niedrigeLebenskraft', required: false }],
    sources: [{ book: 'Regelwerk', page: 166 }],
    url: 'https://dsa.ulisses-regelwiki.de/vorteil.html?vorteil=Hohe+Lebenskraft+I-VII',
  },
  {
    name: 'hoheSeelenkraft',
    label: 'Hohe Seelenkraft',
    cost: 25,
    prerequisite: [{ name: 'niedrigeSeelenkraft', required: false }],
    sources: [{ book: 'Regelwerk', page: 166 }],
    url: 'https://dsa.ulisses-regelwiki.de/vorteil.html?vorteil=Hohe+Seelenkraft',
  },
  {
    name: 'hoheZahigkeit',
    label: 'Hohe Zähigkeit',
    cost: 25,
    prerequisite: [{ name: 'niedrigeZahigkeit', required: false }],
    sources: [{ book: 'Regelwerk', page: 167 }],
    url: 'https://dsa.ulisses-regelwiki.de/vorteil.html?vorteil=Hohe+Z%C3%A4higkeit',
  },
  // â”€â”€ Regelwerk S. 167 â”€â”€
  // Immunität gegen (Gift): AP = halbe Giftstufe (variable)
  {
    name: 'immunitatGift',
    label: 'Immunität gegen (Gift)',
    cost: 5,
    prerequisite: [],
    sources: [{ book: 'Regelwerk', page: 167 }],
    url: 'https://dsa.ulisses-regelwiki.de/vorteil.html?vorteil=Immunit%C3%A4t+gegen+(Gift)',
  },
  // Immunität gegen (Krankheit): AP = halbe Krankheitsstufe (variable)
  {
    name: 'immunitatKrankheit',
    label: 'Immunität gegen (Krankheit)',
    cost: 5,
    prerequisite: [],
    sources: [{ book: 'Regelwerk', page: 167 }],
    url: 'https://dsa.ulisses-regelwiki.de/vorteil.html?vorteil=Immunit%C3%A4t+gegen+(Krankheit)',
  },
  {
    name: 'kalteresistenz',
    label: 'Kälteresistenz',
    cost: 5,
    prerequisite: [{ name: 'kalteempfindlich', required: false }],
    sources: [{ book: 'Regelwerk', page: 167 }],
    url: 'https://dsa.ulisses-regelwiki.de/vorteil.html?vorteil=K%C3%A4lteresistenz',
  },
  {
    name: 'krankheitsresistenz',
    label: 'Krankheitsresistenz I-II',
    cost: 10,
    lvl: 1,
    maxLvl: 2,
    prerequisite: [{ name: 'krankheitsanfallig', required: false }],
    sources: [{ book: 'Regelwerk', page: 167 }],
    url: 'https://dsa.ulisses-regelwiki.de/vorteil.html?vorteil=Krankheitsresistenz+I-II',
  },
  // â”€â”€ Regelwerk S. 167â€“168 â”€â”€
  {
    name: 'nichtschlafer',
    label: 'Nichtschläfer (*)',
    cost: 8,
    prerequisite: [],
    sources: [{ book: 'Regelwerk', page: 167 }],
    url: 'https://dsa.ulisses-regelwiki.de/vorteil.html?vorteil=Nichtschl%C3%A4fer+%28%2A%29',
  },
  {
    name: 'reich',
    label: 'Reich I-X',
    cost: 1,
    lvl: 1,
    maxLvl: 10,
    prerequisite: [{ name: 'arm', required: false }],
    sources: [{ book: 'Regelwerk', page: 168 }],
    url: 'https://dsa.ulisses-regelwiki.de/vorteil.html?vorteil=Reich+I-X',
  },
  {
    name: 'richtungssinn',
    label: 'Richtungssinn',
    cost: 10,
    prerequisite: [],
    sources: [{ book: 'Regelwerk', page: 168 }],
    url: 'https://dsa.ulisses-regelwiki.de/vorteil.html?vorteil=Richtungssinn',
  },
  {
    name: 'schlangenmensch',
    label: 'Schlangenmensch',
    cost: 6,
    prerequisite: [],
    sources: [{ book: 'Regelwerk', page: 168 }],
    url: 'https://dsa.ulisses-regelwiki.de/vorteil.html?vorteil=Schlangenmensch',
  },
  {
    name: 'schwerZuVerzaubern',
    label: 'Schwer zu verzaubern (*)',
    cost: 15,
    prerequisite: [{ name: 'zauberanfallig', required: false }],
    sources: [{ book: 'Regelwerk', page: 168 }],
    url: 'https://dsa.ulisses-regelwiki.de/vorteil.html?vorteil=Schwer+zu+verzaubern+%28%2A%29',
  },
  {
    name: 'sozialeAnpassungsfahigkeit',
    label: 'Soziale Anpassungsfähigkeit',
    cost: 10,
    prerequisite: [{ name: 'unfrei', required: false }],
    sources: [{ book: 'Regelwerk', page: 168 }],
    url: 'https://dsa.ulisses-regelwiki.de/vorteil.html?vorteil=Soziale+Anpassungsf%C3%A4higkeit',
  },
  // â”€â”€ Regelwerk S. 169 â”€â”€
  {
    name: 'verbesserteRegenerationAsp',
    label: 'Verbesserte Regeneration (Astralenergie) I-III',
    cost: 10,
    lvl: 1,
    maxLvl: 3,
    prerequisite: [
      { name: 'zauberer', required: true },
      { name: 'schlechteRegenerationAsp', required: false },
    ],
    sources: [{ book: 'Regelwerk', page: 169 }],
    url: 'https://dsa.ulisses-regelwiki.de/vorteil.html?vorteil=Verbesserte+Regeneration+(Astralenergie)+I-III',
  },
  {
    name: 'verbesserteRegenerationKap',
    label: 'Verbesserte Regeneration (Karmaenergie) I-III',
    cost: 10,
    lvl: 1,
    maxLvl: 3,
    prerequisite: [
      { name: 'geweihter', required: true },
      { name: 'schlechteRegenerationKap', required: false },
    ],
    sources: [{ book: 'Regelwerk', page: 169 }],
    url: 'https://dsa.ulisses-regelwiki.de/vorteil.html?vorteil=Verbesserte+Regeneration+(Karmaenergie)+I-III',
  },
  {
    name: 'verbesserteRegenerationLep',
    label: 'Verbesserte Regeneration (Lebensenergie) I-III',
    cost: 10,
    lvl: 1,
    maxLvl: 3,
    prerequisite: [{ name: 'schlechteRegenerationLep', required: false }],
    sources: [{ book: 'Regelwerk', page: 169 }],
    url: 'https://dsa.ulisses-regelwiki.de/vorteil.html?vorteil=Verbesserte+Regeneration+(Lebensenergie)+I-III',
  },
  // Waffenbegabung: B/C/D = 5/10/15 AP
  {
    name: 'waffenbegabung',
    label: 'Waffenbegabung',
    cost: 5,
    prerequisite: [],
    sources: [{ book: 'Regelwerk', page: 169 }],
    url: 'https://dsa.ulisses-regelwiki.de/vorteil.html?vorteil=Waffenbegabung',
  },
  {
    name: 'zaherHund',
    label: 'Zäher Hund',
    cost: 20,
    prerequisite: [{ name: 'zerbrechlich', required: false }],
    sources: [{ book: 'Regelwerk', page: 169 }],
    url: 'https://dsa.ulisses-regelwiki.de/vorteil.html?vorteil=Z%C3%A4her+Hund',
  },
  {
    name: 'zauberer',
    label: 'Zauberer',
    cost: 25,
    prerequisite: [],
    sources: [{ book: 'Regelwerk', page: 169 }],
    url: 'https://dsa.ulisses-regelwiki.de/vorteil.html?vorteil=Zauberer',
  },
  {
    name: 'zeitgefuhl',
    label: 'Zeitgefühl',
    cost: 2,
    prerequisite: [],
    sources: [{ book: 'Regelwerk', page: 169 }],
    url: 'https://dsa.ulisses-regelwiki.de/vorteil.html?vorteil=Zeitgef%C3%BChl',
  },
  {
    name: 'zweistimmigerGesang',
    label: 'Zweistimmiger Gesang (*)',
    cost: 5,
    prerequisite: [],
    sources: [{ book: 'Regelwerk', page: 170 }],
    url: 'https://dsa.ulisses-regelwiki.de/vorteil.html?vorteil=Zweistimmiger+Gesang+%28%2A%29',
  },
  // â”€â”€ Aventurisches Kompendium â”€â”€
  {
    name: 'eisern',
    label: 'Eisern',
    cost: 5,
    prerequisite: [],
    sources: [{ book: 'Aventurisches Kompendium', page: 128 }],
    url: 'https://dsa.ulisses-regelwiki.de/vorteil.html?vorteil=Eisern',
  },
  {
    name: 'hartImNehmen',
    label: 'Hart im Nehmen',
    cost: 3,
    prerequisite: [],
    sources: [{ book: 'Aventurisches Kompendium', page: 129 }],
    url: 'https://dsa.ulisses-regelwiki.de/vorteil.html?vorteil=Hart+im+Nehmen',
  },
  // â”€â”€ Regelwerk S. 169â€“170 â”€â”€
  {
    name: 'wohlklang',
    label: 'Wohlklang',
    cost: 5,
    prerequisite: [],
    sources: [{ book: 'Regelwerk', page: 169 }],
    url: 'https://dsa.ulisses-regelwiki.de/vorteil.html?vorteil=Wohlklang',
  },
  {
    name: 'zwergennase',
    label: 'Zwergennase',
    cost: 8,
    prerequisite: [],
    sources: [{ book: 'Regelwerk', page: 170 }],
    url: 'https://dsa.ulisses-regelwiki.de/vorteil.html?vorteil=Zwergennase',
  },
  // â”€â”€ Spezies-Erweiterungen â”€â”€
  // Biss I-III: I/II/III: 5/10/15 AP (+ Größenmodifikator)
  {
    name: 'biss',
    label: 'Biss I-III (*)',
    cost: 5,
    lvl: 1,
    maxLvl: 3,
    prerequisite: [],
    sources: [{ book: 'Achaz â€“ Schuppenkleid & Lange Zungen S. 28 / Orks â€“ Hauer & Schwarzer Pelz', page: 30 }],
    url: 'https://dsa.ulisses-regelwiki.de/vorteil.html?vorteil=biss+i-iii+(*)',
  },
  // Natürliche Waffe: parameterized (Biss, Schwanz) 5 AP each
  {
    name: 'naturlicheWaffe',
    label: 'Natürliche Waffe (*)',
    cost: 5,
    prerequisite: [],
    sources: [{ book: 'Achaz â€“ Schuppenkleid & Lange Zungen', page: 28 }],
    url: 'https://dsa.ulisses-regelwiki.de/vorteil.html?vorteil=Nat%C3%BCrliche+Waffe+(Biss)+(*)',
  },
  // Natürlicher Rüstungsschutz I-II: 20 AP/Stufe
  {
    name: 'naturlicherRustungsschutz',
    label: 'Natürlicher Rüstungsschutz I-II (*)',
    cost: 20,
    lvl: 1,
    maxLvl: 2,
    prerequisite: [],
    sources: [{ book: 'Achaz â€“ Schuppenkleid & Lange Zungen S. 29 / Orks â€“ Hauer & Schwarzer Pelz', page: 30 }],
    url: 'https://dsa.ulisses-regelwiki.de/vorteil.html?vorteil=Nat%C3%BCrlicher+R%C3%BCstungsschutz+I-II+(*)',
  },
  // Zusätzliche Gliedmaßen (Schwanz): 5 AP
  {
    name: 'zusatzlicheGliedmasse',
    label: 'Zusätzliche Gliedmaßen (*)',
    cost: 5,
    prerequisite: [],
    sources: [{ book: 'Achaz â€“ Schuppenkleid & Lange Zungen', page: 29 }],
    url: 'https://dsa.ulisses-regelwiki.de/vorteil.html?vorteil=Zus%C3%A4tzliche+Gliedma%C3%9Fen+(Schwanz)+(*)',
  },
  {
    name: 'greifschwanz',
    label: 'Greifschwanz (*)',
    cost: 8,
    prerequisite: [],
    sources: [{ book: 'Achaz â€“ Schuppenkleid & Lange Zungen', page: 28 }],
    url: 'https://dsa.ulisses-regelwiki.de/vorteil.html?vorteil=Greifschwanz+(*)',
  },
  {
    name: 'hauttasche',
    label: 'Hauttasche (*)',
    cost: 10,
    prerequisite: [],
    sources: [{ book: 'Achaz â€“ Schuppenkleid & Lange Zungen', page: 28 }],
    url: 'https://dsa.ulisses-regelwiki.de/vorteil.html?vorteil=Hauttasche+(*)',
  },
];

// â”€â”€â”€ Nachteile (Disadvantages) â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
// Source: DSA 5 Regelwerk (pages 170â€“179) + noted expansion books
// Costs are negative (AP gained by taking the disadvantage).
export const DISADVANTAGE: Advantage[] = [
  // â”€â”€ Regelwerk S. 170 â”€â”€
  // Angst vor â€¦: parameterized â€” specific instance e.g. angstVor_feuer
  {
    name: 'angstVor',
    label: 'Angst vor â€¦ I-III',
    cost: -8,
    lvl: 1,
    maxLvl: 3,
    prerequisite: [],
    sources: [{ book: 'Regelwerk', page: 170 }],
    url: 'https://dsa.ulisses-regelwiki.de/nachteil.html?nachteil=Angst+vor+%E2%80%A6+I-III',
  },
  {
    name: 'arm',
    label: 'Arm I-III',
    cost: -1,
    lvl: 1,
    maxLvl: 3,
    prerequisite: [{ name: 'reich', required: false }],
    sources: [{ book: 'Regelwerk', page: 170 }],
    url: 'https://dsa.ulisses-regelwiki.de/nachteil.html?nachteil=Arm+I-III',
  },
  {
    name: 'behabig',
    label: 'Behäbig',
    cost: -4,
    prerequisite: [{ name: 'flink', required: false }],
    sources: [{ book: 'Regelwerk', page: 170 }],
    url: 'https://dsa.ulisses-regelwiki.de/nachteil.html?nachteil=Beh%C3%A4big',
  },
  {
    name: 'blind',
    label: 'Blind',
    cost: -50,
    prerequisite: [
      { name: 'herausragenderSinn_sicht', required: false },
      { name: 'eingeschrankterSinn_sicht', required: false },
      { name: 'farbenblind', required: false },
      { name: 'nachtblind', required: false },
      { name: 'verstummelt_einaugig', required: false },
    ],
    sources: [{ book: 'Regelwerk', page: 170 }],
    url: 'https://dsa.ulisses-regelwiki.de/nachteil.html?nachteil=Blind',
  },
  {
    name: 'blutrausch',
    label: 'Blutrausch',
    cost: -10,
    prerequisite: [
      { name: 'schlechteEigenschaft_jahzorn', required: true },
      { name: 'angstVor_blut', required: false },
    ],
    sources: [{ book: 'Regelwerk', page: 171 }],
    url: 'https://dsa.ulisses-regelwiki.de/nachteil.html?nachteil=Blutrausch',
  },
  // â”€â”€ Regelwerk S. 171 â”€â”€
  // Eingeschränkter Sinn: Sicht=-15, Gehör=-10, Geruch&Geschmack=-6, Tastsinn=-2
  // Instances: eingeschrankterSinn_sicht, eingeschrankterSinn_gehor, etc.
  {
    name: 'eingeschrankterSinn',
    label: 'Eingeschränkter Sinn',
    cost: -15,
    prerequisite: [
      { name: 'herausragenderSinn', required: false },
      { name: 'blind', required: false },
      { name: 'taub', required: false },
    ],
    sources: [{ book: 'Regelwerk', page: 171 }],
    url: 'https://dsa.ulisses-regelwiki.de/nachteil.html?nachteil=Eingeschr%C3%A4nkter+Sinn',
  },
  {
    name: 'farbenblind',
    label: 'Farbenblind',
    cost: -2,
    prerequisite: [{ name: 'blind', required: false }],
    sources: [{ book: 'Regelwerk', page: 171 }],
    url: 'https://dsa.ulisses-regelwiki.de/nachteil.html?nachteil=Farbenblind',
  },
  {
    name: 'fettleibig',
    label: 'Fettleibig',
    cost: -25,
    prerequisite: [{ name: 'behabig', required: true }],
    sources: [{ book: 'Regelwerk', page: 171 }],
    url: 'https://dsa.ulisses-regelwiki.de/nachteil.html?nachteil=Fettleibig',
  },
  {
    name: 'giftanfallig',
    label: 'Giftanfällig I-II',
    cost: -5,
    lvl: 1,
    maxLvl: 2,
    prerequisite: [{ name: 'giftresistenz', required: false }],
    sources: [{ book: 'Regelwerk', page: 171 }],
    url: 'https://dsa.ulisses-regelwiki.de/nachteil.html?nachteil=Giftanf%C3%A4llig+I-II',
  },
  // â”€â”€ Regelwerk S. 171â€“172 â”€â”€
  {
    name: 'hasslich',
    label: 'Hässlich I-II',
    cost: -10,
    lvl: 1,
    maxLvl: 2,
    prerequisite: [{ name: 'gutaussehend', required: false }],
    sources: [{ book: 'Regelwerk', page: 172 }],
    url: 'https://dsa.ulisses-regelwiki.de/nachteil.html?nachteil=H%C3%A4sslich+I-II',
  },
  {
    name: 'hitzeempfindlich',
    label: 'Hitzeempfindlich',
    cost: -3,
    prerequisite: [{ name: 'hitzeresistenz', required: false }],
    sources: [{ book: 'Regelwerk', page: 172 }],
    url: 'https://dsa.ulisses-regelwiki.de/nachteil.html?nachteil=Hitzeempfindlich',
  },
  {
    name: 'kalteempfindlich',
    label: 'Kälteempfindlich',
    cost: -3,
    prerequisite: [{ name: 'kalteresistenz', required: false }],
    sources: [{ book: 'Regelwerk', page: 172 }],
    url: 'https://dsa.ulisses-regelwiki.de/nachteil.html?nachteil=K%C3%A4lteempfindlich',
  },
  {
    name: 'krankheitsanfallig',
    label: 'Krankheitsanfällig I-II',
    cost: -5,
    lvl: 1,
    maxLvl: 2,
    prerequisite: [{ name: 'krankheitsresistenz', required: false }],
    sources: [{ book: 'Regelwerk', page: 172 }],
    url: 'https://dsa.ulisses-regelwiki.de/nachteil.html?nachteil=Krankheitsanf%C3%A4llig+I-II',
  },
  // â”€â”€ Regelwerk S. 173â€“174 â”€â”€
  {
    name: 'nachtblind',
    label: 'Nachtblind',
    cost: -10,
    prerequisite: [
      { name: 'dunkelsicht', required: false },
      { name: 'blind', required: false },
    ],
    sources: [{ book: 'Regelwerk', page: 173 }],
    url: 'https://dsa.ulisses-regelwiki.de/nachteil.html?nachteil=Nachtblind',
  },
  {
    name: 'niedrigeAstralkraft',
    label: 'Niedrige Astralkraft I-VII',
    cost: -2,
    lvl: 1,
    maxLvl: 7,
    prerequisite: [
      { name: 'zauberer', required: true },
      { name: 'hoheAstralkraft', required: false },
    ],
    sources: [{ book: 'Regelwerk', page: 174 }],
    url: 'https://dsa.ulisses-regelwiki.de/nachteil.html?nachteil=Niedrige+Astralkraft+I-VII',
  },
  {
    name: 'niedrigeKarmalkraft',
    label: 'Niedrige Karmalkraft I-VII',
    cost: -2,
    lvl: 1,
    maxLvl: 7,
    prerequisite: [
      { name: 'geweihter', required: true },
      { name: 'hoheKarmalkraft', required: false },
    ],
    sources: [{ book: 'Regelwerk', page: 174 }],
    url: 'https://dsa.ulisses-regelwiki.de/nachteil.html?nachteil=Niedrige+Karmalkraft+I-VII',
  },
  {
    name: 'niedrigeLebenskraft',
    label: 'Niedrige Lebenskraft I-VII',
    cost: -4,
    lvl: 1,
    maxLvl: 7,
    prerequisite: [{ name: 'hoheLebenskraft', required: false }],
    sources: [{ book: 'Regelwerk', page: 174 }],
    url: 'https://dsa.ulisses-regelwiki.de/nachteil.html?nachteil=Niedrige+Lebenskraft+I-VII',
  },
  {
    name: 'niedrigeSeelenkraft',
    label: 'Niedrige Seelenkraft',
    cost: -25,
    prerequisite: [{ name: 'hoheSeelenkraft', required: false }],
    sources: [{ book: 'Regelwerk', page: 174 }],
    url: 'https://dsa.ulisses-regelwiki.de/nachteil.html?nachteil=Niedrige+Seelenkraft',
  },
  {
    name: 'niedrigeZahigkeit',
    label: 'Niedrige Zähigkeit',
    cost: -25,
    prerequisite: [{ name: 'hoheZahigkeit', required: false }],
    sources: [{ book: 'Regelwerk', page: 174 }],
    url: 'https://dsa.ulisses-regelwiki.de/nachteil.html?nachteil=Niedrige+Z%C3%A4higkeit',
  },
  // â”€â”€ Regelwerk S. 174â€“175 â”€â”€
  // Persönlichkeitsschwäche: varies by type (Arroganz/Eitelkeit/Streitsucht=-10, Neid/Vorurteile=-5, Unheimlich=-8, Weltfremd=-10)
  {
    name: 'personlichkeitsschwache',
    label: 'Persönlichkeitsschwäche',
    cost: -5,
    prerequisite: [],
    sources: [{ book: 'Regelwerk', page: 174 }],
    url: 'https://dsa.ulisses-regelwiki.de/nachteil.html?nachteil=Pers%C3%B6nlichkeitsschw%C3%A4che',
  },
  {
    name: 'pech',
    label: 'Pech I-III',
    cost: -20,
    lvl: 1,
    maxLvl: 3,
    prerequisite: [{ name: 'gluck', required: false }],
    sources: [{ book: 'Regelwerk', page: 175 }],
    url: 'https://dsa.ulisses-regelwiki.de/nachteil.html?nachteil=Pech+I-III',
  },
  {
    name: 'prinzipientreue',
    label: 'Prinzipientreue I-III',
    cost: -10,
    lvl: 1,
    maxLvl: 3,
    prerequisite: [],
    sources: [{ book: 'Regelwerk', page: 175 }],
    url: 'https://dsa.ulisses-regelwiki.de/nachteil.html?nachteil=Prinzipientreue+I-III',
  },
  // â”€â”€ Regelwerk S. 175 â”€â”€
  {
    name: 'schlafwandler',
    label: 'Schlafwandler',
    cost: -10,
    prerequisite: [],
    sources: [{ book: 'Regelwerk', page: 175 }],
    url: 'https://dsa.ulisses-regelwiki.de/nachteil.html?nachteil=Schlafwandler',
  },
  // Schlechte Angewohnheit: -2 AP per habit, max 6 AP total
  {
    name: 'schlechteAngewohnheit',
    label: 'Schlechte Angewohnheit',
    cost: -2,
    prerequisite: [],
    sources: [{ book: 'Regelwerk', page: 175 }],
    url: 'https://dsa.ulisses-regelwiki.de/nachteil.html?nachteil=Schlechte+Angewohnheit',
  },
  // â”€â”€ Regelwerk S. 176â€“177 â”€â”€
  // Schlechte Eigenschaft: varies (Aberglaube=-5, Jähzorn=-10, Kleptomanie=-10, Neugier=-5, etc.)
  {
    name: 'schlechteEigenschaft',
    label: 'Schlechte Eigenschaft',
    cost: -5,
    prerequisite: [],
    sources: [{ book: 'Regelwerk', page: 176 }],
    url: 'https://dsa.ulisses-regelwiki.de/nachteil.html?nachteil=Schlechte+Eigenschaft',
  },
  {
    name: 'schlechteRegenerationAsp',
    label: 'Schlechte Regeneration (Astralenergie) I-III',
    cost: -10,
    lvl: 1,
    maxLvl: 3,
    prerequisite: [
      { name: 'zauberer', required: true },
      { name: 'verbesserteRegenerationAsp', required: false },
    ],
    sources: [{ book: 'Regelwerk', page: 176 }],
    url: 'https://dsa.ulisses-regelwiki.de/nachteil.html?nachteil=Schlechte+Regeneration+(Astralenergie)+I-III',
  },
  {
    name: 'schlechteRegenerationKap',
    label: 'Schlechte Regeneration (Karmaenergie) I-III',
    cost: -10,
    lvl: 1,
    maxLvl: 3,
    prerequisite: [
      { name: 'geweihter', required: true },
      { name: 'verbesserteRegenerationKap', required: false },
    ],
    sources: [{ book: 'Regelwerk', page: 176 }],
    url: 'https://dsa.ulisses-regelwiki.de/nachteil.html?nachteil=Schlechte+Regeneration+(Karmaenergie)+I-III',
  },
  {
    name: 'schlechteRegenerationLep',
    label: 'Schlechte Regeneration (Lebensenergie) I-III',
    cost: -10,
    lvl: 1,
    maxLvl: 3,
    prerequisite: [{ name: 'verbesserteRegenerationLep', required: false }],
    sources: [{ book: 'Regelwerk', page: 177 }],
    url: 'https://dsa.ulisses-regelwiki.de/nachteil.html?nachteil=Schlechte+Regeneration+(Lebensenergie)+I-III',
  },
  {
    name: 'schnelleAlterung',
    label: 'Schnelle Alterung',
    cost: -5,
    prerequisite: [{ name: 'altersresistenz', required: false }],
    sources: [{ book: 'Regelwerk', page: 177 }],
    url: 'https://dsa.ulisses-regelwiki.de/nachteil.html?nachteil=Schnelle+Alterung',
  },
  {
    name: 'sensiblerGeruchssinn',
    label: 'Sensibler Geruchssinn',
    cost: -10,
    prerequisite: [{ name: 'eingeschrankterSinn_geruch', required: false }],
    sources: [{ book: 'Regelwerk', page: 177 }],
    url: 'https://dsa.ulisses-regelwiki.de/nachteil.html?nachteil=Sensibler+Geruchssinn',
  },
  // â”€â”€ Regelwerk S. 178 â”€â”€
  {
    name: 'taub',
    label: 'Taub',
    cost: -40,
    prerequisite: [{ name: 'herausragenderSinn_gehor', required: false }],
    sources: [{ book: 'Regelwerk', page: 178 }],
    url: 'https://dsa.ulisses-regelwiki.de/nachteil.html?nachteil=Taub',
  },
  // Unfähig: A/B/C/D = -1/-2/-3/-4 AP; max 2 talents
  {
    name: 'unfahig',
    label: 'Unfähig',
    cost: -1,
    prerequisite: [{ name: 'begabung', required: false }],
    sources: [{ book: 'Regelwerk', page: 178 }],
    url: 'https://dsa.ulisses-regelwiki.de/nachteil.html?nachteil=Unf%C3%A4hig',
  },
  {
    name: 'unfrei',
    label: 'Unfrei',
    cost: -8,
    prerequisite: [],
    sources: [{ book: 'Regelwerk', page: 178 }],
    url: 'https://dsa.ulisses-regelwiki.de/nachteil.html?nachteil=Unfrei',
  },
  {
    name: 'verpflichtungen',
    label: 'Verpflichtungen I-III',
    cost: -10,
    lvl: 1,
    maxLvl: 3,
    prerequisite: [],
    sources: [{ book: 'Regelwerk', page: 178 }],
    url: 'https://dsa.ulisses-regelwiki.de/nachteil.html?nachteil=Verpflichtungen+I-III',
  },
  // â”€â”€ Regelwerk S. 179 â”€â”€
  // Verstümmelt: Einarmig=-30, Einäugig=-10, Einbeinig=-30, Einhändig=-20, Einohrig=-5
  {
    name: 'verstummelt_einarmig',
    label: 'Verstümmelt (Einarmig)',
    cost: -30,
    prerequisite: [],
    sources: [{ book: 'Regelwerk', page: 179 }],
    url: 'https://dsa.ulisses-regelwiki.de/nachteil.html?nachteil=Verst%C3%BCmmelt',
  },
  {
    name: 'verstummelt_einaugig',
    label: 'Verstümmelt (Einäugig)',
    cost: -10,
    prerequisite: [],
    sources: [{ book: 'Regelwerk', page: 179 }],
    url: 'https://dsa.ulisses-regelwiki.de/nachteil.html?nachteil=Verst%C3%BCmmelt',
  },
  {
    name: 'verstummelt_einbeinig',
    label: 'Verstümmelt (Einbeinig)',
    cost: -30,
    prerequisite: [],
    sources: [{ book: 'Regelwerk', page: 179 }],
    url: 'https://dsa.ulisses-regelwiki.de/nachteil.html?nachteil=Verst%C3%BCmmelt',
  },
  {
    name: 'verstummelt_einhandig',
    label: 'Verstümmelt (Einhändig)',
    cost: -20,
    prerequisite: [],
    sources: [{ book: 'Regelwerk', page: 179 }],
    url: 'https://dsa.ulisses-regelwiki.de/nachteil.html?nachteil=Verst%C3%BCmmelt',
  },
  {
    name: 'verstummelt_einohrig',
    label: 'Verstümmelt (Einohrig)',
    cost: -5,
    prerequisite: [],
    sources: [{ book: 'Regelwerk', page: 179 }],
    url: 'https://dsa.ulisses-regelwiki.de/nachteil.html?nachteil=Verst%C3%BCmmelt',
  },
  {
    name: 'wildeMagie',
    label: 'Wilde Magie',
    cost: -10,
    prerequisite: [{ name: 'zauberer', required: true }],
    sources: [{ book: 'Regelwerk', page: 179 }],
    url: 'https://dsa.ulisses-regelwiki.de/nachteil.html?nachteil=Wilde+Magie',
  },
  {
    name: 'zauberanfallig',
    label: 'Zauberanfällig I-II',
    cost: -12,
    lvl: 1,
    maxLvl: 2,
    prerequisite: [{ name: 'schwerZuVerzaubern', required: false }],
    sources: [{ book: 'Regelwerk', page: 179 }],
    url: 'https://dsa.ulisses-regelwiki.de/nachteil.html?nachteil=Zauberanf%C3%A4llig+I-II',
  },
  {
    name: 'zerbrechlich',
    label: 'Zerbrechlich',
    cost: -20,
    prerequisite: [{ name: 'zaherHund', required: false }],
    sources: [{ book: 'Regelwerk', page: 179 }],
    url: 'https://dsa.ulisses-regelwiki.de/nachteil.html?nachteil=Zerbrechlich',
  },
  // â”€â”€ Aventurisches Kompendium â”€â”€
  {
    name: 'verweichlicht',
    label: 'Verweichlicht',
    cost: -3,
    prerequisite: [],
    sources: [{ book: 'Aventurisches Kompendium', page: 133 }],
    url: 'https://dsa.ulisses-regelwiki.de/nachteil.html?nachteil=Verweichlicht',
  },
  // â”€â”€ Regelwerk S. 172â€“179 (fehlende Einträge) â”€â”€
  {
    name: 'korpergebundeneKraft',
    label: 'Körpergebundene Kraft',
    cost: -5,
    prerequisite: [{ name: 'zauberer', required: true }],
    sources: [{ book: 'Regelwerk', page: 172 }],
    url: 'https://dsa.ulisses-regelwiki.de/nachteil.html?nachteil=K%C3%B6rpergebundene+Kraft',
  },
  {
    name: 'lastigeMindergeister',
    label: 'Lästige Mindergeister',
    cost: -20,
    prerequisite: [{ name: 'zauberer', required: true }],
    sources: [{ book: 'Regelwerk', page: 173 }],
    url: 'https://dsa.ulisses-regelwiki.de/nachteil.html?nachteil=L%C3%A4stige+Mindergeister',
  },
  {
    name: 'lichtempfindlich',
    label: 'Lichtempfindlich',
    cost: -20,
    prerequisite: [],
    sources: [{ book: 'Regelwerk', page: 173 }],
    url: 'https://dsa.ulisses-regelwiki.de/nachteil.html?nachteil=Lichtempfindlich',
  },
  {
    name: 'wahrerName',
    label: 'Wahrer Name',
    cost: -10,
    prerequisite: [],
    sources: [{ book: 'Regelwerk', page: 179 }],
    url: 'https://dsa.ulisses-regelwiki.de/nachteil.html?nachteil=Wahrer+Name',
  },
  // â”€â”€ Spezies-Erweiterungen â”€â”€
  {
    name: 'kaltestarre',
    label: 'Kältestarre (*)',
    cost: -15,
    prerequisite: [],
    sources: [{ book: 'Achaz â€“ Schuppenkleid & Lange Zungen', page: 29 }],
    url: 'https://dsa.ulisses-regelwiki.de/nachteil.html?nachteil=K%C3%A4ltestarre+(*)',
  },
  {
    name: 'stechenderOrkgeruch',
    label: 'Stechender Orkgeruch (*)',
    cost: -12,
    prerequisite: [],
    sources: [{ book: 'Orks â€“ Hauer & Schwarzer Pelz', page: 30 }],
    url: 'https://dsa.ulisses-regelwiki.de/nachteil.html?nachteil=Stechender+Orkgeruch+(*)',
  },
  {
    name: 'empfindlichkeit',
    label: 'Empfindlichkeit (*)',
    cost: -30,
    prerequisite: [],
    speciesRestriction: ['nachtalb'],
    sources: [{ book: 'Helden des Wolfsfrosts', page: 31 }],
    url: 'https://dsa.ulisses-regelwiki.de/nachteil.html?nachteil=Empfindlichkeit+(unedle+Metalle)+(*)',
  },
  {
    name: 'raubtiergeruch',
    label: 'Raubtiergeruch',
    cost: -3,
    prerequisite: [
      { name: 'unfahig_reiten', required: true },
      { name: 'unfahig_tierkunde', required: true },
    ],
    sources: [{ book: 'Aventurisches Bestiarium', page: 121 }],
    url: 'https://dsa.ulisses-regelwiki.de/nachteil.html?nachteil=Raubtiergeruch',
  },
];
