import { Cantrip, SpellTrait } from '../models/magic.model';

// ─── Zaubertricks (Cantrips) ─────────────────────────────────────────────────
// Source: DSA 5 Regelwiki – https://dsa.ulisses-regelwiki.de/zaubertrickauswahl.html
// Total: 113 cantrips, alphabetically ordered
// Traditions are simplified to main tradition names (academy specifiers omitted)

export const ALL_CANTRIPS: Cantrip[] = [
  { name: 'abkuehlung', label: 'Abkühlung', trait: SpellTrait.Elementar, traditions: ['Zauberalchimisten'] },
  { name: 'aranischeRasur', label: 'Aranische Rasur', trait: SpellTrait.Verwandlung, traditions: ['Gildenmagier', 'Hexen', 'Scharlatane'] },
  { name: 'astralesLeuchten', label: 'Astrales Leuchten', trait: SpellTrait.Hellsicht, traditions: ['Gildenmagier', 'Kristallomanten', 'Zauberalchimisten'] },
  { name: 'astralmanifestation', label: 'Astralmanifestation', trait: SpellTrait.Illusion, traditions: ['Gildenmagier', 'Scharlatane'] },
  { name: 'auffaelligerStil', label: 'Auffälliger Stil', trait: SpellTrait.Einfluss, traditions: ['Gildenmagier', 'Scharlatane'] },
  { name: 'auraDerEitelkeit', label: 'Aura der Eitelkeit', trait: SpellTrait.Einfluss, traditions: ['Borbaradianer', 'Gildenmagier'] },
  { name: 'bartwuchs', label: 'Bartwuchs', trait: SpellTrait.Verwandlung, traditions: ['Druiden', 'Geoden'] },
  { name: 'bauchreden', label: 'Bauchreden', trait: SpellTrait.Illusion, traditions: ['Scharlatane', 'Schelme'] },
  { name: 'beerenUndNuesse', label: 'Beeren & Nüsse', trait: SpellTrait.Einfluss, traditions: ['Druiden', 'Geoden', 'Goblinzauberinnen'] },
  { name: 'bereitZumAufbruch', label: 'Bereit zum Aufbruch', trait: SpellTrait.Telekinese, traditions: ['Gildenmagier'] },
  { name: 'beruhigung', label: 'Beruhigung', trait: SpellTrait.Heilung, traditions: ['Gildenmagier', 'Zauberalchimisten'] },
  { name: 'blickInDenLimbus', label: 'Blick in den Limbus', trait: SpellTrait.Hellsicht, traditions: ['Borbaradianer', 'Gildenmagier', 'Kristallomanten'] },
  { name: 'bluetenduft', label: 'Blütenduft', trait: SpellTrait.Illusion, traditions: ['Druiden', 'Elfen', 'Gildenmagier'] },
  { name: 'buchschliesser', label: 'Buchschließer', trait: SpellTrait.Telekinese, traditions: ['Gildenmagier'] },
  { name: 'daemonling', label: 'Dämonling', trait: SpellTrait.Daemonisch, traditions: ['Borbaradianer', 'Gildenmagier'] },
  { name: 'duft', label: 'Duft', trait: SpellTrait.Illusion, traditions: ['Zauberalchimisten'] },
  { name: 'ehrfuerchtigesVerhalten', label: 'Ehrfürchtiges Verhalten', trait: SpellTrait.Einfluss, traditions: ['Animisten', 'Gildenmagier'] },
  {
    name: 'einfacheTelekinese',
    label: 'Einfache Telekinese',
    trait: SpellTrait.Telekinese,
    traditions: ['Animisten', 'Gildenmagier', 'Kristallomanten', 'Scharlatane', 'Zauberalchimisten'],
  },
  { name: 'eiskalterBlick', label: 'Eiskalter Blick', trait: SpellTrait.Einfluss, traditions: ['Borbaradianer', 'Druiden', 'Gildenmagier', 'Nachtalben'] },
  { name: 'elementarling', label: 'Elementarling', trait: SpellTrait.Elementar, traditions: ['Druiden', 'Geoden', 'Gildenmagier'] },
  { name: 'elfenhaar', label: 'Elfenhaar', trait: SpellTrait.Verwandlung, traditions: ['Elfen', 'Nachtalben'] },
  { name: 'essenzDerNiederhoellen', label: 'Essenz der Niederhöllen', trait: SpellTrait.Sphaeren, traditions: ['Borbaradianer', 'Gildenmagier'] },
  { name: 'feenfuesse', label: 'Feenfüße', trait: SpellTrait.Telekinese, traditions: ['Kristallomanten', 'Zauberalchimisten'] },
  { name: 'feenzauber', label: 'Feenzauber', trait: SpellTrait.Sphaeren, traditions: ['Gildenmagier', 'Scharlatane'] },
  { name: 'feuerfinger', label: 'Feuerfinger', trait: SpellTrait.Elementar, traditions: ['Allgemein'] },
  { name: 'feuerspiel', label: 'Feuerspiel', trait: SpellTrait.Elementar, traditions: ['Geoden', 'Gildenmagier'] },
  { name: 'flammenhaar', label: 'Flammenhaar', trait: SpellTrait.Daemonisch, traditions: ['Animisten', 'Gildenmagier'] },
  { name: 'geistergeraeusche', label: 'Geistergeräusche', trait: SpellTrait.Illusion, traditions: ['Borbaradianer', 'Gildenmagier'] },
  { name: 'geloescht', label: 'Gelöscht', trait: SpellTrait.Objekt, traditions: ['Gildenmagier'] },
  { name: 'geraeuischhexerei', label: 'Geräuschhexerei', trait: SpellTrait.Illusion, traditions: ['Goblinzauberinnen', 'Schelme'] },
  { name: 'geraeuschschutz', label: 'Geräuschschutz', trait: SpellTrait.Verwandlung, traditions: ['Gildenmagier'] },
  { name: 'gluecksgriff', label: 'Glücksgriff', trait: SpellTrait.Hellsicht, traditions: ['Kristallomanten', 'Scharlatane', 'Zauberalchimisten'] },
  { name: 'grussworte', label: 'Grußworte', trait: SpellTrait.Einfluss, traditions: ['Elfen', 'Gildenmagier'] },
  { name: 'gutBehuetet', label: 'Gut behütet', trait: SpellTrait.Objekt, traditions: ['Gildenmagier', 'Kristallomanten'] },
  { name: 'gutenMorgen', label: 'Guten Morgen', trait: SpellTrait.Einfluss, traditions: ['Gildenmagier'] },
  { name: 'haarpracht', label: 'Haarpracht', trait: SpellTrait.Verwandlung, traditions: ['Hexen', 'Scharlatane', 'Zaubertänzer'] },
  { name: 'handDerAntimagie', label: 'Hand der Antimagie', trait: SpellTrait.Antimagie, traditions: ['Gildenmagier', 'Kristallomanten'] },
  { name: 'handwaermer', label: 'Handwärmer', trait: SpellTrait.Elementar, traditions: ['Geoden', 'Kristallomanten'] },
  { name: 'hautbild', label: 'Hautbild', trait: SpellTrait.Illusion, traditions: ['Animisten'] },
  { name: 'heilsameBerührung', label: 'Heilsame Berührung', trait: SpellTrait.Heilung, traditions: ['Druiden', 'Gildenmagier'] },
  { name: 'hellerStern', label: 'Heller Stern', trait: SpellTrait.Hellsicht, traditions: ['Gildenmagier'] },
  { name: 'hexenblick', label: 'Hexenblick', trait: SpellTrait.Hellsicht, traditions: ['Hexen'] },
  {
    name: 'hintergrundmusik',
    label: 'Hintergrundmusik',
    trait: SpellTrait.Illusion,
    traditions: ['Gildenmagier', 'Scharlatane', 'Zauberbarden', 'Zaubertänzer'],
  },
  { name: 'hundekeks', label: 'Hundekeks', trait: SpellTrait.Verwandlung, traditions: ['Geoden', 'Goblinzauberinnen'] },
  {
    name: 'insektenbann',
    label: 'Insektenbann',
    trait: SpellTrait.Verwandlung,
    traditions: ['Animisten', 'Druiden', 'Gildenmagier', 'Goblinzauberinnen', 'Hexen'],
  },
  { name: 'jagdtrommel', label: 'Jagdtrommel', trait: SpellTrait.Illusion, traditions: ['Animisten', 'Goblinzauberinnen'] },
  { name: 'kehrbesen', label: 'Kehrbesen', trait: SpellTrait.Telekinese, traditions: ['Hexen'] },
  { name: 'keimling', label: 'Keimling', trait: SpellTrait.Elementar, traditions: ['Druiden', 'Elfen'] },
  { name: 'kleinerFliegenderTeppich', label: 'Kleiner fliegender Teppich', trait: SpellTrait.Elementar, traditions: ['Gildenmagier', 'Scharlatane'] },
  { name: 'kleingeld', label: 'Kleingeld', trait: SpellTrait.Sphaeren, traditions: ['Gildenmagier'] },
  { name: 'kneifen', label: 'Kneifen', trait: SpellTrait.Telekinese, traditions: ['Goblinzauberinnen', 'Schelme'] },
  { name: 'konstanteTemperatur', label: 'Konstante Temperatur', trait: SpellTrait.Elementar, traditions: ['Gildenmagier', 'Zauberalchimisten'] },
  { name: 'koerperpflege', label: 'Körperpflege', trait: SpellTrait.Heilung, traditions: ['Animisten', 'Gildenmagier'] },
  { name: 'kreide', label: 'Kreide', trait: SpellTrait.Objekt, traditions: ['Gildenmagier'] },
  { name: 'kriegsbemalung', label: 'Kriegsbemalung', trait: SpellTrait.Verwandlung, traditions: ['Animisten', 'Gildenmagier'] },
  { name: 'laufendesHaendchen', label: 'Laufendes Händchen', trait: SpellTrait.Daemonisch, traditions: ['Gildenmagier'] },
  { name: 'leselampe', label: 'Leselampe', trait: SpellTrait.Elementar, traditions: ['Gildenmagier', 'Kristallomanten'] },
  { name: 'leuchtblume', label: 'Leuchtblume', trait: SpellTrait.Verwandlung, traditions: ['Elfen'] },
  { name: 'lockruf', label: 'Lockruf', trait: SpellTrait.Einfluss, traditions: ['Druiden', 'Goblinzauberinnen'] },
  { name: 'luftstoss', label: 'Luftstoß', trait: SpellTrait.Telekinese, traditions: ['Elfen', 'Gildenmagier', 'Nachtalben'] },
  { name: 'nagellack', label: 'Nagellack', trait: SpellTrait.Verwandlung, traditions: ['Gildenmagier', 'Hexen', 'Zaubertänzer'] },
  { name: 'ordentlich', label: 'Ordentlich', trait: SpellTrait.Telekinese, traditions: ['Gildenmagier'] },
  { name: 'patronIllusion', label: 'Patron-Illusion', trait: SpellTrait.Illusion, traditions: ['Animisten'] },
  { name: 'pflanzenempathie', label: 'Pflanzenempathie', trait: SpellTrait.Hellsicht, traditions: ['Animisten', 'Druiden'] },
  { name: 'platscher', label: 'Platscher', trait: SpellTrait.Elementar, traditions: ['Druiden', 'Geoden'] },
  { name: 'putzigesTierchen', label: 'Putziges Tierchen', trait: SpellTrait.Einfluss, traditions: ['Elfen'] },
  { name: 'regenbogenaugen', label: 'Regenbogenaugen', trait: SpellTrait.Illusion, traditions: ['Kristallomanten', 'Scharlatane'] },
  { name: 'regenschirm', label: 'Regenschirm', trait: SpellTrait.Telekinese, traditions: ['Gildenmagier'] },
  { name: 'rohrstock', label: 'Rohrstock', trait: SpellTrait.Telekinese, traditions: ['Gildenmagier'] },
  { name: 'ruhigeAusstrahlung', label: 'Ruhige Ausstrahlung', trait: SpellTrait.Einfluss, traditions: ['Animisten', 'Druiden', 'Geoden', 'Gildenmagier'] },
  { name: 'ruehrloefel', label: 'Rührlöffel', trait: SpellTrait.Telekinese, traditions: ['Hexen', 'Zauberalchimisten'] },
  { name: 'rutschigerBoden', label: 'Rutschiger Boden', trait: SpellTrait.Objekt, traditions: ['Schelme'] },
  { name: 'sandfigur', label: 'Sandfigur', trait: SpellTrait.Elementar, traditions: ['Gildenmagier'] },
  { name: 'saberesWerkzeug', label: 'Sauberes Werkzeug', trait: SpellTrait.Objekt, traditions: ['Runenschöpfer'] },
  { name: 'schattenspiel', label: 'Schattenspiel', trait: SpellTrait.Illusion, traditions: ['Gildenmagier', 'Scharlatane'] },
  { name: 'schlangenhaende', label: 'Schlangenhände', trait: SpellTrait.Verwandlung, traditions: ['Kristallomanten'] },
  { name: 'schminken', label: 'Schminken', trait: SpellTrait.Telekinese, traditions: ['Gildenmagier', 'Hexen', 'Scharlatane', 'Zaubertänzer'] },
  { name: 'schmutzabweisend', label: 'Schmutzabweisend', trait: SpellTrait.Verwandlung, traditions: ['Elfen'] },
  { name: 'schnipsen', label: 'Schnipsen', trait: SpellTrait.Telekinese, traditions: ['Allgemein'] },
  { name: 'schoenschrift', label: 'Schönschrift', trait: SpellTrait.Objekt, traditions: ['Gildenmagier', 'Zauberalchimisten'] },
  { name: 'schulgong', label: 'Schulgong', trait: SpellTrait.Illusion, traditions: ['Gildenmagier'] },
  { name: 'schutzVorDemTierpatron', label: 'Schutz vor dem Tierpatron', trait: SpellTrait.Einfluss, traditions: ['Animisten'] },
  { name: 'selbstarchivierung', label: 'Selbstarchivierung', trait: SpellTrait.Telekinese, traditions: ['Gildenmagier'] },
  { name: 'siegelDerElemente', label: 'Siegel der Elemente', trait: SpellTrait.Elementar, traditions: ['Druiden', 'Gildenmagier'] },
  { name: 'signatur', label: 'Signatur', trait: SpellTrait.Objekt, traditions: ['Runenschöpfer'] },
  { name: 'sprechendesKaestchen', label: 'Sprechendes Kästchen', trait: SpellTrait.Objekt, traditions: ['Gildenmagier', 'Kristallomanten'] },
  { name: 'stabhalter', label: 'Stabhalter', trait: SpellTrait.Objekt, traditions: ['Gildenmagier'] },
  { name: 'steinempathie', label: 'Steinempathie', trait: SpellTrait.Hellsicht, traditions: ['Geoden'] },
  { name: 'strahlendesLaecheln', label: 'Strahlendes Lächeln', trait: SpellTrait.Illusion, traditions: ['Scharlatane', 'Schelme', 'Zauberbarden'] },
  { name: 'tafelschwamm', label: 'Tafelschwamm', trait: SpellTrait.Objekt, traditions: ['Gildenmagier'] },
  { name: 'taetowierung', label: 'Tätowierung', trait: SpellTrait.Verwandlung, traditions: ['Gildenmagier', 'Runenschöpfer', 'Zaubertänzer'] },
  { name: 'tentakelgriff', label: 'Tentakelgriff', trait: SpellTrait.Verwandlung, traditions: ['Borbaradianer', 'Gildenmagier'] },
  { name: 'tierpflege', label: 'Tierpflege', trait: SpellTrait.Telekinese, traditions: ['Hexen'] },
  { name: 'tiertrick', label: 'Tiertrick', trait: SpellTrait.Sphaeren, traditions: ['Goblinzauberinnen', 'Scharlatane', 'Schelme'] },
  { name: 'totenmaske', label: 'Totenmaske', trait: SpellTrait.Illusion, traditions: ['Gildenmagier'] },
  { name: 'trocken', label: 'Trocken', trait: SpellTrait.Elementar, traditions: ['Allgemein'] },
  { name: 'tuerklinkenbetatiger', label: 'Türklinkenbetätiger', trait: SpellTrait.Telekinese, traditions: ['Gildenmagier'] },
  { name: 'tuerklopfer', label: 'Türklopfer', trait: SpellTrait.Objekt, traditions: ['Gildenmagier'] },
  { name: 'uebergangen', label: 'Übergangen', trait: SpellTrait.Einfluss, traditions: ['Gildenmagier'] },
  { name: 'unauffaelligerStab', label: 'Unauffälliger Stab', trait: SpellTrait.Einfluss, traditions: ['Gildenmagier', 'Hexen'] },
  { name: 'unheimlichesLachen', label: 'Unheimliches Lachen', trait: SpellTrait.Einfluss, traditions: ['Borbaradianer', 'Gildenmagier', 'Hexen'] },
  { name: 'verbundenheitsgefuehl', label: 'Verbundenheitsgefühl', trait: SpellTrait.Hellsicht, traditions: ['Gildenmagier'] },
  { name: 'verneigung', label: 'Verneigung', trait: SpellTrait.Einfluss, traditions: ['Borbaradianer', 'Gildenmagier'] },
  { name: 'verruecktesKichern', label: 'Verrücktes Kichern', trait: SpellTrait.Einfluss, traditions: ['Hexen'] },
  { name: 'waffensaeuberung', label: 'Waffensäuberung', trait: SpellTrait.Objekt, traditions: ['Animisten', 'Gildenmagier'] },
  { name: 'warmesBlut', label: 'Warmes Blut', trait: SpellTrait.Hellsicht, traditions: ['Kristallomanten', 'Nachtalben'] },
  { name: 'wasserhoehe', label: 'Wasserhöhe', trait: SpellTrait.Hellsicht, traditions: ['Gildenmagier'] },
  { name: 'wechselschein', label: 'Wechselschein', trait: SpellTrait.Sphaeren, traditions: ['Gildenmagier'] },
  { name: 'weisheitDesLeytfadens', label: 'Weisheit des Leytfadens', trait: SpellTrait.Illusion, traditions: ['Gildenmagier'] },
  { name: 'windImHaar', label: 'Wind im Haar', trait: SpellTrait.Elementar, traditions: ['Druiden', 'Gildenmagier'] },
  { name: 'wohlgeruch', label: 'Wohlgeruch', trait: SpellTrait.Verwandlung, traditions: ['Elfen'] },
  { name: 'wuerze', label: 'Würze', trait: SpellTrait.Illusion, traditions: ['Hexen', 'Zauberalchimisten'] },
  { name: 'zauberfeder', label: 'Zauberfeder', trait: SpellTrait.Telekinese, traditions: ['Gildenmagier', 'Runenschöpfer', 'Zauberalchimisten'] },
];
