import { IncreaseFactor } from '../models/magic.model';
import { Ceremony } from '../models/divine.model';

// â”€â”€â”€ Zeremonien (Ceremonies) â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
// Source: DSA 5 Regelwiki â€“ https://dsa.ulisses-regelwiki.de/zeremonien.html
// Total: 138 ceremonies, alphabetically ordered

export const ALL_CEREMONIES: Ceremony[] = [
  // â”€â”€ Batch 1 (1â€“20) â”€â”€
  {
    name: 'aechtungExkommunikation',
    label: 'Ächtung (Exkommunikation)',
    check: ['MU', 'IN', 'CH'],
    traditions: ['Allgemein', 'Allgemein-Schamanenritus'],
    increaseFactor: IncreaseFactor.D,
    url: 'https://dsa.ulisses-regelwiki.de/zeremonie.html?zeremonie=%C3%84chtung+(Exkommunikation)',
    sources: [
      { book: 'Aventurisches Götterwirken', page: 165 },
      { book: 'Aventurisches Götterwirken II', page: 75 },
      { book: 'Divinarium Liturgia', page: 214 },
    ],
  },
  {
    name: 'ackersegen',
    label: 'Ackersegen',
    check: ['MU', 'KL', 'IN'],
    traditions: ['Peraine (Landwirtschaft)'],
    increaseFactor: IncreaseFactor.B,
    url: 'https://dsa.ulisses-regelwiki.de/zeremonie.html?zeremonie=Ackersegen',
    sources: [
      { book: 'Aventurisches Götterwirken', page: 131 },
      { book: 'Divinarium Liturgia', page: 215 },
    ],
  },
  {
    name: 'arcanumInterdictum',
    label: 'Arcanum Interdictum',
    check: ['MU', 'IN', 'CH'],
    traditions: ['Praios (Antimagie)'],
    increaseFactor: IncreaseFactor.D,
    url: 'https://dsa.ulisses-regelwiki.de/zeremonie.html?zeremonie=Arcanum+Interdictum',
    sources: [
      { book: 'Aventurisches Götterwirken', page: 131 },
      { book: 'Divinarium Liturgia', page: 216 },
    ],
  },
  {
    name: 'aufnahmeInitiation',
    label: 'Aufnahme (Initiation)',
    check: ['KL', 'IN', 'CH'],
    traditions: ['Allgemein', 'Allgemein-Schamanenritus'],
    increaseFactor: IncreaseFactor.A,
    url: 'https://dsa.ulisses-regelwiki.de/zeremonie.html?zeremonie=Aufnahme+(Initiation)',
    sources: [
      { book: 'Aventurisches Götterwirken', page: 131 },
      { book: 'Aventurisches Götterwirken II', page: 75 },
      { book: 'Divinarium Liturgia', page: 217 },
    ],
  },
  {
    name: 'ausbrennenPurgation',
    label: 'Ausbrennen (Purgation)',
    check: ['MU', 'KL', 'CH'],
    traditions: ['Allgemein', 'Allgemein-Schamanenritus', 'Praios (Antimagie)'],
    increaseFactor: IncreaseFactor.D,
    url: 'https://dsa.ulisses-regelwiki.de/zeremonie.html?zeremonie=Ausbrennen+(Purgation)',
    sources: [
      { book: 'Aventurisches Götterwirken', page: 132 },
      { book: 'Aventurisches Götterwirken II', page: 75 },
      { book: 'Divinarium Liturgia', page: 218 },
    ],
  },
  {
    name: 'bannfluchAnathema',
    label: 'Bannfluch (Anathema)',
    check: ['MU', 'IN', 'CH'],
    traditions: ['Allgemein'],
    increaseFactor: IncreaseFactor.D,
    url: 'https://dsa.ulisses-regelwiki.de/zeremonie.html?zeremonie=Bannfluch+(Anathema)',
    sources: [
      { book: 'Aventurisches Götterwirken', page: 133 },
      { book: 'Divinarium Liturgia', page: 219 },
    ],
  },
  {
    name: 'berauschenderWein',
    label: 'Berauschender Wein',
    check: ['MU', 'IN', 'CH'],
    traditions: ['Levthan (Rausch)', 'Rahja (Ekstase)'],
    increaseFactor: IncreaseFactor.A,
    url: 'https://dsa.ulisses-regelwiki.de/zeremonie.html?zeremonie=Berauschender+Wein',
    sources: [
      { book: 'Aventurisches Götterwirken II', page: 96 },
      { book: 'Divinarium Liturgia', page: 220 },
      { book: 'Wege der Vereinigungen', page: 187 },
    ],
  },
  {
    name: 'beschwoerungDerHohenDienerDesRattenkindes',
    label: 'Beschwörung der hohen Diener des Rattenkindes',
    check: ['MU', 'CH', 'KO'],
    traditions: ['Namenloser'],
    increaseFactor: IncreaseFactor.C,
    url: 'https://dsa.ulisses-regelwiki.de/zeremonie.html?zeremonie=Beschw%C3%B6rung+der+hohen+Diener+des+Rattenkindes',
    sources: [
      { book: 'Aventurisches Götterwirken', page: 134 },
      { book: 'Divinarium Liturgia', page: 221 },
    ],
  },
  {
    name: 'beschwoerungDerMachtvollenDienerDesRattenkindes',
    label: 'Beschwörung der machtvollen Diener des Rattenkindes',
    check: ['MU', 'CH', 'KO'],
    traditions: ['Namenloser'],
    increaseFactor: IncreaseFactor.D,
    url: 'https://dsa.ulisses-regelwiki.de/zeremonie.html?zeremonie=Beschw%C3%B6rung+der+machtvollen+Diener+des+Rattenkindes',
    sources: [
      { book: 'Aventurisches Götterwirken', page: 134 },
      { book: 'Divinarium Liturgia', page: 222 },
    ],
  },
  {
    name: 'bildFuerDieEwigkeit',
    label: 'Bild für die Ewigkeit',
    check: ['MU', 'KL', 'IN'],
    traditions: ['Boron (Tod)', 'Hesinde (Wissen)', 'Nandus (Bildung)'],
    increaseFactor: IncreaseFactor.B,
    url: 'https://dsa.ulisses-regelwiki.de/zeremonie.html?zeremonie=Bild+f%C3%BCr+die+Ewigkeit',
    sources: [
      { book: 'Aventurisches Götterwirken', page: 135 },
      { book: 'Divinarium Liturgia', page: 223 },
    ],
  },
  {
    name: 'blickInDieFlammen',
    label: 'Blick in die Flammen',
    check: ['MU', 'KL', 'IN'],
    traditions: ['Angrosch (Flammen)', 'Ingerimm (Feuer)'],
    increaseFactor: IncreaseFactor.A,
    url: 'https://dsa.ulisses-regelwiki.de/zeremonie.html?zeremonie=Blick+in+die+Flammen',
    sources: [
      { book: 'Aventurisches Götterwirken', page: 135 },
      { book: 'Divinarium Liturgia', page: 224 },
    ],
  },
  {
    name: 'daemonenpaktBrechen',
    label: 'Dämonenpakt brechen',
    check: ['MU', 'IN', 'CH'],
    traditions: ['Allgemein'],
    increaseFactor: IncreaseFactor.C,
    url: 'https://dsa.ulisses-regelwiki.de/zeremonie.html?zeremonie=D%C3%A4monenpakt+brechen',
    sources: [
      { book: 'Aventurisches Götterwirken', page: 136 },
      { book: 'Divinarium Liturgia', page: 225 },
    ],
  },
  {
    name: 'dasLoeschenDesLichts',
    label: 'Das Löschen des Lichts',
    check: ['MU', 'IN', 'CH'],
    traditions: ['Namenloser'],
    increaseFactor: IncreaseFactor.D,
    url: 'https://dsa.ulisses-regelwiki.de/zeremonie.html?zeremonie=Das+L%C3%B6schen+des+Lichts',
    sources: [
      { book: 'Aventurisches Götterwirken', page: 136 },
      { book: 'Divinarium Liturgia', page: 226 },
    ],
  },
  {
    name: 'delphingestalt',
    label: 'Delphingestalt',
    check: ['MU', 'KL', 'IN'],
    traditions: ['Efferd (Wogen)'],
    increaseFactor: IncreaseFactor.B,
    url: 'https://dsa.ulisses-regelwiki.de/zeremonie.html?zeremonie=Delphingestalt',
    sources: [
      { book: 'Regelwerk', page: 325 },
      { book: 'Aventurisches Götterwirken', page: 167 },
      { book: 'Divinarium Liturgia', page: 227 },
      { book: 'Havena - Versunkene Geheimnisse', page: 85 },
    ],
  },
  {
    name: 'dienerDerErde',
    label: 'Diener der Erde',
    check: ['MU', 'IN', 'CH'],
    traditions: [
      'Achazschamanen (Starre)',
      'Ferkinaschamanen (Blut)',
      'Fjarningerschamanen (Eis)',
      'Gjalskerschamanen (Gemeinschaft)',
      'GjalskerÂ­schamanen (Wildheit)',
      'Nivesenschamanen (Winter)',
      'Tahayaschamanen (Dschungel)',
      'Trollzackerschamanen (Leiden)',
    ],
    increaseFactor: IncreaseFactor.C,
    url: 'https://dsa.ulisses-regelwiki.de/zeremonie.html?zeremonie=Diener+der+Erde',
    sources: [
      { book: 'Aventurisches Götterwirken II', page: 96 },
      { book: 'Divinarium Liturgia', page: 228 },
    ],
  },
  {
    name: 'dienerDerFlammen',
    label: 'Diener der Flammen',
    check: ['MU', 'IN', 'CH'],
    traditions: [
      'Angrosch (Flammen)',
      'Ferkinaschamanen (Blut)',
      'Fjarningerschamanen (Eis)',
      'Gjalskerschamanen (Gemeinschaft)',
      'Gjalskerschamanen (Wildheit)',
      'Tahayaschamanen (Sonne)',
      'Trollzackerschamanen (Leiden)',
    ],
    increaseFactor: IncreaseFactor.C,
    url: 'https://dsa.ulisses-regelwiki.de/zeremonie.html?zeremonie=Diener+der+Flammen',
    sources: [
      { book: 'Aventurisches Götterwirken II', page: 96 },
      { book: 'Divinarium Liturgia', page: 229 },
    ],
  },
  {
    name: 'dienerDerKaelte',
    label: 'Diener der Kälte',
    check: ['MU', 'IN', 'CH'],
    traditions: [
      'Achazschamanen (Starre)',
      'Ferkinaschamanen (Blut)',
      'Fjarningerschamanen (Eis)',
      'Gjalskerschamanen (Gemeinschaft)',
      'Gjalskerschamanen (Wildheit)',
      'Nivesenschamanen (Winter)',
      'Trollzackerschamanen (Leiden)',
    ],
    increaseFactor: IncreaseFactor.C,
    url: 'https://dsa.ulisses-regelwiki.de/zeremonie.html?zeremonie=Diener+der+K%C3%A4lte',
    sources: [
      { book: 'Aventurisches Götterwirken II', page: 96 },
      { book: 'Divinarium Liturgia', page: 230 },
    ],
  },
  {
    name: 'dienerDerWellen',
    label: 'Diener der Wellen',
    check: ['MU', 'IN', 'CH'],
    traditions: [
      'Achazschamanen (Starre)',
      'Ferkinaschamanen (Blut)',
      'Fjarningerschamanen (Eis)',
      'Gjalskerschamanen (Gemeinschaft)',
      'Gjalskerschamanen (Wildheit)',
      'Nivesenschamanen (Winter)',
      'Tahayaschamanen (Dschungel)',
      'Trollzackerschamanen (Leiden)',
    ],
    increaseFactor: IncreaseFactor.C,
    url: 'https://dsa.ulisses-regelwiki.de/zeremonie.html?zeremonie=Diener+der+Wellen',
    sources: [
      { book: 'Aventurisches Götterwirken II', page: 96 },
      { book: 'Divinarium Liturgia', page: 231 },
    ],
  },
  {
    name: 'dienerDerWolken',
    label: 'Diener der Wolken',
    check: ['MU', 'IN', 'CH'],
    traditions: [
      'Achazschamanen (Starre)',
      'Ferkinaschamanen (Blut)',
      'Fjarningerschamanen (Eis)',
      'Gjalskerschamanen (Gemeinschaft)',
      'Gjalskerschamanen (Wildheit)',
      'Nivesenschamanen (Winter)',
      'Tahayaschamanen (Sonne)',
      'Trollzackerschamanen (Leiden)',
    ],
    increaseFactor: IncreaseFactor.C,
    url: 'https://dsa.ulisses-regelwiki.de/zeremonie.html?zeremonie=Diener+der+Wolken',
    sources: [
      { book: 'Aventurisches Götterwirken II', page: 96 },
      { book: 'Divinarium Liturgia', page: 232 },
    ],
  },
  {
    name: 'dienerDesErzes',
    label: 'Diener des Erzes',
    check: ['MU', 'IN', 'CH'],
    traditions: [
      'Angrosch (Erz)',
      'Ferkinaschamanen (Blut)',
      'Fjarningerschamanen (Eis)',
      'Gjalskerschamanen (Gemeinschaft)',
      'Gjalskerschamanen (Wildheit)',
      'Trollzackerschamanen (Leiden)',
    ],
    increaseFactor: IncreaseFactor.C,
    url: 'https://dsa.ulisses-regelwiki.de/zeremonie.html?zeremonie=Diener+des+Erzes',
    sources: [
      { book: 'Aventurisches Götterwirken II', page: 96 },
      { book: 'Divinarium Liturgia', page: 233 },
    ],
  },

  // â”€â”€ Batch 2 (21â€“40) â”€â”€
  {
    name: 'eidechsengestalt',
    label: 'Eidechsengestalt',
    check: ['MU', 'KL', 'IN'],
    traditions: ['Tsa (Wandel)', 'Zsahh (Eidechse)'],
    increaseFactor: IncreaseFactor.A,
    url: 'https://dsa.ulisses-regelwiki.de/zeremonie.html?zeremonie=Eidechsengestalt',
    sources: [
      { book: 'Achaz - Schuppenkleid & Lange Zungen', page: 55 },
      { book: 'Aventurisches Götterwirken', page: 138 },
      { book: 'Divinarium Liturgia', page: 234 },
    ],
  },
  {
    name: 'eidechsenregeneration',
    label: 'Eidechsenregeneration',
    check: ['IN', 'CH', 'KO'],
    traditions: ['Tsa (Wandel)', 'Zsahh (Eidechse)', 'Zsahh (Fürsorge)'],
    increaseFactor: IncreaseFactor.C,
    url: 'https://dsa.ulisses-regelwiki.de/zeremonie.html?zeremonie=Eidechsenregeneration',
    sources: [
      { book: 'Achaz - Schuppenkleid & Lange Zungen', page: 55 },
      { book: 'Aventurisches Götterwirken', page: 138 },
      { book: 'Divinarium Liturgia', page: 235 },
    ],
  },
  {
    name: 'einflüsterung',
    label: 'Einflüsterung',
    check: ['KL', 'IN', 'CH'],
    traditions: ['Levthan (Begierde)'],
    increaseFactor: IncreaseFactor.A,
    url: 'https://dsa.ulisses-regelwiki.de/zeremonie.html?zeremonie=Einfl%C3%BCsterung',
    sources: [
      { book: 'Aventurisches Götterwirken II', page: 97 },
      { book: 'Divinarium Liturgia', page: 236 },
      { book: 'Wege der Vereinigungen', page: 188 },
    ],
  },
  {
    name: 'eingeschworeneMannschaft',
    label: 'Eingeschworene Mannschaft',
    check: ['MU', 'KL', 'IN'],
    traditions: ['Swafnir (Tapferkeit)'],
    increaseFactor: IncreaseFactor.C,
    url: 'https://dsa.ulisses-regelwiki.de/zeremonie.html?zeremonie=Eingeschworene+Mannschaft',
    sources: [
      { book: 'Aventurisches Götterwirken', page: 139 },
      { book: 'Divinarium Liturgia', page: 237 },
    ],
  },
  {
    name: 'einhorngestaltMaechtigeTiergestalt',
    label: 'Einhorngestalt (Mächtige Tiergestalt)',
    check: ['MU', 'KL', 'IN'],
    traditions: ['Nandus (Bildung)'],
    increaseFactor: IncreaseFactor.D,
    url: 'https://dsa.ulisses-regelwiki.de/zeremonie.html?zeremonie=Einhorngestalt+(M%C3%A4chtige+Tiergestalt)',
    sources: [
      { book: 'Aventurisches Götterwirken II', page: 97 },
      { book: 'Divinarium Liturgia', page: 238 },
    ],
  },
  {
    name: 'eisbaergestalt',
    label: 'Eisbärengestalt',
    check: ['MU', 'KL', 'IN'],
    traditions: ['Firun (Kälte)', 'Fjarningerschamanen (Eis)'],
    increaseFactor: IncreaseFactor.C,
    url: 'https://dsa.ulisses-regelwiki.de/zeremonie.html?zeremonie=Eisb%C3%A4rengestalt',
    sources: [
      { book: 'Aventurisches Götterwirken', page: 139 },
      { book: 'Divinarium Liturgia', page: 239 },
    ],
  },
  {
    name: 'elsterngestalt',
    label: 'Elsterngestalt',
    check: ['MU', 'KL', 'IN'],
    traditions: ['Phex (Schatten)'],
    increaseFactor: IncreaseFactor.B,
    url: 'https://dsa.ulisses-regelwiki.de/zeremonie.html?zeremonie=Elsterngestalt',
    sources: [
      { book: 'Aventurisches Götterwirken', page: 139 },
      { book: 'Divinarium Liturgia', page: 240 },
    ],
  },
  {
    name: 'empfaengnisDesKorsmals',
    label: 'Empfängnis des Korsmals',
    check: ['MU', 'IN', 'KO'],
    traditions: ['Kor (Guter Kampf)', 'Kor (Gutes Gold)'],
    increaseFactor: IncreaseFactor.D,
    url: 'https://dsa.ulisses-regelwiki.de/zeremonie.html?zeremonie=Empf%C3%A4ngnis+des+Korsmals',
    sources: [
      { book: 'Aventurisches Götterwirken', page: 139 },
      { book: 'Divinarium Liturgia', page: 241 },
    ],
  },
  {
    name: 'erfolgreichePflanzensuche',
    label: 'Erfolgreiche Pflanzensuche',
    check: ['KL', 'IN', 'KO'],
    traditions: ['Peraine (Heilung)'],
    increaseFactor: IncreaseFactor.B,
    url: 'https://dsa.ulisses-regelwiki.de/zeremonie.html?zeremonie=Erfolgreiche+Pflanzensuche',
    sources: [
      { book: 'Aventurisches Herbarium', page: 145 },
      { book: 'Divinarium Liturgia', page: 242 },
    ],
  },
  {
    name: 'erinnern',
    label: 'Erinnern',
    check: ['MU', 'KL', 'IN'],
    traditions: ['Boron (Tod)', 'Hesinde (Wissen)', 'Nandus (Bildung)'],
    increaseFactor: IncreaseFactor.B,
    url: 'https://dsa.ulisses-regelwiki.de/zeremonie.html?zeremonie=Erinnern',
    sources: [
      { book: 'Aventurisches Götterwirken', page: 140 },
      { book: 'Divinarium Liturgia', page: 243 },
    ],
  },
  {
    name: 'erschaffungVonNachtkindern',
    label: 'Erschaffung von Nachtkindern',
    check: ['MU', 'IN', 'CH'],
    traditions: ['Marbo (Vergänglichkeit)'],
    increaseFactor: IncreaseFactor.D,
    url: 'https://dsa.ulisses-regelwiki.de/zeremonie.html?zeremonie=Erschaffung+von+Nachtkindern',
    sources: [
      { book: 'Aventurisches Götterwirken II', page: 97 },
      { book: 'Divinarium Liturgia', page: 244 },
    ],
  },
  {
    name: 'exorzismus',
    label: 'Exorzismus',
    check: ['MU', 'IN', 'CH'],
    traditions: ['Allgemein', 'Allgemein-Schamanenritus', 'Boron (Tod)', 'Praios (Antimagie)'],
    increaseFactor: IncreaseFactor.C,
    url: 'https://dsa.ulisses-regelwiki.de/zeremonie.html?zeremonie=Exorzismus',
    sources: [
      { book: 'Aventurisches Götterwirken', page: 140 },
      { book: 'Aventurisches Götterwirken II', page: 75 },
      { book: 'Divinarium Liturgia', page: 245 },
    ],
  },
  {
    name: 'falkengestalt',
    label: 'Falkengestalt',
    check: ['MU', 'KL', 'IN'],
    traditions: ['Praios (Ordnung)'],
    increaseFactor: IncreaseFactor.B,
    url: 'https://dsa.ulisses-regelwiki.de/zeremonie.html?zeremonie=Falkengestalt',
    sources: [
      { book: 'Aventurisches Götterwirken', page: 140 },
      { book: 'Divinarium Liturgia', page: 246 },
    ],
  },
  {
    name: 'festDerFreude',
    label: 'Fest der Freude',
    check: ['MU', 'IN', 'CH'],
    traditions: ['Levthan (Rausch)', 'Rahja (Harmonie)'],
    increaseFactor: IncreaseFactor.A,
    url: 'https://dsa.ulisses-regelwiki.de/zeremonie.html?zeremonie=Fest+der+Freude',
    sources: [
      { book: 'Aventurisches Götterwirken II', page: 97 },
      { book: 'Divinarium Liturgia', page: 247 },
      { book: 'Wege der Vereinigungen', page: 189 },
    ],
  },
  {
    name: 'flugechsengestalt',
    label: 'Flugechsengestalt',
    check: ['MU', 'KL', 'IN'],
    traditions: ["Chr'Ssir'Ssr (Wetter)"],
    increaseFactor: IncreaseFactor.C,
    url: 'https://dsa.ulisses-regelwiki.de/zeremonie.html?zeremonie=Flugechsengestalt',
    sources: [
      { book: 'Achaz - Schuppenkleid & Lange Zungen', page: 55 },
      { book: 'Aventurisches Götterwirken II', page: 97 },
      { book: 'Divinarium Liturgia', page: 248 },
    ],
  },
  {
    name: 'freieSeelenfahrt',
    label: 'Freie Seelenfahrt',
    check: ['MU', 'IN', 'CH'],
    traditions: ['Allgemein-Schamanenritus'],
    increaseFactor: IncreaseFactor.C,
    url: 'https://dsa.ulisses-regelwiki.de/zeremonie.html?zeremonie=Freie+Seelenfahrt',
    sources: [
      { book: 'Aventurisches Götterwirken II', page: 97 },
      { book: 'Divinarium Liturgia', page: 249 },
      { book: 'Körperlose Schrecken', page: 156 },
    ],
  },
  {
    name: 'frostschutz',
    label: 'Frostschutz',
    check: ['MU', 'KL', 'IN'],
    traditions: ['Firun (Kälte)', 'Ifirn (Natur)'],
    increaseFactor: IncreaseFactor.B,
    url: 'https://dsa.ulisses-regelwiki.de/zeremonie.html?zeremonie=Frostschutz',
    sources: [
      { book: 'Aventurisches Götterwirken', page: 141 },
      { book: 'Divinarium Liturgia', page: 250 },
    ],
  },
  {
    name: 'fruchtbarkeit',
    label: 'Fruchtbarkeit',
    check: ['MU', 'IN', 'CH'],
    traditions: ['Peraine (Landwirtschaft)', 'Tsa (Wandel)', 'Zsahh (Fürsorge)'],
    increaseFactor: IncreaseFactor.A,
    url: 'https://dsa.ulisses-regelwiki.de/zeremonie.html?zeremonie=Fruchtbarkeit',
    sources: [
      { book: 'Achaz - Schuppenkleid & Lange Zungen', page: 55 },
      { book: 'Aventurisches Götterwirken', page: 141 },
      { book: 'Divinarium Liturgia', page: 251 },
    ],
  },
  {
    name: 'fuchsgestalt',
    label: 'Fuchsgestalt',
    check: ['MU', 'KL', 'IN'],
    traditions: ['Phex (Handel)', 'Phex (Schatten)'],
    increaseFactor: IncreaseFactor.A,
    url: 'https://dsa.ulisses-regelwiki.de/zeremonie.html?zeremonie=Fuchsgestalt',
    sources: [
      { book: 'Aventurisches Götterwirken', page: 142 },
      { book: 'Divinarium Liturgia', page: 252 },
    ],
  },
  {
    name: 'gaensegestalt',
    label: 'Gänsegestalt',
    check: ['MU', 'KL', 'IN'],
    traditions: ['Travia (Freundschaft)', 'Travia (Heim)'],
    increaseFactor: IncreaseFactor.B,
    url: 'https://dsa.ulisses-regelwiki.de/zeremonie.html?zeremonie=G%C3%A4nsegestalt',
    sources: [
      { book: 'Aventurisches Götterwirken', page: 142 },
      { book: 'Divinarium Liturgia', page: 253 },
    ],
  },

  // â”€â”€ Batch 3 (41â€“60) â”€â”€
  {
    name: 'geiergestalt',
    label: 'Geiergestalt',
    check: ['MU', 'KL', 'IN'],
    traditions: ['Marbo (Vergänglichkeit)', 'Marbo (Vision)'],
    increaseFactor: IncreaseFactor.B,
    url: 'https://dsa.ulisses-regelwiki.de/zeremonie.html?zeremonie=Geiergestalt',
    sources: [{ book: 'Divinarium Liturgia', page: 282 }],
  },
  {
    name: 'geistersprache',
    label: 'Geistersprache',
    check: ['MU', 'KL', 'CH'],
    traditions: ['Allgemein-Schamanenritus'],
    increaseFactor: IncreaseFactor.C,
    url: 'https://dsa.ulisses-regelwiki.de/zeremonie.html?zeremonie=Geistersprache',
    sources: [
      { book: 'Aventurisches Götterwirken II', page: 96 },
      { book: 'Das Dornenreich', page: 159 },
      { book: 'Die Dampfenden Dschungel - Der Tiefe Süden & die Waldinseln', page: 159 },
      { book: 'Divinarium Liturgia', page: 283 },
      { book: 'Helden des Wolfsfrosts', page: 69 },
      { book: 'Körperlose Schrecken', page: 156 },
    ],
  },
  {
    name: 'geistheilung',
    label: 'Geistheilung',
    check: ['KL', 'CH', 'KO'],
    traditions: ['Allgemein-Schamanenritus'],
    increaseFactor: IncreaseFactor.B,
    url: 'https://dsa.ulisses-regelwiki.de/zeremonie.html?zeremonie=Geistheilung',
    sources: [
      { book: 'Achaz - Schuppenkleid & Lange Zungen', page: 55 },
      { book: 'Aventurisches Götterwirken II', page: 97 },
      { book: 'Das Wüstenreich', page: 163 },
      { book: 'Die Dampfenden Dschungel - Der Tiefe Süden & die Waldinseln', page: 160 },
      { book: 'Die Gestade des Gottwals - Thorwal und das Gjalskerland', page: 158 },
      { book: 'Divinarium Liturgia', page: 284 },
      { book: 'Geisterwald & Knochenklippen (Die Gestade des Gottwals)', page: 19 },
      { book: 'Helden der Echsensümpfe', page: 69 },
      { book: 'Helden des Gottwals', page: 61 },
      { book: 'Helden des Wolfsfrosts', page: 69 },
    ],
  },
  {
    name: 'geschlechterwechsel',
    label: 'Geschlechterwechsel',
    check: ['MU', 'IN', 'KO'],
    traditions: ["H'Szint (Veränderung)", 'Rahja (Ekstase)', 'Tsa (Wandel)', 'Zsahh (Eidechse)'],
    increaseFactor: IncreaseFactor.C,
    url: 'https://dsa.ulisses-regelwiki.de/zeremonie.html?zeremonie=Geschlechterwechsel',
    sources: [
      { book: 'Achaz - Schuppenkleid & Lange Zungen', page: 55 },
      { book: 'Aventurisches Götterwirken II', page: 97 },
      { book: 'Divinarium Liturgia', page: 285 },
      { book: 'Wege der Vereinigungen', page: 192 },
    ],
  },
  {
    name: 'geschwinderSchritt',
    label: 'Geschwinder Schritt',
    check: ['MU', 'IN', 'CH'],
    traditions: ['Aves (Reise)', 'Shinxir (Taktik)'],
    increaseFactor: IncreaseFactor.A,
    url: 'https://dsa.ulisses-regelwiki.de/zeremonie.html?zeremonie=Geschwinder+Schritt',
    sources: [
      { book: 'Aventurisches Götterwirken', page: 147 },
      { book: 'Divinarium Liturgia', page: 286 },
    ],
  },
  {
    name: 'gespraechMitDenToten',
    label: 'Gespräch mit den Toten',
    check: ['MU', 'KL', 'IN'],
    traditions: ['Boron (Tod)'],
    increaseFactor: IncreaseFactor.C,
    url: 'https://dsa.ulisses-regelwiki.de/zeremonie.html?zeremonie=Gespr%C3%A4ch+mit+den+Toten',
    sources: [
      { book: 'Aventurisches Götterwirken II', page: 98 },
      { book: 'Divinarium Liturgia', page: 287 },
    ],
  },
  {
    name: 'geweihterPanzer',
    label: 'Geweihter Panzer',
    check: ['MU', 'IN', 'CH'],
    traditions: ['Angrosch (Erz)', 'Ingerimm (Feuer)', 'Ingerimm (Handwerk)', 'Kor (Gutes Gold)', 'Rondra (Sturm)', 'Swafnir (Tapferkeit)'],
    increaseFactor: IncreaseFactor.B,
    url: 'https://dsa.ulisses-regelwiki.de/zeremonie.html?zeremonie=Geweihter+Panzer',
    sources: [
      { book: 'Regelwerk', page: 331 },
      { book: 'Aventurisches Götterwirken', page: 169 },
      { book: 'Aventurisches Götterwirken II', page: 74 },
      { book: 'Divinarium Liturgia', page: 289 },
    ],
  },
  {
    name: 'gnadeDesVergessens',
    label: 'Gnade des Vergessens',
    check: ['MU', 'IN', 'CH'],
    traditions: ['Tairachschamanen (Geisterwelt)'],
    increaseFactor: IncreaseFactor.C,
    url: 'https://dsa.ulisses-regelwiki.de/zeremonie.html?zeremonie=Gnade+des+Vergessens',
    sources: [
      { book: 'Bündnis der Wacht (Donnerwacht II)', page: 64 },
      { book: 'Divinarium Liturgia', page: 290 },
      { book: 'Donnerwacht (Kampagne - Sammelband)', page: 142 },
      { book: 'Orks - Hauer & Schwarzer Pelz', page: 51 },
    ],
  },
  {
    name: 'goettlicheErkenntnis',
    label: 'Göttliche Erkenntnis',
    check: ['KL', 'IN', 'CH'],
    traditions: ['Nandus (Bildung)'],
    increaseFactor: IncreaseFactor.B,
    url: 'https://dsa.ulisses-regelwiki.de/zeremonie.html?zeremonie=G%C3%B6ttliche+Erkenntnis',
    sources: [
      { book: 'Aventurisches Götterwirken', page: 147 },
      { book: 'Divinarium Liturgia', page: 291 },
    ],
  },
  {
    name: 'goettlichePraezision',
    label: 'Göttliche Präzision',
    check: ['MU', 'IN', 'KO'],
    traditions: ['Firun (Jagd)', 'Ifirn (Natur)'],
    increaseFactor: IncreaseFactor.B,
    url: 'https://dsa.ulisses-regelwiki.de/zeremonie.html?zeremonie=G%C3%B6ttliche+Pr%C3%A4zision',
    sources: [
      { book: 'Aventurisches Götterwirken II', page: 98 },
      { book: 'Divinarium Liturgia', page: 292 },
    ],
  },
  {
    name: 'greifenruf',
    label: 'Greifenruf',
    check: ['KL', 'IN', 'CH'],
    traditions: ['Praios (Ordnung)'],
    increaseFactor: IncreaseFactor.D,
    url: 'https://dsa.ulisses-regelwiki.de/zeremonie.html?zeremonie=Greifenruf',
    sources: [
      { book: 'Aventurisches Götterwirken', page: 148 },
      { book: 'Divinarium Liturgia', page: 293 },
    ],
  },
  {
    name: 'grosseWaffenweihe',
    label: 'Große Waffenweihe',
    check: ['MU', 'IN', 'CH'],
    traditions: ['Ingerimm (Handwerk)', 'Kor (Guter Kampf)', 'Kor (Gutes Gold)', 'Rondra (Schild)', 'Rondra (Sturm)', 'Shinxir (Taktik)'],
    increaseFactor: IncreaseFactor.D,
    url: 'https://dsa.ulisses-regelwiki.de/zeremonie.html?zeremonie=Gro%C3%9Fe+Waffenweihe',
    sources: [
      { book: 'Aventurisches Götterwirken II', page: 98 },
      { book: 'Divinarium Liturgia', page: 294 },
    ],
  },
  {
    name: 'guterFang',
    label: 'Guter Fang',
    check: ['IN', 'CH', 'KO'],
    traditions: ['Efferd (Wogen)'],
    increaseFactor: IncreaseFactor.B,
    url: 'https://dsa.ulisses-regelwiki.de/zeremonie.html?zeremonie=Guter+Fang',
    sources: [
      { book: 'Aventurisches Götterwirken', page: 149 },
      { book: 'Divinarium Liturgia', page: 296 },
      { book: 'Havena - Versunkene Geheimnisse', page: 86 },
    ],
  },
  {
    name: 'haeutung',
    label: 'Häutung',
    check: ['MU', 'IN', 'CH'],
    traditions: ["H'Szint (Schlange)", "H'Szint (Veränderung)", 'Tsa (Wandel)', 'Zsahh (Eidechse)', 'Zsahh (Fürsorge)'],
    increaseFactor: IncreaseFactor.D,
    url: 'https://dsa.ulisses-regelwiki.de/zeremonie.html?zeremonie=H%C3%A4utung',
    sources: [
      { book: 'Achaz - Schuppenkleid & Lange Zungen', page: 55 },
      { book: 'Aventurisches Götterwirken', page: 149 },
      { book: 'Divinarium Liturgia', page: 297 },
    ],
  },
  {
    name: 'heiligerSchwur',
    label: 'Heiliger Schwur',
    check: ['MU', 'KL', 'CH'],
    traditions: ['Allgemein', 'Allgemein-Schamanenritus'],
    increaseFactor: IncreaseFactor.B,
    url: 'https://dsa.ulisses-regelwiki.de/zeremonie.html?zeremonie=Heiliger+Schwur',
    sources: [
      { book: 'Aventurisches Götterwirken', page: 149 },
      { book: 'Aventurisches Götterwirken II', page: 75 },
      { book: 'Divinarium Liturgia', page: 298 },
    ],
  },
  {
    name: 'heilschlaf',
    label: 'Heilschlaf',
    check: ['MU', 'CH', 'KO'],
    traditions: ['Boron (Traum)', 'Peraine (Heilung)'],
    increaseFactor: IncreaseFactor.B,
    url: 'https://dsa.ulisses-regelwiki.de/zeremonie.html?zeremonie=Heilschlaf',
    sources: [
      { book: 'Aventurisches Götterwirken II', page: 99 },
      { book: 'Divinarium Liturgia', page: 299 },
    ],
  },
  {
    name: 'heilungVonSeelenkranken',
    label: 'Heilung von Seelenkranken',
    check: ['MU', 'IN', 'CH'],
    traditions: ['Boron (Traum)', 'Marbo (Vision)'],
    increaseFactor: IncreaseFactor.B,
    url: 'https://dsa.ulisses-regelwiki.de/zeremonie.html?zeremonie=Heilung+von+Seelenkranken',
    sources: [
      { book: 'Aventurisches Götterwirken II', page: 99 },
      { book: 'Divinarium Liturgia', page: 300 },
    ],
  },
  {
    name: 'herrDerMeere',
    label: 'Herr der Meere',
    check: ['MU', 'IN', 'CH'],
    traditions: ['Swafnir (Kraft)'],
    increaseFactor: IncreaseFactor.B,
    url: 'https://dsa.ulisses-regelwiki.de/zeremonie.html?zeremonie=Herr+der+Meere',
    sources: [
      { book: 'Aventurisches Götterwirken', page: 149 },
      { book: 'Divinarium Liturgia', page: 301 },
    ],
  },
  {
    name: 'hilfeInDerNot',
    label: 'Hilfe in der Not',
    check: ['KL', 'IN', 'CH'],
    traditions: ['Aves (Schicksal)', 'Ifirn (Hilfsbereitschaft)'],
    increaseFactor: IncreaseFactor.A,
    url: 'https://dsa.ulisses-regelwiki.de/zeremonie.html?zeremonie=Hilfe+in+der+Not',
    sources: [
      { book: 'Aventurisches Götterwirken', page: 150 },
      { book: 'Divinarium Liturgia', page: 302 },
      { book: 'Helden des Wolfsfrosts', page: 69 },
    ],
  },
  {
    name: 'himmlischeSchatzkammer',
    label: 'Himmlische Schatzkammer',
    check: ['MU', 'IN', 'CH'],
    traditions: ['Phex (Handel)'],
    increaseFactor: IncreaseFactor.D,
    url: 'https://dsa.ulisses-regelwiki.de/zeremonie.html?zeremonie=Himmlische+Schatzkammer',
    sources: [
      { book: 'Aventurisches Götterwirken II', page: 99 },
      { book: 'Divinarium Liturgia', page: 303 },
    ],
  },

  // â”€â”€ Batch 4 (61â€“80) â”€â”€
  {
    name: 'hundegestalt',
    label: 'Hundegestalt',
    check: ['MU', 'KL', 'IN'],
    traditions: ['Angrosch (Erz)', 'Angrosch (Flammen)', 'Ingerimm (Feuer)', 'Ingerimm (Handwerk)'],
    increaseFactor: IncreaseFactor.A,
    url: 'https://dsa.ulisses-regelwiki.de/zeremonie.html?zeremonie=Hundegestalt',
    sources: [
      { book: 'Aventurisches Götterwirken II', page: 100 },
      { book: 'Divinarium Liturgia', page: 304 },
    ],
  },
  {
    name: 'inspiration',
    label: 'Inspiration',
    check: ['MU', 'KL', 'IN'],
    traditions: ['Hesinde (Wissen)', 'Tsa (Freiheit)'],
    increaseFactor: IncreaseFactor.B,
    url: 'https://dsa.ulisses-regelwiki.de/zeremonie.html?zeremonie=Inspiration',
    sources: [
      { book: 'Aventurisches Götterwirken', page: 150 },
      { book: 'Divinarium Liturgia', page: 305 },
    ],
  },
  {
    name: 'jagdglueck',
    label: 'Jagdglück',
    check: ['MU', 'IN', 'CH'],
    traditions: [
      'Ferkinaschamanen (Tier)',
      'Firun (Jagd)',
      'Fjarningerschamanen (Eis)',
      'Gjalskerschamanen (Gemeinschaft)',
      'Gjalskerschamanen (Wildheit)',
      'Nivesenschamanen (Winter)',
      'Tahayaschamanen (Dschungel)',
      'Trollzackerschamanen (Leiden)',
    ],
    increaseFactor: IncreaseFactor.A,
    url: 'https://dsa.ulisses-regelwiki.de/zeremonie.html?zeremonie=Jagdgl%C3%BCck',
    sources: [
      { book: 'Aventurisches Götterwirken', page: 150 },
      { book: 'Aventurisches Götterwirken II', page: 75 },
      { book: 'Divinarium Liturgia', page: 306 },
      { book: 'Geisterwald & Knochenklippen (Die Gestade des Gottwals)', page: 18 },
    ],
  },
  {
    name: 'jaguargestalt',
    label: 'Jaguargestalt',
    check: ['MU', 'KL', 'IN'],
    traditions: ['Tahayaschamanen (Dschungel)', 'Tahayaschamanen (Sonne)'],
    increaseFactor: IncreaseFactor.C,
    url: 'https://dsa.ulisses-regelwiki.de/zeremonie.html?zeremonie=Jaguargestalt',
    sources: [
      { book: 'Aventurisches Götterwirken II', page: 100 },
      { book: 'Die Dampfenden Dschungel - Der Tiefe Süden & die Waldinseln', page: 160 },
      { book: 'Divinarium Liturgia', page: 308 },
    ],
  },
  {
    name: 'jugendlichkeit',
    label: 'Jugendlichkeit',
    check: ['MU', 'IN', 'CH'],
    traditions: ['Namenloser', 'Rahja (Harmonie)', 'Tsa (Wandel)', 'Zsahh (Eidechse)', 'Zsahh (Fürsorge)'],
    increaseFactor: IncreaseFactor.D,
    url: 'https://dsa.ulisses-regelwiki.de/zeremonie.html?zeremonie=Jugendlichkeit',
    sources: [
      { book: 'Achaz - Schuppenkleid & Lange Zungen', page: 56 },
      { book: 'Aventurisches Götterwirken', page: 151 },
      { book: 'Divinarium Liturgia', page: 309 },
    ],
  },
  {
    name: 'kleineMoralstaerkung',
    label: 'Kleine Moralstärkung',
    check: ['MU', 'IN', 'CH'],
    traditions: ['Aves (Schicksal)', 'Efferd (Wogen)', 'Swafnir (Tapferkeit)'],
    increaseFactor: IncreaseFactor.B,
    url: 'https://dsa.ulisses-regelwiki.de/zeremonie.html?zeremonie=Kleine+Moralst%C3%A4rkung',
    sources: [
      { book: 'Aventurisches Götterwirken', page: 151 },
      { book: 'Divinarium Liturgia', page: 310 },
    ],
  },
  {
    name: 'kriegszustand',
    label: 'Kriegszustand',
    check: ['MU', 'IN', 'CH'],
    traditions: ['Rondra (Schild)', 'Rondra (Sturm)'],
    increaseFactor: IncreaseFactor.D,
    url: 'https://dsa.ulisses-regelwiki.de/zeremonie.html?zeremonie=Kriegszustand',
    sources: [
      { book: 'Aventurisches Götterwirken II', page: 101 },
      { book: 'Divinarium Liturgia', page: 311 },
    ],
  },
  {
    name: 'laeuterungDesErzes',
    label: 'Läuterung des Erzes',
    check: ['MU', 'KL', 'IN'],
    traditions: ['Angrosch (Erz)', 'Gravesh (Brand)', 'Ingerimm (Handwerk)'],
    increaseFactor: IncreaseFactor.C,
    url: 'https://dsa.ulisses-regelwiki.de/zeremonie.html?zeremonie=L%C3%A4uterung+des+Erzes',
    sources: [
      { book: 'Aventurisches Götterwirken', page: 151 },
      { book: 'Aventurisches Götterwirken II', page: 74 },
      { book: 'Divinarium Liturgia', page: 312 },
    ],
  },
  {
    name: 'lebenstausch',
    label: 'Lebenstausch',
    check: ['MU', 'IN', 'KO'],
    traditions: ['Marbo (Vergänglichkeit)', 'Marbo (Vision)'],
    increaseFactor: IncreaseFactor.C,
    url: 'https://dsa.ulisses-regelwiki.de/zeremonie.html?zeremonie=Lebenstausch',
    sources: [
      { book: 'Aventurisches Götterwirken II', page: 102 },
      { book: 'Divinarium Liturgia', page: 313 },
    ],
  },
  {
    name: 'leichtfuessig',
    label: 'Leichtfüssig',
    check: ['IN', 'CH', 'GE'],
    traditions: ['Aves (Reise)', 'Tsa (Freiheit)'],
    increaseFactor: IncreaseFactor.B,
    url: 'https://dsa.ulisses-regelwiki.de/zeremonie.html?zeremonie=Leichtf%C3%BCssig',
    sources: [
      { book: 'Aventurisches Götterwirken II', page: 102 },
      { book: 'Divinarium Liturgia', page: 314 },
    ],
  },
  {
    name: 'leitendeStroemung',
    label: 'Leitende Strömung',
    check: ['KL', 'KL', 'IN'],
    traditions: ['Numinoru (Unendliche Tiefe)'],
    increaseFactor: IncreaseFactor.C,
    url: 'https://dsa.ulisses-regelwiki.de/zeremonie.html?zeremonie=Leitende+Str%C3%B6mung',
    sources: [
      { book: 'Divinarium Liturgia', page: 315 },
      { book: 'Unendlichkeit & Tiefenrausch', page: 20 },
    ],
  },
  {
    name: 'liebestaetowierung',
    label: 'Liebestätowierung',
    check: ['IN', 'CH', 'FF'],
    traditions: ['Rahja (Ekstase)', 'Rahja (Harmonie)'],
    increaseFactor: IncreaseFactor.A,
    url: 'https://dsa.ulisses-regelwiki.de/zeremonie.html?zeremonie=Liebestat%C3%B6wierung',
    sources: [
      { book: 'Aventurisches Götterwirken II', page: 102 },
      { book: 'Divinarium Liturgia', page: 316 },
      { book: 'Wege der Vereinigungen', page: 194 },
    ],
  },
  {
    name: 'liturgieabsorption',
    label: 'Liturgieabsorption',
    check: ['MU', 'MU', 'IN'],
    traditions: ['Namenloser'],
    increaseFactor: IncreaseFactor.D,
    url: 'https://dsa.ulisses-regelwiki.de/zeremonie.html?zeremonie=Liturgieabsorption',
    sources: [
      { book: 'Aventurisches Götterwirken', page: 152 },
      { book: 'Divinarium Liturgia', page: 317 },
    ],
  },
  {
    name: 'loewengestalt',
    label: 'Löwengestalt',
    check: ['MU', 'KL', 'IN'],
    traditions: ['Rondra (Schild)', 'Rondra (Sturm)'],
    increaseFactor: IncreaseFactor.B,
    url: 'https://dsa.ulisses-regelwiki.de/zeremonie.html?zeremonie=L%C3%B6wengestalt',
    sources: [
      { book: 'Regelwerk', page: 332 },
      { book: 'Aventurisches Götterwirken', page: 169 },
      { book: 'Divinarium Liturgia', page: 318 },
    ],
  },
  {
    name: 'luchsgestalt',
    label: 'Luchsgestalt',
    check: ['MU', 'KL', 'IN'],
    traditions: ['Praios (Antimagie)', 'Praios (Ordnung)'],
    increaseFactor: IncreaseFactor.B,
    url: 'https://dsa.ulisses-regelwiki.de/zeremonie.html?zeremonie=Luchsgestalt',
    sources: [
      { book: 'Aventurisches Götterwirken II', page: 102 },
      { book: 'Divinarium Liturgia', page: 319 },
    ],
  },
  {
    name: 'machtvollerExorzismus',
    label: 'Machtvoller Exorzismus',
    check: ['MU', 'IN', 'CH'],
    traditions: ['Boron (Traum)', 'Praios (Antimagie)'],
    increaseFactor: IncreaseFactor.C,
    url: 'https://dsa.ulisses-regelwiki.de/zeremonie.html?zeremonie=Machtvoller+Exorzismus',
    sources: [
      { book: 'Aventurisches Götterwirken II', page: 103 },
      { book: 'Divinarium Liturgia', page: 320 },
    ],
  },
  {
    name: 'makelloserLeib',
    label: 'Makelloser Leib',
    check: ['MU', 'IN', 'CH'],
    traditions: ['Rahja (Harmonie)', 'Tsa (Wandel)'],
    increaseFactor: IncreaseFactor.B,
    url: 'https://dsa.ulisses-regelwiki.de/zeremonie.html?zeremonie=Makelloser+Leib',
    sources: [
      { book: 'Aventurisches Götterwirken', page: 152 },
      { book: 'Divinarium Liturgia', page: 321 },
    ],
  },
  {
    name: 'marbidenmacht',
    label: 'Marbidenmacht',
    check: ['MU', 'KL', 'CH'],
    traditions: ['Marbo (Vergänglichkeit)'],
    increaseFactor: IncreaseFactor.B,
    url: 'https://dsa.ulisses-regelwiki.de/zeremonie.html?zeremonie=Marbidenmacht',
    sources: [
      { book: 'Aventurisches Götterwirken II', page: 103 },
      { book: 'Divinarium Liturgia', page: 322 },
    ],
  },
  {
    name: 'metallerhitzung',
    label: 'Metallerhitzung',
    check: ['MU', 'KL', 'IN'],
    traditions: ['Angrosch (Erz)', 'Gravesh (Brand)', 'Gravesh (Metall)', 'Ingerimm (Handwerk)'],
    increaseFactor: IncreaseFactor.B,
    url: 'https://dsa.ulisses-regelwiki.de/zeremonie.html?zeremonie=Metallerhitzung',
    sources: [
      { book: 'Aventurisches Götterwirken', page: 152 },
      { book: 'Aventurisches Götterwirken II', page: 74 },
      { book: 'Divinarium Liturgia', page: 323 },
    ],
  },
  {
    name: 'moralstaerkung',
    label: 'Moralstärkung',
    check: ['MU', 'IN', 'CH'],
    traditions: ['Efferd (Wogen)'],
    increaseFactor: IncreaseFactor.C,
    url: 'https://dsa.ulisses-regelwiki.de/zeremonie.html?zeremonie=Moralst%C3%A4rkung',
    sources: [
      { book: 'Aventurisches Götterwirken', page: 153 },
      { book: 'Divinarium Liturgia', page: 325 },
    ],
  },

  // â”€â”€ Batch 5 (81â€“100) â”€â”€
  {
    name: 'mungogestalt',
    label: 'Mungogestalt',
    check: ['MU', 'KL', 'IN'],
    traditions: ['Phex (Handel)', 'Phex (Schatten)'],
    increaseFactor: IncreaseFactor.B,
    url: 'https://dsa.ulisses-regelwiki.de/zeremonie.html?zeremonie=Mungogestalt',
    sources: [
      { book: 'Aventurisches Götterwirken II', page: 104 },
      { book: 'Das Dornenreich', page: 161 },
      { book: 'Divinarium Liturgia', page: 326 },
    ],
  },
  {
    name: 'nahrungsreinigung',
    label: 'Nahrungsreinigung',
    check: ['MU', 'KL', 'IN'],
    traditions: ['Travia (Heim)'],
    increaseFactor: IncreaseFactor.A,
    url: 'https://dsa.ulisses-regelwiki.de/zeremonie.html?zeremonie=Nahrungsreinigung',
    sources: [
      { book: 'Aventurisches Götterwirken', page: 153 },
      { book: 'Divinarium Liturgia', page: 327 },
    ],
  },
  {
    name: 'nebelleib',
    label: 'Nebelleib',
    check: ['KL', 'IN', 'CH'],
    traditions: ['Efferd (Wind)', 'Phex (Schatten)'],
    increaseFactor: IncreaseFactor.B,
    url: 'https://dsa.ulisses-regelwiki.de/zeremonie.html?zeremonie=Nebelleib',
    sources: [
      { book: 'Regelwerk', page: 332 },
      { book: 'Aventurisches Götterwirken', page: 169 },
      { book: 'Divinarium Liturgia', page: 328 },
    ],
  },
  {
    name: 'nebelschwaden',
    label: 'Nebelschwaden',
    check: ['IN', 'CH', 'KO'],
    traditions: ["Chr'Ssir'Ssr (Wetter)", 'Efferd (Wind)'],
    increaseFactor: IncreaseFactor.B,
    url: 'https://dsa.ulisses-regelwiki.de/zeremonie.html?zeremonie=Nebelschwaden',
    sources: [
      { book: 'Achaz - Schuppenkleid & Lange Zungen', page: 56 },
      { book: 'Aventurisches Götterwirken', page: 153 },
      { book: 'Divinarium Liturgia', page: 329 },
      { book: 'Havena - Versunkene Geheimnisse', page: 85 },
    ],
  },
  {
    name: 'numinorusFluch',
    label: 'Numinorus Fluch',
    check: ['MU', 'CH', 'KO'],
    traditions: ['Numinoru (Reißender Strudel)'],
    increaseFactor: IncreaseFactor.D,
    url: 'https://dsa.ulisses-regelwiki.de/zeremonie.html?zeremonie=Numinorus+Fluch',
    sources: [
      { book: 'Divinarium Liturgia', page: 330 },
      { book: 'Unendlichkeit & Tiefenrausch', page: 20 },
    ],
  },
  {
    name: 'objektweihe',
    label: 'Objektweihe',
    check: ['KL', 'IN', 'CH'],
    traditions: ['Allgemein', 'Allgemein-Schamanenritus', 'Numinoru (Reißender Strudel)', 'Numinoru (Unendliche Tiefe)'],
    increaseFactor: IncreaseFactor.C,
    url: 'https://dsa.ulisses-regelwiki.de/zeremonie.html?zeremonie=Objektweihe',
    sources: [
      { book: 'Regelwerk', page: 333 },
      { book: 'Aventurisches Götterwirken', page: 169 },
      { book: 'Aventurisches Götterwirken II', page: 75 },
      { book: 'Divinarium Liturgia', page: 331 },
      { book: 'Unendlichkeit & Tiefenrausch', page: 21 },
    ],
  },
  {
    name: 'ogerbindung',
    label: 'Ogerbindung',
    check: ['MU', 'IN', 'CH'],
    traditions: ['Tairachschamanen (Zauberei)'],
    increaseFactor: IncreaseFactor.D,
    url: 'https://dsa.ulisses-regelwiki.de/zeremonie.html?zeremonie=Ogerbindung',
    sources: [
      { book: 'Divinarium Liturgia', page: 332 },
      { book: 'Orks - Hauer & Schwarzer Pelz', page: 51 },
    ],
  },
  {
    name: 'ortsweihe',
    label: 'Ortsweihe (Sanctum)',
    check: ['MU', 'IN', 'CH'],
    traditions: ['Allgemein', 'Allgemein-Schamanenritus'],
    increaseFactor: IncreaseFactor.D,
    url: 'https://dsa.ulisses-regelwiki.de/zeremonie.html?zeremonie=Ortsweihe+(Sanctum)',
    sources: [
      { book: 'Aventurisches Götterwirken', page: 153 },
      { book: 'Aventurisches Götterwirken II', page: 75 },
      { book: 'Divinarium Liturgia', page: 333 },
    ],
  },
  {
    name: 'panthergestalt',
    label: 'Panthergestalt',
    check: ['MU', 'KL', 'IN'],
    traditions: ['Kor (Guter Kampf)', 'Kor (Gutes Gold)'],
    increaseFactor: IncreaseFactor.C,
    url: 'https://dsa.ulisses-regelwiki.de/zeremonie.html?zeremonie=Panthergestalt',
    sources: [
      { book: 'Aventurisches Götterwirken', page: 154 },
      { book: 'Divinarium Liturgia', page: 335 },
    ],
  },
  {
    name: 'paradiesvogelgestalt',
    label: 'Paradiesvogelgestalt',
    check: ['MU', 'KL', 'IN'],
    traditions: ['Aves (Reise)', 'Aves (Schicksal)'],
    increaseFactor: IncreaseFactor.B,
    url: 'https://dsa.ulisses-regelwiki.de/zeremonie.html?zeremonie=Paradiesvogelgestalt',
    sources: [
      { book: 'Aventurisches Götterwirken', page: 154 },
      { book: 'Divinarium Liturgia', page: 336 },
    ],
  },
  {
    name: 'pferdegestalt',
    label: 'Pferdegestalt',
    check: ['MU', 'KL', 'IN'],
    traditions: ['Rahja (Ekstase)', 'Rahja (Harmonie)'],
    increaseFactor: IncreaseFactor.B,
    url: 'https://dsa.ulisses-regelwiki.de/zeremonie.html?zeremonie=Pferdegestalt',
    sources: [
      { book: 'Aventurisches Götterwirken', page: 155 },
      { book: 'Divinarium Liturgia', page: 337 },
    ],
  },
  {
    name: 'pflanzenkraft',
    label: 'Pflanzenkraft',
    check: ['KL', 'IN', 'IN'],
    traditions: ['Allgemein-Schamanenritus'],
    increaseFactor: IncreaseFactor.A,
    url: 'https://dsa.ulisses-regelwiki.de/zeremonie.html?zeremonie=Pflanzenkraft',
    sources: [
      { book: 'Aventurisches Herbarium', page: 145 },
      { book: 'Divinarium Liturgia', page: 338 },
    ],
  },
  {
    name: 'priesterweihe',
    label: 'Priesterweihe (Ordination)',
    check: ['MU', 'IN', 'CH'],
    traditions: ['Allgemein', 'Allgemein-Schamanenritus'],
    increaseFactor: IncreaseFactor.D,
    url: 'https://dsa.ulisses-regelwiki.de/zeremonie.html?zeremonie=Priesterweihe+(Ordination)',
    sources: [
      { book: 'Aventurisches Götterwirken', page: 155 },
      { book: 'Aventurisches Götterwirken II', page: 75 },
      { book: 'Divinarium Liturgia', page: 339 },
    ],
  },
  {
    name: 'rabengestalt',
    label: 'Rabengestalt',
    check: ['MU', 'KL', 'IN'],
    traditions: ['Boron (Tod)', 'Boron (Traum)', 'Marbo (Vergänglichkeit)', 'Marbo (Vision)'],
    increaseFactor: IncreaseFactor.B,
    url: 'https://dsa.ulisses-regelwiki.de/zeremonie.html?zeremonie=Rabengestalt',
    sources: [
      { book: 'Aventurisches Götterwirken', page: 155 },
      { book: 'Aventurisches Götterwirken II', page: 74 },
      { book: 'Divinarium Liturgia', page: 342 },
    ],
  },
  {
    name: 'ratDerAhnen',
    label: 'Rat der Ahnen',
    check: ['MU', 'IN', 'CH'],
    traditions: ['Allgemein-Schamanenritus'],
    increaseFactor: IncreaseFactor.C,
    url: 'https://dsa.ulisses-regelwiki.de/zeremonie.html?zeremonie=Rat+der+Ahnen',
    sources: [
      { book: 'Achaz - Schuppenkleid & Lange Zungen', page: 56 },
      { book: 'Aventurisches Götterwirken II', page: 104 },
      { book: 'Die Dampfenden Dschungel - Der Tiefe Süden & die Waldinseln', page: 161 },
      { book: 'Divinarium Liturgia', page: 343 },
      { book: 'Helden der Echsensümpfe', page: 70 },
      { book: 'Helden des Wolfsfrosts', page: 69 },
      { book: 'Körperlose Schrecken', page: 157 },
    ],
  },
  {
    name: 'regenkontrolle',
    label: 'Regenkontrolle',
    check: ['MU', 'IN', 'CH'],
    traditions: ["Chr'Ssir'Ssr (Wetter)", 'Efferd (Wind)'],
    increaseFactor: IncreaseFactor.B,
    url: 'https://dsa.ulisses-regelwiki.de/zeremonie.html?zeremonie=Regenkontrolle',
    sources: [
      { book: 'Achaz - Schuppenkleid & Lange Zungen', page: 56 },
      { book: 'Aventurisches Götterwirken II', page: 104 },
      { book: 'Divinarium Liturgia', page: 344 },
    ],
  },
  {
    name: 'reisesegen',
    label: 'Reisesegen',
    check: ['MU', 'IN', 'CH'],
    traditions: ['Aves (Reise)', 'Aves (Schicksal)', 'Firun (Jagd)', 'Travia (Freundschaft)'],
    increaseFactor: IncreaseFactor.C,
    url: 'https://dsa.ulisses-regelwiki.de/zeremonie.html?zeremonie=Reisesegen',
    sources: [
      { book: 'Aventurisches Götterwirken', page: 156 },
      { book: 'Divinarium Liturgia', page: 345 },
    ],
  },
  {
    name: 'saettigung',
    label: 'Sättigung',
    check: ['MU', 'KL', 'CH'],
    traditions: ['Peraine (Landwirtschaft)', 'Travia (Freundschaft)'],
    increaseFactor: IncreaseFactor.B,
    url: 'https://dsa.ulisses-regelwiki.de/zeremonie.html?zeremonie=S%C3%A4ttigung',
    sources: [
      { book: 'Aventurisches Götterwirken', page: 156 },
      { book: 'Divinarium Liturgia', page: 346 },
    ],
  },
  {
    name: 'schaffenskraft',
    label: 'Schaffenskraft',
    check: ['IN', 'CH', 'FF'],
    traditions: ['Angrosch (Erz)', 'Ingerimm (Handwerk)'],
    increaseFactor: IncreaseFactor.B,
    url: 'https://dsa.ulisses-regelwiki.de/zeremonie.html?zeremonie=Schaffenskraft',
    sources: [
      { book: 'Aventurisches Götterwirken II', page: 105 },
      { book: 'Die Flusslande - Der Kosch und die Nordmarken', page: 161 },
      { book: 'Divinarium Liturgia', page: 348 },
    ],
  },
  {
    name: 'schattenrochengestalt',
    label: 'Schattenrochengestalt',
    check: ['MU', 'KL', 'IN'],
    traditions: ['Numinoru (Reißender Strudel)', 'Numinoru (Unendliche Tiefe)'],
    increaseFactor: IncreaseFactor.C,
    url: 'https://dsa.ulisses-regelwiki.de/zeremonie.html?zeremonie=Schattenrochengestalt',
    sources: [
      { book: 'Divinarium Liturgia', page: 349 },
      { book: 'Unendlichkeit & Tiefenrausch', page: 21 },
    ],
  },

  // â”€â”€ Batch 6 (101â€“120) â”€â”€
  {
    name: 'schlangenfluch',
    label: 'Schlangenfluch',
    check: ['MU', 'KL', 'CH'],
    traditions: ['Tahayaschamanen (Dschungel)'],
    increaseFactor: IncreaseFactor.C,
    url: 'https://dsa.ulisses-regelwiki.de/zeremonie.html?zeremonie=Schlangenfluch',
    sources: [
      { book: 'Aventurisches Götterwirken II', page: 105 },
      { book: 'Die Dampfenden Dschungel - Der Tiefe Süden & die Waldinseln', page: 161 },
      { book: 'Divinarium Liturgia', page: 350 },
    ],
  },
  {
    name: 'schlangengestalt',
    label: 'Schlangengestalt',
    check: ['MU', 'KL', 'IN'],
    traditions: ['Hesinde (Magie)', 'Hesinde (Wissen)', "H'Szint (Schlange)"],
    increaseFactor: IncreaseFactor.A,
    url: 'https://dsa.ulisses-regelwiki.de/zeremonie.html?zeremonie=Schlangengestalt',
    sources: [
      { book: 'Achaz - Schuppenkleid & Lange Zungen', page: 56 },
      { book: 'Aventurisches Götterwirken', page: 157 },
      { book: 'Divinarium Liturgia', page: 351 },
    ],
  },
  {
    name: 'schmetterlingsgestalt',
    label: 'Schmetterlingsgestalt',
    check: ['MU', 'KL', 'IN'],
    traditions: ['Rahja (Ekstase)', 'Rahja (Harmonie)'],
    increaseFactor: IncreaseFactor.B,
    url: 'https://dsa.ulisses-regelwiki.de/zeremonie.html?zeremonie=Schmetterlingsgestalt',
    sources: [
      { book: 'Aventurisches Götterwirken II', page: 105 },
      { book: 'Divinarium Liturgia', page: 352 },
    ],
  },
  {
    name: 'schwanengestalt',
    label: 'Schwanengestalt',
    check: ['MU', 'KL', 'IN'],
    traditions: ['Ifirn (Hilfsbereitschaft)', 'Ifirn (Natur)'],
    increaseFactor: IncreaseFactor.B,
    url: 'https://dsa.ulisses-regelwiki.de/zeremonie.html?zeremonie=Schwanengestalt',
    sources: [
      { book: 'Aventurisches Götterwirken', page: 157 },
      { book: 'Divinarium Liturgia', page: 353 },
    ],
  },
  {
    name: 'seelenbannung',
    label: 'Seelenbannung',
    check: ['MU', 'IN', 'CH'],
    traditions: ['Namenloser'],
    increaseFactor: IncreaseFactor.D,
    url: 'https://dsa.ulisses-regelwiki.de/zeremonie.html?zeremonie=Seelenbannung',
    sources: [
      { book: 'Aventurisches Götterwirken', page: 158 },
      { book: 'Divinarium Liturgia', page: 354 },
    ],
  },
  {
    name: 'seelenpruefung',
    label: 'Seelenprüfung',
    check: ['MU', 'KL', 'IN'],
    traditions: ['Allgemein', 'Allgemein-Schamanenritus'],
    increaseFactor: IncreaseFactor.C,
    url: 'https://dsa.ulisses-regelwiki.de/zeremonie.html?zeremonie=Seelenpr%C3%BCfung',
    sources: [
      { book: 'Aventurisches Götterwirken', page: 158 },
      { book: 'Aventurisches Götterwirken II', page: 75 },
      { book: 'Divinarium Liturgia', page: 355 },
    ],
  },
  {
    name: 'seemonsterruf',
    label: 'Seemonsterruf',
    check: ['MU', 'CH', 'KO'],
    traditions: ['Numinoru (Reißender Strudel)'],
    increaseFactor: IncreaseFactor.D,
    url: 'https://dsa.ulisses-regelwiki.de/zeremonie.html?zeremonie=Seemonsterruf',
    sources: [
      { book: 'Divinarium Liturgia', page: 356 },
      { book: 'Unendlichkeit & Tiefenrausch', page: 21 },
    ],
  },
  {
    name: 'segnungDesHeims',
    label: 'Segnung des Heims',
    check: ['MU', 'IN', 'CH'],
    traditions: ['Travia (Heim)'],
    increaseFactor: IncreaseFactor.B,
    url: 'https://dsa.ulisses-regelwiki.de/zeremonie.html?zeremonie=Segnung+des+Heims',
    sources: [
      { book: 'Aventurisches Götterwirken', page: 158 },
      { book: 'Divinarium Liturgia', page: 357 },
    ],
  },
  {
    name: 'selbstopferung',
    label: 'Selbstopferung',
    check: ['MU', 'MU', 'KO'],
    traditions: ['Ferkinaschamanen (Blut)', 'Nivesenschamanen (Winter)', 'Trollzackerschamanen (Leiden)'],
    increaseFactor: IncreaseFactor.B,
    url: 'https://dsa.ulisses-regelwiki.de/zeremonie.html?zeremonie=Selbstopferung',
    sources: [
      { book: 'Aventurisches Götterwirken II', page: 106 },
      { book: 'Divinarium Liturgia', page: 359 },
    ],
  },
  {
    name: 'sichererTritt',
    label: 'Sicherer Tritt',
    check: ['IN', 'CH', 'GE'],
    traditions: ['Firun (Kälte)'],
    increaseFactor: IncreaseFactor.B,
    url: 'https://dsa.ulisses-regelwiki.de/zeremonie.html?zeremonie=Sicherer+Tritt',
    sources: [
      { book: 'Aventurisches Götterwirken', page: 158 },
      { book: 'Divinarium Liturgia', page: 360 },
    ],
  },
  {
    name: 'sippenbann',
    label: 'Sippenbann',
    check: ['MU', 'IN', 'CH'],
    traditions: ['Allgemein-Schamanenritus'],
    increaseFactor: IncreaseFactor.D,
    url: 'https://dsa.ulisses-regelwiki.de/zeremonie.html?zeremonie=Sippenbann',
    sources: [
      { book: 'Aventurisches Götterwirken II', page: 106 },
      { book: 'Divinarium Liturgia', page: 361 },
    ],
  },
  {
    name: 'speisung',
    label: 'Speisung',
    check: ['MU', 'IN', 'CH'],
    traditions: ['Travia (Heim)'],
    increaseFactor: IncreaseFactor.B,
    url: 'https://dsa.ulisses-regelwiki.de/zeremonie.html?zeremonie=Speisung',
    sources: [
      { book: 'Aventurisches Götterwirken', page: 159 },
      { book: 'Divinarium Liturgia', page: 362 },
    ],
  },
  {
    name: 'staerkungDerWildnis',
    label: 'Stärkung der Wildnis',
    check: ['MU', 'IN', 'KO'],
    traditions: ['Firun (Jagd)'],
    increaseFactor: IncreaseFactor.C,
    url: 'https://dsa.ulisses-regelwiki.de/zeremonie.html?zeremonie=St%C3%A4rkung+der+Wildnis',
    sources: [
      { book: 'Aventurisches Götterwirken II', page: 106 },
      { book: 'Divinarium Liturgia', page: 363 },
    ],
  },
  {
    name: 'staubUndSchimmel',
    label: 'Staub und Schimmel',
    check: ['IN', 'CH', 'KO'],
    traditions: ['Namenloser'],
    increaseFactor: IncreaseFactor.C,
    url: 'https://dsa.ulisses-regelwiki.de/zeremonie.html?zeremonie=Staub+und+Schimmel',
    sources: [
      { book: 'Aventurisches Götterwirken', page: 159 },
      { book: 'Divinarium Liturgia', page: 365 },
    ],
  },
  {
    name: 'storchengestalt',
    label: 'Storchengestalt',
    check: ['MU', 'KL', 'IN'],
    traditions: ['Peraine (Heilung)', 'Peraine (Landwirtschaft)'],
    increaseFactor: IncreaseFactor.B,
    url: 'https://dsa.ulisses-regelwiki.de/zeremonie.html?zeremonie=Storchengestalt',
    sources: [
      { book: 'Aventurisches Götterwirken', page: 159 },
      { book: 'Divinarium Liturgia', page: 366 },
    ],
  },
  {
    name: 'tabuZone',
    label: 'Tabu-Zone',
    check: ['KL', 'IN', 'CH'],
    traditions: ['Allgemein-Schamanenritus'],
    increaseFactor: IncreaseFactor.C,
    url: 'https://dsa.ulisses-regelwiki.de/zeremonie.html?zeremonie=Tabu-Zone',
    sources: [
      { book: 'Aventurisches Götterwirken II', page: 107 },
      { book: 'Die Dampfenden Dschungel - Der Tiefe Süden & die Waldinseln', page: 161 },
      { book: 'Divinarium Liturgia', page: 367 },
    ],
  },
  {
    name: 'tairachsMachtvolleErhebungVonUntoten',
    label: 'Tairachs machtvolle Erhebung von Untoten',
    check: ['MU', 'MU', 'IN'],
    traditions: ['Tairachschamanen (Geisterwelt)', 'Tairachschamanen (Zauberei)'],
    increaseFactor: IncreaseFactor.D,
    url: 'https://dsa.ulisses-regelwiki.de/zeremonie.html?zeremonie=Tairachs+machtvolle+Erhebung+von+Untoten',
    sources: [
      { book: 'Bündnis der Wacht (Donnerwacht II)', page: 64 },
      { book: 'Divinarium Liturgia', page: 368 },
      { book: 'Donnerwacht (Kampagne - Sammelband)', page: 142 },
      { book: 'Orks - Hauer & Schwarzer Pelz', page: 51 },
    ],
  },
  {
    name: 'talismanverankerung',
    label: 'Talismanverankerung',
    check: ['KL', 'IN', 'CH'],
    traditions: ['Allgemein'],
    increaseFactor: IncreaseFactor.C,
    url: 'https://dsa.ulisses-regelwiki.de/zeremonie.html?zeremonie=Talismanverankerung',
    sources: [
      { book: 'Aventurisches Götterwirken II', page: 107 },
      { book: 'Divinarium Liturgia', page: 369 },
    ],
  },
  {
    name: 'taubengestalt',
    label: 'Taubengestalt',
    check: ['MU', 'KL', 'IN'],
    traditions: ['Marbo (Vergänglichkeit)', 'Marbo (Vision)'],
    increaseFactor: IncreaseFactor.B,
    url: 'https://dsa.ulisses-regelwiki.de/zeremonie.html?zeremonie=Taubengestalt',
    sources: [
      { book: 'Aventurisches Götterwirken II', page: 107 },
      { book: 'Divinarium Liturgia', page: 370 },
    ],
  },
  {
    name: 'tempelweihe',
    label: 'Tempelweihe (Konsekration)',
    check: ['MU', 'IN', 'CH'],
    traditions: ['Allgemein'],
    increaseFactor: IncreaseFactor.C,
    url: 'https://dsa.ulisses-regelwiki.de/zeremonie.html?zeremonie=Tempelweihe+(Konsekration)',
    sources: [
      { book: 'Aventurisches Götterwirken', page: 160 },
      { book: 'Divinarium Liturgia', page: 371 },
    ],
  },

  // â”€â”€ Batch 7 (121â€“138) â”€â”€
  {
    name: 'traumbild',
    label: 'Traumbild',
    check: ['KL', 'IN', 'CH'],
    traditions: ['Boron (Traum)', 'Marbo (Vision)'],
    increaseFactor: IncreaseFactor.B,
    url: 'https://dsa.ulisses-regelwiki.de/zeremonie.html?zeremonie=Traumbild',
    sources: [
      { book: 'Aventurisches Götterwirken', page: 160 },
      { book: 'Aventurisches Götterwirken II', page: 74 },
      { book: 'Divinarium Liturgia', page: 373 },
    ],
  },
  {
    name: 'traumgesicht',
    label: 'Traumgesicht',
    check: ['MU', 'IN', 'CH'],
    traditions: ['Boron (Traum)', 'Marbo (Vision)'],
    increaseFactor: IncreaseFactor.C,
    url: 'https://dsa.ulisses-regelwiki.de/zeremonie.html?zeremonie=Traumgesicht',
    sources: [
      { book: 'Aventurisches Götterwirken II', page: 108 },
      { book: 'Divinarium Liturgia', page: 374 },
    ],
  },
  {
    name: 'traviasWachgaense',
    label: 'Travias Wachgänse',
    check: ['CH', 'CH', 'CH'],
    traditions: ['Travia (Freundschaft)', 'Travia (Heim)'],
    increaseFactor: IncreaseFactor.B,
    url: 'https://dsa.ulisses-regelwiki.de/zeremonie.html?zeremonie=Travias+Wachg%C3%A4nse',
    sources: [{ book: 'Divinarium Liturgia', page: 375 }],
  },
  {
    name: 'unbeschwerteWanderung',
    label: 'Unbeschwerte Wanderung',
    check: ['MU', 'IN', 'KO'],
    traditions: ['Aves (Reise)'],
    increaseFactor: IncreaseFactor.A,
    url: 'https://dsa.ulisses-regelwiki.de/zeremonie.html?zeremonie=Unbeschwerte+Wanderung',
    sources: [
      { book: 'Aventurisches Götterwirken', page: 161 },
      { book: 'Divinarium Liturgia', page: 376 },
    ],
  },
  {
    name: 'untoteErschaffen',
    label: 'Untote erschaffen',
    check: ['MU', 'IN', 'CH'],
    traditions: ['Marbo (Vergänglichkeit)'],
    increaseFactor: IncreaseFactor.D,
    url: 'https://dsa.ulisses-regelwiki.de/zeremonie.html?zeremonie=Untote+erschaffen',
    sources: [
      { book: 'Aventurisches Götterwirken II', page: 108 },
      { book: 'Divinarium Liturgia', page: 377 },
    ],
  },
  {
    name: 'verblassendeErinnerung',
    label: 'Verblassende Erinnerung',
    check: ['MU', 'IN', 'CH'],
    traditions: ['Boron (Traum)', 'Rahja (Harmonie)', 'Travia (Heim)'],
    increaseFactor: IncreaseFactor.A,
    url: 'https://dsa.ulisses-regelwiki.de/zeremonie.html?zeremonie=Verblassende+Erinnerung',
    sources: [
      { book: 'Aventurisches Götterwirken', page: 161 },
      { book: 'Divinarium Liturgia', page: 378 },
    ],
  },
  {
    name: 'vergessen',
    label: 'Vergessen',
    check: ['MU', 'IN', 'CH'],
    traditions: ['Boron (Tod)'],
    increaseFactor: IncreaseFactor.B,
    url: 'https://dsa.ulisses-regelwiki.de/zeremonie.html?zeremonie=Vergessen',
    sources: [
      { book: 'Aventurisches Götterwirken', page: 161 },
      { book: 'Divinarium Liturgia', page: 379 },
    ],
  },
  {
    name: 'waffenfluch',
    label: 'Waffenfluch',
    check: ['MU', 'IN', 'KO'],
    traditions: ['Namenloser'],
    increaseFactor: IncreaseFactor.C,
    url: 'https://dsa.ulisses-regelwiki.de/zeremonie.html?zeremonie=Waffenfluch',
    sources: [
      { book: 'Aventurisches Götterwirken', page: 162 },
      { book: 'Divinarium Liturgia', page: 380 },
    ],
  },
  {
    name: 'wegweiser',
    label: 'Wegweiser',
    check: ['KL', 'IN', 'CH'],
    traditions: ['Aves (Schicksal)'],
    increaseFactor: IncreaseFactor.A,
    url: 'https://dsa.ulisses-regelwiki.de/zeremonie.html?zeremonie=Wegweiser',
    sources: [
      { book: 'Aventurisches Götterwirken', page: 162 },
      { book: 'Divinarium Liturgia', page: 381 },
    ],
  },
  {
    name: 'weiheDesHeims',
    label: 'Weihe des Heims',
    check: ['MU', 'KL', 'IN'],
    traditions: ['Ingerimm (Handwerk)', 'Rondra (Schild)', 'Travia (Heim)'],
    increaseFactor: IncreaseFactor.A,
    url: 'https://dsa.ulisses-regelwiki.de/zeremonie.html?zeremonie=Weihe+des+Heims',
    sources: [
      { book: 'Aventurisches Götterwirken', page: 162 },
      { book: 'Divinarium Liturgia', page: 383 },
    ],
  },
  {
    name: 'widdergestalt',
    label: 'Widdergestalt',
    check: ['MU', 'KL', 'IN'],
    traditions: ['Levthan (Begierde)', 'Levthan (Rausch)'],
    increaseFactor: IncreaseFactor.A,
    url: 'https://dsa.ulisses-regelwiki.de/zeremonie.html?zeremonie=Widdergestalt',
    sources: [
      { book: 'Aventurisches Götterwirken II', page: 108 },
      { book: 'Divinarium Liturgia', page: 384 },
      { book: 'Wege der Vereinigungen', page: 195 },
    ],
  },
  {
    name: 'wiederherstellung',
    label: 'Wiederherstellung',
    check: ['MU', 'FF', 'KO'],
    traditions: ['Angrosch (Erz)', 'Ingerimm (Handwerk)', 'Tsa (Freiheit)', 'Tsa (Wandel)'],
    increaseFactor: IncreaseFactor.B,
    url: 'https://dsa.ulisses-regelwiki.de/zeremonie.html?zeremonie=Wiederherstellung',
    sources: [
      { book: 'Aventurisches Götterwirken', page: 162 },
      { book: 'Aventurisches Götterwirken II', page: 74 },
      { book: 'Divinarium Liturgia', page: 385 },
    ],
  },
  {
    name: 'winterschlaf',
    label: 'Winterschlaf',
    check: ['MU', 'IN', 'CH'],
    traditions: ['Achazschamanen (Starre)', 'Boron (Tod)', 'Firun (Kälte)', 'Marbo (Vergänglichkeit)', 'Nivesenschamanen (Winter)', 'Peraine (Heilung)'],
    increaseFactor: IncreaseFactor.B,
    url: 'https://dsa.ulisses-regelwiki.de/zeremonie.html?zeremonie=Winterschlaf',
    sources: [
      { book: 'Aventurisches Götterwirken', page: 163 },
      { book: 'Aventurisches Götterwirken II', page: 74 },
      { book: 'Divinarium Liturgia', page: 387 },
    ],
  },
  {
    name: 'wolfsfluch',
    label: 'Wolfsfluch',
    check: ['MU', 'KL', 'CH'],
    traditions: ['Nivesenschamanen (Wölfe)'],
    increaseFactor: IncreaseFactor.C,
    url: 'https://dsa.ulisses-regelwiki.de/zeremonie.html?zeremonie=Wolfsfluch',
    sources: [
      { book: 'Aventurisches Götterwirken II', page: 109 },
      { book: 'Divinarium Liturgia', page: 388 },
    ],
  },
  {
    name: 'wolfsgestalt',
    label: 'Wolfsgestalt',
    check: ['MU', 'KL', 'IN'],
    traditions: ['Nivesenschamanen (Winter)', 'Nivesenschamanen (Wölfe)'],
    increaseFactor: IncreaseFactor.B,
    url: 'https://dsa.ulisses-regelwiki.de/zeremonie.html?zeremonie=Wolfsgestalt',
    sources: [
      { book: 'Aventurisches Götterwirken II', page: 109 },
      { book: 'Divinarium Liturgia', page: 389 },
      { book: 'Helden der Echsensümpfe', page: 69 },
      { book: 'Heldenwerk-Archiv IX', page: 107 },
      { book: 'Wolf und Wal', page: 10 },
    ],
  },
  {
    name: 'zuflucht',
    label: 'Zuflucht',
    check: ['IN', 'CH', 'KO'],
    traditions: ['Firun (Kälte)', 'Ifirn (Hilfsbereitschaft)', 'Nivesenschamanen (Winter)', 'Tahayaschamanen (Sonne)', 'Travia (Heim)'],
    increaseFactor: IncreaseFactor.B,
    url: 'https://dsa.ulisses-regelwiki.de/zeremonie.html?zeremonie=Zuflucht',
    sources: [
      { book: 'Aventurisches Götterwirken', page: 163 },
      { book: 'Divinarium Liturgia', page: 390 },
      { book: 'Helden des Wolfsfrosts', page: 70 },
    ],
  },
  {
    name: 'zwergischeVerbruederung',
    label: 'Zwergische Verbrüderung',
    check: ['MU', 'IN', 'CH'],
    traditions: ['Angrosch (Erz)', 'Angrosch (Flammen)'],
    increaseFactor: IncreaseFactor.C,
    url: 'https://dsa.ulisses-regelwiki.de/zeremonie.html?zeremonie=Zwergische+Verbr%C3%BCderung',
    sources: [
      { book: 'Aventurisches Götterwirken II', page: 109 },
      { book: 'Divinarium Liturgia', page: 392 },
    ],
  },
  {
    name: 'zwergwalgestalt',
    label: 'Zwergwalgestalt',
    check: ['MU', 'KL', 'IN'],
    traditions: ['Swafnir (Kraft)', 'Swafnir (Tapferkeit)'],
    increaseFactor: IncreaseFactor.C,
    url: 'https://dsa.ulisses-regelwiki.de/zeremonie.html?zeremonie=Zwergwalgestalt',
    sources: [
      { book: 'Aventurisches Götterwirken', page: 163 },
      { book: 'Divinarium Liturgia', page: 393 },
    ],
  },
];
