import { IncreaseFactor } from '../models/base-creation.model';
import { CombatTechniqueDefinition } from '../models/combat-technique.model';

// ─── AUTO-GENERATED by tools/extract-pdf-data.mjs (KampftechnikGetInfo (Fernkampf)). Do not edit by hand. ───
// DSA Aventurien only (Mythos/Schwarze Katze excluded). Existing names/slugs preserved from the hand snapshot.

export const RANGED_COMBAT_TECHNIQUES: CombatTechniqueDefinition[] = [
  { name: "Armbrüste", label: "Armbrüste", primaryAttribute: "FF", increaseFactor: IncreaseFactor.B, hasParry: false },
  { name: "Bögen", label: "Bögen", primaryAttribute: "FF", increaseFactor: IncreaseFactor.C, hasParry: false },
  { name: "Wurfwaffen", label: "Wurfwaffen", primaryAttribute: "FF", increaseFactor: IncreaseFactor.B, hasParry: false },
  { name: "Feuerspeien", label: "Feuerspeien", primaryAttribute: "FF", increaseFactor: IncreaseFactor.B, hasParry: false },
  { name: "Schleudern", label: "Schleudern", primaryAttribute: "FF", increaseFactor: IncreaseFactor.B, hasParry: false },
  { name: "Blasrohre", label: "Blasrohre", primaryAttribute: "FF", increaseFactor: IncreaseFactor.B, hasParry: false },
  { name: "Diskusse", label: "Diskusse", primaryAttribute: "FF", increaseFactor: IncreaseFactor.C, hasParry: false },
];
