import { Culture } from '../models/culture.model';

// ─── Human Cultures ───────────────────────────────────────────────────────────

export const HUMAN_CULTURES: Culture[] = [
  {
    name: 'andergaster',
    label: 'Andergaster',
    apCost: 20,
    language: 'Garethi (Andergastisch)',
    script: 'Kusliker Zeichen (2 AP)',
    socialStatus: ['Adel', 'Unfrei'],
    culturePackage: [
      { skill: 'Holzbearbeitung', bonus: 2 },
      { skill: 'Orientierung', bonus: 1 },
      { skill: 'Pflanzenkunde', bonus: 1 },
      { skill: 'Sagen & Legenden', bonus: 1 },
      { skill: 'Tierkunde', bonus: 1 },
      { skill: 'Wildnisleben', bonus: 2 },
    ],
    speciesRestriction: ['human', 'halfelf'],
    typicalAdvantages: ['Richtungssinn', 'Zäher Hund'],
    typicalDisadvantages: ['Persönlichkeitsschwächen (Vorurteile)', 'Persönlichkeitsschwächen (Weltfremd)', 'Schlechte Eigenschaften (Aberglaube)'],
    atypicalAdvantages: ['Soziale Anpassungsfähigkeit'],
    atypicalDisadvantages: ['Krankheitsanfällig'],
    url: 'https://dsa.ulisses-regelwiki.de/Kul_Andergaster.html',
  },
  {
    name: 'aranier',
    label: 'Aranier',
    apCost: 26,
    language: 'Tulamidya (Aranisch) oder Garethi (Aretya)',
    script: 'Tulamidya oder Kusliker Zeichen (2 AP)',
    socialStatus: ['Adel', 'Unfrei'],
    culturePackage: [
      { skill: 'Betören', bonus: 1 },
      { skill: 'Brett- & Glücksspiel', bonus: 1 },
      { skill: 'Gassenwissen', bonus: 2 },
      { skill: 'Handel', bonus: 2 },
      { skill: 'Menschenkenntnis', bonus: 1 },
      { skill: 'Rechnen', bonus: 1 },
      { skill: 'Sagen & Legenden', bonus: 1 },
      { skill: 'Stoffbearbeitung', bonus: 1 },
      { skill: 'Überreden', bonus: 2 },
    ],
    speciesRestriction: ['human', 'halfelf'],
    typicalAdvantages: ['Begabung in Gesellschaftstalenten', 'Entfernungssinn'],
    typicalDisadvantages: [
      'Persönlichkeitsschwächen (Eitelkeit)',
      'Persönlichkeitsschwächen (Vorurteile)',
      'Schlechte Eigenschaften (Aberglaube)',
      'Zerbrechlich',
    ],
    atypicalAdvantages: ['Kälteresistenz'],
    atypicalDisadvantages: ['Blutrausch'],
    url: 'https://dsa.ulisses-regelwiki.de/Kul_Aranier.html',
  },
  {
    name: 'bornlaender',
    label: 'Bornländer',
    apCost: 18,
    language: 'Garethi (Bornländisch)',
    script: 'Kusliker Zeichen (2 AP)',
    socialStatus: ['Adel', 'Unfrei'],
    culturePackage: [
      { skill: 'Fährtensuchen', bonus: 1 },
      { skill: 'Holzbearbeitung', bonus: 2 },
      { skill: 'Lebensmittelbearbeitung', bonus: 1 },
      { skill: 'Orientierung', bonus: 1 },
      { skill: 'Pflanzenkunde', bonus: 1 },
      { skill: 'Wildnisleben', bonus: 1 },
      { skill: 'Zechen', bonus: 2 },
    ],
    speciesRestriction: ['human', 'halfelf'],
    typicalAdvantages: ['Kälteresistenz', 'Richtungssinn', 'Zäher Hund'],
    typicalDisadvantages: ['Hitzeempfindlich', 'Persönlichkeitsschwächen (Vorurteile)', 'Schlechte Eigenschaften (Aberglaube)'],
    atypicalAdvantages: ['Hitzeresistenz'],
    atypicalDisadvantages: [],
    url: 'https://dsa.ulisses-regelwiki.de/Kul_Bornl%C3%A4nder.html',
  },
  {
    name: 'fjarninger',
    label: 'Fjarninger',
    apCost: 33,
    language: 'Fjarningsch',
    script: 'keine',
    socialStatus: ['Adel'],
    culturePackage: [
      { skill: 'Einschüchtern', bonus: 2 },
      { skill: 'Fährtensuchen', bonus: 1 },
      { skill: 'Körperbeherrschung', bonus: 1 },
      { skill: 'Kraftakt', bonus: 2 },
      { skill: 'Metallbearbeitung', bonus: 1 },
      { skill: 'Orientierung', bonus: 2 },
      { skill: 'Selbstbeherrschung', bonus: 1 },
      { skill: 'Steinbearbeitung', bonus: 1 },
      { skill: 'Wildnisleben', bonus: 2 },
    ],
    speciesRestriction: ['human'],
    typicalAdvantages: ['Entfernungssinn', 'Kälteresistenz', 'Richtungssinn', 'Verbesserte Regeneration (Lebensenergie)', 'Zäher Hund'],
    typicalDisadvantages: [
      'Angst vor … (dem Meer)',
      'Blutrausch',
      'Hitzeempfindlich',
      'Schlechte Eigenschaften (Aberglaube, Jähzorn)',
      'Unfähig in Gesellschaftstalenten',
    ],
    atypicalAdvantages: ['Hitzeresistenz', 'Soziale Anpassungsfähigkeit', 'Unscheinbar'],
    atypicalDisadvantages: [
      'Angst vor … (Dunkelheit, engen Räumen oder Höhe)',
      'Fettleibig',
      'Kälteempfindlich',
      'Krankheitsanfällig',
      'Nachtblind',
      'Persönlichkeitsschwächen (Eitelkeit)',
      'Zerbrechlich',
    ],
    url: 'https://dsa.ulisses-regelwiki.de/Kul_Fjarninger.html',
  },
  {
    name: 'horasier',
    label: 'Horasier',
    apCost: 27,
    language: 'Garethi (Horathi)',
    script: 'Kusliker Zeichen (2 AP)',
    socialStatus: ['Adel'],
    culturePackage: [
      { skill: 'Betören', bonus: 1 },
      { skill: 'Boote & Schiffe', bonus: 1 },
      { skill: 'Etikette', bonus: 2 },
      { skill: 'Gassenwissen', bonus: 2 },
      { skill: 'Geographie', bonus: 1 },
      { skill: 'Geschichtswissen', bonus: 1 },
      { skill: 'Handel', bonus: 1 },
      { skill: 'Mechanik', bonus: 1 },
      { skill: 'Rechnen', bonus: 2 },
      { skill: 'Rechtskunde', bonus: 2 },
      { skill: 'Tanzen', bonus: 1 },
    ],
    speciesRestriction: ['human', 'halfelf'],
    typicalAdvantages: ['Soziale Anpassungsfähigkeit'],
    typicalDisadvantages: ['Persönlichkeitsschwächen (Arroganz, Eitelkeit, Vorurteile)'],
    atypicalAdvantages: ['Begabung in Naturtalenten'],
    atypicalDisadvantages: ['Angst vor … (engen Räumen)'],
    url: 'https://dsa.ulisses-regelwiki.de/Kul_Horasier.html',
  },
  {
    name: 'maraskaner',
    label: 'Maraskaner',
    apCost: 26,
    language: 'Garethi (Maraskani) oder Tulamidya (Maraskani-Tulamidya)',
    script: 'Kusliker Zeichen oder Tulamidya (2 AP)',
    socialStatus: ['Adel'],
    culturePackage: [
      { skill: 'Götter & Kulte', bonus: 1 },
      { skill: 'Heilkunde Gift', bonus: 2 },
      { skill: 'Orientierung', bonus: 1 },
      { skill: 'Pflanzenkunde', bonus: 2 },
      { skill: 'Tierkunde', bonus: 2 },
      { skill: 'Verbergen', bonus: 1 },
      { skill: 'Wildnisleben', bonus: 1 },
    ],
    speciesRestriction: ['human', 'halfelf'],
    typicalAdvantages: ['Giftresistenz', 'Hitzeresistenz', 'Krankheitsresistenz', 'Richtungssinn', 'Soziale Anpassungsfähigkeit'],
    typicalDisadvantages: ['Persönlichkeitsschwächen (Arroganz, Vorurteile)', 'Schlechte Eigenschaften (Neugier)'],
    atypicalAdvantages: ['Kälteresistenz'],
    atypicalDisadvantages: ['Angst vor … (Insekten)', 'Farbenblind', 'Schlechte Eigenschaften (Jähzorn)'],
    url: 'https://dsa.ulisses-regelwiki.de/Kul_Maraskaner.html',
  },
  {
    name: 'mhanadistani',
    label: 'Mhanadistani',
    apCost: 28,
    language: 'Tulamidya (Mhanadisch-Balashidisch)',
    script: 'Tulamidya (2 AP)',
    socialStatus: ['Adel', 'Unfrei'],
    culturePackage: [
      { skill: 'Brett- & Glücksspiel', bonus: 2 },
      { skill: 'Gassenwissen', bonus: 2 },
      { skill: 'Geschichtswissen', bonus: 1 },
      { skill: 'Götter & Kulte', bonus: 2 },
      { skill: 'Handel', bonus: 2 },
      { skill: 'Magiekunde', bonus: 1 },
      { skill: 'Sagen & Legenden', bonus: 2 },
      { skill: 'Überreden', bonus: 1 },
    ],
    speciesRestriction: ['human', 'halfelf'],
    typicalAdvantages: ['Glück', 'Hitzeresistenz', 'Soziale Anpassungsfähigkeit'],
    typicalDisadvantages: ['Persönlichkeitsschwächen (Eitelkeit, Vorurteile)', 'Schlechte Eigenschaften (Aberglaube, Goldgier, Neugier)'],
    atypicalAdvantages: ['Kälteresistenz'],
    atypicalDisadvantages: ['Angst vor … (engen Räumen, Menschenmassen)'],
    url: 'https://dsa.ulisses-regelwiki.de/Kul_Mhanadistani.html',
  },
  {
    name: 'mittelreicher',
    label: 'Mittelreicher',
    apCost: 12,
    language: 'Garethi',
    script: 'Kusliker Zeichen (2 AP)',
    socialStatus: ['Adel', 'Unfrei'],
    culturePackage: [
      { skill: 'Holzbearbeitung', bonus: 1 },
      { skill: 'Metallbearbeitung', bonus: 1 },
      { skill: 'Pflanzenkunde', bonus: 1 },
      { skill: 'Stoffbearbeitung', bonus: 1 },
      { skill: 'Tierkunde', bonus: 1 },
    ],
    speciesRestriction: ['human', 'halfelf', 'halforc'],
    typicalAdvantages: ['Glück'],
    typicalDisadvantages: ['Persönlichkeitsschwächen (Vorurteile)', 'Schlechte Eigenschaften (Aberglaube)'],
    atypicalAdvantages: ['Hitzeresistenz', 'Kälteresistenz'],
    atypicalDisadvantages: [],
    url: 'https://dsa.ulisses-regelwiki.de/Kul_Mittelreicher.html',
  },
  {
    name: 'nivesen',
    label: 'Nivesen',
    apCost: 37,
    language: 'Nujuka',
    script: 'keine',
    socialStatus: ['Adel'],
    culturePackage: [
      { skill: 'Fährtensuchen', bonus: 2 },
      { skill: 'Fahrzeuge', bonus: 1 },
      { skill: 'Orientierung', bonus: 2 },
      { skill: 'Pflanzenkunde', bonus: 1 },
      { skill: 'Sagen & Legenden', bonus: 2 },
      { skill: 'Sinnesschärfe', bonus: 1 },
      { skill: 'Tierkunde', bonus: 2 },
      { skill: 'Verbergen', bonus: 1 },
      { skill: 'Wildnisleben', bonus: 2 },
    ],
    speciesRestriction: ['human'],
    typicalAdvantages: ['Kälteresistenz', 'Richtungssinn'],
    typicalDisadvantages: ['Angst vor … (engen Räumen, Höhe und Toten und Untoten)'],
    atypicalAdvantages: ['Hitzeresistenz', 'Soziale Anpassungsfähigkeit'],
    atypicalDisadvantages: ['Fettleibig', 'Persönlichkeitsschwächen (Arroganz)', 'Schlechte Eigenschaften (Goldgier)'],
    url: 'https://dsa.ulisses-regelwiki.de/Kul_Nivesen.html',
  },
  {
    name: 'norbarden',
    label: 'Norbarden',
    apCost: 18,
    language: 'Alaani (Gajka, Takellen)',
    script: 'Kusliker Zeichen (2 AP)',
    socialStatus: [],
    culturePackage: [
      { skill: 'Fahrzeuge', bonus: 2 },
      { skill: 'Geographie', bonus: 2 },
      { skill: 'Handel', bonus: 2 },
      { skill: 'Orientierung', bonus: 1 },
      { skill: 'Überreden', bonus: 1 },
      { skill: 'Wildnisleben', bonus: 1 },
    ],
    speciesRestriction: ['human', 'halfelf'],
    typicalAdvantages: ['Kälteresistenz', 'Richtungssinn'],
    typicalDisadvantages: ['Angst vor … (engen Räumen oder Höhe)', 'Schlechte Eigenschaften (Goldgier, Neugier)', 'Verpflichtungen (gegenüber der Sippe)'],
    atypicalAdvantages: ['Hitzeresistenz'],
    atypicalDisadvantages: ['Persönlichkeitsschwächen (Arroganz)', 'Prinzipientreue'],
    url: 'https://dsa.ulisses-regelwiki.de/Kul_Norbarden.html',
  },
  {
    name: 'nordaventurier',
    label: 'Nordaventurier',
    apCost: 25,
    language: 'Alaani, Garethi, Nujuka oder Thorwalsch',
    script: 'Kusliker Zeichen (2 AP)',
    socialStatus: ['Adel', 'Unfrei'],
    culturePackage: [
      { skill: 'Fährtensuchen', bonus: 1 },
      { skill: 'Handel', bonus: 1 },
      { skill: 'Holzbearbeitung', bonus: 1 },
      { skill: 'Lederbearbeitung', bonus: 1 },
      { skill: 'Orientierung', bonus: 1 },
      { skill: 'Pflanzenkunde', bonus: 1 },
      { skill: 'Selbstbeherrschung', bonus: 1 },
      { skill: 'Tierkunde', bonus: 1 },
      { skill: 'Wildnisleben', bonus: 1 },
      { skill: 'Zechen', bonus: 1 },
    ],
    speciesRestriction: ['human', 'halfelf'],
    typicalAdvantages: ['Entfernungssinn', 'Richtungssinn', 'Zäher Hund'],
    typicalDisadvantages: ['Angst vor … (engen Räumen)', 'Schlechte Eigenschaften (Aberglaube)'],
    atypicalAdvantages: ['Hitzeresistenz'],
    atypicalDisadvantages: ['Krankheitsanfällig'],
    url: 'https://dsa.ulisses-regelwiki.de/Kul_Nordaventurier.html',
  },
  {
    name: 'nostrier',
    label: 'Nostrier',
    apCost: 15,
    language: 'Garethi (Nostrisch)',
    script: 'Kusliker Zeichen (2 AP)',
    socialStatus: ['Adel', 'Unfrei'],
    culturePackage: [
      { skill: 'Fischen & Angeln', bonus: 2 },
      { skill: 'Orientierung', bonus: 1 },
      { skill: 'Pflanzenkunde', bonus: 1 },
      { skill: 'Sagen & Legenden', bonus: 1 },
      { skill: 'Tierkunde', bonus: 1 },
      { skill: 'Wildnisleben', bonus: 1 },
    ],
    speciesRestriction: ['human', 'halfelf'],
    typicalAdvantages: ['Richtungssinn', 'Zäher Hund'],
    typicalDisadvantages: ['Persönlichkeitsschwächen (Vorurteile, Weltfremd)', 'Schlechte Eigenschaften (Aberglaube)'],
    atypicalAdvantages: ['Soziale Anpassungsfähigkeit'],
    atypicalDisadvantages: ['Krankheitsanfällig'],
    url: 'https://dsa.ulisses-regelwiki.de/Kul_Nostrier.html',
  },
  {
    name: 'novadis',
    label: 'Novadis',
    apCost: 25,
    language: 'Tulamidya (Khôm-Novadisch)',
    script: 'Heilige Glyphen von Unau (2 AP)',
    socialStatus: ['Adel', 'Unfrei'],
    culturePackage: [
      { skill: 'Einschüchtern', bonus: 2 },
      { skill: 'Fährtensuchen', bonus: 1 },
      { skill: 'Orientierung', bonus: 2 },
      { skill: 'Rechtskunde', bonus: 1 },
      { skill: 'Reiten', bonus: 2 },
      { skill: 'Tierkunde', bonus: 1 },
      { skill: 'Wildnisleben', bonus: 2 },
    ],
    speciesRestriction: ['human'],
    typicalAdvantages: ['Entfernungssinn', 'Hitzeresistenz', 'Richtungssinn', 'Schwer zu verzaubern', 'Zäher Hund'],
    typicalDisadvantages: [
      'Angst vor … (engen Räumen und dem Meer)',
      'Persönlichkeitsschwächen (Arroganz, Vorurteile)',
      'Prinzipientreue (99 Gesetze)',
      'Schlechte Eigenschaften (Jähzorn, Rachsucht)',
    ],
    atypicalAdvantages: ['Hitzeempfindlich', 'Kälteresistenz'],
    atypicalDisadvantages: [],
    url: 'https://dsa.ulisses-regelwiki.de/Kul_Novadis.html',
  },
  {
    name: 'svellttaler',
    label: 'Svellttaler',
    apCost: 21,
    language: 'Garethi',
    script: 'Kusliker Zeichen (2 AP)',
    socialStatus: ['Adel', 'Unfrei'],
    culturePackage: [
      { skill: 'Fährtensuchen', bonus: 2 },
      { skill: 'Fahrzeuge', bonus: 2 },
      { skill: 'Orientierung', bonus: 1 },
      { skill: 'Pflanzenkunde', bonus: 1 },
      { skill: 'Sagen & Legenden', bonus: 1 },
      { skill: 'Tierkunde', bonus: 1 },
      { skill: 'Wildnisleben', bonus: 1 },
    ],
    speciesRestriction: ['human', 'halfelf'],
    typicalAdvantages: ['Entfernungssinn', 'Richtungssinn', 'Zäher Hund'],
    typicalDisadvantages: ['Angst vor … (engen Räumen)', 'Persönlichkeitsschwächen (Vorurteile)', 'Schlechte Eigenschaften (Aberglaube)'],
    atypicalAdvantages: ['Hitzeresistenz'],
    atypicalDisadvantages: ['Krankheitsanfällig'],
    url: 'https://dsa.ulisses-regelwiki.de/Kul_Svellttaler.html',
  },
  {
    name: 'suedaventurier',
    label: 'Südaventurier',
    apCost: 26,
    language: 'Garethi (Brabaci, Charypto, Gatamo)',
    script: 'Kusliker Zeichen (2 AP)',
    socialStatus: ['Adel', 'Unfrei'],
    culturePackage: [
      { skill: 'Betören', bonus: 1 },
      { skill: 'Boote & Schiffe', bonus: 1 },
      { skill: 'Fischen & Angeln', bonus: 1 },
      { skill: 'Gassenwissen', bonus: 2 },
      { skill: 'Heilkunde Gift', bonus: 1 },
      { skill: 'Menschenkenntnis', bonus: 2 },
      { skill: 'Überreden', bonus: 1 },
      { skill: 'Willenskraft', bonus: 1 },
    ],
    speciesRestriction: ['human', 'halfelf'],
    typicalAdvantages: ['Hitzeresistenz', 'Soziale Anpassungsfähigkeit'],
    typicalDisadvantages: [
      'Kälteempfindlich',
      'Persönlichkeitsschwächen (Arroganz, Eitelkeit)',
      'Schlechte Eigenschaften (Aberglaube, Goldgier, Jähzorn, Neugier)',
    ],
    atypicalAdvantages: ['Kälteresistenz'],
    atypicalDisadvantages: ['Angst vor … (engen Räumen, Menschenmassen und Toten und Untoten)'],
    url: 'https://dsa.ulisses-regelwiki.de/Kul_S%C3%BCdaventurier.html',
  },
  {
    name: 'thorwaler',
    label: 'Thorwaler',
    apCost: 24,
    language: 'Thorwalsch',
    script: 'Thorwalsche Runen oder Kusliker Zeichen (2 AP)',
    socialStatus: ['Adel'],
    culturePackage: [
      { skill: 'Boote & Schiffe', bonus: 2 },
      { skill: 'Einschüchtern', bonus: 1 },
      { skill: 'Fischen & Angeln', bonus: 2 },
      { skill: 'Geographie', bonus: 1 },
      { skill: 'Holzbearbeitung', bonus: 2 },
      { skill: 'Kraftakt', bonus: 2 },
      { skill: 'Orientierung', bonus: 1 },
      { skill: 'Sagen & Legenden', bonus: 1 },
      { skill: 'Zechen', bonus: 2 },
    ],
    speciesRestriction: ['human', 'halfelf'],
    typicalAdvantages: ['Entfernungssinn', 'Glück', 'Richtungssinn', 'Verbesserte Regeneration (Lebensenergie)', 'Zäher Hund'],
    typicalDisadvantages: ['Blutrausch', 'Persönlichkeitsschwächen (Vorurteile)', 'Schlechte Eigenschaften (Aberglaube, Neugier, Rachsucht)'],
    atypicalAdvantages: ['Soziale Anpassungsfähigkeit'],
    atypicalDisadvantages: ['Angst vor … (dem Meer)'],
    url: 'https://dsa.ulisses-regelwiki.de/Kul_Thorwaler.html',
  },
  {
    name: 'trollzacker',
    label: 'Trollzacker',
    apCost: 38,
    language: 'Zhulchammaqra',
    script: 'keine',
    socialStatus: ['Adel', 'Unfrei'],
    culturePackage: [
      { skill: 'Einschüchtern', bonus: 2 },
      { skill: 'Fährtensuchen', bonus: 1 },
      { skill: 'Klettern', bonus: 2 },
      { skill: 'Körperbeherrschung', bonus: 1 },
      { skill: 'Kraftakt', bonus: 1 },
      { skill: 'Orientierung', bonus: 1 },
      { skill: 'Selbstbeherrschung', bonus: 2 },
      { skill: 'Steinbearbeitung', bonus: 2 },
      { skill: 'Tierkunde', bonus: 1 },
      { skill: 'Verbergen', bonus: 1 },
      { skill: 'Wildnisleben', bonus: 1 },
    ],
    speciesRestriction: ['human', 'halforc'],
    typicalAdvantages: ['Hohe Lebenskraft', 'Richtungssinn', 'Verbesserte Regeneration (Lebensenergie)', 'Zäher Hund'],
    typicalDisadvantages: ['Blutrausch', 'Hässlich', 'Schlechte Eigenschaften (Aberglaube, Jähzorn, Rachsucht)'],
    atypicalAdvantages: ['Soziale Anpassungsfähigkeit'],
    atypicalDisadvantages: ['Krankheitsanfällig', 'Niedrige Lebenskraft', 'Unfähig in Naturtalenten', 'Zerbrechlich'],
    url: 'https://dsa.ulisses-regelwiki.de/Kul_Trollzacker.html',
  },
  {
    name: 'utulus',
    label: 'Utulus',
    apCost: 40,
    language: 'Tahaya',
    script: 'keine',
    socialStatus: ['Adel', 'Unfrei'],
    culturePackage: [
      { skill: 'Einschüchtern', bonus: 1 },
      { skill: 'Fährtensuchen', bonus: 1 },
      { skill: 'Heilkunde Gift', bonus: 1 },
      { skill: 'Heilkunde Krankheiten', bonus: 1 },
      { skill: 'Holzbearbeitung', bonus: 1 },
      { skill: 'Körperbeherrschung', bonus: 1 },
      { skill: 'Orientierung', bonus: 1 },
      { skill: 'Pflanzenkunde', bonus: 1 },
      { skill: 'Sagen & Legenden', bonus: 1 },
      { skill: 'Schwimmen', bonus: 1 },
      { skill: 'Sinnesschärfe', bonus: 1 },
      { skill: 'Tierkunde', bonus: 2 },
      { skill: 'Wildnisleben', bonus: 2 },
    ],
    speciesRestriction: ['human'],
    typicalAdvantages: ['Giftresistenz', 'Glück', 'Gutaussehend', 'Hitzeresistenz', 'Hohe Zähigkeit', 'Richtungssinn', 'Schlangenmensch'],
    typicalDisadvantages: [
      'Angst vor … (engen Räumen, dem Meer, Toten und Untoten)',
      'Kälteempfindlich',
      'Niedrige Seelenkraft',
      'Schlechte Eigenschaften (Aberglaube, Neugier)',
    ],
    atypicalAdvantages: ['Kälteresistenz'],
    atypicalDisadvantages: [
      'Angst vor … (Insekten, Reptilien, Spinnen)',
      'Krankheitsanfällig',
      'Nachtblind',
      'Persönlichkeitsschwächen (Eitelkeit)',
      'Schlechte Eigenschaften (Goldgier)',
      'Unfähig in Naturtalenten',
    ],
    url: 'https://dsa.ulisses-regelwiki.de/Kul_Utulus.html',
  },
  {
    name: 'waldmenschen',
    label: 'Waldmenschen',
    apCost: 42,
    language: 'Tahaya',
    script: 'keine',
    socialStatus: ['Adel'],
    culturePackage: [
      { skill: 'Fährtensuchen', bonus: 1 },
      { skill: 'Heilkunde Gift', bonus: 1 },
      { skill: 'Heilkunde Krankheiten', bonus: 1 },
      { skill: 'Klettern', bonus: 1 },
      { skill: 'Körperbeherrschung', bonus: 1 },
      { skill: 'Orientierung', bonus: 1 },
      { skill: 'Pflanzenkunde', bonus: 2 },
      { skill: 'Sagen & Legenden', bonus: 1 },
      { skill: 'Sinnesschärfe', bonus: 1 },
      { skill: 'Tierkunde', bonus: 2 },
      { skill: 'Verbergen', bonus: 1 },
      { skill: 'Wildnisleben', bonus: 2 },
    ],
    speciesRestriction: ['human'],
    typicalAdvantages: ['Angenehmer Geruch', 'Giftresistenz', 'Glück', 'Gutaussehend', 'Hitzeresistenz', 'Richtungssinn', 'Schlangenmensch'],
    typicalDisadvantages: [
      'Angst vor … (engen Räumen)',
      'Kälteempfindlich',
      'Niedrige Seelenkraft',
      'Persönlichkeitsschwächen (Weltfremd)',
      'Schlechte Eigenschaften (Aberglaube, Neugier)',
    ],
    atypicalAdvantages: ['Kälteresistenz'],
    atypicalDisadvantages: [
      'Angst vor … (Höhe, Insekten, Reptilien, Spinnen)',
      'Krankheitsanfällig',
      'Nachtblind',
      'Persönlichkeitsschwächen (Eitelkeit, Streitsucht)',
      'Schlechte Eigenschaften (Goldgier)',
      'Unfähig in Naturtalenten',
    ],
    url: 'https://dsa.ulisses-regelwiki.de/Kul_Waldmenschen.html',
  },
  {
    name: 'zyklopaeer',
    label: 'Zyklopäer',
    apCost: 16,
    language: 'Garethi (Horathi) oder Zyklopäisch',
    script: 'Kusliker Zeichen (2 AP)',
    socialStatus: ['Adel'],
    culturePackage: [
      { skill: 'Boote & Schiffe', bonus: 1 },
      { skill: 'Fischen & Angeln', bonus: 2 },
      { skill: 'Geschichtswissen', bonus: 1 },
      { skill: 'Götter & Kulte', bonus: 2 },
      { skill: 'Musizieren', bonus: 1 },
      { skill: 'Rechnen', bonus: 1 },
      { skill: 'Rechtskunde', bonus: 1 },
      { skill: 'Sagen & Legenden', bonus: 1 },
      { skill: 'Tanzen', bonus: 1 },
    ],
    speciesRestriction: ['human', 'halfelf'],
    typicalAdvantages: ['Begabung in Schwimmen', 'Entfernungssinn', 'Gutaussehend', 'Richtungssinn', 'Wohlklang'],
    typicalDisadvantages: ['Persönlichkeitsschwächen (Arroganz, Eitelkeit, Vorurteile)'],
    atypicalAdvantages: ['Kälteresistenz'],
    atypicalDisadvantages: ['Angst vor … (dem Meer)'],
    url: 'https://dsa.ulisses-regelwiki.de/Kul_Zyklop%C3%A4er.html',
  },
];

// ─── Expansion Human Cultures ─────────────────────────────────────────────────

export const EXPANSION_HUMAN_CULTURES: Culture[] = [
  {
    name: 'adoru',
    label: 'Adoru',
    apCost: 28,
    language: 'Adorunu',
    script: 'Adorunu-Zeichen (2 AP)',
    socialStatus: ['Adel', 'Frei'],
    culturePackage: [
      { skill: 'Alchimie', bonus: 1 },
      { skill: 'Etikette', bonus: 2 },
      { skill: 'Fischen & Angeln', bonus: 1 },
      { skill: 'Götter & Kulte', bonus: 1 },
      { skill: 'Heilkunde Gift', bonus: 1 },
      { skill: 'Kriegskunst', bonus: 1 },
      { skill: 'Magiekunde', bonus: 1 },
      { skill: 'Mechanik', bonus: 1 },
      { skill: 'Metallbearbeitung', bonus: 1 },
      { skill: 'Rechnen', bonus: 1 },
      { skill: 'Selbstbeherrschung', bonus: 1 },
      { skill: 'Steinbearbeitung', bonus: 1 },
    ],
    speciesRestriction: ['human'],
    typicalAdvantages: ['Begabung in Handwerkstalenten', 'Giftresistenz', 'Hitzeresistenz', 'Richtungssinn', 'Soziale Anpassungsfähigkeit'],
    typicalDisadvantages: ['Kälteempfindlich', 'Prinzipientreue', 'Schlechte Eigenschaften (Aberglaube, Neugier)'],
    atypicalAdvantages: ['Kälteresistenz'],
    atypicalDisadvantages: ['Angst vor … (Insekten, Spinnen, Höhe, engen Räumen)', 'Farbenblind', 'Hitzeempfindlich', 'Schlechte Eigenschaften (Jähzorn)'],
    url: 'https://dsa.ulisses-regelwiki.de/kulturen/adoru.html',
  },
  {
    name: 'ferkinas',
    label: 'Ferkinas',
    apCost: 39,
    language: 'Ferkina',
    script: 'keine',
    socialStatus: ['Adel', 'Unfrei'],
    culturePackage: [
      { skill: 'Einschüchtern', bonus: 1 },
      { skill: 'Fährtensuchen', bonus: 1 },
      { skill: 'Klettern', bonus: 2 },
      { skill: 'Körperbeherrschung', bonus: 1 },
      { skill: 'Kraftakt', bonus: 1 },
      { skill: 'Pflanzenkunde', bonus: 1 },
      { skill: 'Reiten', bonus: 1 },
      { skill: 'Selbstbeherrschung', bonus: 1 },
      { skill: 'Steinbearbeitung', bonus: 2 },
      { skill: 'Tierkunde', bonus: 1 },
      { skill: 'Verbergen', bonus: 1 },
      { skill: 'Wildnisleben', bonus: 2 },
      { skill: 'Zechen', bonus: 1 },
    ],
    speciesRestriction: ['human'],
    typicalAdvantages: ['Giftresistenz', 'Hohe Lebenskraft', 'Richtungssinn', 'Verbesserte Regeneration (Lebensenergie)', 'Zäher Hund'],
    typicalDisadvantages: [
      'Blutrausch',
      'Hässlich',
      'Persönlichkeitsschwächen (Vorurteile)',
      'Schlechte Eigenschaften (Aberglaube, Jähzorn, Rachsucht)',
      'Unfähig in Gesellschaftstalenten',
    ],
    atypicalAdvantages: ['Angenehmer Geruch', 'Hohe Seelenkraft', 'Schwer zu verzaubern', 'Soziale Anpassungsfähigkeit'],
    atypicalDisadvantages: ['Krankheitsanfällig', 'Niedrige Lebenskraft', 'Zerbrechlich'],
    url: 'https://dsa.ulisses-regelwiki.de/kul_Ferkinas.html',
  },
  {
    name: 'gjalsker',
    label: 'Gjalsker',
    apCost: 34,
    language: 'Gjalskisch',
    script: 'keine',
    socialStatus: ['Adel', 'Unfrei'],
    culturePackage: [
      { skill: 'Einschüchtern', bonus: 1 },
      { skill: 'Fährtensuchen', bonus: 1 },
      { skill: 'Klettern', bonus: 1 },
      { skill: 'Körperbeherrschung', bonus: 1 },
      { skill: 'Kraftakt', bonus: 2 },
      { skill: 'Orientierung', bonus: 1 },
      { skill: 'Pflanzenkunde', bonus: 1 },
      { skill: 'Sagen & Legenden', bonus: 2 },
      { skill: 'Selbstbeherrschung', bonus: 1 },
      { skill: 'Tierkunde', bonus: 1 },
      { skill: 'Wildnisleben', bonus: 1 },
    ],
    speciesRestriction: ['human'],
    typicalAdvantages: ['Hohe Lebenskraft', 'Kälteresistenz', 'Richtungssinn', 'Verbesserte Regeneration (Lebensenergie)', 'Zäher Hund'],
    typicalDisadvantages: [
      'Angst vor … (Toten und Untoten, dem Meer)',
      'Blutrausch',
      'Persönlichkeitsschwächen (Vorurteile)',
      'Schlechte Eigenschaften (Aberglaube)',
    ],
    atypicalAdvantages: ['Hitzeresistenz', 'Soziale Anpassungsfähigkeit'],
    atypicalDisadvantages: [
      'Angst vor … (Dunkelheit, Höhe)',
      'Behäbig',
      'Fettleibig',
      'Glasknochen',
      'Krankheitsanfällig',
      'Nachtblind',
      'Niedrige Lebenskraft',
      'Zerbrechlich',
    ],
    url: 'https://dsa.ulisses-regelwiki.de/kul_Gjalsker.html',
  },
  {
    name: 'koboldweltler',
    label: 'Koboldweltler',
    apCost: 18,
    language: 'Garethi und Koboldisch',
    script: 'keine',
    socialStatus: [],
    culturePackage: [
      { skill: 'Brett- & Glücksspiel', bonus: 1 },
      { skill: 'Gassenwissen', bonus: 1 },
      { skill: 'Gaukeleien', bonus: 2 },
      { skill: 'Klettern', bonus: 1 },
      { skill: 'Magiekunde', bonus: 1 },
      { skill: 'Malen & Zeichnen', bonus: 1 },
      { skill: 'Musizieren', bonus: 1 },
      { skill: 'Singen', bonus: 1 },
      { skill: 'Sphärenkunde', bonus: 1 },
      { skill: 'Tanzen', bonus: 1 },
      { skill: 'Zechen', bonus: 1 },
    ],
    speciesRestriction: ['human', 'halfelf'],
    typicalAdvantages: ['Begabung in Gesellschaftstalenten'],
    typicalDisadvantages: ['Persönlichkeitsschwächen (Weltfremd)'],
    atypicalAdvantages: ['Begabung in Wissenstalenten', 'Soziale Anpassungsfähigkeit'],
    atypicalDisadvantages: ['Schlechte Eigenschaften (Goldgier)', 'Unfähig in Körper- und Naturtalenten'],
    url: 'https://dsa.ulisses-regelwiki.de/rergbgfb.html',
  },
  {
    name: 'nuanaaeLie',
    label: 'Nuanaä-Lie',
    apCost: 40,
    language: 'Nujuka',
    script: 'keine',
    socialStatus: ['Frei'],
    culturePackage: [
      { skill: 'Einschüchtern', bonus: 1 },
      { skill: 'Fährtensuchen', bonus: 2 },
      { skill: 'Holzbearbeitung', bonus: 1 },
      { skill: 'Orientierung', bonus: 2 },
      { skill: 'Sinnesschärfe', bonus: 1 },
      { skill: 'Steinbearbeitung', bonus: 1 },
      { skill: 'Tierkunde', bonus: 3 },
      { skill: 'Verbergen', bonus: 2 },
      { skill: 'Wildnisleben', bonus: 2 },
    ],
    speciesRestriction: ['human'],
    typicalAdvantages: ['Kälteresistenz', 'Richtungssinn'],
    typicalDisadvantages: ['Angst vor … (weiten Flächen und Toten und Untoten)', 'Schlechte Eigenschaften (Aberglaube, Jähzorn, Naiv, Neugier)'],
    atypicalAdvantages: ['Hitzeresistenz', 'Soziale Anpassungsfähigkeit'],
    atypicalDisadvantages: ['Fettleibig', 'Kälteempfindlich', 'Lichtempfindlich', 'Persönlichkeitsschwächen (Arroganz)', 'Schlechte Eigenschaften (Goldgier)'],
    url: 'https://dsa.ulisses-regelwiki.de/Kul_Menschen/nuanaae-lie.html',
  },
  {
    name: 'tocamuyac',
    label: 'Tocamuyac',
    apCost: 0,
    language: '',
    script: 'keine',
    socialStatus: [],
    culturePackage: [],
    speciesRestriction: ['human'],
    typicalAdvantages: [],
    typicalDisadvantages: [],
    atypicalAdvantages: [],
    atypicalDisadvantages: [],
    url: 'https://dsa.ulisses-regelwiki.de/Kul_Menschen/tocamuyac.html',
  },
  {
    name: 'zahori',
    label: 'Zahori',
    apCost: 27,
    language: 'Tulamidya (Zahorisch)',
    script: 'Kusliker Zeichen (2 AP)',
    socialStatus: [],
    culturePackage: [
      { skill: 'Betören', bonus: 1 },
      { skill: 'Gaukeleien', bonus: 2 },
      { skill: 'Körperbeherrschung', bonus: 1 },
      { skill: 'Orientierung', bonus: 1 },
      { skill: 'Sagen & Legenden', bonus: 1 },
      { skill: 'Tanzen', bonus: 1 },
      { skill: 'Taschendiebstahl', bonus: 2 },
      { skill: 'Überreden', bonus: 1 },
      { skill: 'Verbergen', bonus: 1 },
      { skill: 'Verkleiden', bonus: 1 },
      { skill: 'Wildnisleben', bonus: 1 },
    ],
    speciesRestriction: ['human', 'halfelf'],
    typicalAdvantages: ['Beidhändig', 'Flink', 'Fuchssinn', 'Richtungssinn', 'Schlangenmensch'],
    typicalDisadvantages: ['Arm', 'Blutrausch', 'Schlechte Eigenschaften (Jähzorn, Rachsucht)', 'Verpflichtungen (Sippe)'],
    atypicalAdvantages: ['Adel', 'Reich', 'Vertrauenerweckend'],
    atypicalDisadvantages: ['Prinzipientreue'],
    url: 'https://dsa.ulisses-regelwiki.de/kul_Zahori.html',
  },
];

// ─── Elf Cultures ─────────────────────────────────────────────────────────────

export const ELF_CULTURES: Culture[] = [
  {
    name: 'auelfen',
    label: 'Auelfen',
    apCost: 43,
    language: 'Isdira (auelfischer Dialekt)',
    script: 'Isdira-Zeichen (2 AP)',
    socialStatus: [],
    culturePackage: [
      { skill: 'Betören', bonus: 1 },
      { skill: 'Boote & Schiffe', bonus: 1 },
      { skill: 'Fährtensuchen', bonus: 1 },
      { skill: 'Fischen & Angeln', bonus: 2 },
      { skill: 'Körperbeherrschung', bonus: 2 },
      { skill: 'Musizieren', bonus: 2 },
      { skill: 'Orientierung', bonus: 1 },
      { skill: 'Pflanzenkunde', bonus: 1 },
      { skill: 'Schwimmen', bonus: 2 },
      { skill: 'Singen', bonus: 2 },
      { skill: 'Sinnesschärfe', bonus: 1 },
      { skill: 'Tierkunde', bonus: 1 },
      { skill: 'Verbergen', bonus: 1 },
      { skill: 'Wildnisleben', bonus: 1 },
    ],
    speciesRestriction: ['elf', 'halfelf'],
    typicalAdvantages: ['Begabung in Handwerkstalenten', 'Magische Einstimmung (Wesen der Auen)', 'Waffenbegabung (Bögen)'],
    typicalDisadvantages: [
      'Artefaktgebunden (Instrument)',
      'Persönlichkeitsschwächen (Arroganz, Vorurteile, Weltfremd)',
      'Prinzipientreue (Elfische Weltsicht)',
      'Schlechte Eigenschaften (Neugier)',
    ],
    atypicalAdvantages: ['Begabung in Wissenstalenten'],
    atypicalDisadvantages: ['Schlechte Eigenschaften (Goldgier, Rachsucht)', 'Unfähig in Körper- und Naturtalenten'],
    url: 'https://dsa.ulisses-regelwiki.de/Kul_Auelfen.html',
  },
  {
    name: 'firnelfen',
    label: 'Firnelfen',
    apCost: 55,
    language: 'Isdira (firnelfischer Dialekt)',
    script: 'Isdira-Zeichen (2 AP)',
    socialStatus: [],
    culturePackage: [
      { skill: 'Fährtensuchen', bonus: 2 },
      { skill: 'Fischen & Angeln', bonus: 1 },
      { skill: 'Klettern', bonus: 1 },
      { skill: 'Körperbeherrschung', bonus: 2 },
      { skill: 'Musizieren', bonus: 2 },
      { skill: 'Orientierung', bonus: 2 },
      { skill: 'Selbstbeherrschung', bonus: 1 },
      { skill: 'Singen', bonus: 2 },
      { skill: 'Sinnesschärfe', bonus: 2 },
      { skill: 'Tierkunde', bonus: 2 },
      { skill: 'Verbergen', bonus: 2 },
      { skill: 'Wildnisleben', bonus: 2 },
    ],
    speciesRestriction: ['elf', 'halfelf'],
    typicalAdvantages: [
      'Begabung in Körper- und Naturtalenten',
      'Kälteresistenz',
      'Magische Einstimmung (Wesen des Eises)',
      'Richtungssinn',
      'Waffenbegabung (Bögen und Wurfwaffen)',
    ],
    typicalDisadvantages: [
      'Artefaktgebunden (Instrument)',
      'Persönlichkeitsschwächen (Arroganz, Vorurteile, Weltfremd)',
      'Prinzipientreue (Elfische Weltsicht)',
      'Unfähig in Wissenstalenten',
    ],
    atypicalAdvantages: ['Begabung in Wissenstalenten', 'Soziale Anpassungsfähigkeit'],
    atypicalDisadvantages: [
      'Angst vor … (Dunkelheit, engen Räumen)',
      'Kälteempfindlich',
      'Schlechte Eigenschaften (Goldgier, Rachsucht)',
      'Unfähig in Körper- und Naturtalenten',
    ],
    url: 'https://dsa.ulisses-regelwiki.de/Kul_Firnelfen.html',
  },
  {
    name: 'steppenelfen',
    label: 'Steppenelfen',
    apCost: 48,
    language: 'Isdira (steppenelfischer Dialekt)',
    script: 'Isdira-Zeichen (2 AP)',
    socialStatus: [],
    culturePackage: [
      { skill: 'Fährtensuchen', bonus: 2 },
      { skill: 'Körperbeherrschung', bonus: 2 },
      { skill: 'Musizieren', bonus: 1 },
      { skill: 'Orientierung', bonus: 2 },
      { skill: 'Pflanzenkunde', bonus: 1 },
      { skill: 'Reiten', bonus: 2 },
      { skill: 'Singen', bonus: 1 },
      { skill: 'Sinnesschärfe', bonus: 2 },
      { skill: 'Tanzen', bonus: 1 },
      { skill: 'Tierkunde', bonus: 2 },
      { skill: 'Wildnisleben', bonus: 2 },
    ],
    speciesRestriction: ['elf', 'halfelf'],
    typicalAdvantages: ['Begabung in Körper- und Naturtalenten', 'Begabung in Kampftechniken (Bögen)', 'Magische Einstimmung (Wesen der Steppe)'],
    typicalDisadvantages: [
      'Angst vor … (engen Räumen)',
      'Artefaktgebunden (Instrument)',
      'Persönlichkeitsschwächen (Arroganz, Vorurteile, Weltfremd)',
      'Unfähig in Wissenstalenten',
    ],
    atypicalAdvantages: ['Begabung in Wissenstalenten', 'Soziale Anpassungsfähigkeit'],
    atypicalDisadvantages: ['Schlechte Eigenschaften (Goldgier)', 'Unfähig in Körper- und Naturtalenten'],
    url: 'https://dsa.ulisses-regelwiki.de/Kult_Steppenelfen.html',
  },
  {
    name: 'waldelfen',
    label: 'Waldelfen',
    apCost: 47,
    language: 'Isdira (waldelfischer Dialekt)',
    script: 'Isdira-Zeichen (2 AP)',
    socialStatus: [],
    culturePackage: [
      { skill: 'Fährtensuchen', bonus: 2 },
      { skill: 'Klettern', bonus: 1 },
      { skill: 'Körperbeherrschung', bonus: 2 },
      { skill: 'Musizieren', bonus: 2 },
      { skill: 'Orientierung', bonus: 1 },
      { skill: 'Pflanzenkunde', bonus: 2 },
      { skill: 'Singen', bonus: 2 },
      { skill: 'Sinnesschärfe', bonus: 1 },
      { skill: 'Tierkunde', bonus: 2 },
      { skill: 'Verbergen', bonus: 2 },
      { skill: 'Wildnisleben', bonus: 1 },
    ],
    speciesRestriction: ['elf', 'halfelf'],
    typicalAdvantages: ['Begabung in Körper- und Naturtalenten', 'Magische Einstimmung (Wesen des Waldes)', 'Waffenbegabung (Bögen)'],
    typicalDisadvantages: [
      'Angst vor … (engen Räumen)',
      'Artefaktgebunden (Instrument)',
      'Körpergebundene Kraft',
      'Persönlichkeitsschwächen (Arroganz, Vorurteile, Weltfremd)',
      'Prinzipientreue (Elfische Weltsicht)',
      'Unfähig in Wissenstalenten',
    ],
    atypicalAdvantages: ['Begabung in Wissenstalenten', 'Soziale Anpassungsfähigkeit'],
    atypicalDisadvantages: ['Schlechte Eigenschaften (Goldgier, Jähzorn, Rachsucht)', 'Unfähig in Körper- und Naturtalenten'],
    url: 'https://dsa.ulisses-regelwiki.de/Kul_Waldelfen.html',
  },
  {
    name: 'wuestenelfen',
    label: 'Wüstenelfen',
    apCost: 55,
    language: 'Isdira (wüstenelfischer Dialekt)',
    script: 'Isdira-Zeichen (2 AP)',
    socialStatus: [],
    culturePackage: [
      { skill: 'Fährtensuchen', bonus: 2 },
      { skill: 'Körperbeherrschung', bonus: 2 },
      { skill: 'Musizieren', bonus: 1 },
      { skill: 'Orientierung', bonus: 2 },
      { skill: 'Pflanzenkunde', bonus: 1 },
      { skill: 'Sagen & Legenden', bonus: 1 },
      { skill: 'Selbstbeherrschung', bonus: 1 },
      { skill: 'Singen', bonus: 1 },
      { skill: 'Sinnesschärfe', bonus: 2 },
      { skill: 'Tierkunde', bonus: 2 },
      { skill: 'Verbergen', bonus: 2 },
      { skill: 'Wildnisleben', bonus: 2 },
    ],
    speciesRestriction: ['elf', 'halfelf'],
    typicalAdvantages: [
      'Begabung in Körper- und Naturtalenten',
      'Hitzeresistenz',
      'Magische Einstimmung (Wesen der Wüste)',
      'Richtungssinn',
      'Waffenbegabung (Bögen und Wurfwaffen)',
    ],
    typicalDisadvantages: ['Artefaktgebunden (Instrument)', 'Persönlichkeitsschwächen (Arroganz, Vorurteile)'],
    atypicalAdvantages: ['Kälteresistenz', 'Soziale Anpassungsfähigkeit'],
    atypicalDisadvantages: ['Hitzeempfindlich', 'Schlechte Eigenschaften (Goldgier)', 'Unfähig in Körper- und Naturtalenten'],
    url: 'https://dsa.ulisses-regelwiki.de/Kul_Elfen/wuestenelfen.html',
  },
];

// ─── Dwarf Cultures ───────────────────────────────────────────────────────────

export const DWARF_CULTURES: Culture[] = [
  {
    name: 'ambosszwerge',
    label: 'Ambosszwerge',
    apCost: 31,
    language: 'Rogolan (ambosszwergischer Dialekt)',
    script: 'Rogolan-Runen (2 AP)',
    socialStatus: [],
    culturePackage: [
      { skill: 'Einschüchtern', bonus: 1 },
      { skill: 'Geschichtswissen', bonus: 1 },
      { skill: 'Kraftakt', bonus: 2 },
      { skill: 'Kriegskunst', bonus: 2 },
      { skill: 'Mechanik', bonus: 1 },
      { skill: 'Metallbearbeitung', bonus: 2 },
      { skill: 'Orientierung', bonus: 1 },
      { skill: 'Sagen & Legenden', bonus: 1 },
      { skill: 'Steinbearbeitung', bonus: 2 },
      { skill: 'Verbergen', bonus: 1 },
      { skill: 'Zechen', bonus: 2 },
    ],
    speciesRestriction: ['dwarf'],
    typicalAdvantages: [
      'Begabung in Handwerkstalenten',
      'Verbesserte Regeneration (Lebensenergie)',
      'Waffenbegabung (Armbrüste, Hiebwaffen, Zweihandhiebwaffen)',
      'Zäher Hund',
    ],
    typicalDisadvantages: [
      'Angst vor … (dem Meer)',
      'Persönlichkeitsschwächen (Arroganz, Vorurteile)',
      'Prinzipientreue (zwergischer Ehrenkodex)',
      'Schlechte Eigenschaften (Geiz, Goldgier)',
    ],
    atypicalAdvantages: ['Soziale Anpassungsfähigkeit'],
    atypicalDisadvantages: ['Angst vor … (Dunkelheit oder engen Räumen)', 'Nachtblind', 'Persönlichkeitsschwächen (Eitelkeit)'],
    url: 'https://dsa.ulisses-regelwiki.de/ZK_Ambosszwerge.html',
  },
  {
    name: 'brillantzwerge',
    label: 'Brillantzwerge',
    apCost: 29,
    language: 'Rogolan (brillantzwergischer Dialekt)',
    script: 'Rogolan-Runen (2 AP)',
    socialStatus: [],
    culturePackage: [
      { skill: 'Betören', bonus: 1 },
      { skill: 'Geographie', bonus: 2 },
      { skill: 'Geschichtswissen', bonus: 1 },
      { skill: 'Metallbearbeitung', bonus: 1 },
      { skill: 'Musizieren', bonus: 1 },
      { skill: 'Sagen & Legenden', bonus: 1 },
      { skill: 'Schlösserknacken', bonus: 2 },
      { skill: 'Steinbearbeitung', bonus: 1 },
      { skill: 'Tanzen', bonus: 1 },
      { skill: 'Verbergen', bonus: 2 },
      { skill: 'Zechen', bonus: 1 },
    ],
    speciesRestriction: ['dwarf'],
    typicalAdvantages: ['Begabung in Handwerkstalenten', 'Soziale Anpassungsfähigkeit'],
    typicalDisadvantages: ['Angst vor … (dem Meer)', 'Persönlichkeitsschwächen (Eitelkeit)', 'Schlechte Eigenschaften (Geiz, Goldgier, Neugier)'],
    atypicalAdvantages: [],
    atypicalDisadvantages: ['Angst vor … (engen Räumen)', 'Blutrausch', 'Nachtblind'],
    url: 'https://dsa.ulisses-regelwiki.de/ZL_Brillantzwerge.html',
  },
  {
    name: 'erzzwerge',
    label: 'Erzzwerge',
    apCost: 34,
    language: 'Rogolan (erzzwergischer Dialekt)',
    script: 'Rogolan-Runen (2 AP)',
    socialStatus: [],
    culturePackage: [
      { skill: 'Geschichtswissen', bonus: 2 },
      { skill: 'Götter & Kulte', bonus: 2 },
      { skill: 'Mechanik', bonus: 2 },
      { skill: 'Metallbearbeitung', bonus: 1 },
      { skill: 'Rechnen', bonus: 2 },
      { skill: 'Rechtskunde', bonus: 1 },
      { skill: 'Sagen & Legenden', bonus: 2 },
      { skill: 'Selbstbeherrschung', bonus: 1 },
      { skill: 'Steinbearbeitung', bonus: 1 },
      { skill: 'Verbergen', bonus: 2 },
      { skill: 'Zechen', bonus: 1 },
    ],
    speciesRestriction: ['dwarf'],
    typicalAdvantages: ['Begabung in Wissens- oder Handwerkstalenten'],
    typicalDisadvantages: ['Angst vor … (Höhe oder dem Meer)', 'Persönlichkeitsschwächen (Arroganz, Vorurteile)', 'Schlechte Eigenschaften (Geiz, Goldgier)'],
    atypicalAdvantages: ['Soziale Anpassungsfähigkeit'],
    atypicalDisadvantages: ['Angst vor … (Dunkelheit, engen Räumen)', 'Nachtblind', 'Schlechte Eigenschaften (Neugier)'],
    url: 'https://dsa.ulisses-regelwiki.de/ZK_Erzzwerge.html',
  },
  {
    name: 'huegelzwerge',
    label: 'Hügelzwerge',
    apCost: 13,
    language: 'Rogolan (hügelzwergischer Dialekt)',
    script: 'Rogolan-Runen (2 AP)',
    socialStatus: [],
    culturePackage: [
      { skill: 'Fahrzeuge', bonus: 1 },
      { skill: 'Fischen & Angeln', bonus: 1 },
      { skill: 'Lebensmittelbearbeitung', bonus: 2 },
      { skill: 'Singen', bonus: 1 },
      { skill: 'Tanzen', bonus: 1 },
      { skill: 'Verbergen', bonus: 2 },
      { skill: 'Zechen', bonus: 1 },
    ],
    speciesRestriction: ['dwarf'],
    typicalAdvantages: ['Begabung in Gesellschafts- und Handwerkstalenten', 'Soziale Anpassungsfähigkeit'],
    typicalDisadvantages: ['Angst vor … (dem Meer)', 'Schlechte Eigenschaften (Goldgier, Neugier)'],
    atypicalAdvantages: [],
    atypicalDisadvantages: ['Angst vor … (Dunkelheit oder engen Räumen)', 'Blutrausch', 'Nachtblind'],
    url: 'https://dsa.ulisses-regelwiki.de/ZK_H%C3%BCgelzwerge.html',
  },
  {
    name: 'wildzwerge',
    label: 'Wildzwerge',
    apCost: 17,
    language: 'Rogolan (Brobimisch)',
    script: 'keine',
    socialStatus: ['Unfrei'],
    culturePackage: [
      { skill: 'Einschüchtern', bonus: 2 },
      { skill: 'Klettern', bonus: 2 },
      { skill: 'Steinbearbeitung', bonus: 2 },
      { skill: 'Verbergen', bonus: 2 },
      { skill: 'Zechen', bonus: 1 },
    ],
    speciesRestriction: ['dwarf'],
    typicalAdvantages: ['Dunkelsicht', 'Hitzeresistenz', 'Richtungssinn', 'Verbesserte Regeneration (Lebensenergie)', 'Zäher Hund'],
    typicalDisadvantages: [
      'Angst vor … (Flugwesen, Höhe, dem Meer)',
      'Persönlichkeitsschwächen (Autoritätsgläubig, Vorurteile)',
      'Schlechte Eigenschaften (Aberglaube, Jähzorn)',
      'Hässlich',
    ],
    atypicalAdvantages: ['Begabung in Wissenstalenten', 'Soziale Anpassungsfähigkeit'],
    atypicalDisadvantages: ['Angst vor … (Dunkelheit, engen Räumen)'],
    url: 'https://dsa.ulisses-regelwiki.de/kultur_wildzwerge.html',
  },
];

// ─── Orc Cultures ─────────────────────────────────────────────────────────────

export const ORC_CULTURES: Culture[] = [
  {
    name: 'orkland',
    label: 'Orkland',
    apCost: 40,
    language: 'Ologhaijan',
    script: 'keine',
    socialStatus: ['Adel', 'Unfrei'],
    culturePackage: [
      { skill: 'Einschüchtern', bonus: 2 },
      { skill: 'Holzbearbeitung', bonus: 1 },
      { skill: 'Klettern', bonus: 1 },
      { skill: 'Körperbeherrschung', bonus: 1 },
      { skill: 'Kraftakt', bonus: 2 },
      { skill: 'Kriegskunst', bonus: 1 },
      { skill: 'Lederbearbeitung', bonus: 1 },
      { skill: 'Orientierung', bonus: 1 },
      { skill: 'Selbstbeherrschung', bonus: 1 },
      { skill: 'Sinnesschärfe', bonus: 1 },
      { skill: 'Steinbearbeitung', bonus: 1 },
      { skill: 'Tierkunde', bonus: 1 },
      { skill: 'Wildnisleben', bonus: 2 },
    ],
    speciesRestriction: ['orc', 'halforc'],
    typicalAdvantages: ['Verbesserte Regeneration (Lebensenergie)', 'Zäher Hund'],
    typicalDisadvantages: ['Persönlichkeitsschwächen (Vorurteile)', 'Schlechte Eigenschaften (Aberglaube, Jähzorn)'],
    atypicalAdvantages: ['Soziale Anpassungsfähigkeit'],
    atypicalDisadvantages: ['Krankheitsanfällig'],
    url: 'https://dsa.ulisses-regelwiki.de/Kul_Orkland.html',
  },
];

// ─── Achaz Cultures ───────────────────────────────────────────────────────────

export const ACHAZ_CULTURES: Culture[] = [
  {
    name: 'stammesachaz',
    label: 'Stammesachaz',
    apCost: 50,
    language: 'Rssahh',
    script: 'keine',
    socialStatus: ['Adel'],
    culturePackage: [
      { skill: 'Boote & Schiffe', bonus: 1 },
      { skill: 'Fischen & Angeln', bonus: 2 },
      { skill: 'Holzbearbeitung', bonus: 1 },
      { skill: 'Körperbeherrschung', bonus: 1 },
      { skill: 'Lederbearbeitung', bonus: 2 },
      { skill: 'Orientierung', bonus: 1 },
      { skill: 'Pflanzenkunde', bonus: 1 },
      { skill: 'Sagen & Legenden', bonus: 1 },
      { skill: 'Schwimmen', bonus: 2 },
      { skill: 'Selbstbeherrschung', bonus: 1 },
      { skill: 'Sinnesschärfe', bonus: 1 },
      { skill: 'Steinbearbeitung', bonus: 1 },
      { skill: 'Tierkunde', bonus: 1 },
      { skill: 'Verbergen', bonus: 1 },
      { skill: 'Wildnisleben', bonus: 2 },
      { skill: 'Willenskraft', bonus: 1 },
    ],
    speciesRestriction: ['achaz'],
    typicalAdvantages: [],
    typicalDisadvantages: ['Persönlichkeitsschwächen (Vorurteile)'],
    atypicalAdvantages: ['Feenfreund', 'Koboldfreund', 'Soziale Anpassungsfähigkeit'],
    atypicalDisadvantages: ['Angst vor … (dem Meer, engen Räumen, Toten und Untoten)'],
    url: 'https://dsa.ulisses-regelwiki.de/Kul_Stammesachaz.html',
  },
  {
    name: 'achazRha',
    label: 'Achaz-Rha',
    apCost: 55,
    language: 'Rssahh (Achaz-Rha-Rssahh)',
    script: 'Chuchas (6 AP) oder Chrmk (4 AP)',
    socialStatus: ['Adel'],
    culturePackage: [
      { skill: 'Boote & Schiffe', bonus: 1 },
      { skill: 'Fischen & Angeln', bonus: 1 },
      { skill: 'Geschichtswissen', bonus: 2 },
      { skill: 'Götter & Kulte', bonus: 1 },
      { skill: 'Körperbeherrschung', bonus: 1 },
      { skill: 'Lederbearbeitung', bonus: 1 },
      { skill: 'Magiekunde', bonus: 1 },
      { skill: 'Mechanik', bonus: 1 },
      { skill: 'Rechnen', bonus: 2 },
      { skill: 'Sagen & Legenden', bonus: 2 },
      { skill: 'Schwimmen', bonus: 1 },
      { skill: 'Selbstbeherrschung', bonus: 1 },
      { skill: 'Sinnesschärfe', bonus: 1 },
      { skill: 'Sphärenkunde', bonus: 1 },
      { skill: 'Steinbearbeitung', bonus: 2 },
      { skill: 'Sternkunde', bonus: 1 },
      { skill: 'Tierkunde', bonus: 1 },
      { skill: 'Wildnisleben', bonus: 1 },
      { skill: 'Willenskraft', bonus: 2 },
    ],
    speciesRestriction: ['achaz'],
    typicalAdvantages: [],
    typicalDisadvantages: ['Persönlichkeitsschwächen (Arroganz, Vorurteile)'],
    atypicalAdvantages: ['Feenfreund', 'Koboldfreund', 'Soziale Anpassungsfähigkeit'],
    atypicalDisadvantages: ['Angst vor … (dem Meer, engen Räumen, Toten und Untoten)'],
    url: 'https://dsa.ulisses-regelwiki.de/Kul_Achaz-Rha.html',
  },
  {
    name: 'ctkiSsrr',
    label: "Ctki'Ssrr",
    apCost: 49,
    language: "Rssahh (Ctki'Ssrr-Rssahh)",
    script: 'Chrmk (4 AP)',
    socialStatus: ['Adel', 'Unfrei'],
    culturePackage: [
      { skill: 'Fischen & Angeln', bonus: 1 },
      { skill: 'Geschichtswissen', bonus: 1 },
      { skill: 'Götter & Kulte', bonus: 1 },
      { skill: 'Holzbearbeitung', bonus: 1 },
      { skill: 'Klettern', bonus: 1 },
      { skill: 'Körperbeherrschung', bonus: 1 },
      { skill: 'Kraftakt', bonus: 1 },
      { skill: 'Lederbearbeitung', bonus: 1 },
      { skill: 'Orientierung', bonus: 1 },
      { skill: 'Sagen & Legenden', bonus: 1 },
      { skill: 'Schwimmen', bonus: 1 },
      { skill: 'Selbstbeherrschung', bonus: 1 },
      { skill: 'Sinnesschärfe', bonus: 1 },
      { skill: 'Steinbearbeitung', bonus: 2 },
      { skill: 'Tierkunde', bonus: 2 },
      { skill: 'Verbergen', bonus: 1 },
      { skill: 'Wildnisleben', bonus: 1 },
      { skill: 'Willenskraft', bonus: 1 },
    ],
    speciesRestriction: ['achaz'],
    typicalAdvantages: [],
    typicalDisadvantages: ['Persönlichkeitsschwächen (Arroganz, Vorurteile)'],
    atypicalAdvantages: ['Feenfreund', 'Koboldfreund', 'Soziale Anpassungsfähigkeit'],
    atypicalDisadvantages: ['Angst vor … (dem Meer, engen Räumen, Toten und Untoten)'],
    url: 'https://dsa.ulisses-regelwiki.de/Kul_CtkiSsrr.html',
  },
];

// ─── Goblin Cultures ──────────────────────────────────────────────────────────

export const GOBLIN_CULTURES: Culture[] = [
  {
    name: 'stammesgoblins',
    label: 'Stammesgoblins',
    apCost: 0,
    language: 'Goblinisch',
    script: 'keine',
    socialStatus: [],
    culturePackage: [],
    speciesRestriction: ['goblin'],
    typicalAdvantages: [],
    typicalDisadvantages: [],
    atypicalAdvantages: [],
    atypicalDisadvantages: [],
    url: 'https://dsa.ulisses-regelwiki.de/kulturen/goblin-kulturen/stammesgoblins.html',
  },
];

// ─── Nachtalb Cultures ────────────────────────────────────────────────────────

export const NACHTALB_CULTURES: Culture[] = [
  {
    name: 'nachtalbenDerNaiAshyrr',
    label: 'Nachtalben der Nai Ashyrr',
    apCost: 55,
    language: 'Asdharia (Shakagoran)',
    script: 'Isdira-Zeichen (2 AP)',
    socialStatus: [],
    culturePackage: [
      { skill: 'Einschüchtern', bonus: 2 },
      { skill: 'Fährtensuchen', bonus: 2 },
      { skill: 'Fischen & Angeln', bonus: 1 },
      { skill: 'Klettern', bonus: 1 },
      { skill: 'Körperbeherrschung', bonus: 2 },
      { skill: 'Orientierung', bonus: 2 },
      { skill: 'Selbstbeherrschung', bonus: 1 },
      { skill: 'Sinnesschärfe', bonus: 2 },
      { skill: 'Tierkunde', bonus: 2 },
      { skill: 'Verbergen', bonus: 2 },
      { skill: 'Wildnisleben', bonus: 2 },
    ],
    speciesRestriction: ['nachtalb'],
    typicalAdvantages: ['Begabung in Körper- und Naturtalenten', 'Kälteresistenz', 'Magische Einstimmung', 'Richtungssinn', 'Waffenbegabung'],
    typicalDisadvantages: ['Hitzeempfindlich', 'Lichtempfindlich', 'Persönlichkeitsschwächen (Arroganz, Vorurteile, Weltfremd)'],
    atypicalAdvantages: ['Allerweltsname', 'Begabung in Gesellschaftstalenten', 'Soziale Anpassungsfähigkeit'],
    atypicalDisadvantages: [
      'Angst vor … (Dunkelheit, engen Räumen)',
      'Kälteempfindlich',
      'Schlechte Eigenschaften (Goldgier, Naiv)',
      'Unfähig in Körper- und Naturtalenten',
    ],
    url: 'https://dsa.ulisses-regelwiki.de/kulturen/nachtalben-der-nai-ashyrr.html',
  },
];

// ─── Special Cultures ─────────────────────────────────────────────────────────

export const SPECIAL_CULTURES: Culture[] = [
  {
    name: 'holberk',
    label: 'Holberk',
    apCost: 27,
    language: 'Garethi (Holberkisch)',
    script: 'keine',
    socialStatus: ['Adel', 'Unfrei'],
    culturePackage: [
      { skill: 'Holzbearbeitung', bonus: 1 },
      { skill: 'Körperbeherrschung', bonus: 1 },
      { skill: 'Kraftakt', bonus: 1 },
      { skill: 'Lederbearbeitung', bonus: 1 },
      { skill: 'Metallbearbeitung', bonus: 1 },
      { skill: 'Pflanzenkunde', bonus: 1 },
      { skill: 'Sinnesschärfe', bonus: 1 },
      { skill: 'Steinbearbeitung', bonus: 1 },
      { skill: 'Tierkunde', bonus: 1 },
      { skill: 'Wildnisleben', bonus: 1 },
    ],
    speciesRestriction: ['holberker'],
    typicalAdvantages: ['Verbesserte Regeneration (Lebensenergie)', 'Zäher Hund'],
    typicalDisadvantages: ['Schlechte Eigenschaften (Aberglaube, Jähzorn)'],
    atypicalAdvantages: [],
    atypicalDisadvantages: ['Krankheitsanfällig'],
    url: 'https://dsa.ulisses-regelwiki.de/Kul_Holberk.html',
  },
  {
    name: 'raeuberbande',
    label: 'Räuberbande',
    apCost: 34,
    language: 'je nach Ursprungskultur',
    script: 'keine',
    socialStatus: ['Adel', 'Unfrei'],
    culturePackage: [
      { skill: 'Einschüchtern', bonus: 2 },
      { skill: 'Fährtensuchen', bonus: 1 },
      { skill: 'Fesseln', bonus: 2 },
      { skill: 'Gassenwissen', bonus: 1 },
      { skill: 'Holzbearbeitung', bonus: 1 },
      { skill: 'Orientierung', bonus: 1 },
      { skill: 'Rechtskunde', bonus: 1 },
      { skill: 'Sinnesschärfe', bonus: 1 },
      { skill: 'Tierkunde', bonus: 1 },
      { skill: 'Verbergen', bonus: 2 },
      { skill: 'Wildnisleben', bonus: 1 },
      { skill: 'Zechen', bonus: 1 },
    ],
    speciesRestriction: ['human', 'halfelf', 'halforc', 'orc', 'goblin'],
    typicalAdvantages: ['Verbesserte Regeneration (Lebensenergie)', 'Zäher Hund'],
    typicalDisadvantages: ['Persönlichkeitsschwächen (Vorurteile)', 'Schlechte Eigenschaften (Aberglaube, Jähzorn)'],
    atypicalAdvantages: ['Soziale Anpassungsfähigkeit'],
    atypicalDisadvantages: ['Krankheitsanfällig'],
    url: 'https://dsa.ulisses-regelwiki.de/Kul_Raeuberbande.html',
  },
];

// ─── Master list ──────────────────────────────────────────────────────────────

export const ALL_CULTURES: Culture[] = [
  ...HUMAN_CULTURES,
  ...EXPANSION_HUMAN_CULTURES,
  ...ELF_CULTURES,
  ...DWARF_CULTURES,
  ...ORC_CULTURES,
  ...ACHAZ_CULTURES,
  ...GOBLIN_CULTURES,
  ...NACHTALB_CULTURES,
  ...SPECIAL_CULTURES,
];
