import { Culture } from '../models/culture.model';

/** Social-status tiers (low → high) shared by all cultures; used to group the dropdown. */
export const SOCIAL_STATUS_ORDER = ['Unfrei', 'Frei', 'Adel'];

/**
 * The tier every culture has and every hero defaults to. A culture's own `socialStatus` list holds
 * only the ADDITIONAL tiers that occur there (which is why almost none of them mention "Frei", and
 * why the "Kultur muss über einen passenden Adel verfügen" prerequisite reads that list) — so this
 * one is implicit everywhere and must never be taken from the culture data.
 */
export const DEFAULT_SOCIAL_STATUS = 'Frei';

// ─── Human Cultures ───────────────────────────────────────────────────────────

export const HUMAN_CULTURES: Culture[] = [
  {
    name: 'andergaster',
    label: 'Andergaster',
    apCost: 20,
    language: 'Garethi (Andergastisch)',
    script: 'Kusliker Zeichen (2 AP)',
    socialStatus: ['Adel', 'Unfrei'],
    culturePackage: [
      { skill: 'Holzbearbeitung', bonus: 2 },
      { skill: 'Orientierung', bonus: 1 },
      { skill: 'Pflanzenkunde', bonus: 1 },
      { skill: 'Sagen & Legenden', bonus: 1 },
      { skill: 'Tierkunde', bonus: 1 },
      { skill: 'Wildnisleben', bonus: 2 },
    ],
    speciesRestriction: ['human', 'halfelf'],
    typicalAdvantages: [{ name: 'richtungssinn' }, { name: 'zaherHund' }],
    typicalDisadvantages: [{ name: 'personlichkeitsschwache', option: 'vorurteile' }, { name: 'personlichkeitsschwache', option: 'weltfremd' }, { name: 'schlechteEigenschaft', option: 'aberglaube' }],
    atypicalAdvantages: [{ name: 'sozialeAnpassungsfahigkeit' }],
    atypicalDisadvantages: [{ name: 'krankheitsanfallig' }],
    url: 'https://dsa.ulisses-regelwiki.de/Kul_Andergaster.html',
  },
  {
    name: 'aranier',
    label: 'Aranier',
    apCost: 26,
    language: 'Tulamidya (Aranisch) oder Garethi (Aretya)',
    script: 'Tulamidya oder Kusliker Zeichen (2 AP)',
    socialStatus: ['Adel', 'Unfrei'],
    culturePackage: [
      { skill: 'Betören', bonus: 1 },
      { skill: 'Brett- & Glücksspiel', bonus: 1 },
      { skill: 'Gassenwissen', bonus: 2 },
      { skill: 'Handel', bonus: 2 },
      { skill: 'Menschenkenntnis', bonus: 1 },
      { skill: 'Rechnen', bonus: 1 },
      { skill: 'Sagen & Legenden', bonus: 1 },
      { skill: 'Stoffbearbeitung', bonus: 1 },
      { skill: 'Überreden', bonus: 2 },
    ],
    speciesRestriction: ['human', 'halfelf'],
    typicalAdvantages: [{ name: 'begabung', label: 'Begabung in Gesellschaftstalenten' }, { name: 'entfernungssinn' }],
    typicalDisadvantages: [
      { name: 'personlichkeitsschwache', option: 'eitelkeit' },
      { name: 'personlichkeitsschwache', option: 'vorurteile' },
      { name: 'schlechteEigenschaft', option: 'aberglaube' },
      { name: 'zerbrechlich' },
    ],
    atypicalAdvantages: [{ name: 'kalteresistenz' }],
    atypicalDisadvantages: [{ name: 'blutrausch' }],
    url: 'https://dsa.ulisses-regelwiki.de/Kul_Aranier.html',
  },
  {
    name: 'bornlaender',
    label: 'Bornländer',
    apCost: 18,
    language: 'Garethi (Bornländisch)',
    script: 'Kusliker Zeichen (2 AP)',
    socialStatus: ['Adel', 'Unfrei'],
    culturePackage: [
      { skill: 'Fährtensuchen', bonus: 1 },
      { skill: 'Holzbearbeitung', bonus: 2 },
      { skill: 'Lebensmittelbearbeitung', bonus: 1 },
      { skill: 'Orientierung', bonus: 1 },
      { skill: 'Pflanzenkunde', bonus: 1 },
      { skill: 'Wildnisleben', bonus: 1 },
      { skill: 'Zechen', bonus: 2 },
    ],
    speciesRestriction: ['human', 'halfelf'],
    typicalAdvantages: [{ name: 'kalteresistenz' }, { name: 'richtungssinn' }, { name: 'zaherHund' }],
    typicalDisadvantages: [{ name: 'hitzeempfindlich' }, { name: 'personlichkeitsschwache', option: 'vorurteile' }, { name: 'schlechteEigenschaft', option: 'aberglaube' }],
    atypicalAdvantages: [{ name: 'hitzeresistenz' }],
    atypicalDisadvantages: [],
    url: 'https://dsa.ulisses-regelwiki.de/Kul_Bornl%C3%A4nder.html',
  },
  {
    name: 'fjarninger',
    label: 'Fjarninger',
    apCost: 33,
    language: 'Fjarningsch',
    script: 'keine',
    socialStatus: ['Adel'],
    culturePackage: [
      { skill: 'Einschüchtern', bonus: 2 },
      { skill: 'Fährtensuchen', bonus: 1 },
      { skill: 'Körperbeherrschung', bonus: 1 },
      { skill: 'Kraftakt', bonus: 2 },
      { skill: 'Metallbearbeitung', bonus: 1 },
      { skill: 'Orientierung', bonus: 2 },
      { skill: 'Selbstbeherrschung', bonus: 1 },
      { skill: 'Steinbearbeitung', bonus: 1 },
      { skill: 'Wildnisleben', bonus: 2 },
    ],
    speciesRestriction: ['human'],
    typicalAdvantages: [{ name: 'entfernungssinn' }, { name: 'kalteresistenz' }, { name: 'richtungssinn' }, { name: 'verbesserteRegenerationLep', label: 'Verbesserte Regeneration (Lebensenergie)' }, { name: 'zaherHund' }],
    typicalDisadvantages: [
      { name: 'angstVor', option: 'demmeer' },
      { name: 'blutrausch' },
      { name: 'hitzeempfindlich' },
      { name: 'schlechteEigenschaft', label: 'Schlechte Eigenschaften (Aberglaube, Jähzorn)' },
      { name: 'unfahig', label: 'Unfähig in Gesellschaftstalenten' },
    ],
    atypicalAdvantages: [{ name: 'hitzeresistenz' }, { name: 'sozialeAnpassungsfahigkeit' }, { name: 'unscheinbar' }],
    atypicalDisadvantages: [
      { name: 'angstVor', label: 'Angst vor … (Dunkelheit, engen Räumen oder Höhe)' },
      { name: 'fettleibig' },
      { name: 'kalteempfindlich' },
      { name: 'krankheitsanfallig' },
      { name: 'nachtblind' },
      { name: 'personlichkeitsschwache', option: 'eitelkeit' },
      { name: 'zerbrechlich' },
    ],
    url: 'https://dsa.ulisses-regelwiki.de/Kul_Fjarninger.html',
  },
  {
    name: 'horasier',
    label: 'Horasier',
    apCost: 27,
    language: 'Garethi (Horathi)',
    script: 'Kusliker Zeichen (2 AP)',
    socialStatus: ['Adel'],
    culturePackage: [
      { skill: 'Betören', bonus: 1 },
      { skill: 'Boote & Schiffe', bonus: 1 },
      { skill: 'Etikette', bonus: 2 },
      { skill: 'Gassenwissen', bonus: 2 },
      { skill: 'Geographie', bonus: 1 },
      { skill: 'Geschichtswissen', bonus: 1 },
      { skill: 'Handel', bonus: 1 },
      { skill: 'Mechanik', bonus: 1 },
      { skill: 'Rechnen', bonus: 2 },
      { skill: 'Rechtskunde', bonus: 2 },
      { skill: 'Tanzen', bonus: 1 },
    ],
    speciesRestriction: ['human', 'halfelf'],
    typicalAdvantages: [{ name: 'sozialeAnpassungsfahigkeit' }],
    typicalDisadvantages: [{ name: 'personlichkeitsschwache', label: 'Persönlichkeitsschwächen (Arroganz, Eitelkeit, Vorurteile)' }],
    atypicalAdvantages: [{ name: 'begabung', label: 'Begabung in Naturtalenten' }],
    atypicalDisadvantages: [{ name: 'angstVor', option: 'engenraeumen' }],
    url: 'https://dsa.ulisses-regelwiki.de/Kul_Horasier.html',
  },
  {
    name: 'maraskaner',
    label: 'Maraskaner',
    apCost: 26,
    language: 'Garethi (Maraskani) oder Tulamidya (Maraskani-Tulamidya)',
    script: 'Kusliker Zeichen oder Tulamidya (2 AP)',
    socialStatus: ['Adel'],
    culturePackage: [
      { skill: 'Götter & Kulte', bonus: 1 },
      { skill: 'Heilkunde Gift', bonus: 2 },
      { skill: 'Orientierung', bonus: 1 },
      { skill: 'Pflanzenkunde', bonus: 2 },
      { skill: 'Tierkunde', bonus: 2 },
      { skill: 'Verbergen', bonus: 1 },
      { skill: 'Wildnisleben', bonus: 1 },
    ],
    speciesRestriction: ['human', 'halfelf'],
    typicalAdvantages: [{ name: 'giftresistenz' }, { name: 'hitzeresistenz' }, { name: 'krankheitsresistenz' }, { name: 'richtungssinn' }, { name: 'sozialeAnpassungsfahigkeit' }],
    typicalDisadvantages: [{ name: 'personlichkeitsschwache', label: 'Persönlichkeitsschwächen (Arroganz, Vorurteile)' }, { name: 'schlechteEigenschaft', option: 'neugier' }],
    atypicalAdvantages: [{ name: 'kalteresistenz' }],
    atypicalDisadvantages: [{ name: 'angstVor', option: 'insekten' }, { name: 'farbenblind' }, { name: 'schlechteEigenschaft', option: 'jaehzorn' }],
    url: 'https://dsa.ulisses-regelwiki.de/Kul_Maraskaner.html',
  },
  {
    name: 'mhanadistani',
    label: 'Mhanadistani',
    apCost: 28,
    language: 'Tulamidya (Mhanadisch-Balashidisch)',
    script: 'Tulamidya (2 AP)',
    socialStatus: ['Adel', 'Unfrei'],
    culturePackage: [
      { skill: 'Brett- & Glücksspiel', bonus: 2 },
      { skill: 'Gassenwissen', bonus: 2 },
      { skill: 'Geschichtswissen', bonus: 1 },
      { skill: 'Götter & Kulte', bonus: 2 },
      { skill: 'Handel', bonus: 2 },
      { skill: 'Magiekunde', bonus: 1 },
      { skill: 'Sagen & Legenden', bonus: 2 },
      { skill: 'Überreden', bonus: 1 },
    ],
    speciesRestriction: ['human', 'halfelf'],
    typicalAdvantages: [{ name: 'gluck' }, { name: 'hitzeresistenz' }, { name: 'sozialeAnpassungsfahigkeit' }],
    typicalDisadvantages: [{ name: 'personlichkeitsschwache', label: 'Persönlichkeitsschwächen (Eitelkeit, Vorurteile)' }, { name: 'schlechteEigenschaft', label: 'Schlechte Eigenschaften (Aberglaube, Goldgier, Neugier)' }],
    atypicalAdvantages: [{ name: 'kalteresistenz' }],
    atypicalDisadvantages: [{ name: 'angstVor', label: 'Angst vor … (engen Räumen, Menschenmassen)' }],
    url: 'https://dsa.ulisses-regelwiki.de/Kul_Mhanadistani.html',
  },
  {
    name: 'mittelreicher',
    label: 'Mittelreicher',
    apCost: 12,
    language: 'Garethi',
    script: 'Kusliker Zeichen (2 AP)',
    socialStatus: ['Adel', 'Unfrei'],
    culturePackage: [
      { skill: 'Holzbearbeitung', bonus: 1 },
      { skill: 'Metallbearbeitung', bonus: 1 },
      { skill: 'Pflanzenkunde', bonus: 1 },
      { skill: 'Stoffbearbeitung', bonus: 1 },
      { skill: 'Tierkunde', bonus: 1 },
    ],
    speciesRestriction: ['human', 'halfelf', 'halforc'],
    typicalAdvantages: [{ name: 'gluck' }],
    typicalDisadvantages: [{ name: 'personlichkeitsschwache', option: 'vorurteile' }, { name: 'schlechteEigenschaft', option: 'aberglaube' }],
    atypicalAdvantages: [{ name: 'hitzeresistenz' }, { name: 'kalteresistenz' }],
    atypicalDisadvantages: [],
    url: 'https://dsa.ulisses-regelwiki.de/Kul_Mittelreicher.html',
  },
  {
    name: 'nivesen',
    label: 'Nivesen',
    apCost: 37,
    language: 'Nujuka',
    script: 'keine',
    socialStatus: ['Adel'],
    culturePackage: [
      { skill: 'Fährtensuchen', bonus: 2 },
      { skill: 'Fahrzeuge', bonus: 1 },
      { skill: 'Orientierung', bonus: 2 },
      { skill: 'Pflanzenkunde', bonus: 1 },
      { skill: 'Sagen & Legenden', bonus: 2 },
      { skill: 'Sinnesschärfe', bonus: 1 },
      { skill: 'Tierkunde', bonus: 2 },
      { skill: 'Verbergen', bonus: 1 },
      { skill: 'Wildnisleben', bonus: 2 },
    ],
    speciesRestriction: ['human'],
    typicalAdvantages: [{ name: 'kalteresistenz' }, { name: 'richtungssinn' }],
    typicalDisadvantages: [{ name: 'angstVor', label: 'Angst vor … (engen Räumen, Höhe und Toten und Untoten)' }],
    atypicalAdvantages: [{ name: 'hitzeresistenz' }, { name: 'sozialeAnpassungsfahigkeit' }],
    atypicalDisadvantages: [{ name: 'fettleibig' }, { name: 'personlichkeitsschwache', option: 'arroganz' }, { name: 'schlechteEigenschaft', option: 'goldgier' }],
    url: 'https://dsa.ulisses-regelwiki.de/Kul_Nivesen.html',
  },
  {
    name: 'norbarden',
    label: 'Norbarden',
    apCost: 18,
    language: 'Alaani (Gajka, Takellen)',
    script: 'Kusliker Zeichen (2 AP)',
    socialStatus: [],
    culturePackage: [
      { skill: 'Fahrzeuge', bonus: 2 },
      { skill: 'Geographie', bonus: 2 },
      { skill: 'Handel', bonus: 2 },
      { skill: 'Orientierung', bonus: 1 },
      { skill: 'Überreden', bonus: 1 },
      { skill: 'Wildnisleben', bonus: 1 },
    ],
    speciesRestriction: ['human', 'halfelf'],
    typicalAdvantages: [{ name: 'kalteresistenz' }, { name: 'richtungssinn' }],
    typicalDisadvantages: [{ name: 'angstVor', label: 'Angst vor … (engen Räumen oder Höhe)' }, { name: 'schlechteEigenschaft', label: 'Schlechte Eigenschaften (Goldgier, Neugier)' }, { name: 'verpflichtungen', label: 'Verpflichtungen (gegenüber der Sippe)' }],
    atypicalAdvantages: [{ name: 'hitzeresistenz' }],
    atypicalDisadvantages: [{ name: 'personlichkeitsschwache', option: 'arroganz' }, { name: 'prinzipientreue' }],
    url: 'https://dsa.ulisses-regelwiki.de/Kul_Norbarden.html',
  },
  {
    name: 'nordaventurier',
    label: 'Nordaventurier',
    apCost: 25,
    language: 'Alaani, Garethi, Nujuka oder Thorwalsch',
    script: 'Kusliker Zeichen (2 AP)',
    socialStatus: ['Adel', 'Unfrei'],
    culturePackage: [
      { skill: 'Fährtensuchen', bonus: 1 },
      { skill: 'Handel', bonus: 1 },
      { skill: 'Holzbearbeitung', bonus: 1 },
      { skill: 'Lederbearbeitung', bonus: 1 },
      { skill: 'Orientierung', bonus: 1 },
      { skill: 'Pflanzenkunde', bonus: 1 },
      { skill: 'Selbstbeherrschung', bonus: 1 },
      { skill: 'Tierkunde', bonus: 1 },
      { skill: 'Wildnisleben', bonus: 1 },
      { skill: 'Zechen', bonus: 1 },
    ],
    speciesRestriction: ['human', 'halfelf'],
    typicalAdvantages: [{ name: 'entfernungssinn' }, { name: 'richtungssinn' }, { name: 'zaherHund' }],
    typicalDisadvantages: [{ name: 'angstVor', option: 'engenraeumen' }, { name: 'schlechteEigenschaft', option: 'aberglaube' }],
    atypicalAdvantages: [{ name: 'hitzeresistenz' }],
    atypicalDisadvantages: [{ name: 'krankheitsanfallig' }],
    url: 'https://dsa.ulisses-regelwiki.de/Kul_Nordaventurier.html',
  },
  {
    name: 'nostrier',
    label: 'Nostrier',
    apCost: 15,
    language: 'Garethi (Nostrisch)',
    script: 'Kusliker Zeichen (2 AP)',
    socialStatus: ['Adel', 'Unfrei'],
    culturePackage: [
      { skill: 'Fischen & Angeln', bonus: 2 },
      { skill: 'Orientierung', bonus: 1 },
      { skill: 'Pflanzenkunde', bonus: 1 },
      { skill: 'Sagen & Legenden', bonus: 1 },
      { skill: 'Tierkunde', bonus: 1 },
      { skill: 'Wildnisleben', bonus: 1 },
    ],
    speciesRestriction: ['human', 'halfelf'],
    typicalAdvantages: [{ name: 'richtungssinn' }, { name: 'zaherHund' }],
    typicalDisadvantages: [{ name: 'personlichkeitsschwache', label: 'Persönlichkeitsschwächen (Vorurteile, Weltfremd)' }, { name: 'schlechteEigenschaft', option: 'aberglaube' }],
    atypicalAdvantages: [{ name: 'sozialeAnpassungsfahigkeit' }],
    atypicalDisadvantages: [{ name: 'krankheitsanfallig' }],
    url: 'https://dsa.ulisses-regelwiki.de/Kul_Nostrier.html',
  },
  {
    name: 'novadis',
    label: 'Novadis',
    apCost: 25,
    language: 'Tulamidya (Khôm-Novadisch)',
    script: 'Heilige Glyphen von Unau (2 AP)',
    socialStatus: ['Adel', 'Unfrei'],
    culturePackage: [
      { skill: 'Einschüchtern', bonus: 2 },
      { skill: 'Fährtensuchen', bonus: 1 },
      { skill: 'Orientierung', bonus: 2 },
      { skill: 'Rechtskunde', bonus: 1 },
      { skill: 'Reiten', bonus: 2 },
      { skill: 'Tierkunde', bonus: 1 },
      { skill: 'Wildnisleben', bonus: 2 },
    ],
    speciesRestriction: ['human'],
    typicalAdvantages: [{ name: 'entfernungssinn' }, { name: 'hitzeresistenz' }, { name: 'richtungssinn' }, { name: 'schwerZuVerzaubern' }, { name: 'zaherHund' }],
    typicalDisadvantages: [
      { name: 'angstVor', label: 'Angst vor … (engen Räumen und dem Meer)' },
      { name: 'personlichkeitsschwache', label: 'Persönlichkeitsschwächen (Arroganz, Vorurteile)' },
      { name: 'prinzipientreue', option: '99gesetze' },
      { name: 'schlechteEigenschaft', label: 'Schlechte Eigenschaften (Jähzorn, Rachsucht)' },
    ],
    atypicalAdvantages: [{ name: 'hitzeempfindlich' }, { name: 'kalteresistenz' }],
    atypicalDisadvantages: [],
    url: 'https://dsa.ulisses-regelwiki.de/Kul_Novadis.html',
  },
  {
    name: 'svellttaler',
    label: 'Svellttaler',
    apCost: 21,
    language: 'Garethi',
    script: 'Kusliker Zeichen (2 AP)',
    socialStatus: ['Adel', 'Unfrei'],
    culturePackage: [
      { skill: 'Fährtensuchen', bonus: 2 },
      { skill: 'Fahrzeuge', bonus: 2 },
      { skill: 'Orientierung', bonus: 1 },
      { skill: 'Pflanzenkunde', bonus: 1 },
      { skill: 'Sagen & Legenden', bonus: 1 },
      { skill: 'Tierkunde', bonus: 1 },
      { skill: 'Wildnisleben', bonus: 1 },
    ],
    speciesRestriction: ['human', 'halfelf'],
    typicalAdvantages: [{ name: 'entfernungssinn' }, { name: 'richtungssinn' }, { name: 'zaherHund' }],
    typicalDisadvantages: [{ name: 'angstVor', option: 'engenraeumen' }, { name: 'personlichkeitsschwache', option: 'vorurteile' }, { name: 'schlechteEigenschaft', option: 'aberglaube' }],
    atypicalAdvantages: [{ name: 'hitzeresistenz' }],
    atypicalDisadvantages: [{ name: 'krankheitsanfallig' }],
    url: 'https://dsa.ulisses-regelwiki.de/Kul_Svellttaler.html',
  },
  {
    name: 'suedaventurier',
    label: 'Südaventurier',
    apCost: 26,
    language: 'Garethi (Brabaci, Charypto, Gatamo)',
    script: 'Kusliker Zeichen (2 AP)',
    socialStatus: ['Adel', 'Unfrei'],
    culturePackage: [
      { skill: 'Betören', bonus: 1 },
      { skill: 'Boote & Schiffe', bonus: 1 },
      { skill: 'Fischen & Angeln', bonus: 1 },
      { skill: 'Gassenwissen', bonus: 2 },
      { skill: 'Heilkunde Gift', bonus: 1 },
      { skill: 'Menschenkenntnis', bonus: 2 },
      { skill: 'Überreden', bonus: 1 },
      { skill: 'Willenskraft', bonus: 1 },
    ],
    speciesRestriction: ['human', 'halfelf'],
    typicalAdvantages: [{ name: 'hitzeresistenz' }, { name: 'sozialeAnpassungsfahigkeit' }],
    typicalDisadvantages: [
      { name: 'kalteempfindlich' },
      { name: 'personlichkeitsschwache', label: 'Persönlichkeitsschwächen (Arroganz, Eitelkeit)' },
      { name: 'schlechteEigenschaft', label: 'Schlechte Eigenschaften (Aberglaube, Goldgier, Jähzorn, Neugier)' },
    ],
    atypicalAdvantages: [{ name: 'kalteresistenz' }],
    atypicalDisadvantages: [{ name: 'angstVor', label: 'Angst vor … (engen Räumen, Menschenmassen und Toten und Untoten)' }],
    url: 'https://dsa.ulisses-regelwiki.de/Kul_S%C3%BCdaventurier.html',
  },
  {
    name: 'thorwaler',
    label: 'Thorwaler',
    apCost: 24,
    language: 'Thorwalsch',
    script: 'Thorwalsche Runen oder Kusliker Zeichen (2 AP)',
    socialStatus: ['Adel'],
    culturePackage: [
      { skill: 'Boote & Schiffe', bonus: 2 },
      { skill: 'Einschüchtern', bonus: 1 },
      { skill: 'Fischen & Angeln', bonus: 2 },
      { skill: 'Geographie', bonus: 1 },
      { skill: 'Holzbearbeitung', bonus: 2 },
      { skill: 'Kraftakt', bonus: 2 },
      { skill: 'Orientierung', bonus: 1 },
      { skill: 'Sagen & Legenden', bonus: 1 },
      { skill: 'Zechen', bonus: 2 },
    ],
    speciesRestriction: ['human', 'halfelf'],
    typicalAdvantages: [{ name: 'entfernungssinn' }, { name: 'gluck' }, { name: 'richtungssinn' }, { name: 'verbesserteRegenerationLep', label: 'Verbesserte Regeneration (Lebensenergie)' }, { name: 'zaherHund' }],
    typicalDisadvantages: [{ name: 'blutrausch' }, { name: 'personlichkeitsschwache', option: 'vorurteile' }, { name: 'schlechteEigenschaft', label: 'Schlechte Eigenschaften (Aberglaube, Neugier, Rachsucht)' }],
    atypicalAdvantages: [{ name: 'sozialeAnpassungsfahigkeit' }],
    atypicalDisadvantages: [{ name: 'angstVor', option: 'demmeer' }],
    url: 'https://dsa.ulisses-regelwiki.de/Kul_Thorwaler.html',
  },
  {
    name: 'trollzacker',
    label: 'Trollzacker',
    apCost: 38,
    language: 'Zhulchammaqra',
    script: 'keine',
    socialStatus: ['Adel', 'Unfrei'],
    culturePackage: [
      { skill: 'Einschüchtern', bonus: 2 },
      { skill: 'Fährtensuchen', bonus: 1 },
      { skill: 'Klettern', bonus: 2 },
      { skill: 'Körperbeherrschung', bonus: 1 },
      { skill: 'Kraftakt', bonus: 1 },
      { skill: 'Orientierung', bonus: 1 },
      { skill: 'Selbstbeherrschung', bonus: 2 },
      { skill: 'Steinbearbeitung', bonus: 2 },
      { skill: 'Tierkunde', bonus: 1 },
      { skill: 'Verbergen', bonus: 1 },
      { skill: 'Wildnisleben', bonus: 1 },
    ],
    speciesRestriction: ['human', 'halforc'],
    typicalAdvantages: [{ name: 'hoheLebenskraft' }, { name: 'richtungssinn' }, { name: 'verbesserteRegenerationLep', label: 'Verbesserte Regeneration (Lebensenergie)' }, { name: 'zaherHund' }],
    typicalDisadvantages: [{ name: 'blutrausch' }, { name: 'hasslich' }, { name: 'schlechteEigenschaft', label: 'Schlechte Eigenschaften (Aberglaube, Jähzorn, Rachsucht)' }],
    atypicalAdvantages: [{ name: 'sozialeAnpassungsfahigkeit' }],
    atypicalDisadvantages: [{ name: 'krankheitsanfallig' }, { name: 'niedrigeLebenskraft' }, { name: 'unfahig', label: 'Unfähig in Naturtalenten' }, { name: 'zerbrechlich' }],
    url: 'https://dsa.ulisses-regelwiki.de/Kul_Trollzacker.html',
  },
  {
    name: 'utulus',
    label: 'Utulus',
    apCost: 40,
    language: 'Tahaya',
    script: 'keine',
    socialStatus: ['Adel', 'Unfrei'],
    culturePackage: [
      { skill: 'Einschüchtern', bonus: 1 },
      { skill: 'Fährtensuchen', bonus: 1 },
      { skill: 'Heilkunde Gift', bonus: 1 },
      { skill: 'Heilkunde Krankheiten', bonus: 1 },
      { skill: 'Holzbearbeitung', bonus: 1 },
      { skill: 'Körperbeherrschung', bonus: 1 },
      { skill: 'Orientierung', bonus: 1 },
      { skill: 'Pflanzenkunde', bonus: 1 },
      { skill: 'Sagen & Legenden', bonus: 1 },
      { skill: 'Schwimmen', bonus: 1 },
      { skill: 'Sinnesschärfe', bonus: 1 },
      { skill: 'Tierkunde', bonus: 2 },
      { skill: 'Wildnisleben', bonus: 2 },
    ],
    speciesRestriction: ['human'],
    typicalAdvantages: [{ name: 'giftresistenz' }, { name: 'gluck' }, { name: 'gutaussehend' }, { name: 'hitzeresistenz' }, { name: 'hoheZahigkeit' }, { name: 'richtungssinn' }, { name: 'schlangenmensch' }],
    typicalDisadvantages: [
      { name: 'angstVor', label: 'Angst vor … (engen Räumen, dem Meer, Toten und Untoten)' },
      { name: 'kalteempfindlich' },
      { name: 'niedrigeSeelenkraft' },
      { name: 'schlechteEigenschaft', label: 'Schlechte Eigenschaften (Aberglaube, Neugier)' },
    ],
    atypicalAdvantages: [{ name: 'kalteresistenz' }],
    atypicalDisadvantages: [
      { name: 'angstVor', label: 'Angst vor … (Insekten, Reptilien, Spinnen)' },
      { name: 'krankheitsanfallig' },
      { name: 'nachtblind' },
      { name: 'personlichkeitsschwache', option: 'eitelkeit' },
      { name: 'schlechteEigenschaft', option: 'goldgier' },
      { name: 'unfahig', label: 'Unfähig in Naturtalenten' },
    ],
    url: 'https://dsa.ulisses-regelwiki.de/Kul_Utulus.html',
  },
  {
    name: 'waldmenschen',
    label: 'Waldmenschen',
    apCost: 42,
    language: 'Tahaya',
    script: 'keine',
    socialStatus: ['Adel'],
    culturePackage: [
      { skill: 'Fährtensuchen', bonus: 1 },
      { skill: 'Heilkunde Gift', bonus: 1 },
      { skill: 'Heilkunde Krankheiten', bonus: 1 },
      { skill: 'Klettern', bonus: 1 },
      { skill: 'Körperbeherrschung', bonus: 1 },
      { skill: 'Orientierung', bonus: 1 },
      { skill: 'Pflanzenkunde', bonus: 2 },
      { skill: 'Sagen & Legenden', bonus: 1 },
      { skill: 'Sinnesschärfe', bonus: 1 },
      { skill: 'Tierkunde', bonus: 2 },
      { skill: 'Verbergen', bonus: 1 },
      { skill: 'Wildnisleben', bonus: 2 },
    ],
    speciesRestriction: ['human'],
    typicalAdvantages: [{ name: 'angenehmerGeruch' }, { name: 'giftresistenz' }, { name: 'gluck' }, { name: 'gutaussehend' }, { name: 'hitzeresistenz' }, { name: 'richtungssinn' }, { name: 'schlangenmensch' }],
    typicalDisadvantages: [
      { name: 'angstVor', option: 'engenraeumen' },
      { name: 'kalteempfindlich' },
      { name: 'niedrigeSeelenkraft' },
      { name: 'personlichkeitsschwache', option: 'weltfremd' },
      { name: 'schlechteEigenschaft', label: 'Schlechte Eigenschaften (Aberglaube, Neugier)' },
    ],
    atypicalAdvantages: [{ name: 'kalteresistenz' }],
    atypicalDisadvantages: [
      { name: 'angstVor', label: 'Angst vor … (Höhe, Insekten, Reptilien, Spinnen)' },
      { name: 'krankheitsanfallig' },
      { name: 'nachtblind' },
      { name: 'personlichkeitsschwache', label: 'Persönlichkeitsschwächen (Eitelkeit, Streitsucht)' },
      { name: 'schlechteEigenschaft', option: 'goldgier' },
      { name: 'unfahig', label: 'Unfähig in Naturtalenten' },
    ],
    url: 'https://dsa.ulisses-regelwiki.de/Kul_Waldmenschen.html',
  },
  {
    name: 'zyklopaeer',
    label: 'Zyklopäer',
    apCost: 16,
    language: 'Garethi (Horathi) oder Zyklopäisch',
    script: 'Kusliker Zeichen (2 AP)',
    socialStatus: ['Adel'],
    culturePackage: [
      { skill: 'Boote & Schiffe', bonus: 1 },
      { skill: 'Fischen & Angeln', bonus: 2 },
      { skill: 'Geschichtswissen', bonus: 1 },
      { skill: 'Götter & Kulte', bonus: 2 },
      { skill: 'Musizieren', bonus: 1 },
      { skill: 'Rechnen', bonus: 1 },
      { skill: 'Rechtskunde', bonus: 1 },
      { skill: 'Sagen & Legenden', bonus: 1 },
      { skill: 'Tanzen', bonus: 1 },
    ],
    speciesRestriction: ['human', 'halfelf'],
    typicalAdvantages: [{ name: 'begabung', option: 'schwimmen' }, { name: 'entfernungssinn' }, { name: 'gutaussehend' }, { name: 'richtungssinn' }, { name: 'wohlklang' }],
    typicalDisadvantages: [{ name: 'personlichkeitsschwache', label: 'Persönlichkeitsschwächen (Arroganz, Eitelkeit, Vorurteile)' }],
    atypicalAdvantages: [{ name: 'kalteresistenz' }],
    atypicalDisadvantages: [{ name: 'angstVor', option: 'demmeer' }],
    url: 'https://dsa.ulisses-regelwiki.de/Kul_Zyklop%C3%A4er.html',
  },
];

// ─── Expansion Human Cultures ─────────────────────────────────────────────────

export const EXPANSION_HUMAN_CULTURES: Culture[] = [
  {
    name: 'adoru',
    label: 'Adoru',
    apCost: 28,
    language: 'Adorunu',
    script: 'Adorunu-Zeichen (2 AP)',
    socialStatus: ['Adel', 'Frei'],
    culturePackage: [
      { skill: 'Alchimie', bonus: 1 },
      { skill: 'Etikette', bonus: 2 },
      { skill: 'Fischen & Angeln', bonus: 1 },
      { skill: 'Götter & Kulte', bonus: 1 },
      { skill: 'Heilkunde Gift', bonus: 1 },
      { skill: 'Kriegskunst', bonus: 1 },
      { skill: 'Magiekunde', bonus: 1 },
      { skill: 'Mechanik', bonus: 1 },
      { skill: 'Metallbearbeitung', bonus: 1 },
      { skill: 'Rechnen', bonus: 1 },
      { skill: 'Selbstbeherrschung', bonus: 1 },
      { skill: 'Steinbearbeitung', bonus: 1 },
    ],
    speciesRestriction: ['human'],
    typicalAdvantages: [{ name: 'begabung', label: 'Begabung in Handwerkstalenten' }, { name: 'giftresistenz' }, { name: 'hitzeresistenz' }, { name: 'richtungssinn' }, { name: 'sozialeAnpassungsfahigkeit' }],
    typicalDisadvantages: [{ name: 'kalteempfindlich' }, { name: 'prinzipientreue' }, { name: 'schlechteEigenschaft', label: 'Schlechte Eigenschaften (Aberglaube, Neugier)' }],
    atypicalAdvantages: [{ name: 'kalteresistenz' }],
    atypicalDisadvantages: [{ name: 'angstVor', label: 'Angst vor … (Insekten, Spinnen, Höhe, engen Räumen)' }, { name: 'farbenblind' }, { name: 'hitzeempfindlich' }, { name: 'schlechteEigenschaft', option: 'jaehzorn' }],
    url: 'https://dsa.ulisses-regelwiki.de/kulturen/adoru.html',
  },
  {
    name: 'ferkinas',
    label: 'Ferkinas',
    apCost: 39,
    language: 'Ferkina',
    script: 'keine',
    socialStatus: ['Adel', 'Unfrei'],
    culturePackage: [
      { skill: 'Einschüchtern', bonus: 1 },
      { skill: 'Fährtensuchen', bonus: 1 },
      { skill: 'Klettern', bonus: 2 },
      { skill: 'Körperbeherrschung', bonus: 1 },
      { skill: 'Kraftakt', bonus: 1 },
      { skill: 'Pflanzenkunde', bonus: 1 },
      { skill: 'Reiten', bonus: 1 },
      { skill: 'Selbstbeherrschung', bonus: 1 },
      { skill: 'Steinbearbeitung', bonus: 2 },
      { skill: 'Tierkunde', bonus: 1 },
      { skill: 'Verbergen', bonus: 1 },
      { skill: 'Wildnisleben', bonus: 2 },
      { skill: 'Zechen', bonus: 1 },
    ],
    speciesRestriction: ['human'],
    typicalAdvantages: [{ name: 'giftresistenz' }, { name: 'hoheLebenskraft' }, { name: 'richtungssinn' }, { name: 'verbesserteRegenerationLep', label: 'Verbesserte Regeneration (Lebensenergie)' }, { name: 'zaherHund' }],
    typicalDisadvantages: [
      { name: 'blutrausch' },
      { name: 'hasslich' },
      { name: 'personlichkeitsschwache', option: 'vorurteile' },
      { name: 'schlechteEigenschaft', label: 'Schlechte Eigenschaften (Aberglaube, Jähzorn, Rachsucht)' },
      { name: 'unfahig', label: 'Unfähig in Gesellschaftstalenten' },
    ],
    atypicalAdvantages: [{ name: 'angenehmerGeruch' }, { name: 'hoheSeelenkraft' }, { name: 'schwerZuVerzaubern' }, { name: 'sozialeAnpassungsfahigkeit' }],
    atypicalDisadvantages: [{ name: 'krankheitsanfallig' }, { name: 'niedrigeLebenskraft' }, { name: 'zerbrechlich' }],
    url: 'https://dsa.ulisses-regelwiki.de/kul_Ferkinas.html',
  },
  {
    name: 'gjalsker',
    label: 'Gjalsker',
    apCost: 34,
    language: 'Gjalskisch',
    script: 'keine',
    socialStatus: ['Adel', 'Unfrei'],
    culturePackage: [
      { skill: 'Einschüchtern', bonus: 1 },
      { skill: 'Fährtensuchen', bonus: 1 },
      { skill: 'Klettern', bonus: 1 },
      { skill: 'Körperbeherrschung', bonus: 1 },
      { skill: 'Kraftakt', bonus: 2 },
      { skill: 'Orientierung', bonus: 1 },
      { skill: 'Pflanzenkunde', bonus: 1 },
      { skill: 'Sagen & Legenden', bonus: 2 },
      { skill: 'Selbstbeherrschung', bonus: 1 },
      { skill: 'Tierkunde', bonus: 1 },
      { skill: 'Wildnisleben', bonus: 1 },
    ],
    speciesRestriction: ['human'],
    typicalAdvantages: [{ name: 'hoheLebenskraft' }, { name: 'kalteresistenz' }, { name: 'richtungssinn' }, { name: 'verbesserteRegenerationLep', label: 'Verbesserte Regeneration (Lebensenergie)' }, { name: 'zaherHund' }],
    typicalDisadvantages: [
      { name: 'angstVor', label: 'Angst vor … (Toten und Untoten, dem Meer)' },
      { name: 'blutrausch' },
      { name: 'personlichkeitsschwache', option: 'vorurteile' },
      { name: 'schlechteEigenschaft', option: 'aberglaube' },
    ],
    atypicalAdvantages: [{ name: 'hitzeresistenz' }, { name: 'sozialeAnpassungsfahigkeit' }],
    atypicalDisadvantages: [
      { name: 'angstVor', label: 'Angst vor … (Dunkelheit, Höhe)' },
      { name: 'behabig' },
      { name: 'fettleibig' },
      { name: 'glaesern' },
      { name: 'krankheitsanfallig' },
      { name: 'nachtblind' },
      { name: 'niedrigeLebenskraft' },
      { name: 'zerbrechlich' },
    ],
    url: 'https://dsa.ulisses-regelwiki.de/kul_Gjalsker.html',
  },
  {
    name: 'koboldweltler',
    label: 'Koboldweltler',
    apCost: 18,
    language: 'Garethi und Koboldisch',
    script: 'keine',
    socialStatus: [],
    culturePackage: [
      { skill: 'Brett- & Glücksspiel', bonus: 1 },
      { skill: 'Gassenwissen', bonus: 1 },
      { skill: 'Gaukeleien', bonus: 2 },
      { skill: 'Klettern', bonus: 1 },
      { skill: 'Magiekunde', bonus: 1 },
      { skill: 'Malen & Zeichnen', bonus: 1 },
      { skill: 'Musizieren', bonus: 1 },
      { skill: 'Singen', bonus: 1 },
      { skill: 'Sphärenkunde', bonus: 1 },
      { skill: 'Tanzen', bonus: 1 },
      { skill: 'Zechen', bonus: 1 },
    ],
    speciesRestriction: ['human', 'halfelf'],
    typicalAdvantages: [{ name: 'begabung', label: 'Begabung in Gesellschaftstalenten' }],
    typicalDisadvantages: [{ name: 'personlichkeitsschwache', option: 'weltfremd' }],
    atypicalAdvantages: [{ name: 'begabung', label: 'Begabung in Wissenstalenten' }, { name: 'sozialeAnpassungsfahigkeit' }],
    atypicalDisadvantages: [{ name: 'schlechteEigenschaft', option: 'goldgier' }, { name: 'unfahig', label: 'Unfähig in Körper- und Naturtalenten' }],
    url: 'https://dsa.ulisses-regelwiki.de/rergbgfb.html',
  },
  {
    name: 'nuanaaeLie',
    label: 'Nuanaä-Lie',
    apCost: 40,
    language: 'Nujuka',
    script: 'keine',
    socialStatus: ['Frei'],
    culturePackage: [
      { skill: 'Einschüchtern', bonus: 1 },
      { skill: 'Fährtensuchen', bonus: 2 },
      { skill: 'Holzbearbeitung', bonus: 1 },
      { skill: 'Orientierung', bonus: 2 },
      { skill: 'Sinnesschärfe', bonus: 1 },
      { skill: 'Steinbearbeitung', bonus: 1 },
      { skill: 'Tierkunde', bonus: 3 },
      { skill: 'Verbergen', bonus: 2 },
      { skill: 'Wildnisleben', bonus: 2 },
    ],
    speciesRestriction: ['human'],
    typicalAdvantages: [{ name: 'kalteresistenz' }, { name: 'richtungssinn' }],
    typicalDisadvantages: [{ name: 'angstVor', label: 'Angst vor … (weiten Flächen und Toten und Untoten)' }, { name: 'schlechteEigenschaft', label: 'Schlechte Eigenschaften (Aberglaube, Jähzorn, Naiv, Neugier)' }],
    atypicalAdvantages: [{ name: 'hitzeresistenz' }, { name: 'sozialeAnpassungsfahigkeit' }],
    atypicalDisadvantages: [{ name: 'fettleibig' }, { name: 'kalteempfindlich' }, { name: 'lichtempfindlich' }, { name: 'personlichkeitsschwache', option: 'arroganz' }, { name: 'schlechteEigenschaft', option: 'goldgier' }],
    url: 'https://dsa.ulisses-regelwiki.de/Kul_Menschen/nuanaae-lie.html',
  },
  {
    name: 'tocamuyac',
    label: 'Tocamuyac',
    apCost: 0,
    language: '',
    script: 'keine',
    socialStatus: [],
    culturePackage: [],
    speciesRestriction: ['human'],
    typicalAdvantages: [],
    typicalDisadvantages: [],
    atypicalAdvantages: [],
    atypicalDisadvantages: [],
    url: 'https://dsa.ulisses-regelwiki.de/Kul_Menschen/tocamuyac.html',
  },
  {
    name: 'zahori',
    label: 'Zahori',
    apCost: 27,
    language: 'Tulamidya (Zahorisch)',
    script: 'Kusliker Zeichen (2 AP)',
    socialStatus: [],
    culturePackage: [
      { skill: 'Betören', bonus: 1 },
      { skill: 'Gaukeleien', bonus: 2 },
      { skill: 'Körperbeherrschung', bonus: 1 },
      { skill: 'Orientierung', bonus: 1 },
      { skill: 'Sagen & Legenden', bonus: 1 },
      { skill: 'Tanzen', bonus: 1 },
      { skill: 'Taschendiebstahl', bonus: 2 },
      { skill: 'Überreden', bonus: 1 },
      { skill: 'Verbergen', bonus: 1 },
      { skill: 'Verkleiden', bonus: 1 },
      { skill: 'Wildnisleben', bonus: 1 },
    ],
    speciesRestriction: ['human', 'halfelf'],
    typicalAdvantages: [{ name: 'beidhandig' }, { name: 'flink' }, { name: 'fuchssinn' }, { name: 'richtungssinn' }, { name: 'schlangenmensch' }],
    typicalDisadvantages: [{ name: 'arm' }, { name: 'blutrausch' }, { name: 'schlechteEigenschaft', label: 'Schlechte Eigenschaften (Jähzorn, Rachsucht)' }, { name: 'verpflichtungen', option: 'sippe' }],
    atypicalAdvantages: [{ name: 'adel' }, { name: 'reich' }, { name: 'vertrauenerweckend' }],
    atypicalDisadvantages: [{ name: 'prinzipientreue' }],
    url: 'https://dsa.ulisses-regelwiki.de/kul_Zahori.html',
  },
];

// ─── Elf Cultures ─────────────────────────────────────────────────────────────

export const ELF_CULTURES: Culture[] = [
  {
    name: 'auelfen',
    label: 'Auelfen',
    apCost: 43,
    language: 'Isdira (auelfischer Dialekt)',
    script: 'Isdira-Zeichen (2 AP)',
    socialStatus: [],
    culturePackage: [
      { skill: 'Betören', bonus: 1 },
      { skill: 'Boote & Schiffe', bonus: 1 },
      { skill: 'Fährtensuchen', bonus: 1 },
      { skill: 'Fischen & Angeln', bonus: 2 },
      { skill: 'Körperbeherrschung', bonus: 2 },
      { skill: 'Musizieren', bonus: 2 },
      { skill: 'Orientierung', bonus: 1 },
      { skill: 'Pflanzenkunde', bonus: 1 },
      { skill: 'Schwimmen', bonus: 2 },
      { skill: 'Singen', bonus: 2 },
      { skill: 'Sinnesschärfe', bonus: 1 },
      { skill: 'Tierkunde', bonus: 1 },
      { skill: 'Verbergen', bonus: 1 },
      { skill: 'Wildnisleben', bonus: 1 },
    ],
    speciesRestriction: ['elf', 'halfelf'],
    typicalAdvantages: [{ name: 'begabung', label: 'Begabung in Handwerkstalenten' }, { name: 'magischeeinstimmung', option: 'wesenderauen' }, { name: 'waffenbegabung', option: 'boegen' }],
    typicalDisadvantages: [
      { name: 'artefaktgebunden', label: 'Artefaktgebunden (Instrument)' },
      { name: 'personlichkeitsschwache', label: 'Persönlichkeitsschwächen (Arroganz, Vorurteile, Weltfremd)' },
      { name: 'prinzipientreue', label: 'Prinzipientreue (Elfische Weltsicht)' },
      { name: 'schlechteEigenschaft', option: 'neugier' },
    ],
    atypicalAdvantages: [{ name: 'begabung', label: 'Begabung in Wissenstalenten' }],
    atypicalDisadvantages: [{ name: 'schlechteEigenschaft', label: 'Schlechte Eigenschaften (Goldgier, Rachsucht)' }, { name: 'unfahig', label: 'Unfähig in Körper- und Naturtalenten' }],
    url: 'https://dsa.ulisses-regelwiki.de/Kul_Auelfen.html',
  },
  {
    name: 'firnelfen',
    label: 'Firnelfen',
    apCost: 55,
    language: 'Isdira (firnelfischer Dialekt)',
    script: 'Isdira-Zeichen (2 AP)',
    socialStatus: [],
    culturePackage: [
      { skill: 'Fährtensuchen', bonus: 2 },
      { skill: 'Fischen & Angeln', bonus: 1 },
      { skill: 'Klettern', bonus: 1 },
      { skill: 'Körperbeherrschung', bonus: 2 },
      { skill: 'Musizieren', bonus: 2 },
      { skill: 'Orientierung', bonus: 2 },
      { skill: 'Selbstbeherrschung', bonus: 1 },
      { skill: 'Singen', bonus: 2 },
      { skill: 'Sinnesschärfe', bonus: 2 },
      { skill: 'Tierkunde', bonus: 2 },
      { skill: 'Verbergen', bonus: 2 },
      { skill: 'Wildnisleben', bonus: 2 },
    ],
    speciesRestriction: ['elf', 'halfelf'],
    typicalAdvantages: [
      { name: 'begabung', label: 'Begabung in Körper- und Naturtalenten' },
      { name: 'kalteresistenz' },
      { name: 'magischeeinstimmung', option: 'wesendeseises' },
      { name: 'richtungssinn' },
      { name: 'waffenbegabung', label: 'Waffenbegabung (Bögen und Wurfwaffen)' },
    ],
    typicalDisadvantages: [
      { name: 'artefaktgebunden', label: 'Artefaktgebunden (Instrument)' },
      { name: 'personlichkeitsschwache', label: 'Persönlichkeitsschwächen (Arroganz, Vorurteile, Weltfremd)' },
      { name: 'prinzipientreue', label: 'Prinzipientreue (Elfische Weltsicht)' },
      { name: 'unfahig', label: 'Unfähig in Wissenstalenten' },
    ],
    atypicalAdvantages: [{ name: 'begabung', label: 'Begabung in Wissenstalenten' }, { name: 'sozialeAnpassungsfahigkeit' }],
    atypicalDisadvantages: [
      { name: 'angstVor', label: 'Angst vor … (Dunkelheit, engen Räumen)' },
      { name: 'kalteempfindlich' },
      { name: 'schlechteEigenschaft', label: 'Schlechte Eigenschaften (Goldgier, Rachsucht)' },
      { name: 'unfahig', label: 'Unfähig in Körper- und Naturtalenten' },
    ],
    url: 'https://dsa.ulisses-regelwiki.de/Kul_Firnelfen.html',
  },
  {
    name: 'steppenelfen',
    label: 'Steppenelfen',
    apCost: 48,
    language: 'Isdira (steppenelfischer Dialekt)',
    script: 'Isdira-Zeichen (2 AP)',
    socialStatus: [],
    culturePackage: [
      { skill: 'Fährtensuchen', bonus: 2 },
      { skill: 'Körperbeherrschung', bonus: 2 },
      { skill: 'Musizieren', bonus: 1 },
      { skill: 'Orientierung', bonus: 2 },
      { skill: 'Pflanzenkunde', bonus: 1 },
      { skill: 'Reiten', bonus: 2 },
      { skill: 'Singen', bonus: 1 },
      { skill: 'Sinnesschärfe', bonus: 2 },
      { skill: 'Tanzen', bonus: 1 },
      { skill: 'Tierkunde', bonus: 2 },
      { skill: 'Wildnisleben', bonus: 2 },
    ],
    speciesRestriction: ['elf', 'halfelf'],
    typicalAdvantages: [{ name: 'begabung', label: 'Begabung in Körper- und Naturtalenten' }, { name: 'begabung', label: 'Begabung in Kampftechniken (Bögen)' }, { name: 'magischeeinstimmung', option: 'wesendersteppe' }],
    typicalDisadvantages: [
      { name: 'angstVor', option: 'engenraeumen' },
      { name: 'artefaktgebunden', label: 'Artefaktgebunden (Instrument)' },
      { name: 'personlichkeitsschwache', label: 'Persönlichkeitsschwächen (Arroganz, Vorurteile, Weltfremd)' },
      { name: 'unfahig', label: 'Unfähig in Wissenstalenten' },
    ],
    atypicalAdvantages: [{ name: 'begabung', label: 'Begabung in Wissenstalenten' }, { name: 'sozialeAnpassungsfahigkeit' }],
    atypicalDisadvantages: [{ name: 'schlechteEigenschaft', option: 'goldgier' }, { name: 'unfahig', label: 'Unfähig in Körper- und Naturtalenten' }],
    url: 'https://dsa.ulisses-regelwiki.de/Kult_Steppenelfen.html',
  },
  {
    name: 'waldelfen',
    label: 'Waldelfen',
    apCost: 47,
    language: 'Isdira (waldelfischer Dialekt)',
    script: 'Isdira-Zeichen (2 AP)',
    socialStatus: [],
    culturePackage: [
      { skill: 'Fährtensuchen', bonus: 2 },
      { skill: 'Klettern', bonus: 1 },
      { skill: 'Körperbeherrschung', bonus: 2 },
      { skill: 'Musizieren', bonus: 2 },
      { skill: 'Orientierung', bonus: 1 },
      { skill: 'Pflanzenkunde', bonus: 2 },
      { skill: 'Singen', bonus: 2 },
      { skill: 'Sinnesschärfe', bonus: 1 },
      { skill: 'Tierkunde', bonus: 2 },
      { skill: 'Verbergen', bonus: 2 },
      { skill: 'Wildnisleben', bonus: 1 },
    ],
    speciesRestriction: ['elf', 'halfelf'],
    typicalAdvantages: [{ name: 'begabung', label: 'Begabung in Körper- und Naturtalenten' }, { name: 'magischeeinstimmung', option: 'wesendeswaldes' }, { name: 'waffenbegabung', option: 'boegen' }],
    typicalDisadvantages: [
      { name: 'angstVor', option: 'engenraeumen' },
      { name: 'artefaktgebunden', label: 'Artefaktgebunden (Instrument)' },
      { name: 'korpergebundeneKraft' },
      { name: 'personlichkeitsschwache', label: 'Persönlichkeitsschwächen (Arroganz, Vorurteile, Weltfremd)' },
      { name: 'prinzipientreue', label: 'Prinzipientreue (Elfische Weltsicht)' },
      { name: 'unfahig', label: 'Unfähig in Wissenstalenten' },
    ],
    atypicalAdvantages: [{ name: 'begabung', label: 'Begabung in Wissenstalenten' }, { name: 'sozialeAnpassungsfahigkeit' }],
    atypicalDisadvantages: [{ name: 'schlechteEigenschaft', label: 'Schlechte Eigenschaften (Goldgier, Jähzorn, Rachsucht)' }, { name: 'unfahig', label: 'Unfähig in Körper- und Naturtalenten' }],
    url: 'https://dsa.ulisses-regelwiki.de/Kul_Waldelfen.html',
  },
  {
    name: 'wuestenelfen',
    label: 'Wüstenelfen',
    apCost: 55,
    language: 'Isdira (wüstenelfischer Dialekt)',
    script: 'Isdira-Zeichen (2 AP)',
    socialStatus: [],
    culturePackage: [
      { skill: 'Fährtensuchen', bonus: 2 },
      { skill: 'Körperbeherrschung', bonus: 2 },
      { skill: 'Musizieren', bonus: 1 },
      { skill: 'Orientierung', bonus: 2 },
      { skill: 'Pflanzenkunde', bonus: 1 },
      { skill: 'Sagen & Legenden', bonus: 1 },
      { skill: 'Selbstbeherrschung', bonus: 1 },
      { skill: 'Singen', bonus: 1 },
      { skill: 'Sinnesschärfe', bonus: 2 },
      { skill: 'Tierkunde', bonus: 2 },
      { skill: 'Verbergen', bonus: 2 },
      { skill: 'Wildnisleben', bonus: 2 },
    ],
    speciesRestriction: ['elf', 'halfelf'],
    typicalAdvantages: [
      { name: 'begabung', label: 'Begabung in Körper- und Naturtalenten' },
      { name: 'hitzeresistenz' },
      { name: 'magischeeinstimmung', option: 'wesenderwueste' },
      { name: 'richtungssinn' },
      { name: 'waffenbegabung', label: 'Waffenbegabung (Bögen und Wurfwaffen)' },
    ],
    typicalDisadvantages: [{ name: 'artefaktgebunden', label: 'Artefaktgebunden (Instrument)' }, { name: 'personlichkeitsschwache', label: 'Persönlichkeitsschwächen (Arroganz, Vorurteile)' }],
    atypicalAdvantages: [{ name: 'kalteresistenz' }, { name: 'sozialeAnpassungsfahigkeit' }],
    atypicalDisadvantages: [{ name: 'hitzeempfindlich' }, { name: 'schlechteEigenschaft', option: 'goldgier' }, { name: 'unfahig', label: 'Unfähig in Körper- und Naturtalenten' }],
    url: 'https://dsa.ulisses-regelwiki.de/Kul_Elfen/wuestenelfen.html',
  },
];

// ─── Dwarf Cultures ───────────────────────────────────────────────────────────

export const DWARF_CULTURES: Culture[] = [
  {
    name: 'ambosszwerge',
    label: 'Ambosszwerge',
    apCost: 31,
    language: 'Rogolan (ambosszwergischer Dialekt)',
    script: 'Rogolan-Runen (2 AP)',
    socialStatus: [],
    culturePackage: [
      { skill: 'Einschüchtern', bonus: 1 },
      { skill: 'Geschichtswissen', bonus: 1 },
      { skill: 'Kraftakt', bonus: 2 },
      { skill: 'Kriegskunst', bonus: 2 },
      { skill: 'Mechanik', bonus: 1 },
      { skill: 'Metallbearbeitung', bonus: 2 },
      { skill: 'Orientierung', bonus: 1 },
      { skill: 'Sagen & Legenden', bonus: 1 },
      { skill: 'Steinbearbeitung', bonus: 2 },
      { skill: 'Verbergen', bonus: 1 },
      { skill: 'Zechen', bonus: 2 },
    ],
    speciesRestriction: ['dwarf'],
    typicalAdvantages: [
      { name: 'begabung', label: 'Begabung in Handwerkstalenten' },
      { name: 'verbesserteRegenerationLep', label: 'Verbesserte Regeneration (Lebensenergie)' },
      { name: 'waffenbegabung', label: 'Waffenbegabung (Armbrüste, Hiebwaffen, Zweihandhiebwaffen)' },
      { name: 'zaherHund' },
    ],
    typicalDisadvantages: [
      { name: 'angstVor', option: 'demmeer' },
      { name: 'personlichkeitsschwache', label: 'Persönlichkeitsschwächen (Arroganz, Vorurteile)' },
      { name: 'prinzipientreue', label: 'Prinzipientreue (zwergischer Ehrenkodex)' },
      { name: 'schlechteEigenschaft', label: 'Schlechte Eigenschaften (Geiz, Goldgier)' },
    ],
    atypicalAdvantages: [{ name: 'sozialeAnpassungsfahigkeit' }],
    atypicalDisadvantages: [{ name: 'angstVor', label: 'Angst vor … (Dunkelheit oder engen Räumen)' }, { name: 'nachtblind' }, { name: 'personlichkeitsschwache', option: 'eitelkeit' }],
    url: 'https://dsa.ulisses-regelwiki.de/ZK_Ambosszwerge.html',
  },
  {
    name: 'brillantzwerge',
    label: 'Brillantzwerge',
    apCost: 29,
    language: 'Rogolan (brillantzwergischer Dialekt)',
    script: 'Rogolan-Runen (2 AP)',
    socialStatus: [],
    culturePackage: [
      { skill: 'Betören', bonus: 1 },
      { skill: 'Geographie', bonus: 2 },
      { skill: 'Geschichtswissen', bonus: 1 },
      { skill: 'Metallbearbeitung', bonus: 1 },
      { skill: 'Musizieren', bonus: 1 },
      { skill: 'Sagen & Legenden', bonus: 1 },
      { skill: 'Schlösserknacken', bonus: 2 },
      { skill: 'Steinbearbeitung', bonus: 1 },
      { skill: 'Tanzen', bonus: 1 },
      { skill: 'Verbergen', bonus: 2 },
      { skill: 'Zechen', bonus: 1 },
    ],
    speciesRestriction: ['dwarf'],
    typicalAdvantages: [{ name: 'begabung', label: 'Begabung in Handwerkstalenten' }, { name: 'sozialeAnpassungsfahigkeit' }],
    typicalDisadvantages: [{ name: 'angstVor', option: 'demmeer' }, { name: 'personlichkeitsschwache', option: 'eitelkeit' }, { name: 'schlechteEigenschaft', label: 'Schlechte Eigenschaften (Geiz, Goldgier, Neugier)' }],
    atypicalAdvantages: [],
    atypicalDisadvantages: [{ name: 'angstVor', option: 'engenraeumen' }, { name: 'blutrausch' }, { name: 'nachtblind' }],
    url: 'https://dsa.ulisses-regelwiki.de/ZL_Brillantzwerge.html',
  },
  {
    name: 'erzzwerge',
    label: 'Erzzwerge',
    apCost: 34,
    language: 'Rogolan (erzzwergischer Dialekt)',
    script: 'Rogolan-Runen (2 AP)',
    socialStatus: [],
    culturePackage: [
      { skill: 'Geschichtswissen', bonus: 2 },
      { skill: 'Götter & Kulte', bonus: 2 },
      { skill: 'Mechanik', bonus: 2 },
      { skill: 'Metallbearbeitung', bonus: 1 },
      { skill: 'Rechnen', bonus: 2 },
      { skill: 'Rechtskunde', bonus: 1 },
      { skill: 'Sagen & Legenden', bonus: 2 },
      { skill: 'Selbstbeherrschung', bonus: 1 },
      { skill: 'Steinbearbeitung', bonus: 1 },
      { skill: 'Verbergen', bonus: 2 },
      { skill: 'Zechen', bonus: 1 },
    ],
    speciesRestriction: ['dwarf'],
    typicalAdvantages: [{ name: 'begabung', label: 'Begabung in Wissens- oder Handwerkstalenten' }],
    typicalDisadvantages: [{ name: 'angstVor', label: 'Angst vor … (Höhe oder dem Meer)' }, { name: 'personlichkeitsschwache', label: 'Persönlichkeitsschwächen (Arroganz, Vorurteile)' }, { name: 'schlechteEigenschaft', label: 'Schlechte Eigenschaften (Geiz, Goldgier)' }],
    atypicalAdvantages: [{ name: 'sozialeAnpassungsfahigkeit' }],
    atypicalDisadvantages: [{ name: 'angstVor', label: 'Angst vor … (Dunkelheit, engen Räumen)' }, { name: 'nachtblind' }, { name: 'schlechteEigenschaft', option: 'neugier' }],
    url: 'https://dsa.ulisses-regelwiki.de/ZK_Erzzwerge.html',
  },
  {
    name: 'huegelzwerge',
    label: 'Hügelzwerge',
    apCost: 13,
    language: 'Rogolan (hügelzwergischer Dialekt)',
    script: 'Rogolan-Runen (2 AP)',
    socialStatus: [],
    culturePackage: [
      { skill: 'Fahrzeuge', bonus: 1 },
      { skill: 'Fischen & Angeln', bonus: 1 },
      { skill: 'Lebensmittelbearbeitung', bonus: 2 },
      { skill: 'Singen', bonus: 1 },
      { skill: 'Tanzen', bonus: 1 },
      { skill: 'Verbergen', bonus: 2 },
      { skill: 'Zechen', bonus: 1 },
    ],
    speciesRestriction: ['dwarf'],
    typicalAdvantages: [{ name: 'begabung', label: 'Begabung in Gesellschafts- und Handwerkstalenten' }, { name: 'sozialeAnpassungsfahigkeit' }],
    typicalDisadvantages: [{ name: 'angstVor', option: 'demmeer' }, { name: 'schlechteEigenschaft', label: 'Schlechte Eigenschaften (Goldgier, Neugier)' }],
    atypicalAdvantages: [],
    atypicalDisadvantages: [{ name: 'angstVor', label: 'Angst vor … (Dunkelheit oder engen Räumen)' }, { name: 'blutrausch' }, { name: 'nachtblind' }],
    url: 'https://dsa.ulisses-regelwiki.de/ZK_H%C3%BCgelzwerge.html',
  },
  {
    name: 'wildzwerge',
    label: 'Wildzwerge',
    apCost: 17,
    language: 'Rogolan (Brobimisch)',
    script: 'keine',
    socialStatus: ['Unfrei'],
    culturePackage: [
      { skill: 'Einschüchtern', bonus: 2 },
      { skill: 'Klettern', bonus: 2 },
      { skill: 'Steinbearbeitung', bonus: 2 },
      { skill: 'Verbergen', bonus: 2 },
      { skill: 'Zechen', bonus: 1 },
    ],
    speciesRestriction: ['dwarf'],
    typicalAdvantages: [{ name: 'dunkelsicht' }, { name: 'hitzeresistenz' }, { name: 'richtungssinn' }, { name: 'verbesserteRegenerationLep', label: 'Verbesserte Regeneration (Lebensenergie)' }, { name: 'zaherHund' }],
    typicalDisadvantages: [
      { name: 'angstVor', label: 'Angst vor … (Flugwesen, Höhe, dem Meer)' },
      { name: 'personlichkeitsschwache', label: 'Persönlichkeitsschwächen (Autoritätsgläubig, Vorurteile)' },
      { name: 'schlechteEigenschaft', label: 'Schlechte Eigenschaften (Aberglaube, Jähzorn)' },
      { name: 'hasslich' },
    ],
    atypicalAdvantages: [{ name: 'begabung', label: 'Begabung in Wissenstalenten' }, { name: 'sozialeAnpassungsfahigkeit' }],
    atypicalDisadvantages: [{ name: 'angstVor', label: 'Angst vor … (Dunkelheit, engen Räumen)' }],
    url: 'https://dsa.ulisses-regelwiki.de/kultur_wildzwerge.html',
  },
];

// ─── Orc Cultures ─────────────────────────────────────────────────────────────

export const ORC_CULTURES: Culture[] = [
  {
    name: 'orkland',
    label: 'Orkland',
    apCost: 40,
    language: 'Ologhaijan',
    script: 'keine',
    socialStatus: ['Adel', 'Unfrei'],
    culturePackage: [
      { skill: 'Einschüchtern', bonus: 2 },
      { skill: 'Holzbearbeitung', bonus: 1 },
      { skill: 'Klettern', bonus: 1 },
      { skill: 'Körperbeherrschung', bonus: 1 },
      { skill: 'Kraftakt', bonus: 2 },
      { skill: 'Kriegskunst', bonus: 1 },
      { skill: 'Lederbearbeitung', bonus: 1 },
      { skill: 'Orientierung', bonus: 1 },
      { skill: 'Selbstbeherrschung', bonus: 1 },
      { skill: 'Sinnesschärfe', bonus: 1 },
      { skill: 'Steinbearbeitung', bonus: 1 },
      { skill: 'Tierkunde', bonus: 1 },
      { skill: 'Wildnisleben', bonus: 2 },
    ],
    speciesRestriction: ['orc', 'halforc'],
    typicalAdvantages: [{ name: 'verbesserteRegenerationLep', label: 'Verbesserte Regeneration (Lebensenergie)' }, { name: 'zaherHund' }],
    typicalDisadvantages: [{ name: 'personlichkeitsschwache', option: 'vorurteile' }, { name: 'schlechteEigenschaft', label: 'Schlechte Eigenschaften (Aberglaube, Jähzorn)' }],
    atypicalAdvantages: [{ name: 'sozialeAnpassungsfahigkeit' }],
    atypicalDisadvantages: [{ name: 'krankheitsanfallig' }],
    url: 'https://dsa.ulisses-regelwiki.de/Kul_Orkland.html',
  },
];

// ─── Achaz Cultures ───────────────────────────────────────────────────────────

export const ACHAZ_CULTURES: Culture[] = [
  {
    name: 'stammesachaz',
    label: 'Stammesachaz',
    apCost: 50,
    language: 'Rssahh',
    script: 'keine',
    socialStatus: ['Adel'],
    culturePackage: [
      { skill: 'Boote & Schiffe', bonus: 1 },
      { skill: 'Fischen & Angeln', bonus: 2 },
      { skill: 'Holzbearbeitung', bonus: 1 },
      { skill: 'Körperbeherrschung', bonus: 1 },
      { skill: 'Lederbearbeitung', bonus: 2 },
      { skill: 'Orientierung', bonus: 1 },
      { skill: 'Pflanzenkunde', bonus: 1 },
      { skill: 'Sagen & Legenden', bonus: 1 },
      { skill: 'Schwimmen', bonus: 2 },
      { skill: 'Selbstbeherrschung', bonus: 1 },
      { skill: 'Sinnesschärfe', bonus: 1 },
      { skill: 'Steinbearbeitung', bonus: 1 },
      { skill: 'Tierkunde', bonus: 1 },
      { skill: 'Verbergen', bonus: 1 },
      { skill: 'Wildnisleben', bonus: 2 },
      { skill: 'Willenskraft', bonus: 1 },
    ],
    speciesRestriction: ['achaz'],
    typicalAdvantages: [],
    typicalDisadvantages: [{ name: 'personlichkeitsschwache', option: 'vorurteile' }],
    atypicalAdvantages: [{ name: 'feenfreundin' }, { name: 'koboldfreundin' }, { name: 'sozialeAnpassungsfahigkeit' }],
    atypicalDisadvantages: [{ name: 'angstVor', label: 'Angst vor … (dem Meer, engen Räumen, Toten und Untoten)' }],
    url: 'https://dsa.ulisses-regelwiki.de/Kul_Stammesachaz.html',
  },
  {
    name: 'achazRha',
    label: 'Achaz-Rha',
    apCost: 55,
    language: 'Rssahh (Achaz-Rha-Rssahh)',
    script: 'Chuchas (6 AP) oder Chrmk (4 AP)',
    socialStatus: ['Adel'],
    culturePackage: [
      { skill: 'Boote & Schiffe', bonus: 1 },
      { skill: 'Fischen & Angeln', bonus: 1 },
      { skill: 'Geschichtswissen', bonus: 2 },
      { skill: 'Götter & Kulte', bonus: 1 },
      { skill: 'Körperbeherrschung', bonus: 1 },
      { skill: 'Lederbearbeitung', bonus: 1 },
      { skill: 'Magiekunde', bonus: 1 },
      { skill: 'Mechanik', bonus: 1 },
      { skill: 'Rechnen', bonus: 2 },
      { skill: 'Sagen & Legenden', bonus: 2 },
      { skill: 'Schwimmen', bonus: 1 },
      { skill: 'Selbstbeherrschung', bonus: 1 },
      { skill: 'Sinnesschärfe', bonus: 1 },
      { skill: 'Sphärenkunde', bonus: 1 },
      { skill: 'Steinbearbeitung', bonus: 2 },
      { skill: 'Sternkunde', bonus: 1 },
      { skill: 'Tierkunde', bonus: 1 },
      { skill: 'Wildnisleben', bonus: 1 },
      { skill: 'Willenskraft', bonus: 2 },
    ],
    speciesRestriction: ['achaz'],
    typicalAdvantages: [],
    typicalDisadvantages: [{ name: 'personlichkeitsschwache', label: 'Persönlichkeitsschwächen (Arroganz, Vorurteile)' }],
    atypicalAdvantages: [{ name: 'feenfreundin' }, { name: 'koboldfreundin' }, { name: 'sozialeAnpassungsfahigkeit' }],
    atypicalDisadvantages: [{ name: 'angstVor', label: 'Angst vor … (dem Meer, engen Räumen, Toten und Untoten)' }],
    url: 'https://dsa.ulisses-regelwiki.de/Kul_Achaz-Rha.html',
  },
  {
    name: 'ctkiSsrr',
    label: "Ctki'Ssrr",
    apCost: 49,
    language: "Rssahh (Ctki'Ssrr-Rssahh)",
    script: 'Chrmk (4 AP)',
    socialStatus: ['Adel', 'Unfrei'],
    culturePackage: [
      { skill: 'Fischen & Angeln', bonus: 1 },
      { skill: 'Geschichtswissen', bonus: 1 },
      { skill: 'Götter & Kulte', bonus: 1 },
      { skill: 'Holzbearbeitung', bonus: 1 },
      { skill: 'Klettern', bonus: 1 },
      { skill: 'Körperbeherrschung', bonus: 1 },
      { skill: 'Kraftakt', bonus: 1 },
      { skill: 'Lederbearbeitung', bonus: 1 },
      { skill: 'Orientierung', bonus: 1 },
      { skill: 'Sagen & Legenden', bonus: 1 },
      { skill: 'Schwimmen', bonus: 1 },
      { skill: 'Selbstbeherrschung', bonus: 1 },
      { skill: 'Sinnesschärfe', bonus: 1 },
      { skill: 'Steinbearbeitung', bonus: 2 },
      { skill: 'Tierkunde', bonus: 2 },
      { skill: 'Verbergen', bonus: 1 },
      { skill: 'Wildnisleben', bonus: 1 },
      { skill: 'Willenskraft', bonus: 1 },
    ],
    speciesRestriction: ['achaz'],
    typicalAdvantages: [],
    typicalDisadvantages: [{ name: 'personlichkeitsschwache', label: 'Persönlichkeitsschwächen (Arroganz, Vorurteile)' }],
    atypicalAdvantages: [{ name: 'feenfreundin' }, { name: 'koboldfreundin' }, { name: 'sozialeAnpassungsfahigkeit' }],
    atypicalDisadvantages: [{ name: 'angstVor', label: 'Angst vor … (dem Meer, engen Räumen, Toten und Untoten)' }],
    url: 'https://dsa.ulisses-regelwiki.de/Kul_CtkiSsrr.html',
  },
];

// ─── Goblin Cultures ──────────────────────────────────────────────────────────

export const GOBLIN_CULTURES: Culture[] = [
  {
    name: 'stammesgoblins',
    label: 'Stammesgoblins',
    apCost: 0,
    language: 'Goblinisch',
    script: 'keine',
    socialStatus: [],
    culturePackage: [],
    speciesRestriction: ['goblin'],
    typicalAdvantages: [],
    typicalDisadvantages: [],
    atypicalAdvantages: [],
    atypicalDisadvantages: [],
    url: 'https://dsa.ulisses-regelwiki.de/kulturen/goblin-kulturen/stammesgoblins.html',
  },
];

// ─── Nachtalb Cultures ────────────────────────────────────────────────────────

export const NACHTALB_CULTURES: Culture[] = [
  {
    name: 'nachtalbenDerNaiAshyrr',
    label: 'Nachtalben der Nai Ashyrr',
    apCost: 55,
    language: 'Asdharia (Shakagoran)',
    script: 'Isdira-Zeichen (2 AP)',
    socialStatus: [],
    culturePackage: [
      { skill: 'Einschüchtern', bonus: 2 },
      { skill: 'Fährtensuchen', bonus: 2 },
      { skill: 'Fischen & Angeln', bonus: 1 },
      { skill: 'Klettern', bonus: 1 },
      { skill: 'Körperbeherrschung', bonus: 2 },
      { skill: 'Orientierung', bonus: 2 },
      { skill: 'Selbstbeherrschung', bonus: 1 },
      { skill: 'Sinnesschärfe', bonus: 2 },
      { skill: 'Tierkunde', bonus: 2 },
      { skill: 'Verbergen', bonus: 2 },
      { skill: 'Wildnisleben', bonus: 2 },
    ],
    speciesRestriction: ['nachtalb'],
    typicalAdvantages: [{ name: 'begabung', label: 'Begabung in Körper- und Naturtalenten' }, { name: 'kalteresistenz' }, { name: 'magischeeinstimmung' }, { name: 'richtungssinn' }, { name: 'waffenbegabung' }],
    typicalDisadvantages: [{ name: 'hitzeempfindlich' }, { name: 'lichtempfindlich' }, { name: 'personlichkeitsschwache', label: 'Persönlichkeitsschwächen (Arroganz, Vorurteile, Weltfremd)' }],
    atypicalAdvantages: [{ name: 'allerweltsname' }, { name: 'begabung', label: 'Begabung in Gesellschaftstalenten' }, { name: 'sozialeAnpassungsfahigkeit' }],
    atypicalDisadvantages: [
      { name: 'angstVor', label: 'Angst vor … (Dunkelheit, engen Räumen)' },
      { name: 'kalteempfindlich' },
      { name: 'schlechteEigenschaft', label: 'Schlechte Eigenschaften (Goldgier, Naiv)' },
      { name: 'unfahig', label: 'Unfähig in Körper- und Naturtalenten' },
    ],
    url: 'https://dsa.ulisses-regelwiki.de/kulturen/nachtalben-der-nai-ashyrr.html',
  },
];

// ─── Special Cultures ─────────────────────────────────────────────────────────

export const SPECIAL_CULTURES: Culture[] = [
  {
    name: 'holberk',
    label: 'Holberk',
    apCost: 27,
    language: 'Garethi (Holberkisch)',
    script: 'keine',
    socialStatus: ['Adel', 'Unfrei'],
    culturePackage: [
      { skill: 'Holzbearbeitung', bonus: 1 },
      { skill: 'Körperbeherrschung', bonus: 1 },
      { skill: 'Kraftakt', bonus: 1 },
      { skill: 'Lederbearbeitung', bonus: 1 },
      { skill: 'Metallbearbeitung', bonus: 1 },
      { skill: 'Pflanzenkunde', bonus: 1 },
      { skill: 'Sinnesschärfe', bonus: 1 },
      { skill: 'Steinbearbeitung', bonus: 1 },
      { skill: 'Tierkunde', bonus: 1 },
      { skill: 'Wildnisleben', bonus: 1 },
    ],
    speciesRestriction: ['holberker'],
    typicalAdvantages: [{ name: 'verbesserteRegenerationLep', label: 'Verbesserte Regeneration (Lebensenergie)' }, { name: 'zaherHund' }],
    typicalDisadvantages: [{ name: 'schlechteEigenschaft', label: 'Schlechte Eigenschaften (Aberglaube, Jähzorn)' }],
    atypicalAdvantages: [],
    atypicalDisadvantages: [{ name: 'krankheitsanfallig' }],
    url: 'https://dsa.ulisses-regelwiki.de/Kul_Holberk.html',
  },
  {
    name: 'raeuberbande',
    label: 'Räuberbande',
    apCost: 34,
    language: 'je nach Ursprungskultur',
    script: 'keine',
    socialStatus: ['Adel', 'Unfrei'],
    culturePackage: [
      { skill: 'Einschüchtern', bonus: 2 },
      { skill: 'Fährtensuchen', bonus: 1 },
      { skill: 'Fesseln', bonus: 2 },
      { skill: 'Gassenwissen', bonus: 1 },
      { skill: 'Holzbearbeitung', bonus: 1 },
      { skill: 'Orientierung', bonus: 1 },
      { skill: 'Rechtskunde', bonus: 1 },
      { skill: 'Sinnesschärfe', bonus: 1 },
      { skill: 'Tierkunde', bonus: 1 },
      { skill: 'Verbergen', bonus: 2 },
      { skill: 'Wildnisleben', bonus: 1 },
      { skill: 'Zechen', bonus: 1 },
    ],
    speciesRestriction: ['human', 'halfelf', 'halforc', 'orc', 'goblin'],
    typicalAdvantages: [{ name: 'verbesserteRegenerationLep', label: 'Verbesserte Regeneration (Lebensenergie)' }, { name: 'zaherHund' }],
    typicalDisadvantages: [{ name: 'personlichkeitsschwache', option: 'vorurteile' }, { name: 'schlechteEigenschaft', label: 'Schlechte Eigenschaften (Aberglaube, Jähzorn)' }],
    atypicalAdvantages: [{ name: 'sozialeAnpassungsfahigkeit' }],
    atypicalDisadvantages: [{ name: 'krankheitsanfallig' }],
    url: 'https://dsa.ulisses-regelwiki.de/Kul_Raeuberbande.html',
  },
];

// ─── Master list ──────────────────────────────────────────────────────────────

export const ALL_CULTURES: Culture[] = [
  ...HUMAN_CULTURES,
  ...EXPANSION_HUMAN_CULTURES,
  ...ELF_CULTURES,
  ...DWARF_CULTURES,
  ...ORC_CULTURES,
  ...ACHAZ_CULTURES,
  ...GOBLIN_CULTURES,
  ...NACHTALB_CULTURES,
  ...SPECIAL_CULTURES,
];
