import { IncreaseFactor } from '../models/magic.model';
import { Liturgy } from '../models/divine.model';

// â”€â”€â”€ Liturgien (Liturgies) â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
// Source: DSA 5 Regelwiki â€“ https://dsa.ulisses-regelwiki.de/liturgien.html
// Total: 199 liturgies, alphabetically ordered

export const ALL_LITURGIES: Liturgy[] = [
  // â”€â”€ Batch 1 (1â€“20) â”€â”€
  {
    name: 'angriffslust',
    label: 'Angriffslust',
    check: ['MU', 'MU', 'IN'],
    traditions: ['Kor (Guter Kampf)', 'Rondra (Sturm)'],
    increaseFactor: IncreaseFactor.B,
    url: 'https://dsa.ulisses-regelwiki.de/liturgie.html?liturgie=Angriffslust',
    sources: [
      { book: 'Aventurisches Götterwirken', page: 131 },
      { book: 'Divinarium Liturgia', page: 15 },
    ],
  },
  {
    name: 'angriffswelle',
    label: 'Angriffswelle',
    check: ['MU', 'IN', 'KO'],
    traditions: ['Numinoru (Reißender Strudel)'],
    increaseFactor: IncreaseFactor.C,
    url: 'https://dsa.ulisses-regelwiki.de/liturgie.html?liturgie=Angriffswelle',
    sources: [
      { book: 'Divinarium Liturgia', page: 16 },
      { book: 'Unendlichkeit & Tiefenrausch', page: 18 },
    ],
  },
  {
    name: 'augeDesJaegers',
    label: 'Auge des Jägers',
    check: ['MU', 'IN', 'CH'],
    traditions: ['Firun (Jagd)'],
    increaseFactor: IncreaseFactor.B,
    url: 'https://dsa.ulisses-regelwiki.de/liturgie.html?liturgie=Auge+des+J%C3%A4gers',
    sources: [
      { book: 'Aventurisches Götterwirken', page: 131 },
      { book: 'Divinarium Liturgia', page: 17 },
    ],
  },
  {
    name: 'ausnuechtern',
    label: 'Ausnüchtern',
    check: ['KL', 'IN', 'CH'],
    traditions: ['Peraine (Heilung)', 'Travia (Freundschaft)'],
    increaseFactor: IncreaseFactor.A,
    url: 'https://dsa.ulisses-regelwiki.de/liturgie.html?liturgie=Ausn%C3%BCchtern',
    sources: [
      { book: 'Aventurisches Götterwirken', page: 131 },
      { book: 'Divinarium Liturgia', page: 18 },
    ],
  },
  {
    name: 'bannDerDunkelheit',
    label: 'Bann der Dunkelheit',
    check: ['MU', 'KL', 'CH'],
    traditions: ['Praios (Ordnung)'],
    increaseFactor: IncreaseFactor.A,
    url: 'https://dsa.ulisses-regelwiki.de/liturgie.html?liturgie=Bann+der+Dunkelheit',
    sources: [
      { book: 'Regelwerk', page: 324 },
      { book: 'Aventurisches Götterwirken', page: 167 },
      { book: 'Divinarium Liturgia', page: 19 },
    ],
  },
  {
    name: 'bannDerFurcht',
    label: 'Bann der Furcht',
    check: ['IN', 'CH', 'CH'],
    traditions: ['Praios (Ordnung)', 'Rondra (Sturm)', 'Shinxir (Taktik)'],
    increaseFactor: IncreaseFactor.B,
    url: 'https://dsa.ulisses-regelwiki.de/liturgie.html?liturgie=Bann+der+Furcht',
    sources: [
      { book: 'Aventurisches Götterwirken', page: 132 },
      { book: 'Divinarium Liturgia', page: 20 },
    ],
  },
  {
    name: 'bannDerGoettlichenGaben',
    label: 'Bann der göttlichen Gaben',
    check: ['KL', 'IN', 'CH'],
    traditions: ['Namenloser'],
    increaseFactor: IncreaseFactor.A,
    url: 'https://dsa.ulisses-regelwiki.de/liturgie.html?liturgie=Bann+der+g%C3%B6ttlichen+Gaben',
    sources: [
      { book: 'Aventurisches Götterwirken', page: 132 },
      { book: 'Divinarium Liturgia', page: 21 },
    ],
  },
  {
    name: 'bannDesLichts',
    label: 'Bann des Lichts',
    check: ['MU', 'KL', 'CH'],
    traditions: ['Boron (Tod)', 'Phex (Schatten)'],
    increaseFactor: IncreaseFactor.B,
    url: 'https://dsa.ulisses-regelwiki.de/liturgie.html?liturgie=Bann+des+Lichts',
    sources: [
      { book: 'Aventurisches Götterwirken', page: 132 },
      { book: 'Divinarium Liturgia', page: 22 },
    ],
  },
  {
    name: 'bannWiderUntote',
    label: 'Bann wider Untote',
    check: ['MU', 'KL', 'CH'],
    traditions: ['Boron (Tod)', 'Praios (Antimagie)'],
    increaseFactor: IncreaseFactor.C,
    url: 'https://dsa.ulisses-regelwiki.de/liturgie.html?liturgie=Bann+wider+Untote',
    sources: [
      { book: 'Aventurisches Götterwirken', page: 132 },
      { book: 'Divinarium Liturgia', page: 23 },
    ],
  },
  {
    name: 'bannstrahl',
    label: 'Bannstrahl',
    check: ['MU', 'IN', 'CH'],
    traditions: ['Praios (Antimagie)', 'Praios (Ordnung)'],
    increaseFactor: IncreaseFactor.C,
    url: 'https://dsa.ulisses-regelwiki.de/liturgie.html?liturgie=Bannstrahl',
    sources: [
      { book: 'Regelwerk', page: 324 },
      { book: 'Aventurisches Götterwirken', page: 167 },
      { book: 'Divinarium Liturgia', page: 24 },
    ],
  },
  {
    name: 'bannzone',
    label: 'Bannzone',
    check: ['MU', 'IN', 'CH'],
    traditions: ['Praios (Antimagie)'],
    increaseFactor: IncreaseFactor.B,
    url: 'https://dsa.ulisses-regelwiki.de/liturgie.html?liturgie=Bannzone',
    sources: [
      { book: 'Aventurisches Götterwirken', page: 133 },
      { book: 'Divinarium Liturgia', page: 25 },
    ],
  },
  {
    name: 'baerenhaut',
    label: 'Bärenhaut',
    check: ['IN', 'CH', 'KO'],
    traditions: ['Firun (Kälte)', 'Ifirn (Natur)'],
    increaseFactor: IncreaseFactor.B,
    url: 'https://dsa.ulisses-regelwiki.de/liturgie.html?liturgie=B%C3%A4renhaut',
    sources: [
      { book: 'Aventurisches Götterwirken', page: 133 },
      { book: 'Divinarium Liturgia', page: 26 },
    ],
  },
  {
    name: 'befehlDesSchamanen',
    label: 'Befehl des Schamanen',
    check: ['MU', 'KL', 'CH'],
    traditions: ['Allgemein-Schamanenritus'],
    increaseFactor: IncreaseFactor.C,
    url: 'https://dsa.ulisses-regelwiki.de/liturgie.html?liturgie=Befehl+des+Schamanen',
    sources: [
      { book: 'Aventurisches Götterwirken II', page: 82 },
      { book: 'Divinarium Liturgia', page: 27 },
    ],
  },
  {
    name: 'befreiungDesGeistes',
    label: 'Befreiung des Geistes',
    check: ['MU', 'IN', 'CH'],
    traditions: ['Praios (Ordnung)'],
    increaseFactor: IncreaseFactor.B,
    url: 'https://dsa.ulisses-regelwiki.de/liturgie.html?liturgie=Befreiung+des+Geistes',
    sources: [
      { book: 'Aventurisches Götterwirken', page: 133 },
      { book: 'Divinarium Liturgia', page: 28 },
    ],
  },
  {
    name: 'begnadeterReiter',
    label: 'Begnadeter Reiter',
    check: ['MU', 'IN', 'CH'],
    traditions: ['Aves (Reise)', 'Rahja (Harmonie)'],
    increaseFactor: IncreaseFactor.A,
    url: 'https://dsa.ulisses-regelwiki.de/liturgie.html?liturgie=Begnadeter+Reiter',
    sources: [
      { book: 'Aventurisches Götterwirken', page: 133 },
      { book: 'Divinarium Liturgia', page: 29 },
    ],
  },
  {
    name: 'berauschen',
    label: 'Berauschen',
    check: ['MU', 'CH', 'KO'],
    traditions: ['Levthan (Rausch)', 'Rahja (Ekstase)'],
    increaseFactor: IncreaseFactor.B,
    url: 'https://dsa.ulisses-regelwiki.de/liturgie.html?liturgie=Berauschen',
    sources: [
      { book: 'Aventurisches Götterwirken II', page: 83 },
      { book: 'Divinarium Liturgia', page: 30 },
      { book: 'Wege der Vereinigungen', page: 187 },
    ],
  },
  {
    name: 'besaenftigung',
    label: 'Besänftigung',
    check: ['MU', 'KL', 'CH'],
    traditions: ['Boron (Traum)', 'Travia (Freundschaft)'],
    increaseFactor: IncreaseFactor.A,
    url: 'https://dsa.ulisses-regelwiki.de/liturgie.html?liturgie=Bes%C3%A4nftigung',
    sources: [
      { book: 'Aventurisches Götterwirken', page: 134 },
      { book: 'Divinarium Liturgia', page: 31 },
    ],
  },
  {
    name: 'bescheidenheit',
    label: 'Bescheidenheit',
    check: ['MU', 'KL', 'CH'],
    traditions: ['Boron (Tod)'],
    increaseFactor: IncreaseFactor.A,
    url: 'https://dsa.ulisses-regelwiki.de/liturgie.html?liturgie=Bescheidenheit',
    sources: [
      { book: 'Aventurisches Götterwirken', page: 134 },
      { book: 'Divinarium Liturgia', page: 32 },
    ],
  },
  {
    name: 'beschwoerungDerGemeinenDienerDesRattenkindes',
    label: 'Beschwörung der gemeinen Diener des Rattenkindes',
    check: ['MU', 'CH', 'KO'],
    traditions: ['Namenloser'],
    increaseFactor: IncreaseFactor.B,
    url: 'https://dsa.ulisses-regelwiki.de/liturgie.html?liturgie=Beschw%C3%B6rung+der+gemeinen+Diener+des+Rattenkindes',
    sources: [
      { book: 'Aventurisches Götterwirken', page: 134 },
      { book: 'Divinarium Liturgia', page: 33 },
    ],
  },
  {
    name: 'blendstrahl',
    label: 'Blendstrahl',
    check: ['MU', 'KL', 'IN'],
    traditions: ['Praios (Ordnung)'],
    increaseFactor: IncreaseFactor.A,
    url: 'https://dsa.ulisses-regelwiki.de/liturgie.html?liturgie=Blendstrahl',
    sources: [
      { book: 'Regelwerk', page: 324 },
      { book: 'Aventurisches Götterwirken', page: 167 },
      { book: 'Divinarium Liturgia', page: 34 },
    ],
  },

  // â”€â”€ Batch 2 (21â€“40) â”€â”€
  {
    name: 'blendung',
    label: 'Blendung',
    check: ['MU', 'KL', 'CH'],
    traditions: ['Praios (Ordnung)'],
    increaseFactor: IncreaseFactor.C,
    url: 'https://dsa.ulisses-regelwiki.de/liturgie.html?liturgie=Blendung',
    sources: [
      { book: 'Aventurisches Götterwirken', page: 135 },
      { book: 'Divinarium Liturgia', page: 35 },
    ],
  },
  {
    name: 'blickAufDenMeeresgrund',
    label: 'Blick auf den Meeresgrund',
    check: ['KL', 'IN', 'IN'],
    traditions: ['Efferd (Wogen)', 'Numinoru (Unendliche Tiefe)', 'Swafnir (Kraft)'],
    increaseFactor: IncreaseFactor.A,
    url: 'https://dsa.ulisses-regelwiki.de/liturgie.html?liturgie=Blick+auf+den+Meeresgrund',
    sources: [
      { book: 'Aventurisches Götterwirken', page: 135 },
      { book: 'Divinarium Liturgia', page: 36 },
      { book: 'Havena - Versunkene Geheimnisse', page: 84 },
      { book: 'Unendlichkeit & Tiefenrausch', page: 18 },
    ],
  },
  {
    name: 'blickDesHeilers',
    label: 'Blick des Heilers',
    check: ['KL', 'IN', 'CH'],
    traditions: ['Peraine (Heilung)'],
    increaseFactor: IncreaseFactor.A,
    url: 'https://dsa.ulisses-regelwiki.de/liturgie.html?liturgie=Blick+des+Heilers',
    sources: [
      { book: 'Aventurisches Götterwirken', page: 135 },
      { book: 'Divinarium Liturgia', page: 37 },
    ],
  },
  {
    name: 'blitzschlag',
    label: 'Blitzschlag',
    check: ['MU', 'IN', 'CH'],
    traditions: ['Rondra (Sturm)'],
    increaseFactor: IncreaseFactor.D,
    url: 'https://dsa.ulisses-regelwiki.de/liturgie.html?liturgie=Blitzschlag',
    sources: [
      { book: 'Regelwerk', page: 325 },
      { book: 'Aventurisches Götterwirken', page: 167 },
      { book: 'Divinarium Liturgia', page: 38 },
    ],
  },
  {
    name: 'blutigerZorn',
    label: 'Blutiger Zorn',
    check: ['MU', 'IN', 'CH'],
    traditions: ['Kor (Guter Kampf)'],
    increaseFactor: IncreaseFactor.C,
    url: 'https://dsa.ulisses-regelwiki.de/liturgie.html?liturgie=Blutiger+Zorn',
    sources: [
      { book: 'Aventurisches Götterwirken', page: 135 },
      { book: 'Divinarium Liturgia', page: 39 },
    ],
  },
  {
    name: 'blutigesSiegel',
    label: 'Blutiges Siegel',
    check: ['MU', 'IN', 'CH'],
    traditions: ['Kor (Gutes Gold)'],
    increaseFactor: IncreaseFactor.B,
    url: 'https://dsa.ulisses-regelwiki.de/liturgie.html?liturgie=Blutiges+Siegel',
    sources: [
      { book: 'Aventurisches Götterwirken', page: 136 },
      { book: 'Divinarium Liturgia', page: 40 },
    ],
  },
  {
    name: 'blutzoll',
    label: 'Blutzoll',
    check: ['MU', 'IN', 'CH'],
    traditions: ['Namenloser'],
    increaseFactor: IncreaseFactor.B,
    url: 'https://dsa.ulisses-regelwiki.de/liturgie.html?liturgie=Blutzoll',
    sources: [
      { book: 'Aventurisches Götterwirken', page: 136 },
      { book: 'Divinarium Liturgia', page: 41 },
    ],
  },
  {
    name: 'bodenweihe',
    label: 'Bodenweihe',
    check: ['MU', 'IN', 'CH'],
    traditions: ['Allgemein-Schamanenritus'],
    increaseFactor: IncreaseFactor.B,
    url: 'https://dsa.ulisses-regelwiki.de/liturgie.html?liturgie=Bodenweihe',
    sources: [
      { book: 'Aventurisches Götterwirken II', page: 83 },
      { book: 'Divinarium Liturgia', page: 42 },
    ],
  },
  {
    name: 'botschaftAusDerTiefe',
    label: 'Botschaft aus der Tiefe',
    check: ['MU', 'IN', 'CH'],
    traditions: ['Numinoru (Reißender Strudel)', 'Numinoru (Unendliche Tiefe)'],
    increaseFactor: IncreaseFactor.C,
    url: 'https://dsa.ulisses-regelwiki.de/liturgie.html?liturgie=Botschaft+aus+der+Tiefe',
    sources: [
      { book: 'Divinarium Liturgia', page: 43 },
      { book: 'Unendlichkeit & Tiefenrausch', page: 18 },
    ],
  },
  {
    name: 'brazoraghsKrieger',
    label: 'Brazoraghs Krieger',
    check: ['MU', 'MU', 'IN'],
    traditions: ['Brazoragh (Krieg)'],
    increaseFactor: IncreaseFactor.B,
    url: 'https://dsa.ulisses-regelwiki.de/liturgie.html?liturgie=Brazoraghs+Krieger',
    sources: [
      { book: 'Divinarium Liturgia', page: 44 },
      { book: 'Orks - Hauer & Schwarzer Pelz', page: 49 },
    ],
  },
  {
    name: 'buechersuche',
    label: 'Büchersuche',
    check: ['KL', 'KL', 'IN'],
    traditions: ['Hesinde (Wissen)', 'Nandus (Bildung)'],
    increaseFactor: IncreaseFactor.B,
    url: 'https://dsa.ulisses-regelwiki.de/liturgie.html?liturgie=B%C3%BCchersuche',
    sources: [
      { book: 'Aventurisches Götterwirken', page: 136 },
      { book: 'Divinarium Liturgia', page: 45 },
    ],
  },
  {
    name: 'daemonenwall',
    label: 'Dämonenwall',
    check: ['MU', 'KL', 'CH'],
    traditions: ['Praios (Antimagie)'],
    increaseFactor: IncreaseFactor.B,
    url: 'https://dsa.ulisses-regelwiki.de/liturgie.html?liturgie=D%C3%A4monenwall',
    sources: [
      { book: 'Aventurisches Götterwirken', page: 136 },
      { book: 'Divinarium Liturgia', page: 46 },
    ],
  },
  {
    name: 'delphinruf',
    label: 'Delphinruf',
    check: ['KL', 'IN', 'CH'],
    traditions: ['Efferd (Wogen)'],
    increaseFactor: IncreaseFactor.A,
    url: 'https://dsa.ulisses-regelwiki.de/liturgie.html?liturgie=Delphinruf',
    sources: [
      { book: 'Aventurisches Götterwirken', page: 137 },
      { book: 'Divinarium Liturgia', page: 47 },
    ],
  },
  {
    name: 'desEinenBezaubernderSphaerenklang',
    label: 'Des Einen bezaubernder Sphärenklang',
    check: ['IN', 'CH', 'CH'],
    traditions: ['Levthan (Begierde)', 'Levthan (Rausch)'],
    increaseFactor: IncreaseFactor.C,
    url: 'https://dsa.ulisses-regelwiki.de/liturgie.html?liturgie=Des+Einen+bezaubernder+Sph%C3%A4renklang',
    sources: [
      { book: 'Aventurisches Götterwirken II', page: 84 },
      { book: 'Divinarium Liturgia', page: 48 },
      { book: 'Wege der Vereinigungen', page: 188 },
    ],
  },
  {
    name: 'doppelgaenger',
    label: 'Doppelgänger',
    check: ['MU', 'KL', 'IN'],
    traditions: ['Phex (Schatten)'],
    increaseFactor: IncreaseFactor.D,
    url: 'https://dsa.ulisses-regelwiki.de/liturgie.html?liturgie=Doppelg%C3%A4nger',
    sources: [
      { book: 'Aventurisches Götterwirken', page: 137 },
      { book: 'Divinarium Liturgia', page: 49 },
    ],
  },
  {
    name: 'ehrenhaftigkeit',
    label: 'Ehrenhaftigkeit',
    check: ['MU', 'IN', 'CH'],
    traditions: ['Rondra (Schild)'],
    increaseFactor: IncreaseFactor.B,
    url: 'https://dsa.ulisses-regelwiki.de/liturgie.html?liturgie=Ehrenhaftigkeit',
    sources: [
      { book: 'Aventurisches Götterwirken', page: 137 },
      { book: 'Divinarium Liturgia', page: 50 },
    ],
  },
  {
    name: 'ehrlicherVertrag',
    label: 'Ehrlicher Vertrag',
    check: ['KL', 'IN', 'CH'],
    traditions: ['Phex (Handel)'],
    increaseFactor: IncreaseFactor.A,
    url: 'https://dsa.ulisses-regelwiki.de/liturgie.html?liturgie=Ehrlicher+Vertrag',
    sources: [
      { book: 'Aventurisches Götterwirken', page: 137 },
      { book: 'Divinarium Liturgia', page: 51 },
    ],
  },
  {
    name: 'eisbaerennruf',
    label: 'Eisbärenruf',
    check: ['MU', 'IN', 'CH'],
    traditions: ['Firun (Kälte)'],
    increaseFactor: IncreaseFactor.C,
    url: 'https://dsa.ulisses-regelwiki.de/liturgie.html?liturgie=Eisb%C3%A4renruf',
    sources: [
      { book: 'Aventurisches Götterwirken', page: 138 },
      { book: 'Divinarium Liturgia', page: 52 },
    ],
  },
  {
    name: 'entfesselung',
    label: 'Entfesselung',
    check: ['MU', 'KL', 'IN'],
    traditions: ['Aves (Schicksal)', 'Phex (Schatten)', 'Tsa (Freiheit)'],
    increaseFactor: IncreaseFactor.B,
    url: 'https://dsa.ulisses-regelwiki.de/liturgie.html?liturgie=Entfesselung',
    sources: [
      { book: 'Aventurisches Götterwirken', page: 138 },
      { book: 'Divinarium Liturgia', page: 53 },
    ],
  },
  {
    name: 'entstelltesAntlitz',
    label: 'Entstelltes Antlitz',
    check: ['MU', 'IN', 'CH'],
    traditions: ['Namenloser'],
    increaseFactor: IncreaseFactor.B,
    url: 'https://dsa.ulisses-regelwiki.de/liturgie.html?liturgie=Entstelltes+Antlitz',
    sources: [
      { book: 'Aventurisches Götterwirken', page: 138 },
      { book: 'Divinarium Liturgia', page: 54 },
    ],
  },

  // â”€â”€ Batch 3 (41â€“60) â”€â”€
  {
    name: 'entzifferung',
    label: 'Entzifferung',
    check: ['KL', 'KL', 'IN'],
    traditions: ['Hesinde (Magie)', 'Hesinde (Wissen)', 'Nandus (Bildung)'],
    increaseFactor: IncreaseFactor.A,
    url: 'https://dsa.ulisses-regelwiki.de/liturgie.html?liturgie=Entzifferung',
    sources: [
      { book: 'Aventurisches Götterwirken', page: 138 },
      { book: 'Divinarium Liturgia', page: 55 },
    ],
  },
  {
    name: 'erdbeben',
    label: 'Erdbeben',
    check: ['MU', 'KL', 'IN'],
    traditions: ['Gravesh (Erdspalte)'],
    increaseFactor: IncreaseFactor.C,
    url: 'https://dsa.ulisses-regelwiki.de/liturgie.html?liturgie=Erdbeben',
    sources: [
      { book: 'Aventurisches Götterwirken II', page: 85 },
      { book: 'Divinarium Liturgia', page: 56 },
    ],
  },
  {
    name: 'ermutigung',
    label: 'Ermutigung',
    check: ['MU', 'IN', 'CH'],
    traditions: ['Aves (Schicksal)', 'Kor (Guter Kampf)', 'Rondra (Schild)', 'Swafnir (Tapferkeit)'],
    increaseFactor: IncreaseFactor.B,
    url: 'https://dsa.ulisses-regelwiki.de/liturgie.html?liturgie=Ermutigung',
    sources: [
      { book: 'Aventurisches Götterwirken', page: 139 },
      { book: 'Divinarium Liturgia', page: 57 },
    ],
  },
  {
    name: 'ernuechterung',
    label: 'Ernüchterung',
    check: ['MU', 'KL', 'CH'],
    traditions: ['Peraine (Heilung)', 'Travia (Freundschaft)'],
    increaseFactor: IncreaseFactor.A,
    url: 'https://dsa.ulisses-regelwiki.de/liturgie.html?liturgie=Ern%C3%BCchterung',
    sources: [
      { book: 'Aventurisches Götterwirken II', page: 85 },
      { book: 'Divinarium Liturgia', page: 58 },
      { book: 'Wege der Vereinigungen', page: 188 },
    ],
  },
  {
    name: 'erregenderRausch',
    label: 'Erregender Rausch',
    check: ['MU', 'IN', 'KO'],
    traditions: ['Levthan (Rausch)', 'Rahja (Ekstase)'],
    increaseFactor: IncreaseFactor.A,
    url: 'https://dsa.ulisses-regelwiki.de/liturgie.html?liturgie=Erregender+Rausch',
    sources: [
      { book: 'Aventurisches Götterwirken II', page: 86 },
      { book: 'Divinarium Liturgia', page: 59 },
      { book: 'Wege der Vereinigungen', page: 189 },
    ],
  },
  {
    name: 'ertrinken',
    label: 'Ertrinken',
    check: ['MU', 'KL', 'KO'],
    traditions: ['Numinoru (Reißender Strudel)'],
    increaseFactor: IncreaseFactor.B,
    url: 'https://dsa.ulisses-regelwiki.de/liturgie.html?liturgie=Ertrinken',
    sources: [
      { book: 'Divinarium Liturgia', page: 60 },
      { book: 'Unendlichkeit & Tiefenrausch', page: 19 },
    ],
  },
  {
    name: 'erwachen',
    label: 'Erwachen',
    check: ['MU', 'IN', 'CH'],
    traditions: ['Boron (Tod)', 'Boron (Traum)'],
    increaseFactor: IncreaseFactor.A,
    url: 'https://dsa.ulisses-regelwiki.de/liturgie.html?liturgie=Erwachen',
    sources: [
      { book: 'Aventurisches Götterwirken', page: 139 },
      { book: 'Divinarium Liturgia', page: 61 },
    ],
  },
  {
    name: 'erzeneOpfergabe',
    label: 'Erzene Opfergabe',
    check: ['MU', 'IN', 'CH'],
    traditions: ['Angrosch (Erz)'],
    increaseFactor: IncreaseFactor.B,
    url: 'https://dsa.ulisses-regelwiki.de/liturgie.html?liturgie=Erzene+Opfergabe',
    sources: [
      { book: 'Aventurisches Götterwirken', page: 139 },
      { book: 'Divinarium Liturgia', page: 62 },
    ],
  },
  {
    name: 'fallInsNichts',
    label: 'Fall ins Nichts',
    check: ['MU', 'IN', 'GE'],
    traditions: ['Phex (Schatten)'],
    increaseFactor: IncreaseFactor.A,
    url: 'https://dsa.ulisses-regelwiki.de/liturgie.html?liturgie=Fall+ins+Nichts',
    sources: [
      { book: 'Aventurisches Götterwirken', page: 139 },
      { book: 'Divinarium Liturgia', page: 63 },
    ],
  },
  {
    name: 'fesselndesBand',
    label: 'Fesselndes Band',
    check: ['MU', 'IN', 'CH'],
    traditions: ['Travia (Freundschaft)'],
    increaseFactor: IncreaseFactor.B,
    url: 'https://dsa.ulisses-regelwiki.de/liturgie.html?liturgie=Fesselndes+Band',
    sources: [
      { book: 'Aventurisches Götterwirken', page: 140 },
      { book: 'Divinarium Liturgia', page: 64 },
    ],
  },
  {
    name: 'feuerwall',
    label: 'Feuerwall',
    check: ['MU', 'KL', 'CH'],
    traditions: ['Angrosch (Flammen)', 'Gravesh (Brand)', 'Ingerimm (Feuer)'],
    increaseFactor: IncreaseFactor.B,
    url: 'https://dsa.ulisses-regelwiki.de/liturgie.html?liturgie=Feuerwall',
    sources: [
      { book: 'Aventurisches Götterwirken', page: 140 },
      { book: 'Aventurisches Götterwirken II', page: 74 },
      { book: 'Divinarium Liturgia', page: 65 },
    ],
  },
  {
    name: 'flugechsenruf',
    label: 'Flugechsenruf',
    check: ['MU', 'IN', 'CH'],
    traditions: ["Chr'Ssir'Ssr (Wetter)"],
    increaseFactor: IncreaseFactor.C,
    url: 'https://dsa.ulisses-regelwiki.de/liturgie.html?liturgie=Flugechsenruf',
    sources: [
      { book: 'Achaz - Schuppenkleid & Lange Zungen', page: 54 },
      { book: 'Aventurisches Götterwirken II', page: 86 },
      { book: 'Divinarium Liturgia', page: 66 },
    ],
  },
  {
    name: 'freundschaftlichesAuftreten',
    label: 'Freundschaftliches Auftreten',
    check: ['IN', 'CH', 'CH'],
    traditions: ['Levthan (Begierde)', 'Rahja (Harmonie)', 'Travia (Freundschaft)'],
    increaseFactor: IncreaseFactor.B,
    url: 'https://dsa.ulisses-regelwiki.de/liturgie.html?liturgie=Freundschaftliches+Auftreten',
    sources: [
      { book: 'Aventurisches Götterwirken', page: 140 },
      { book: 'Divinarium Liturgia', page: 67 },
      { book: 'Wege der Vereinigungen', page: 189 },
    ],
  },
  {
    name: 'friedfertigkeit',
    label: 'Friedfertigkeit',
    check: ['MU', 'IN', 'CH'],
    traditions: ['Boron (Tod)', 'Travia (Freundschaft)'],
    increaseFactor: IncreaseFactor.B,
    url: 'https://dsa.ulisses-regelwiki.de/liturgie.html?liturgie=Friedfertigkeit',
    sources: [
      { book: 'Aventurisches Götterwirken', page: 141 },
      { book: 'Divinarium Liturgia', page: 68 },
    ],
  },
  {
    name: 'friedvolleAura',
    label: 'Friedvolle Aura',
    check: ['MU', 'IN', 'CH'],
    traditions: ['Travia (Heim)'],
    increaseFactor: IncreaseFactor.B,
    url: 'https://dsa.ulisses-regelwiki.de/liturgie.html?liturgie=Friedvolle+Aura',
    sources: [
      { book: 'Aventurisches Götterwirken', page: 141 },
      { book: 'Divinarium Liturgia', page: 69 },
    ],
  },
  {
    name: 'friedvollerRausch',
    label: 'Friedvoller Rausch',
    check: ['MU', 'IN', 'CH'],
    traditions: ['Levthan (Rausch)', 'Rahja (Harmonie)'],
    increaseFactor: IncreaseFactor.B,
    url: 'https://dsa.ulisses-regelwiki.de/liturgie.html?liturgie=Friedvoller+Rausch',
    sources: [
      { book: 'Aventurisches Götterwirken II', page: 86 },
      { book: 'Divinarium Liturgia', page: 70 },
      { book: 'Wege der Vereinigungen', page: 189 },
    ],
  },
  {
    name: 'froststurm',
    label: 'Froststurm',
    check: ['MU', 'IN', 'CH'],
    traditions: ['Firun (Kälte)'],
    increaseFactor: IncreaseFactor.C,
    url: 'https://dsa.ulisses-regelwiki.de/liturgie.html?liturgie=Froststurm',
    sources: [
      { book: 'Aventurisches Götterwirken', page: 141 },
      { book: 'Divinarium Liturgia', page: 71 },
    ],
  },
  {
    name: 'furchteinfloeßendeTiergeister',
    label: 'Furchteinflößende Tiergeister',
    check: ['MU', 'IN', 'CH'],
    traditions: ['Allgemein-Schamanenritus'],
    increaseFactor: IncreaseFactor.B,
    url: 'https://dsa.ulisses-regelwiki.de/liturgie.html?liturgie=Furchteinfl%C3%B6%C3%9Fende+Tiergeister',
    sources: [
      { book: 'Aventurisches Götterwirken II', page: 87 },
      { book: 'Divinarium Liturgia', page: 72 },
    ],
  },
  {
    name: 'furchtresistenz',
    label: 'Furchtresistenz',
    check: ['MU', 'CH', 'KO'],
    traditions: ['Kor (Guter Kampf)', 'Kor (Gutes Gold)', 'Rondra (Schild)', 'Shinxir (Taktik)'],
    increaseFactor: IncreaseFactor.C,
    url: 'https://dsa.ulisses-regelwiki.de/liturgie.html?liturgie=Furchtresistenz',
    sources: [
      { book: 'Aventurisches Götterwirken', page: 141 },
      { book: 'Divinarium Liturgia', page: 73 },
    ],
  },
  {
    name: 'gebieterDerFlammen',
    label: 'Gebieter der Flammen',
    check: ['MU', 'KL', 'IN'],
    traditions: ['Angrosch (Flammen)', 'Gravesh (Brand)', 'Ingerimm (Feuer)'],
    increaseFactor: IncreaseFactor.B,
    url: 'https://dsa.ulisses-regelwiki.de/liturgie.html?liturgie=Gebieter+der+Flammen',
    sources: [
      { book: 'Aventurisches Götterwirken', page: 142 },
      { book: 'Aventurisches Götterwirken II', page: 74 },
      { book: 'Divinarium Liturgia', page: 74 },
    ],
  },

  // â”€â”€ Batch 4 (61â€“80) â”€â”€
  {
    name: 'gefuehlskaelte',
    label: 'Gefühlskälte',
    check: ['MU', 'IN', 'CH'],
    traditions: ['Boron (Tod)', 'Firun (Kälte)'],
    increaseFactor: IncreaseFactor.B,
    url: 'https://dsa.ulisses-regelwiki.de/liturgie.html?liturgie=Gef%C3%BChlsk%C3%A4lte',
    sources: [
      { book: 'Aventurisches Götterwirken', page: 142 },
      { book: 'Divinarium Liturgia', page: 75 },
    ],
  },
  {
    name: 'geistDesStrategen',
    label: 'Geist des Strategen',
    check: ['MU', 'KL', 'IN'],
    traditions: ['Kor (Gutes Gold)', 'Rondra (Schild)', 'Shinxir (Taktik)'],
    increaseFactor: IncreaseFactor.B,
    url: 'https://dsa.ulisses-regelwiki.de/liturgie.html?liturgie=Geist+des+Strategen',
    sources: [
      { book: 'Aventurisches Götterwirken', page: 142 },
      { book: 'Divinarium Liturgia', page: 76 },
    ],
  },
  {
    name: 'geisterblick',
    label: 'Geisterblick',
    check: ['MU', 'IN', 'CH'],
    traditions: ['Allgemein-Schamanenritus'],
    increaseFactor: IncreaseFactor.A,
    url: 'https://dsa.ulisses-regelwiki.de/liturgie.html?liturgie=Geisterblick',
    sources: [
      { book: 'Aventurisches Götterwirken II', page: 88 },
      { book: 'Divinarium Liturgia', page: 77 },
    ],
  },
  {
    name: 'geisterfalle',
    label: 'Geisterfalle',
    check: ['MU', 'IN', 'CH'],
    traditions: ['Allgemein-Schamanenritus'],
    increaseFactor: IncreaseFactor.B,
    url: 'https://dsa.ulisses-regelwiki.de/liturgie.html?liturgie=Geisterfalle',
    sources: [
      { book: 'Aventurisches Götterwirken II', page: 88 },
      { book: 'Divinarium Liturgia', page: 78 },
      { book: 'Körperlose Schrecken', page: 155 },
    ],
  },
  {
    name: 'geldwechsel',
    label: 'Geldwechsel',
    check: ['KL', 'IN', 'FF'],
    traditions: ['Phex (Handel)'],
    increaseFactor: IncreaseFactor.A,
    url: 'https://dsa.ulisses-regelwiki.de/liturgie.html?liturgie=Geldwechsel',
    sources: [
      { book: 'Aventurisches Götterwirken', page: 142 },
      { book: 'Divinarium Liturgia', page: 79 },
    ],
  },
  {
    name: 'gesegneterRausch',
    label: 'Gesegneter Rausch',
    check: ['MU', 'IN', 'CH'],
    traditions: ['Levthan (Rausch)', 'Rahja (Ekstase)'],
    increaseFactor: IncreaseFactor.A,
    url: 'https://dsa.ulisses-regelwiki.de/liturgie.html?liturgie=Gesegneter+Rausch',
    sources: [
      { book: 'Aventurisches Götterwirken II', page: 88 },
      { book: 'Divinarium Liturgia', page: 80 },
      { book: 'Wege der Vereinigungen', page: 190 },
    ],
  },
  {
    name: 'gespuerFuerDasGoettliche',
    label: 'Gespür für das Göttliche',
    check: ['MU', 'IN', 'CH'],
    traditions: ['Praios (Ordnung)'],
    increaseFactor: IncreaseFactor.C,
    url: 'https://dsa.ulisses-regelwiki.de/liturgie.html?liturgie=Gesp%C3%BCr+f%C3%BCr+das+G%C3%B6ttliche',
    sources: [
      { book: 'Aventurisches Götterwirken', page: 143 },
      { book: 'Divinarium Liturgia', page: 81 },
    ],
  },
  {
    name: 'getreidewachstum',
    label: 'Getreidewachstum',
    check: ['KL', 'IN', 'CH'],
    traditions: ['Peraine (Landwirtschaft)'],
    increaseFactor: IncreaseFactor.A,
    url: 'https://dsa.ulisses-regelwiki.de/liturgie.html?liturgie=Getreidewachstum',
    sources: [
      { book: 'Aventurisches Götterwirken', page: 143 },
      { book: 'Divinarium Liturgia', page: 82 },
    ],
  },
  {
    name: 'giftbann',
    label: 'Giftbann',
    check: ['KL', 'IN', 'CH'],
    traditions: ['Ifirn (Natur)', 'Peraine (Heilung)'],
    increaseFactor: IncreaseFactor.B,
    url: 'https://dsa.ulisses-regelwiki.de/liturgie.html?liturgie=Giftbann',
    sources: [
      { book: 'Regelwerk', page: 326 },
      { book: 'Aventurisches Götterwirken', page: 167 },
      { book: 'Divinarium Liturgia', page: 83 },
    ],
  },
  {
    name: 'gnadenstoss',
    label: 'Gnadenstoß',
    check: ['MU', 'IN', 'CH'],
    traditions: ['Boron (Tod)', 'Kor (Guter Kampf)'],
    increaseFactor: IncreaseFactor.B,
    url: 'https://dsa.ulisses-regelwiki.de/liturgie.html?liturgie=Gnadenstoss',
    sources: [
      { book: 'Aventurisches Götterwirken', page: 143 },
      { book: 'Divinarium Liturgia', page: 84 },
    ],
  },
  {
    name: 'goldeneHand',
    label: 'Goldene Hand',
    check: ['KL', 'IN', 'CH'],
    traditions: ['Phex (Handel)'],
    increaseFactor: IncreaseFactor.C,
    url: 'https://dsa.ulisses-regelwiki.de/liturgie.html?liturgie=Goldene+Hand',
    sources: [
      { book: 'Aventurisches Götterwirken', page: 143 },
      { book: 'Divinarium Liturgia', page: 85 },
    ],
  },
  {
    name: 'goldeneRuestung',
    label: 'Goldene Rüstung',
    check: ['MU', 'KL', 'IN'],
    traditions: ['Praios (Ordnung)'],
    increaseFactor: IncreaseFactor.C,
    url: 'https://dsa.ulisses-regelwiki.de/liturgie.html?liturgie=Goldene+R%C3%BCstung',
    sources: [
      { book: 'Aventurisches Götterwirken', page: 144 },
      { book: 'Divinarium Liturgia', page: 86 },
    ],
  },
  {
    name: 'goettlicheKlinge',
    label: 'Göttliche Klinge',
    check: ['MU', 'KL', 'IN'],
    traditions: ['Rondra (Sturm)'],
    increaseFactor: IncreaseFactor.B,
    url: 'https://dsa.ulisses-regelwiki.de/liturgie.html?liturgie=G%C3%B6ttliche+Klinge',
    sources: [
      { book: 'Aventurisches Götterwirken', page: 144 },
      { book: 'Divinarium Liturgia', page: 87 },
    ],
  },
  {
    name: 'goettlicheVerstaendigung',
    label: 'Göttliche Verständigung',
    check: ['MU', 'IN', 'CH'],
    traditions: ['Nandus (Bildung)'],
    increaseFactor: IncreaseFactor.C,
    url: 'https://dsa.ulisses-regelwiki.de/liturgie.html?liturgie=G%C3%B6ttliche+Verst%C3%A4ndigung',
    sources: [
      { book: 'Aventurisches Götterwirken', page: 144 },
      { book: 'Divinarium Liturgia', page: 88 },
    ],
  },
  {
    name: 'goettlicherFingerzeig',
    label: 'Göttlicher Fingerzeig',
    check: ['KL', 'IN', 'IN'],
    traditions: ['Allgemein', 'Nandus (Bildung)'],
    increaseFactor: IncreaseFactor.A,
    url: 'https://dsa.ulisses-regelwiki.de/liturgie.html?liturgie=G%C3%B6ttlicher+Fingerzeig',
    sources: [
      { book: 'Regelwerk', page: 326 },
      { book: 'Aventurisches Götterwirken', page: 167 },
      { book: 'Divinarium Liturgia', page: 89 },
    ],
  },
  {
    name: 'goettlicherRausch',
    label: 'Göttlicher Rausch',
    check: ['MU', 'IN', 'CH'],
    traditions: ['Levthan (Begierde)', 'Levthan (Rausch)'],
    increaseFactor: IncreaseFactor.B,
    url: 'https://dsa.ulisses-regelwiki.de/liturgie.html?liturgie=G%C3%B6ttlicher+Rausch',
    sources: [
      { book: 'Aventurisches Götterwirken II', page: 89 },
      { book: 'Divinarium Liturgia', page: 90 },
      { book: 'Wege der Vereinigungen', page: 190 },
    ],
  },
  {
    name: 'goettlichesZeichen',
    label: 'Göttliches Zeichen',
    check: ['IN', 'IN', 'CH'],
    traditions: ['Allgemein'],
    increaseFactor: IncreaseFactor.A,
    url: 'https://dsa.ulisses-regelwiki.de/liturgie.html?liturgie=G%C3%B6ttliches+Zeichen',
    sources: [
      { book: 'Regelwerk', page: 327 },
      { book: 'Aventurisches Götterwirken', page: 168 },
      { book: 'Divinarium Liturgia', page: 91 },
    ],
  },
  {
    name: 'hairuf',
    label: 'Hairuf',
    check: ['MU', 'IN', 'CH'],
    traditions: ['Efferd (Wogen)'],
    increaseFactor: IncreaseFactor.C,
    url: 'https://dsa.ulisses-regelwiki.de/liturgie.html?liturgie=Hairuf',
    sources: [
      { book: 'Aventurisches Götterwirken', page: 144 },
      { book: 'Divinarium Liturgia', page: 92 },
      { book: 'Havena - Versunkene Geheimnisse', page: 84 },
    ],
  },
  {
    name: 'hauchDesElements',
    label: 'Hauch des Elements',
    check: ['MU', 'KL', 'CH'],
    traditions: ['Allgemein-Schamanenritus'],
    increaseFactor: IncreaseFactor.B,
    url: 'https://dsa.ulisses-regelwiki.de/liturgie.html?liturgie=Hauch+des+Elements',
    sources: [
      { book: 'Aventurisches Götterwirken II', page: 89 },
      { book: 'Divinarium Liturgia', page: 93 },
    ],
  },
  {
    name: 'heiligerBefehl',
    label: 'Heiliger Befehl',
    check: ['MU', 'KL', 'CH'],
    traditions: ['Praios (Ordnung)'],
    increaseFactor: IncreaseFactor.C,
    url: 'https://dsa.ulisses-regelwiki.de/liturgie.html?liturgie=Heiliger+Befehl',
    sources: [
      { book: 'Regelwerk', page: 327 },
      { book: 'Aventurisches Götterwirken', page: 168 },
      { book: 'Divinarium Liturgia', page: 94 },
    ],
  },

  // â”€â”€ Batch 5 (81â€“100) â”€â”€
  {
    name: 'heiligesLiebesspiel',
    label: 'Heiliges Liebesspiel',
    check: ['MU', 'IN', 'CH'],
    traditions: ['Levthan (Begierde)', 'Rahja (Ekstase)'],
    increaseFactor: IncreaseFactor.A,
    url: 'https://dsa.ulisses-regelwiki.de/liturgie.html?liturgie=Heiliges+Liebesspiel',
    sources: [
      { book: 'Aventurisches Götterwirken II', page: 89 },
      { book: 'Divinarium Liturgia', page: 95 },
      { book: 'Wege der Vereinigungen', page: 191 },
    ],
  },
  {
    name: 'heilsameQuelle',
    label: 'Heilsame Quelle',
    check: ['KL', 'IN', 'CH'],
    traditions: ['Peraine (Heilung)'],
    increaseFactor: IncreaseFactor.A,
    url: 'https://dsa.ulisses-regelwiki.de/liturgie.html?liturgie=Heilsame+Quelle',
    sources: [
      { book: 'Aventurisches Götterwirken', page: 145 },
      { book: 'Divinarium Liturgia', page: 96 },
    ],
  },
  {
    name: 'heilsegen',
    label: 'Heilsegen',
    check: ['KL', 'IN', 'CH'],
    traditions: ['Peraine (Heilung)'],
    increaseFactor: IncreaseFactor.B,
    url: 'https://dsa.ulisses-regelwiki.de/liturgie.html?liturgie=Heilsegen',
    sources: [
      { book: 'Regelwerk', page: 328 },
      { book: 'Aventurisches Götterwirken', page: 168 },
      { book: 'Divinarium Liturgia', page: 97 },
    ],
  },
  {
    name: 'heldenkraft',
    label: 'Heldenkraft',
    check: ['MU', 'IN', 'CH'],
    traditions: ['Rondra (Sturm)'],
    increaseFactor: IncreaseFactor.B,
    url: 'https://dsa.ulisses-regelwiki.de/liturgie.html?liturgie=Heldenkraft',
    sources: [
      { book: 'Regelwerk', page: 328 },
      { book: 'Aventurisches Götterwirken', page: 168 },
      { book: 'Divinarium Liturgia', page: 98 },
    ],
  },
  {
    name: 'helfendeHand',
    label: 'Helfende Hand',
    check: ['KL', 'IN', 'CH'],
    traditions: ['Peraine (Heilung)'],
    increaseFactor: IncreaseFactor.B,
    url: 'https://dsa.ulisses-regelwiki.de/liturgie.html?liturgie=Helfende+Hand',
    sources: [
      { book: 'Aventurisches Götterwirken', page: 145 },
      { book: 'Divinarium Liturgia', page: 99 },
    ],
  },
  {
    name: 'herbeirufungDerHeerscharenDesRattenkindesRatten',
    label: 'Herbeirufung der Heerscharen des Rattenkindes (Ratten)',
    check: ['MU', 'IN', 'CH'],
    traditions: ['Namenloser'],
    increaseFactor: IncreaseFactor.B,
    url: 'https://dsa.ulisses-regelwiki.de/liturgie.html?liturgie=Herbeirufung+der+Heerscharen+des+Rattenkindes+(Ratten)',
    sources: [
      { book: 'Aventurisches Götterwirken', page: 145 },
      { book: 'Divinarium Liturgia', page: 100 },
    ],
  },
  {
    name: 'herbeirufungDerHeerscharenDesRattenkindesSchakale',
    label: 'Herbeirufung der Heerscharen des Rattenkindes (Schakale)',
    check: ['MU', 'IN', 'CH'],
    traditions: ['Namenloser'],
    increaseFactor: IncreaseFactor.C,
    url: 'https://dsa.ulisses-regelwiki.de/liturgie.html?liturgie=Herbeirufung+der+Heerscharen+des+Rattenkindes+(Schakale)',
    sources: [
      { book: 'Aventurisches Götterwirken', page: 145 },
      { book: 'Divinarium Liturgia', page: 101 },
    ],
  },
  {
    name: 'herbeirufungDerHeerscharenDesRattenkindesVampirfledermaeuse',
    label: 'Herbeirufung der Heerscharen des Rattenkindes (Vampirfledermäuse)',
    check: ['MU', 'IN', 'CH'],
    traditions: ['Namenloser'],
    increaseFactor: IncreaseFactor.B,
    url: 'https://dsa.ulisses-regelwiki.de/liturgie.html?liturgie=Herbeirufung+der+Heerscharen+des+Rattenkindes+(Vampirflederm%C3%A4use)',
    sources: [
      { book: 'Aventurisches Götterwirken', page: 146 },
      { book: 'Divinarium Liturgia', page: 102 },
    ],
  },
  {
    name: 'herbeirufungDerHeerscharenDesRattenkindesWolfsspinnen',
    label: 'Herbeirufung der Heerscharen des Rattenkindes (Wolfsspinnen)',
    check: ['MU', 'IN', 'CH'],
    traditions: ['Namenloser'],
    increaseFactor: IncreaseFactor.C,
    url: 'https://dsa.ulisses-regelwiki.de/liturgie.html?liturgie=Herbeirufung+der+Heerscharen+des+Rattenkindes+(Wolfsspinnen)',
    sources: [
      { book: 'Aventurisches Götterwirken', page: 146 },
      { book: 'Divinarium Liturgia', page: 103 },
    ],
  },
  {
    name: 'herbeirufungVonTairachsDienernNebelkraehen',
    label: 'Herbeirufung von Tairachs Dienern (Nebelkrähen)',
    check: ['MU', 'IN', 'CH'],
    traditions: ['Tairachschamanen (Geisterwelt)', 'Tairachschamanen (Zauberei)'],
    increaseFactor: IncreaseFactor.C,
    url: 'https://dsa.ulisses-regelwiki.de/liturgie.html?liturgie=Herbeirufung+von+Tairachs+Dienern+(Nebelkr%C3%A4hen)',
    sources: [
      { book: 'Divinarium Liturgia', page: 104 },
      { book: 'Orks - Hauer & Schwarzer Pelz', page: 50 },
    ],
  },
  {
    name: 'herrDerFlammen',
    label: 'Herr der Flammen',
    check: ['MU', 'IN', 'CH'],
    traditions: ['Angrosch (Flammen)', 'Gravesh (Brand)', 'Ingerimm (Feuer)'],
    increaseFactor: IncreaseFactor.B,
    url: 'https://dsa.ulisses-regelwiki.de/liturgie.html?liturgie=Herr+der+Flammen',
    sources: [
      { book: 'Aventurisches Götterwirken', page: 146 },
      { book: 'Aventurisches Götterwirken II', page: 74 },
      { book: 'Divinarium Liturgia', page: 105 },
    ],
  },
  {
    name: 'hilfreicheSeele',
    label: 'Hilfreiche Seele',
    check: ['MU', 'IN', 'CH'],
    traditions: ['Allgemein-Schamanenritus'],
    increaseFactor: IncreaseFactor.A,
    url: 'https://dsa.ulisses-regelwiki.de/liturgie.html?liturgie=Hilfreiche+Seele',
    sources: [
      { book: 'Aventurisches Götterwirken II', page: 90 },
      { book: 'Divinarium Liturgia', page: 106 },
    ],
  },
  {
    name: 'innereRuhe',
    label: 'Innere Ruhe',
    check: ['MU', 'KL', 'IN'],
    traditions: ['Boron (Traum)', 'Hesinde (Wissen)', 'Nandus (Bildung)'],
    increaseFactor: IncreaseFactor.B,
    url: 'https://dsa.ulisses-regelwiki.de/liturgie.html?liturgie=Innere+Ruhe',
    sources: [
      { book: 'Aventurisches Götterwirken', page: 147 },
      { book: 'Divinarium Liturgia', page: 107 },
    ],
  },
  {
    name: 'jaguarruf',
    label: 'Jaguarruf',
    check: ['MU', 'IN', 'CH'],
    traditions: ['Tahayaschamanen (Dschungel)'],
    increaseFactor: IncreaseFactor.C,
    url: 'https://dsa.ulisses-regelwiki.de/liturgie.html?liturgie=Jaguarruf',
    sources: [
      { book: 'Aventurisches Götterwirken II', page: 90 },
      { book: 'Die Dampfenden Dschungel - Der Tiefe Süden & die Waldinseln', page: 159 },
      { book: 'Divinarium Liturgia', page: 108 },
    ],
  },
  {
    name: 'kaelteexplosion',
    label: 'Kälteexplosion',
    check: ['MU', 'IN', 'KO'],
    traditions: ['Firun (Kälte)'],
    increaseFactor: IncreaseFactor.C,
    url: 'https://dsa.ulisses-regelwiki.de/liturgie.html?liturgie=K%C3%A4lteexplosion',
    sources: [
      { book: 'Aventurisches Götterwirken II', page: 90 },
      { book: 'Divinarium Liturgia', page: 109 },
    ],
  },
  {
    name: 'kampfgeschick',
    label: 'Kampfgeschick',
    check: ['MU', 'IN', 'KO'],
    traditions: ['Kor (Guter Kampf)', 'Rondra (Sturm)', 'Shinxir (Taktik)'],
    increaseFactor: IncreaseFactor.B,
    url: 'https://dsa.ulisses-regelwiki.de/liturgie.html?liturgie=Kampfgeschick',
    sources: [
      { book: 'Aventurisches Götterwirken', page: 147 },
      { book: 'Divinarium Liturgia', page: 110 },
    ],
  },
  {
    name: 'klarerGeist',
    label: 'Klarer Geist',
    check: ['MU', 'KL', 'IN'],
    traditions: ['Hesinde (Magie)', 'Hesinde (Wissen)'],
    increaseFactor: IncreaseFactor.B,
    url: 'https://dsa.ulisses-regelwiki.de/liturgie.html?liturgie=Klarer+Geist',
    sources: [
      { book: 'Aventurisches Götterwirken', page: 147 },
      { book: 'Divinarium Liturgia', page: 111 },
    ],
  },
  {
    name: 'kleidungschamaeleon',
    label: 'Kleidungschamäleon',
    check: ['KL', 'IN', 'CH'],
    traditions: ['Phex (Schatten)'],
    increaseFactor: IncreaseFactor.A,
    url: 'https://dsa.ulisses-regelwiki.de/liturgie.html?liturgie=Kleidungscham%C3%A4leon',
    sources: [
      { book: 'Aventurisches Götterwirken', page: 147 },
      { book: 'Divinarium Liturgia', page: 112 },
    ],
  },
  {
    name: 'kleineWindhose',
    label: 'Kleine Windhose',
    check: ['MU', 'CH', 'KO'],
    traditions: ['Efferd (Wind)', 'Swafnir (Kraft)'],
    increaseFactor: IncreaseFactor.B,
    url: 'https://dsa.ulisses-regelwiki.de/liturgie.html?liturgie=Kleine+Windhose',
    sources: [
      { book: 'Regelwerk', page: 328 },
      { book: 'Aventurisches Götterwirken', page: 168 },
      { book: 'Divinarium Liturgia', page: 113 },
    ],
  },
  {
    name: 'kleinerBannWiderUntote',
    label: 'Kleiner Bann wider Untote',
    check: ['MU', 'MU', 'CH'],
    traditions: ['Boron (Tod)', 'Praios (Antimagie)'],
    increaseFactor: IncreaseFactor.B,
    url: 'https://dsa.ulisses-regelwiki.de/liturgie.html?liturgie=Kleiner+Bann+wider+Untote',
    sources: [
      { book: 'Regelwerk', page: 329 },
      { book: 'Aventurisches Götterwirken', page: 168 },
      { book: 'Divinarium Liturgia', page: 114 },
    ],
  },

  // â”€â”€ Batch 6 (101â€“120) â”€â”€
  {
    name: 'kleinerBannstrahl',
    label: 'Kleiner Bannstrahl',
    check: ['MU', 'IN', 'CH'],
    traditions: ['Praios (Antimagie)'],
    increaseFactor: IncreaseFactor.B,
    url: 'https://dsa.ulisses-regelwiki.de/liturgie.html?liturgie=Kleiner+Bannstrahl',
    sources: [
      { book: 'Regelwerk', page: 329 },
      { book: 'Aventurisches Götterwirken', page: 168 },
      { book: 'Divinarium Liturgia', page: 115 },
    ],
  },
  {
    name: 'kraftvollerKoerper',
    label: 'Kraftvoller Körper',
    check: ['MU', 'IN', 'KO'],
    traditions: ['Firun (Jagd)', 'Ifirn (Natur)', 'Kor (Guter Kampf)', 'Rondra (Sturm)'],
    increaseFactor: IncreaseFactor.B,
    url: 'https://dsa.ulisses-regelwiki.de/liturgie.html?liturgie=Kraftvoller+K%C3%B6rper',
    sources: [
      { book: 'Aventurisches Götterwirken', page: 148 },
      { book: 'Divinarium Liturgia', page: 116 },
    ],
  },
  {
    name: 'krankheitenVorbeugen',
    label: 'Krankheiten vorbeugen',
    check: ['IN', 'IN', 'CH'],
    traditions: ['Peraine (Heilung)', 'Peraine (Landwirtschaft)'],
    increaseFactor: IncreaseFactor.B,
    url: 'https://dsa.ulisses-regelwiki.de/liturgie.html?liturgie=Krankheiten+vorbeugen',
    sources: [
      { book: 'Aventurisches Götterwirken', page: 148 },
      { book: 'Divinarium Liturgia', page: 117 },
    ],
  },
  {
    name: 'krankheitsbann',
    label: 'Krankheitsbann',
    check: ['KL', 'IN', 'CH'],
    traditions: ['Peraine (Heilung)'],
    increaseFactor: IncreaseFactor.B,
    url: 'https://dsa.ulisses-regelwiki.de/liturgie.html?liturgie=Krankheitsbann',
    sources: [
      { book: 'Regelwerk', page: 329 },
      { book: 'Aventurisches Götterwirken', page: 168 },
      { book: 'Divinarium Liturgia', page: 118 },
    ],
  },
  {
    name: 'kriegsfarben',
    label: 'Kriegsfarben',
    check: ['MU', 'IN', 'KO'],
    traditions: ['Allgemein-Schamanenritus'],
    increaseFactor: IncreaseFactor.A,
    url: 'https://dsa.ulisses-regelwiki.de/liturgie.html?liturgie=Kriegsfarben',
    sources: [
      { book: 'Aventurisches Götterwirken II', page: 91 },
      { book: 'Divinarium Liturgia', page: 119 },
    ],
  },
  {
    name: 'lautlos',
    label: 'Lautlos',
    check: ['IN', 'IN', 'GE'],
    traditions: ['Phex (Schatten)'],
    increaseFactor: IncreaseFactor.B,
    url: 'https://dsa.ulisses-regelwiki.de/liturgie.html?liturgie=Lautlos',
    sources: [
      { book: 'Aventurisches Götterwirken', page: 148 },
      { book: 'Divinarium Liturgia', page: 120 },
    ],
  },
  {
    name: 'lebensschutz',
    label: 'Lebensschutz',
    check: ['MU', 'KL', 'IN'],
    traditions: ['Peraine (Heilung)', 'Tsa (Freiheit)', 'Tsa (Wandel)'],
    increaseFactor: IncreaseFactor.C,
    url: 'https://dsa.ulisses-regelwiki.de/liturgie.html?liturgie=Lebensschutz',
    sources: [
      { book: 'Aventurisches Götterwirken', page: 148 },
      { book: 'Divinarium Liturgia', page: 121 },
    ],
  },
  {
    name: 'levthanischerLiebhaber',
    label: 'Levthanischer Liebhaber',
    check: ['MU', 'IN', 'CH'],
    traditions: ['Levthan (Begierde)'],
    increaseFactor: IncreaseFactor.A,
    url: 'https://dsa.ulisses-regelwiki.de/liturgie.html?liturgie=Levthanischer+Liebhaber',
    sources: [
      { book: 'Aventurisches Götterwirken II', page: 91 },
      { book: 'Divinarium Liturgia', page: 122 },
      { book: 'Wege der Vereinigungen', page: 191 },
    ],
  },
  {
    name: 'liturgieschild',
    label: 'Liturgieschild',
    check: ['MU', 'KL', 'CH'],
    traditions: ['Allgemein'],
    increaseFactor: IncreaseFactor.B,
    url: 'https://dsa.ulisses-regelwiki.de/liturgie.html?liturgie=Liturgieschild',
    sources: [
      { book: 'Regelwerk', page: 329 },
      { book: 'Aventurisches Götterwirken', page: 168 },
      { book: 'Divinarium Liturgia', page: 123 },
    ],
  },
  {
    name: 'lustErzeugen',
    label: 'Lust erzeugen',
    check: ['MU', 'IN', 'CH'],
    traditions: ['Levthan (Begierde)', 'Rahja (Ekstase)'],
    increaseFactor: IncreaseFactor.A,
    url: 'https://dsa.ulisses-regelwiki.de/liturgie.html?liturgie=Lust+erzeugen',
    sources: [
      { book: 'Aventurisches Götterwirken II', page: 91 },
      { book: 'Divinarium Liturgia', page: 124 },
      { book: 'Wege der Vereinigungen', page: 191 },
    ],
  },
  {
    name: 'machtDesLevthan',
    label: 'Macht des Levthan',
    check: ['MU', 'CH', 'KO'],
    traditions: ['Levthan (Begierde)', 'Levthan (Rausch)'],
    increaseFactor: IncreaseFactor.C,
    url: 'https://dsa.ulisses-regelwiki.de/liturgie.html?liturgie=Macht+des+Levthan',
    sources: [
      { book: 'Aventurisches Götterwirken II', page: 91 },
      { book: 'Divinarium Liturgia', page: 125 },
      { book: 'Wege der Vereinigungen', page: 192 },
    ],
  },
  {
    name: 'maechtigerAngriff',
    label: 'Mächtiger Angriff',
    check: ['MU', 'IN', 'KO'],
    traditions: ['Rondra (Sturm)'],
    increaseFactor: IncreaseFactor.C,
    url: 'https://dsa.ulisses-regelwiki.de/liturgie.html?liturgie=M%C3%A4chtiger+Angriff',
    sources: [
      { book: 'Regelwerk', page: 330 },
      { book: 'Aventurisches Götterwirken', page: 168 },
      { book: 'Divinarium Liturgia', page: 126 },
    ],
  },
  {
    name: 'magieanalyse',
    label: 'Magieanalyse',
    check: ['KL', 'KL', 'IN'],
    traditions: ['Hesinde (Magie)'],
    increaseFactor: IncreaseFactor.C,
    url: 'https://dsa.ulisses-regelwiki.de/liturgie.html?liturgie=Magieanalyse',
    sources: [
      { book: 'Aventurisches Götterwirken', page: 149 },
      { book: 'Divinarium Liturgia', page: 127 },
    ],
  },
  {
    name: 'magiebann',
    label: 'Magiebann',
    check: ['KL', 'IN', 'CH'],
    traditions: ['Hesinde (Magie)', 'Praios (Antimagie)'],
    increaseFactor: IncreaseFactor.D,
    url: 'https://dsa.ulisses-regelwiki.de/liturgie.html?liturgie=Magiebann',
    sources: [
      { book: 'Aventurisches Götterwirken', page: 149 },
      { book: 'Divinarium Liturgia', page: 128 },
    ],
  },
  {
    name: 'magieschutz',
    label: 'Magieschutz',
    check: ['MU', 'IN', 'CH'],
    traditions: ['Praios (Antimagie)'],
    increaseFactor: IncreaseFactor.C,
    url: 'https://dsa.ulisses-regelwiki.de/liturgie.html?liturgie=Magieschutz',
    sources: [
      { book: 'Aventurisches Götterwirken', page: 149 },
      { book: 'Divinarium Liturgia', page: 129 },
    ],
  },
  {
    name: 'magiesicht',
    label: 'Magiesicht',
    check: ['KL', 'IN', 'IN'],
    traditions: ['Hesinde (Magie)', 'Praios (Antimagie)'],
    increaseFactor: IncreaseFactor.A,
    url: 'https://dsa.ulisses-regelwiki.de/liturgie.html?liturgie=Magiesicht',
    sources: [
      { book: 'Aventurisches Götterwirken', page: 149 },
      { book: 'Divinarium Liturgia', page: 130 },
    ],
  },
  {
    name: 'magiespiegel',
    label: 'Magiespiegel',
    check: ['MU', 'KL', 'IN'],
    traditions: ['Hesinde (Magie)', 'Praios (Antimagie)'],
    increaseFactor: IncreaseFactor.D,
    url: 'https://dsa.ulisses-regelwiki.de/liturgie.html?liturgie=Magiespiegel',
    sources: [
      { book: 'Aventurisches Götterwirken', page: 150 },
      { book: 'Divinarium Liturgia', page: 131 },
    ],
  },
  {
    name: 'mammutruf',
    label: 'Mammutruf',
    check: ['MU', 'IN', 'CH'],
    traditions: ['Firun (Jagd)', 'Firun (Kälte)'],
    increaseFactor: IncreaseFactor.C,
    url: 'https://dsa.ulisses-regelwiki.de/liturgie.html?liturgie=Mammutruf',
    sources: [
      { book: 'Aventurisches Götterwirken', page: 150 },
      { book: 'Divinarium Liturgia', page: 132 },
    ],
  },
  {
    name: 'maske',
    label: 'Maske',
    check: ['KL', 'IN', 'CH'],
    traditions: ['Phex (Schatten)'],
    increaseFactor: IncreaseFactor.B,
    url: 'https://dsa.ulisses-regelwiki.de/liturgie.html?liturgie=Maske',
    sources: [
      { book: 'Aventurisches Götterwirken', page: 150 },
      { book: 'Divinarium Liturgia', page: 133 },
    ],
  },
  {
    name: 'mauereinsturz',
    label: 'Mauereinsturz',
    check: ['MU', 'IN', 'CH'],
    traditions: ['Gravesh (Erdspalte)'],
    increaseFactor: IncreaseFactor.C,
    url: 'https://dsa.ulisses-regelwiki.de/liturgie.html?liturgie=Mauereinsturz',
    sources: [
      { book: 'Aventurisches Götterwirken II', page: 92 },
      { book: 'Divinarium Liturgia', page: 134 },
    ],
  },

  // â”€â”€ Batch 7 (121â€“140) â”€â”€
  {
    name: 'meeresungeheuerVertreiben',
    label: 'Meeresungeheuer vertreiben',
    check: ['MU', 'IN', 'CH'],
    traditions: ['Efferd (Wogen)', 'Swafnir (Kraft)'],
    increaseFactor: IncreaseFactor.C,
    url: 'https://dsa.ulisses-regelwiki.de/liturgie.html?liturgie=Meeresungeheuer+vertreiben',
    sources: [
      { book: 'Aventurisches Götterwirken', page: 150 },
      { book: 'Divinarium Liturgia', page: 135 },
    ],
  },
  {
    name: 'mitDummheitSchlagen',
    label: 'Mit Dummheit schlagen',
    check: ['KL', 'IN', 'CH'],
    traditions: ['Namenloser'],
    increaseFactor: IncreaseFactor.B,
    url: 'https://dsa.ulisses-regelwiki.de/liturgie.html?liturgie=Mit+Dummheit+schlagen',
    sources: [
      { book: 'Aventurisches Götterwirken', page: 151 },
      { book: 'Divinarium Liturgia', page: 136 },
    ],
  },
  {
    name: 'mondsicht',
    label: 'Mondsicht',
    check: ['KL', 'KL', 'IN'],
    traditions: ['Phex (Schatten)'],
    increaseFactor: IncreaseFactor.A,
    url: 'https://dsa.ulisses-regelwiki.de/liturgie.html?liturgie=Mondsicht',
    sources: [
      { book: 'Aventurisches Götterwirken', page: 151 },
      { book: 'Divinarium Liturgia', page: 137 },
    ],
  },
  {
    name: 'mondsilberzunge',
    label: 'Mondsilberzunge',
    check: ['KL', 'IN', 'CH'],
    traditions: ['Phex (Handel)', 'Phex (Schatten)'],
    increaseFactor: IncreaseFactor.B,
    url: 'https://dsa.ulisses-regelwiki.de/liturgie.html?liturgie=Mondsilberzunge',
    sources: [
      { book: 'Regelwerk', page: 330 },
      { book: 'Aventurisches Götterwirken', page: 169 },
      { book: 'Divinarium Liturgia', page: 138 },
    ],
  },
  {
    name: 'motivation',
    label: 'Motivation',
    check: ['MU', 'IN', 'CH'],
    traditions: ['Aves (Schicksal)', 'Rondra (Schild)', 'Travia (Freundschaft)'],
    increaseFactor: IncreaseFactor.A,
    url: 'https://dsa.ulisses-regelwiki.de/liturgie.html?liturgie=Motivation',
    sources: [
      { book: 'Regelwerk', page: 330 },
      { book: 'Aventurisches Götterwirken', page: 169 },
      { book: 'Divinarium Liturgia', page: 139 },
    ],
  },
  {
    name: 'namenloseKaelte',
    label: 'Namenlose Kälte',
    check: ['KL', 'IN', 'CH'],
    traditions: ['Namenloser'],
    increaseFactor: IncreaseFactor.C,
    url: 'https://dsa.ulisses-regelwiki.de/liturgie.html?liturgie=Namenlose+K%C3%A4lte',
    sources: [
      { book: 'Aventurisches Götterwirken', page: 151 },
      { book: 'Divinarium Liturgia', page: 140 },
    ],
  },
  {
    name: 'namenloseRaserei',
    label: 'Namenlose Raserei',
    check: ['MU', 'IN', 'CH'],
    traditions: ['Namenloser'],
    increaseFactor: IncreaseFactor.B,
    url: 'https://dsa.ulisses-regelwiki.de/liturgie.html?liturgie=Namenlose+Raserei',
    sources: [
      { book: 'Aventurisches Götterwirken', page: 151 },
      { book: 'Divinarium Liturgia', page: 141 },
    ],
  },
  {
    name: 'namenloseZweifel',
    label: 'Namenlose Zweifel',
    check: ['MU', 'IN', 'CH'],
    traditions: ['Namenloser'],
    increaseFactor: IncreaseFactor.B,
    url: 'https://dsa.ulisses-regelwiki.de/liturgie.html?liturgie=Namenlose+Zweifel',
    sources: [
      { book: 'Aventurisches Götterwirken', page: 152 },
      { book: 'Divinarium Liturgia', page: 142 },
    ],
  },
  {
    name: 'namenlosesvergessen',
    label: 'Namenloses Vergessen',
    check: ['KL', 'IN', 'CH'],
    traditions: ['Namenloser'],
    increaseFactor: IncreaseFactor.B,
    url: 'https://dsa.ulisses-regelwiki.de/liturgie.html?liturgie=Namenloses+Vergessen',
    sources: [
      { book: 'Aventurisches Götterwirken', page: 152 },
      { book: 'Divinarium Liturgia', page: 143 },
    ],
  },
  {
    name: 'nebelkraehenschwarm',
    label: 'Nebelkrähenschwarm',
    check: ['MU', 'KL', 'IN'],
    traditions: ['Tairachschamanen (Geisterwelt)'],
    increaseFactor: IncreaseFactor.C,
    url: 'https://dsa.ulisses-regelwiki.de/liturgie.html?liturgie=Nebelkr%C3%A4henschwarm',
    sources: [
      { book: 'Divinarium Liturgia', page: 144 },
      { book: 'Orks - Hauer & Schwarzer Pelz', page: 50 },
    ],
  },
  {
    name: 'numinorusFesseln',
    label: 'Numinorus Fesseln',
    check: ['MU', 'KL', 'KK'],
    traditions: ['Numinoru (Reißender Strudel)'],
    increaseFactor: IncreaseFactor.B,
    url: 'https://dsa.ulisses-regelwiki.de/liturgie.html?liturgie=Numinorus+Fesseln',
    sources: [
      { book: 'Divinarium Liturgia', page: 145 },
      { book: 'Unendlichkeit & Tiefenrausch', page: 19 },
    ],
  },
  {
    name: 'obaransBlendung',
    label: 'Obarans Blendung',
    check: ['MU', 'KL', 'CH'],
    traditions: ['Brazoragh (Krieg)'],
    increaseFactor: IncreaseFactor.B,
    url: 'https://dsa.ulisses-regelwiki.de/liturgie.html?liturgie=Obarans+Blendung',
    sources: [
      { book: 'Divinarium Liturgia', page: 146 },
      { book: 'Orks - Hauer & Schwarzer Pelz', page: 50 },
    ],
  },
  {
    name: 'objektsegen',
    label: 'Objektsegen',
    check: ['MU', 'IN', 'CH'],
    traditions: ['Allgemein', 'Allgemein-Schamanenritus'],
    increaseFactor: IncreaseFactor.B,
    url: 'https://dsa.ulisses-regelwiki.de/liturgie.html?liturgie=Objektsegen',
    sources: [
      { book: 'Regelwerk', page: 330 },
      { book: 'Aventurisches Götterwirken', page: 169 },
      { book: 'Aventurisches Götterwirken II', page: 75 },
      { book: 'Divinarium Liturgia', page: 147 },
    ],
  },
  {
    name: 'obsession',
    label: 'Obsession',
    check: ['KL', 'IN', 'CH'],
    traditions: ['Levthan (Begierde)'],
    increaseFactor: IncreaseFactor.B,
    url: 'https://dsa.ulisses-regelwiki.de/liturgie.html?liturgie=Obsession',
    sources: [
      { book: 'Aventurisches Götterwirken II', page: 92 },
      { book: 'Divinarium Liturgia', page: 148 },
      { book: 'Wege der Vereinigungen', page: 192 },
    ],
  },
  {
    name: 'offenlegungDesGeistes',
    label: 'Offenlegung des Geistes',
    check: ['KL', 'IN', 'CH'],
    traditions: ['Praios (Ordnung)'],
    increaseFactor: IncreaseFactor.C,
    url: 'https://dsa.ulisses-regelwiki.de/liturgie.html?liturgie=Offenlegung+des+Geistes',
    sources: [
      { book: 'Aventurisches Götterwirken', page: 152 },
      { book: 'Divinarium Liturgia', page: 149 },
    ],
  },
  {
    name: 'ogerruf',
    label: 'Ogerruf',
    check: ['KL', 'IN', 'CH'],
    traditions: ['Tairachschamanen (Geisterwelt)', 'Tairachschamanen (Zauberei)'],
    increaseFactor: IncreaseFactor.C,
    url: 'https://dsa.ulisses-regelwiki.de/liturgie.html?liturgie=Ogerruf',
    sources: [
      { book: 'Divinarium Liturgia', page: 150 },
      { book: 'Orks - Hauer & Schwarzer Pelz', page: 50 },
    ],
  },
  {
    name: 'opfergang',
    label: 'Opfergang',
    check: ['MU', 'KO', 'KK'],
    traditions: ['Rondra (Schild)', 'Rondra (Sturm)'],
    increaseFactor: IncreaseFactor.D,
    url: 'https://dsa.ulisses-regelwiki.de/liturgie.html?liturgie=Opfergang',
    sources: [
      { book: 'Aventurisches Götterwirken', page: 152 },
      { book: 'Divinarium Liturgia', page: 151 },
    ],
  },
  {
    name: 'ortDerRuhe',
    label: 'Ort der Ruhe',
    check: ['MU', 'KL', 'IN'],
    traditions: ['Boron (Traum)'],
    increaseFactor: IncreaseFactor.A,
    url: 'https://dsa.ulisses-regelwiki.de/liturgie.html?liturgie=Ort+der+Ruhe',
    sources: [
      { book: 'Aventurisches Götterwirken', page: 152 },
      { book: 'Divinarium Liturgia', page: 152 },
    ],
  },
  {
    name: 'pechUndSchwefel',
    label: 'Pech und Schwefel',
    check: ['MU', 'KL', 'CH'],
    traditions: ['Angrosch (Flammen)', 'Gravesh (Brand)', 'Ingerimm (Feuer)'],
    increaseFactor: IncreaseFactor.C,
    url: 'https://dsa.ulisses-regelwiki.de/liturgie.html?liturgie=Pech+und+Schwefel',
    sources: [
      { book: 'Aventurisches Götterwirken', page: 153 },
      { book: 'Aventurisches Götterwirken II', page: 74 },
      { book: 'Divinarium Liturgia', page: 153 },
    ],
  },
  {
    name: 'perainesGnade',
    label: 'Peraines Gnade',
    check: ['IN', 'CH', 'FF'],
    traditions: ['Peraine (Heilung)'],
    increaseFactor: IncreaseFactor.B,
    url: 'https://dsa.ulisses-regelwiki.de/liturgie.html?liturgie=Peraines+Gnade',
    sources: [
      { book: 'Aventurisches Götterwirken', page: 153 },
      { book: 'Divinarium Liturgia', page: 154 },
    ],
  },

  // â”€â”€ Batch 8 (141â€“160) â”€â”€
  {
    name: 'pflanzenwuchs',
    label: 'Pflanzenwuchs',
    check: ['KL', 'IN', 'CH'],
    traditions: ['Ifirn (Natur)', 'Peraine (Landwirtschaft)'],
    increaseFactor: IncreaseFactor.A,
    url: 'https://dsa.ulisses-regelwiki.de/liturgie.html?liturgie=Pflanzenwuchs',
    sources: [
      { book: 'Aventurisches Götterwirken', page: 153 },
      { book: 'Divinarium Liturgia', page: 155 },
    ],
  },
  {
    name: 'quallenhaut',
    label: 'Quallenhaut',
    check: ['MU', 'KL', 'KK'],
    traditions: ['Numinoru (Reißender Strudel)'],
    increaseFactor: IncreaseFactor.C,
    url: 'https://dsa.ulisses-regelwiki.de/liturgie.html?liturgie=Quallenhaut',
    sources: [
      { book: 'Divinarium Liturgia', page: 156 },
      { book: 'Unendlichkeit & Tiefenrausch', page: 19 },
    ],
  },
  {
    name: 'quallenruf',
    label: 'Quallenruf',
    check: ['MU', 'IN', 'CH'],
    traditions: ['Numinoru (Reißender Strudel)', 'Numinoru (Unendliche Tiefe)'],
    increaseFactor: IncreaseFactor.C,
    url: 'https://dsa.ulisses-regelwiki.de/liturgie.html?liturgie=Quallenruf',
    sources: [
      { book: 'Divinarium Liturgia', page: 157 },
      { book: 'Unendlichkeit & Tiefenrausch', page: 20 },
    ],
  },
  {
    name: 'rabenruf',
    label: 'Rabenruf',
    check: ['MU', 'KL', 'IN'],
    traditions: ['Boron (Tod)'],
    increaseFactor: IncreaseFactor.A,
    url: 'https://dsa.ulisses-regelwiki.de/liturgie.html?liturgie=Rabenruf',
    sources: [
      { book: 'Aventurisches Götterwirken', page: 154 },
      { book: 'Divinarium Liturgia', page: 158 },
    ],
  },
  {
    name: 'rattenschwarm',
    label: 'Rattenschwarm',
    check: ['MU', 'KL', 'IN'],
    traditions: ['Namenloser'],
    increaseFactor: IncreaseFactor.C,
    url: 'https://dsa.ulisses-regelwiki.de/liturgie.html?liturgie=Rattenschwarm',
    sources: [
      { book: 'Aventurisches Götterwirken', page: 154 },
      { book: 'Divinarium Liturgia', page: 159 },
    ],
  },
  {
    name: 'regenbogenbruecke',
    label: 'Regenbogenbrücke',
    check: ['MU', 'IN', 'KO'],
    traditions: ['Ifirn (Hilfsbereitschaft)', 'Ifirn (Natur)'],
    increaseFactor: IncreaseFactor.C,
    url: 'https://dsa.ulisses-regelwiki.de/liturgie.html?liturgie=Regenbogenbr%C3%BCcke',
    sources: [
      { book: 'Aventurisches Götterwirken', page: 154 },
      { book: 'Divinarium Liturgia', page: 160 },
    ],
  },
  {
    name: 'reinigungDesBoesen',
    label: 'Reinigung des Bösen',
    check: ['MU', 'IN', 'CH'],
    traditions: ['Praios (Ordnung)'],
    increaseFactor: IncreaseFactor.C,
    url: 'https://dsa.ulisses-regelwiki.de/liturgie.html?liturgie=Reinigung+des+B%C3%B6sen',
    sources: [
      { book: 'Aventurisches Götterwirken', page: 155 },
      { book: 'Divinarium Liturgia', page: 161 },
    ],
  },
  {
    name: 'rinderruf',
    label: 'Rinderruf',
    check: ['MU', 'IN', 'CH'],
    traditions: ['Peraine (Landwirtschaft)'],
    increaseFactor: IncreaseFactor.B,
    url: 'https://dsa.ulisses-regelwiki.de/liturgie.html?liturgie=Rinderruf',
    sources: [
      { book: 'Aventurisches Götterwirken', page: 155 },
      { book: 'Divinarium Liturgia', page: 162 },
    ],
  },
  {
    name: 'rufDerHeimat',
    label: 'Ruf der Heimat',
    check: ['KL', 'IN', 'CH'],
    traditions: ['Travia (Heim)'],
    increaseFactor: IncreaseFactor.A,
    url: 'https://dsa.ulisses-regelwiki.de/liturgie.html?liturgie=Ruf+der+Heimat',
    sources: [
      { book: 'Aventurisches Götterwirken', page: 155 },
      { book: 'Divinarium Liturgia', page: 163 },
    ],
  },
  {
    name: 'schattenfessel',
    label: 'Schattenfessel',
    check: ['MU', 'IN', 'KO'],
    traditions: ['Phex (Schatten)'],
    increaseFactor: IncreaseFactor.B,
    url: 'https://dsa.ulisses-regelwiki.de/liturgie.html?liturgie=Schattenfessel',
    sources: [
      { book: 'Aventurisches Götterwirken', page: 155 },
      { book: 'Divinarium Liturgia', page: 164 },
    ],
  },
  {
    name: 'schiffsgespuer',
    label: 'Schiffsgespür',
    check: ['KL', 'IN', 'IN'],
    traditions: ['Efferd (Wogen)', 'Swafnir (Tapferkeit)'],
    increaseFactor: IncreaseFactor.A,
    url: 'https://dsa.ulisses-regelwiki.de/liturgie.html?liturgie=Schiffsgsp%C3%BCr',
    sources: [
      { book: 'Aventurisches Götterwirken', page: 156 },
      { book: 'Divinarium Liturgia', page: 165 },
    ],
  },
  {
    name: 'schlaf',
    label: 'Schlaf',
    check: ['KL', 'IN', 'CH'],
    traditions: ['Boron (Traum)'],
    increaseFactor: IncreaseFactor.B,
    url: 'https://dsa.ulisses-regelwiki.de/liturgie.html?liturgie=Schlaf',
    sources: [
      { book: 'Regelwerk', page: 331 },
      { book: 'Aventurisches Götterwirken', page: 169 },
      { book: 'Divinarium Liturgia', page: 166 },
    ],
  },
  {
    name: 'schlangenruf',
    label: 'Schlangenruf',
    check: ['MU', 'IN', 'CH'],
    traditions: ["H'Szint (Schlange)", 'Hesinde (Magie)'],
    increaseFactor: IncreaseFactor.B,
    url: 'https://dsa.ulisses-regelwiki.de/liturgie.html?liturgie=Schlangenruf',
    sources: [
      { book: 'Achaz - Schuppenkleid & Lange Zungen', page: 55 },
      { book: 'Aventurisches Götterwirken', page: 156 },
      { book: 'Divinarium Liturgia', page: 167 },
    ],
  },
  {
    name: 'schlangenstab',
    label: 'Schlangenstab',
    check: ['MU', 'KL', 'IN'],
    traditions: ['Hesinde (Magie)', 'Hesinde (Wissen)'],
    increaseFactor: IncreaseFactor.B,
    url: 'https://dsa.ulisses-regelwiki.de/liturgie.html?liturgie=Schlangenstab',
    sources: [
      { book: 'Aventurisches Götterwirken', page: 156 },
      { book: 'Divinarium Liturgia', page: 168 },
    ],
  },
  {
    name: 'schlangenzunge',
    label: 'Schlangenzunge',
    check: ['MU', 'KL', 'IN'],
    traditions: ['Namenloser'],
    increaseFactor: IncreaseFactor.A,
    url: 'https://dsa.ulisses-regelwiki.de/liturgie.html?liturgie=Schlangenzunge',
    sources: [
      { book: 'Aventurisches Götterwirken', page: 156 },
      { book: 'Divinarium Liturgia', page: 169 },
    ],
  },
  {
    name: 'schleichendeFaeulnis',
    label: 'Schleichende Fäulnis',
    check: ['MU', 'IN', 'KO'],
    traditions: ['Namenloser'],
    increaseFactor: IncreaseFactor.C,
    url: 'https://dsa.ulisses-regelwiki.de/liturgie.html?liturgie=Schleichende+F%C3%A4ulnis',
    sources: [
      { book: 'Aventurisches Götterwirken', page: 157 },
      { book: 'Divinarium Liturgia', page: 170 },
    ],
  },
  {
    name: 'schleichendeFaeulnisPflanzen',
    label: 'Schleichende Fäulnis (Pflanzen)',
    check: ['KL', 'IN', 'CH'],
    traditions: ['Namenloser'],
    increaseFactor: IncreaseFactor.B,
    url: 'https://dsa.ulisses-regelwiki.de/liturgie.html?liturgie=Schleichende+F%C3%A4ulnis+(Pflanzen)',
    sources: [
      { book: 'Aventurisches Götterwirken', page: 157 },
      { book: 'Divinarium Liturgia', page: 171 },
    ],
  },
  {
    name: 'schlingerruf',
    label: 'Schlingerruf',
    check: ['MU', 'IN', 'CH'],
    traditions: ['Numinoru (Unendliche Tiefe)'],
    increaseFactor: IncreaseFactor.D,
    url: 'https://dsa.ulisses-regelwiki.de/liturgie.html?liturgie=Schlingerruf',
    sources: [
      { book: 'Divinarium Liturgia', page: 172 },
      { book: 'Unendlichkeit & Tiefenrausch', page: 20 },
    ],
  },
  {
    name: 'schmerzresistenz',
    label: 'Schmerzresistenz',
    check: ['MU', 'IN', 'KO'],
    traditions: ['Kor (Guter Kampf)', 'Rondra (Schild)'],
    increaseFactor: IncreaseFactor.C,
    url: 'https://dsa.ulisses-regelwiki.de/liturgie.html?liturgie=Schmerzresistenz',
    sources: [
      { book: 'Aventurisches Götterwirken', page: 157 },
      { book: 'Divinarium Liturgia', page: 173 },
    ],
  },
  {
    name: 'schonfrist',
    label: 'Schonfrist',
    check: ['KL', 'IN', 'CH'],
    traditions: ['Peraine (Heilung)'],
    increaseFactor: IncreaseFactor.C,
    url: 'https://dsa.ulisses-regelwiki.de/liturgie.html?liturgie=Schonfrist',
    sources: [
      { book: 'Aventurisches Götterwirken', page: 158 },
      { book: 'Divinarium Liturgia', page: 174 },
    ],
  },

  // â”€â”€ Batch 9 (161â€“180) â”€â”€
  {
    name: 'schutzDerHornisskoenigin',
    label: 'Schutz der Hornissenkönigin',
    check: ['KL', 'IN', 'KO'],
    traditions: ['Peraine (Landwirtschaft)'],
    increaseFactor: IncreaseFactor.D,
    url: 'https://dsa.ulisses-regelwiki.de/liturgie.html?liturgie=Schutz+der+Hornissenk%C3%B6nigin',
    sources: [
      { book: 'Aventurisches Götterwirken', page: 158 },
      { book: 'Divinarium Liturgia', page: 175 },
    ],
  },
  {
    name: 'schutzDerWehrlosen',
    label: 'Schutz der Wehrlosen',
    check: ['MU', 'IN', 'CH'],
    traditions: ['Ifirn (Hilfsbereitschaft)', 'Rondra (Schild)', 'Travia (Heim)'],
    increaseFactor: IncreaseFactor.B,
    url: 'https://dsa.ulisses-regelwiki.de/liturgie.html?liturgie=Schutz+der+Wehrlosen',
    sources: [
      { book: 'Aventurisches Götterwirken', page: 158 },
      { book: 'Divinarium Liturgia', page: 176 },
    ],
  },
  {
    name: 'schutzsegen',
    label: 'Schutzsegen',
    check: ['MU', 'IN', 'CH'],
    traditions: ['Rondra (Schild)'],
    increaseFactor: IncreaseFactor.B,
    url: 'https://dsa.ulisses-regelwiki.de/liturgie.html?liturgie=Schutzsegen',
    sources: [
      { book: 'Regelwerk', page: 331 },
      { book: 'Aventurisches Götterwirken', page: 169 },
      { book: 'Divinarium Liturgia', page: 177 },
    ],
  },
  {
    name: 'schwindendeZauberkraft',
    label: 'Schwindende Zauberkraft',
    check: ['IN', 'IN', 'CH'],
    traditions: ['Praios (Antimagie)'],
    increaseFactor: IncreaseFactor.C,
    url: 'https://dsa.ulisses-regelwiki.de/liturgie.html?liturgie=Schwindende+Zauberkraft',
    sources: [
      { book: 'Aventurisches Götterwirken', page: 158 },
      { book: 'Divinarium Liturgia', page: 178 },
    ],
  },
  {
    name: 'seelenschatten',
    label: 'Seelenschatten',
    check: ['MU', 'IN', 'CH'],
    traditions: ['Namenloser'],
    increaseFactor: IncreaseFactor.B,
    url: 'https://dsa.ulisses-regelwiki.de/liturgie.html?liturgie=Seelenschatten',
    sources: [
      { book: 'Aventurisches Götterwirken', page: 158 },
      { book: 'Divinarium Liturgia', page: 179 },
    ],
  },
  {
    name: 'seevogelsprache',
    label: 'Seevogelsprache',
    check: ['KL', 'IN', 'CH'],
    traditions: ['Efferd (Wind)', 'Efferd (Wogen)'],
    increaseFactor: IncreaseFactor.A,
    url: 'https://dsa.ulisses-regelwiki.de/liturgie.html?liturgie=Seevogelsprache',
    sources: [
      { book: 'Aventurisches Götterwirken', page: 159 },
      { book: 'Divinarium Liturgia', page: 180 },
    ],
  },
  {
    name: 'sichererWeg',
    label: 'Sicherer Weg',
    check: ['MU', 'KL', 'IN'],
    traditions: ['Aves (Reise)', 'Aves (Schicksal)'],
    increaseFactor: IncreaseFactor.B,
    url: 'https://dsa.ulisses-regelwiki.de/liturgie.html?liturgie=Sicherer+Weg',
    sources: [
      { book: 'Aventurisches Götterwirken', page: 159 },
      { book: 'Divinarium Liturgia', page: 181 },
    ],
  },
  {
    name: 'sichtInDerDunkelheit',
    label: 'Sicht in der Dunkelheit',
    check: ['KL', 'IN', 'KO'],
    traditions: ['Boron (Traum)', 'Firun (Jagd)'],
    increaseFactor: IncreaseFactor.A,
    url: 'https://dsa.ulisses-regelwiki.de/liturgie.html?liturgie=Sicht+in+der+Dunkelheit',
    sources: [
      { book: 'Aventurisches Götterwirken', page: 159 },
      { book: 'Divinarium Liturgia', page: 182 },
    ],
  },
  {
    name: 'speerDesAthleten',
    label: 'Speer des Athleten',
    check: ['MU', 'IN', 'KK'],
    traditions: ['Kor (Guter Kampf)', 'Kor (Gutes Gold)'],
    increaseFactor: IncreaseFactor.C,
    url: 'https://dsa.ulisses-regelwiki.de/liturgie.html?liturgie=Speer+des+Athleten',
    sources: [
      { book: 'Aventurisches Götterwirken', page: 159 },
      { book: 'Divinarium Liturgia', page: 183 },
    ],
  },
  {
    name: 'spracheDesTapams',
    label: 'Sprache des Tapams',
    check: ['KL', 'IN', 'CH'],
    traditions: ['Allgemein-Schamanenritus'],
    increaseFactor: IncreaseFactor.B,
    url: 'https://dsa.ulisses-regelwiki.de/liturgie.html?liturgie=Sprache+des+Tapams',
    sources: [
      { book: 'Aventurisches Götterwirken II', page: 94 },
      { book: 'Divinarium Liturgia', page: 184 },
    ],
  },
  {
    name: 'steinhaut',
    label: 'Steinhaut',
    check: ['IN', 'CH', 'KO'],
    traditions: ['Angrosch (Erz)', 'Rondra (Schild)'],
    increaseFactor: IncreaseFactor.C,
    url: 'https://dsa.ulisses-regelwiki.de/liturgie.html?liturgie=Steinhaut',
    sources: [
      { book: 'Aventurisches Götterwirken', page: 159 },
      { book: 'Divinarium Liturgia', page: 185 },
    ],
  },
  {
    name: 'sternenglanz',
    label: 'Sternenglanz',
    check: ['KL', 'IN', 'CH'],
    traditions: ['Hesinde (Wissen)'],
    increaseFactor: IncreaseFactor.A,
    url: 'https://dsa.ulisses-regelwiki.de/liturgie.html?liturgie=Sternenglanz',
    sources: [
      { book: 'Aventurisches Götterwirken', page: 160 },
      { book: 'Divinarium Liturgia', page: 186 },
    ],
  },
  {
    name: 'sturmruf',
    label: 'Sturmruf',
    check: ['MU', 'IN', 'CH'],
    traditions: ['Efferd (Wind)', 'Swafnir (Kraft)'],
    increaseFactor: IncreaseFactor.B,
    url: 'https://dsa.ulisses-regelwiki.de/liturgie.html?liturgie=Sturmruf',
    sources: [
      { book: 'Regelwerk', page: 331 },
      { book: 'Aventurisches Götterwirken', page: 169 },
      { book: 'Divinarium Liturgia', page: 187 },
    ],
  },
  {
    name: 'talismanruf',
    label: 'Talismanruf',
    check: ['KL', 'IN', 'CH'],
    traditions: ['Allgemein'],
    increaseFactor: IncreaseFactor.D,
    url: 'https://dsa.ulisses-regelwiki.de/liturgie.html?liturgie=Talismanruf',
    sources: [
      { book: 'Aventurisches Götterwirken II', page: 94 },
      { book: 'Divinarium Liturgia', page: 188 },
    ],
  },
  {
    name: 'tierbeherrschung',
    label: 'Tierbeherrschung',
    check: ['MU', 'IN', 'CH'],
    traditions: ['Allgemein-Schamanenritus'],
    increaseFactor: IncreaseFactor.B,
    url: 'https://dsa.ulisses-regelwiki.de/liturgie.html?liturgie=Tierbeherrschung',
    sources: [
      { book: 'Aventurisches Götterwirken II', page: 95 },
      { book: 'Divinarium Liturgia', page: 189 },
    ],
  },
  {
    name: 'tiereBeruhigen',
    label: 'Tiere beruhigen',
    check: ['MU', 'IN', 'CH'],
    traditions: ['Allgemein-Schamanenritus', 'Firun (Jagd)', 'Ifirn (Natur)', 'Peraine (Landwirtschaft)'],
    increaseFactor: IncreaseFactor.A,
    url: 'https://dsa.ulisses-regelwiki.de/liturgie.html?liturgie=Tiere+beruhigen',
    sources: [
      { book: 'Aventurisches Götterwirken', page: 160 },
      { book: 'Aventurisches Götterwirken II', page: 75 },
      { book: 'Divinarium Liturgia', page: 190 },
    ],
  },
  {
    name: 'tierleidLindern',
    label: 'Tierleid lindern',
    check: ['MU', 'IN', 'CH'],
    traditions: ['Ifirn (Hilfsbereitschaft)', 'Peraine (Heilung)'],
    increaseFactor: IncreaseFactor.A,
    url: 'https://dsa.ulisses-regelwiki.de/liturgie.html?liturgie=Tierleid+lindern',
    sources: [
      { book: 'Aventurisches Götterwirken', page: 160 },
      { book: 'Divinarium Liturgia', page: 191 },
    ],
  },
  {
    name: 'tiersprache',
    label: 'Tiersprache',
    check: ['MU', 'IN', 'CH'],
    traditions: ['Allgemein-Schamanenritus', 'Firun (Jagd)', 'Ifirn (Natur)'],
    increaseFactor: IncreaseFactor.B,
    url: 'https://dsa.ulisses-regelwiki.de/liturgie.html?liturgie=Tiersprache',
    sources: [
      { book: 'Aventurisches Götterwirken', page: 160 },
      { book: 'Aventurisches Götterwirken II', page: 75 },
      { book: 'Divinarium Liturgia', page: 192 },
    ],
  },
  {
    name: 'trankfluch',
    label: 'Trankfluch',
    check: ['KL', 'IN', 'CH'],
    traditions: ['Namenloser'],
    increaseFactor: IncreaseFactor.B,
    url: 'https://dsa.ulisses-regelwiki.de/liturgie.html?liturgie=Trankfluch',
    sources: [
      { book: 'Aventurisches Götterwirken', page: 161 },
      { book: 'Divinarium Liturgia', page: 193 },
    ],
  },
  {
    name: 'treuerBegleiter',
    label: 'Treuer Begleiter',
    check: ['MU', 'KL', 'IN'],
    traditions: ['Allgemein-Schamanenritus', 'Firun (Jagd)', 'Ifirn (Natur)'],
    increaseFactor: IncreaseFactor.A,
    url: 'https://dsa.ulisses-regelwiki.de/liturgie.html?liturgie=Treuer+Begleiter',
    sources: [
      { book: 'Aventurisches Götterwirken', page: 161 },
      { book: 'Aventurisches Götterwirken II', page: 75 },
      { book: 'Divinarium Liturgia', page: 194 },
    ],
  },

  // â”€â”€ Batch 10 (181â€“199) â”€â”€
  {
    name: 'tsasGedankenspiel',
    label: 'Tsas Gedankenspiel',
    check: ['MU', 'KL', 'IN'],
    traditions: ['Tsa (Freiheit)'],
    increaseFactor: IncreaseFactor.B,
    url: 'https://dsa.ulisses-regelwiki.de/liturgie.html?liturgie=Tsas+Gedankenspiel',
    sources: [
      { book: 'Aventurisches Götterwirken', page: 161 },
      { book: 'Divinarium Liturgia', page: 195 },
    ],
  },
  {
    name: 'unsichtbareFlut',
    label: 'Unsichtbare Flut',
    check: ['MU', 'KL', 'KO'],
    traditions: ['Numinoru (Reißender Strudel)', 'Numinoru (Unendliche Tiefe)'],
    increaseFactor: IncreaseFactor.C,
    url: 'https://dsa.ulisses-regelwiki.de/liturgie.html?liturgie=Unsichtbare+Flut',
    sources: [
      { book: 'Divinarium Liturgia', page: 196 },
      { book: 'Unendlichkeit & Tiefenrausch', page: 20 },
    ],
  },
  {
    name: 'unterwasseratmung',
    label: 'Unterwasseratmung',
    check: ['MU', 'IN', 'KO'],
    traditions: ['Efferd (Wogen)', 'Numinoru (Unendliche Tiefe)', 'Swafnir (Kraft)'],
    increaseFactor: IncreaseFactor.B,
    url: 'https://dsa.ulisses-regelwiki.de/liturgie.html?liturgie=Unterwasseratmung',
    sources: [
      { book: 'Regelwerk', page: 332 },
      { book: 'Aventurisches Götterwirken', page: 169 },
      { book: 'Divinarium Liturgia', page: 197 },
      { book: 'Unendlichkeit & Tiefenrausch', page: 20 },
    ],
  },
  {
    name: 'untotenerhebung',
    label: 'Untotenerhebung',
    check: ['MU', 'KL', 'CH'],
    traditions: ['Tairachschamanen (Geisterwelt)'],
    increaseFactor: IncreaseFactor.B,
    url: 'https://dsa.ulisses-regelwiki.de/liturgie.html?liturgie=Untotenerhebung',
    sources: [
      { book: 'Bündnis der Wacht (Donnerwacht II)', page: 63 },
      { book: 'Divinarium Liturgia', page: 198 },
      { book: 'Donnerwacht (Kampagne - Sammelband)', page: 142 },
      { book: 'Orks - Hauer & Schwarzer Pelz', page: 50 },
    ],
  },
  {
    name: 'vampirischeKraefte',
    label: 'Vampirische Kräfte',
    check: ['MU', 'IN', 'KO'],
    traditions: ['Marbo (Vergänglichkeit)'],
    increaseFactor: IncreaseFactor.D,
    url: 'https://dsa.ulisses-regelwiki.de/liturgie.html?liturgie=Vampirische+Kr%C3%A4fte',
    sources: [
      { book: 'Aventurisches Götterwirken II', page: 95 },
      { book: 'Divinarium Liturgia', page: 199 },
    ],
  },
  {
    name: 'verstecktesBegehren',
    label: 'Verstecktes Begehren',
    check: ['MU', 'IN', 'CH'],
    traditions: ['Levthan (Begierde)', 'Rahja (Harmonie)'],
    increaseFactor: IncreaseFactor.B,
    url: 'https://dsa.ulisses-regelwiki.de/liturgie.html?liturgie=Verstecktes+Begehren',
    sources: [
      { book: 'Aventurisches Götterwirken II', page: 95 },
      { book: 'Divinarium Liturgia', page: 200 },
      { book: 'Wege der Vereinigungen', page: 194 },
    ],
  },
  {
    name: 'versteinerung',
    label: 'Versteinerung',
    check: ['MU', 'KL', 'IN'],
    traditions: ['Angrosch (Erz)'],
    increaseFactor: IncreaseFactor.B,
    url: 'https://dsa.ulisses-regelwiki.de/liturgie.html?liturgie=Versteinerung',
    sources: [
      { book: 'Aventurisches Götterwirken', page: 161 },
      { book: 'Divinarium Liturgia', page: 201 },
    ],
  },
  {
    name: 'wahrheit',
    label: 'Wahrheit',
    check: ['MU', 'KL', 'IN'],
    traditions: ['Praios (Ordnung)'],
    increaseFactor: IncreaseFactor.C,
    url: 'https://dsa.ulisses-regelwiki.de/liturgie.html?liturgie=Wahrheit',
    sources: [
      { book: 'Aventurisches Götterwirken', page: 162 },
      { book: 'Divinarium Liturgia', page: 202 },
    ],
  },
  {
    name: 'wandWiderDaemonen',
    label: 'Wand wider Dämonen',
    check: ['MU', 'KL', 'CH'],
    traditions: ['Praios (Antimagie)'],
    increaseFactor: IncreaseFactor.B,
    url: 'https://dsa.ulisses-regelwiki.de/liturgie.html?liturgie=Wand+wider+D%C3%A4monen',
    sources: [
      { book: 'Aventurisches Götterwirken', page: 163 },
      { book: 'Divinarium Liturgia', page: 203 },
    ],
  },
  {
    name: 'wasserlauf',
    label: 'Wasserlauf',
    check: ['MU', 'IN', 'GE'],
    traditions: ['Efferd (Wogen)'],
    increaseFactor: IncreaseFactor.B,
    url: 'https://dsa.ulisses-regelwiki.de/liturgie.html?liturgie=Wasserlauf',
    sources: [
      { book: 'Regelwerk', page: 332 },
      { book: 'Aventurisches Götterwirken', page: 169 },
      { book: 'Divinarium Liturgia', page: 204 },
    ],
  },
  {
    name: 'weiheDesBodens',
    label: 'Weihe des Bodens',
    check: ['MU', 'IN', 'CH'],
    traditions: ['Boron (Tod)'],
    increaseFactor: IncreaseFactor.B,
    url: 'https://dsa.ulisses-regelwiki.de/liturgie.html?liturgie=Weihe+des+Bodens',
    sources: [
      { book: 'Aventurisches Götterwirken', page: 163 },
      { book: 'Divinarium Liturgia', page: 205 },
    ],
  },
  {
    name: 'wieselflink',
    label: 'Wieselflink',
    check: ['IN', 'IN', 'GE'],
    traditions: ['Phex (Schatten)'],
    increaseFactor: IncreaseFactor.B,
    url: 'https://dsa.ulisses-regelwiki.de/liturgie.html?liturgie=Wieselflink',
    sources: [
      { book: 'Aventurisches Götterwirken', page: 163 },
      { book: 'Divinarium Liturgia', page: 206 },
    ],
  },
  {
    name: 'windhose',
    label: 'Windhose',
    check: ['MU', 'CH', 'KO'],
    traditions: ['Efferd (Wind)', 'Swafnir (Kraft)'],
    increaseFactor: IncreaseFactor.C,
    url: 'https://dsa.ulisses-regelwiki.de/liturgie.html?liturgie=Windhose',
    sources: [
      { book: 'Regelwerk', page: 332 },
      { book: 'Aventurisches Götterwirken', page: 169 },
      { book: 'Divinarium Liturgia', page: 207 },
    ],
  },
  {
    name: 'windruf',
    label: 'Windruf',
    check: ['MU', 'IN', 'CH'],
    traditions: ['Efferd (Wind)'],
    increaseFactor: IncreaseFactor.B,
    url: 'https://dsa.ulisses-regelwiki.de/liturgie.html?liturgie=Windruf',
    sources: [
      { book: 'Aventurisches Götterwirken', page: 163 },
      { book: 'Divinarium Liturgia', page: 208 },
    ],
  },
  {
    name: 'wolfsruf',
    label: 'Wolfsruf',
    check: ['MU', 'IN', 'CH'],
    traditions: ['Firun (Jagd)'],
    increaseFactor: IncreaseFactor.B,
    url: 'https://dsa.ulisses-regelwiki.de/liturgie.html?liturgie=Wolfsruf',
    sources: [
      { book: 'Aventurisches Götterwirken', page: 164 },
      { book: 'Divinarium Liturgia', page: 209 },
    ],
  },
  {
    name: 'wundersameVerstaendigung',
    label: 'Wundersame Verständigung',
    check: ['KL', 'KL', 'IN'],
    traditions: ['Nandus (Bildung)'],
    increaseFactor: IncreaseFactor.B,
    url: 'https://dsa.ulisses-regelwiki.de/liturgie.html?liturgie=Wundersame+Verst%C3%A4ndigung',
    sources: [
      { book: 'Aventurisches Götterwirken', page: 164 },
      { book: 'Divinarium Liturgia', page: 210 },
    ],
  },
  {
    name: 'zaeheHaut',
    label: 'Zähe Haut',
    check: ['MU', 'IN', 'KO'],
    traditions: ['Allgemein-Schamanenritus'],
    increaseFactor: IncreaseFactor.B,
    url: 'https://dsa.ulisses-regelwiki.de/liturgie.html?liturgie=Z%C3%A4he+Haut',
    sources: [
      { book: 'Aventurisches Götterwirken II', page: 96 },
      { book: 'Divinarium Liturgia', page: 211 },
    ],
  },
  {
    name: 'zauberschutz',
    label: 'Zauberschutz',
    check: ['MU', 'KL', 'CH'],
    traditions: ['Hesinde (Magie)'],
    increaseFactor: IncreaseFactor.D,
    url: 'https://dsa.ulisses-regelwiki.de/liturgie.html?liturgie=Zauberschutz',
    sources: [
      { book: 'Aventurisches Götterwirken', page: 164 },
      { book: 'Divinarium Liturgia', page: 212 },
    ],
  },
  {
    name: 'zwergenmacht',
    label: 'Zwergenmacht',
    check: ['MU', 'IN', 'KO'],
    traditions: ['Angrosch (Erz)', 'Angrosch (Flammen)'],
    increaseFactor: IncreaseFactor.B,
    url: 'https://dsa.ulisses-regelwiki.de/liturgie.html?liturgie=Zwergenmacht',
    sources: [
      { book: 'Aventurisches Götterwirken', page: 164 },
      { book: 'Divinarium Liturgia', page: 213 },
    ],
  },
];
