import { Ritual, SpellCheck, SpellTrait, IncreaseFactor } from '../models/magic.model';

// ─── Rituale (Rituals) ───────────────────────────────────────────────────────
// Source: DSA 5 Regelwiki – https://dsa.ulisses-regelwiki.de/ritualauswahl.html
// Total: 74 rituals, alphabetically ordered

export const ALL_RITUALS: Ritual[] = [
  {
    name: 'accuratum',
    label: 'Accuratum',
    check: ['KL', 'CH', 'FF'] as SpellCheck,
    trait: SpellTrait.Objekt,
    traditions: ['Scharlatane'],
    increaseFactor: IncreaseFactor.A,
  },
  {
    name: 'adamantium',
    label: 'Adamantium',
    check: ['KL', 'IN', 'KO'] as SpellCheck,
    trait: SpellTrait.Elementar,
    traditions: ['Druiden', 'Gildenmagier', 'Kristallomanten'],
    increaseFactor: IncreaseFactor.A,
  },
  {
    name: 'animatio',
    label: 'Animatio',
    check: ['KL', 'IN', 'GE'] as SpellCheck,
    trait: SpellTrait.Telekinese,
    traditions: ['Gildenmagier'],
    increaseFactor: IncreaseFactor.B,
  },
  {
    name: 'applicatus',
    label: 'Applicatus',
    check: ['KL', 'IN', 'FF'] as SpellCheck,
    trait: SpellTrait.Objekt,
    traditions: ['Allgemein'],
    increaseFactor: IncreaseFactor.B,
  },
  {
    name: 'arcanovi',
    label: 'Arcanovi',
    check: ['KL', 'IN', 'FF'] as SpellCheck,
    trait: SpellTrait.Objekt,
    traditions: ['Allgemein'],
    increaseFactor: IncreaseFactor.D,
  },
  {
    name: 'aurumArgentor',
    label: 'Aurum Argentor',
    check: ['KL', 'IN', 'KO'] as SpellCheck,
    trait: SpellTrait.Objekt,
    traditions: ['Gildenmagier'],
    increaseFactor: IncreaseFactor.C,
  },
  {
    name: 'bandDerFreundschaft',
    label: 'Band der Freundschaft',
    check: ['IN', 'CH', 'CH'] as SpellCheck,
    trait: SpellTrait.Einfluss,
    traditions: ['Elfen'],
    increaseFactor: IncreaseFactor.C,
  },
  {
    name: 'baerenruhe',
    label: 'Bärenruhe',
    check: ['MU', 'IN', 'KO'] as SpellCheck,
    trait: SpellTrait.Verwandlung,
    traditions: ['Elfen', 'Geoden', 'Goblinzauberinnen', 'Kristallomanten'],
    increaseFactor: IncreaseFactor.B,
  },
  {
    name: 'blickDurchFremdeAugen',
    label: 'Blick durch fremde Augen',
    check: ['MU', 'IN', 'CH'] as SpellCheck,
    trait: SpellTrait.Hellsicht,
    traditions: ['Druiden', 'Hexen'],
    increaseFactor: IncreaseFactor.C,
  },
  {
    name: 'blickInDieVergangenheit',
    label: 'Blick in die Vergangenheit',
    check: ['MU', 'KL', 'IN'] as SpellCheck,
    trait: SpellTrait.Hellsicht,
    traditions: ['Druiden', 'Geoden', 'Gildenmagier', 'Goblinzauberinnen', 'Kristallomanten'],
    increaseFactor: IncreaseFactor.C,
  },
  {
    name: 'brandform',
    label: 'Brandform',
    check: ['KL', 'FF', 'KK'] as SpellCheck,
    trait: SpellTrait.Elementar,
    traditions: ['Elfen'],
    increaseFactor: IncreaseFactor.B,
  },
  {
    name: 'caldofrigo',
    label: 'Caldofrigo',
    check: ['IN', 'CH', 'KO'] as SpellCheck,
    trait: SpellTrait.Elementar,
    traditions: ['Druiden', 'Gildenmagier', 'Kristallomanten'],
    increaseFactor: IncreaseFactor.B,
  },
  {
    name: 'chimaeroform',
    label: 'Chimaeroform',
    check: ['KL', 'IN', 'KO'] as SpellCheck,
    trait: SpellTrait.Daemonisch,
    traditions: ['Gildenmagier', 'Hexen'],
    increaseFactor: IncreaseFactor.C,
  },
  {
    name: 'chronoklassis',
    label: 'Chronoklassis',
    check: ['KL', 'IN', 'KO'] as SpellCheck,
    trait: SpellTrait.Temporal,
    traditions: ['Druiden', 'Elfen', 'Gildenmagier', 'Hexen', 'Kristallomanten'],
    increaseFactor: IncreaseFactor.D,
  },
  {
    name: 'chrononautos',
    label: 'Chrononautos',
    check: ['MU', 'CH', 'KO'] as SpellCheck,
    trait: SpellTrait.Temporal,
    traditions: ['Druiden', 'Elfen', 'Gildenmagier', 'Hexen', 'Kristallomanten'],
    increaseFactor: IncreaseFactor.D,
  },
  {
    name: 'custodosigil',
    label: 'Custodosigil',
    check: ['MU', 'KL', 'FF'] as SpellCheck,
    trait: SpellTrait.Objekt,
    traditions: ['Gildenmagier'],
    increaseFactor: IncreaseFactor.A,
  },
  {
    name: 'daemonenpaktBeenden',
    label: 'Dämonenpakt beenden',
    check: ['MU', 'IN', 'CH'] as SpellCheck,
    trait: SpellTrait.Antimagie,
    traditions: ['Druiden', 'Geoden', 'Gildenmagier', 'Hexen'],
    increaseFactor: IncreaseFactor.C,
  },
  {
    name: 'destructibo',
    label: 'Destructibo',
    check: ['KL', 'KL', 'FF'] as SpellCheck,
    trait: SpellTrait.Objekt,
    traditions: ['Allgemein'],
    increaseFactor: IncreaseFactor.C,
  },
  {
    name: 'dschinnenruf',
    label: 'Dschinnenruf',
    check: ['MU', 'CH', 'KO'] as SpellCheck,
    trait: SpellTrait.Sphaeren,
    traditions: ['Druiden', 'Geoden', 'Gildenmagier', 'Nachtalben'],
    increaseFactor: IncreaseFactor.C,
  },
  {
    name: 'einsMitDerNatur',
    label: 'Eins mit der Natur',
    check: ['MU', 'IN', 'KO'] as SpellCheck,
    trait: SpellTrait.Heilung,
    traditions: ['Druiden', 'Elfen', 'Geoden', 'Goblinzauberinnen'],
    increaseFactor: IncreaseFactor.B,
  },
  {
    name: 'elementarerDiener',
    label: 'Elementarer Diener',
    check: ['MU', 'CH', 'KO'] as SpellCheck,
    trait: SpellTrait.Sphaeren,
    traditions: ['Druiden', 'Geoden', 'Gildenmagier', 'Nachtalben'],
    increaseFactor: IncreaseFactor.B,
  },
  {
    name: 'ergebenheitDerWogen',
    label: 'Ergebenheit der Wogen',
    check: ['MU', 'IN', 'KO'] as SpellCheck,
    trait: SpellTrait.Elementar,
    traditions: ['Elfen'],
    increaseFactor: IncreaseFactor.C,
  },
  {
    name: 'erhabenheitDesMarmors',
    label: 'Erhabenheit des Marmors',
    check: ['MU', 'IN', 'KO'] as SpellCheck,
    trait: SpellTrait.Elementar,
    traditions: ['Geoden', 'Gildenmagier', 'Hexen'],
    increaseFactor: IncreaseFactor.C,
  },
  {
    name: 'felsenform',
    label: 'Felsenform',
    check: ['KL', 'FF', 'KK'] as SpellCheck,
    trait: SpellTrait.Elementar,
    traditions: ['Elfen', 'Kristallomanten'],
    increaseFactor: IncreaseFactor.D,
  },
  {
    name: 'freiheitDerWolken',
    label: 'Freiheit der Wolken',
    check: ['MU', 'IN', 'KO'] as SpellCheck,
    trait: SpellTrait.Elementar,
    traditions: ['Elfen'],
    increaseFactor: IncreaseFactor.C,
  },
  {
    name: 'gefaessDerJahre',
    label: 'Gefäß der Jahre',
    check: ['MU', 'KL', 'KO'] as SpellCheck,
    trait: SpellTrait.Temporal,
    traditions: ['Gildenmagier'],
    increaseFactor: IncreaseFactor.D,
  },
  {
    name: 'geisterbeschwoeung',
    label: 'Geisterbeschwörung',
    check: ['MU', 'CH', 'KO'] as SpellCheck,
    trait: SpellTrait.Sphaeren,
    traditions: ['Druiden', 'Geoden', 'Gildenmagier', 'Goblinzauberinnen', 'Hexen'],
    increaseFactor: IncreaseFactor.C,
  },
  {
    name: 'geisterruf',
    label: 'Geisterruf',
    check: ['MU', 'CH', 'KO'] as SpellCheck,
    trait: SpellTrait.Sphaeren,
    traditions: ['Druiden', 'Geoden', 'Gildenmagier', 'Goblinzauberinnen', 'Hexen'],
    increaseFactor: IncreaseFactor.B,
  },
  {
    name: 'gletscherform',
    label: 'Gletscherform',
    check: ['KL', 'FF', 'KK'] as SpellCheck,
    trait: SpellTrait.Elementar,
    traditions: ['Elfen', 'Nachtalben'],
    increaseFactor: IncreaseFactor.C,
  },
  {
    name: 'hagelschlagUndSturmgebruell',
    label: 'Hagelschlag und Sturmgebrüll',
    check: ['MU', 'CH', 'KO'] as SpellCheck,
    trait: SpellTrait.Elementar,
    traditions: ['Druiden', 'Geoden', 'Goblinzauberinnen'],
    increaseFactor: IncreaseFactor.D,
  },
  {
    name: 'hartesSchmelze',
    label: 'Hartes schmelze',
    check: ['MU', 'IN', 'KO'] as SpellCheck,
    trait: SpellTrait.Elementar,
    traditions: ['Borbaradianer', 'Gildenmagier'],
    increaseFactor: IncreaseFactor.B,
  },
  {
    name: 'immortalisLebenszeit',
    label: 'Immortalis Lebenszeit',
    check: ['MU', 'CH', 'KO'] as SpellCheck,
    trait: SpellTrait.Temporal,
    traditions: ['Gildenmagier', 'Hexen'],
    increaseFactor: IncreaseFactor.D,
  },
  {
    name: 'infinitumImmerdar',
    label: 'Infinitum Immerdar',
    check: ['KL', 'CH', 'KO'] as SpellCheck,
    trait: SpellTrait.Temporal,
    traditions: ['Druiden', 'Elfen', 'Geoden', 'Gildenmagier', 'Hexen', 'Kristallomanten'],
    increaseFactor: IncreaseFactor.D,
  },
  {
    name: 'invocatioMaior',
    label: 'Invocatio Maior',
    check: ['MU', 'CH', 'KO'] as SpellCheck,
    trait: SpellTrait.Sphaeren,
    traditions: ['Borbaradianer', 'Gildenmagier', 'Hexen', 'Nachtalben'],
    increaseFactor: IncreaseFactor.C,
  },
  {
    name: 'invocatioMaxima',
    label: 'Invocatio Maxima',
    check: ['MU', 'CH', 'KO'] as SpellCheck,
    trait: SpellTrait.Sphaeren,
    traditions: ['Borbaradianer', 'Gildenmagier', 'Hexen'],
    increaseFactor: IncreaseFactor.D,
  },
  {
    name: 'invocatioMinor',
    label: 'Invocatio Minor',
    check: ['MU', 'CH', 'KO'] as SpellCheck,
    trait: SpellTrait.Sphaeren,
    traditions: ['Borbaradianer', 'Gildenmagier', 'Hexen', 'Nachtalben'],
    increaseFactor: IncreaseFactor.B,
  },
  {
    name: 'klarheitDesEises',
    label: 'Klarheit des Eises',
    check: ['MU', 'IN', 'KO'] as SpellCheck,
    trait: SpellTrait.Elementar,
    traditions: ['Elfen'],
    increaseFactor: IncreaseFactor.C,
  },
  {
    name: 'koerperloseReise',
    label: 'Körperlose Reise',
    check: ['MU', 'KL', 'IN'] as SpellCheck,
    trait: SpellTrait.Sphaeren,
    traditions: ['Druiden', 'Gildenmagier'],
    increaseFactor: IncreaseFactor.C,
  },
  {
    name: 'lawinenfallUndTruemmerfeld',
    label: 'Lawinenfall und Trümmerfeld',
    check: ['MU', 'CH', 'KO'] as SpellCheck,
    trait: SpellTrait.Elementar,
    traditions: ['Geoden'],
    increaseFactor: IncreaseFactor.D,
  },
  {
    name: 'leidensbund',
    label: 'Leidensbund',
    check: ['MU', 'IN', 'KO'] as SpellCheck,
    trait: SpellTrait.Heilung,
    traditions: ['Gildenmagier', 'Goblinzauberinnen', 'Kristallomanten'],
    increaseFactor: IncreaseFactor.A,
  },
  {
    name: 'madasSpiegel',
    label: 'Madas Spiegel',
    check: ['MU', 'KL', 'IN'] as SpellCheck,
    trait: SpellTrait.Hellsicht,
    traditions: ['Hexen'],
    increaseFactor: IncreaseFactor.B,
  },
  {
    name: 'magischerRaub',
    label: 'Magischer Raub',
    check: ['MU', 'KL', 'KO'] as SpellCheck,
    trait: SpellTrait.Einfluss,
    traditions: ['Druiden', 'Geoden', 'Gildenmagier', 'Kristallomanten'],
    increaseFactor: IncreaseFactor.B,
  },
  {
    name: 'meisterDerElemente',
    label: 'Meister der Elemente',
    check: ['MU', 'CH', 'KO'] as SpellCheck,
    trait: SpellTrait.Sphaeren,
    traditions: ['Druiden', 'Geoden', 'Gildenmagier'],
    increaseFactor: IncreaseFactor.D,
  },
  {
    name: 'memorabiaFalsifir',
    label: 'Memorabia Falsifir',
    check: ['KL', 'IN', 'CH'] as SpellCheck,
    trait: SpellTrait.Einfluss,
    traditions: ['Druiden', 'Gildenmagier'],
    increaseFactor: IncreaseFactor.C,
  },
  {
    name: 'movimento',
    label: 'Movimento',
    check: ['MU', 'IN', 'KO'] as SpellCheck,
    trait: SpellTrait.Heilung,
    traditions: ['Elfen'],
    increaseFactor: IncreaseFactor.A,
  },
  {
    name: 'nekropathia',
    label: 'Nekropathia',
    check: ['MU', 'KL', 'CH'] as SpellCheck,
    trait: SpellTrait.Sphaeren,
    traditions: ['Geoden', 'Gildenmagier', 'Hexen'],
    increaseFactor: IncreaseFactor.C,
  },
  {
    name: 'nihilogravo',
    label: 'Nihilogravo',
    check: ['KL', 'IN', 'KO'] as SpellCheck,
    trait: SpellTrait.Telekinese,
    traditions: ['Gildenmagier'],
    increaseFactor: IncreaseFactor.B,
  },
  {
    name: 'pflanzenform',
    label: 'Pflanzenform',
    check: ['KL', 'FF', 'KK'] as SpellCheck,
    trait: SpellTrait.Elementar,
    traditions: ['Elfen', 'Kristallomanten'],
    increaseFactor: IncreaseFactor.C,
  },
  {
    name: 'planastrale',
    label: 'Planastrale',
    check: ['MU', 'IN', 'KO'] as SpellCheck,
    trait: SpellTrait.Sphaeren,
    traditions: ['Gildenmagier'],
    increaseFactor: IncreaseFactor.D,
  },
  {
    name: 'reinheitDerLohe',
    label: 'Reinheit der Lohe',
    check: ['MU', 'IN', 'KO'] as SpellCheck,
    trait: SpellTrait.Elementar,
    traditions: ['Elfen'],
    increaseFactor: IncreaseFactor.C,
  },
  {
    name: 'riesengestalt',
    label: 'Riesengestalt',
    check: ['KL', 'FF', 'KO'] as SpellCheck,
    trait: SpellTrait.Verwandlung,
    traditions: ['Druiden', 'Gildenmagier'],
    increaseFactor: IncreaseFactor.D,
  },
  {
    name: 'rufDerFeenwesen',
    label: 'Ruf der Feenwesen',
    check: ['MU', 'CH', 'KO'] as SpellCheck,
    trait: SpellTrait.Sphaeren,
    traditions: ['Elfen'],
    increaseFactor: IncreaseFactor.C,
  },
  {
    name: 'ruheKoerper',
    label: 'Ruhe Körper',
    check: ['KL', 'CH', 'KO'] as SpellCheck,
    trait: SpellTrait.Heilung,
    traditions: ['Elfen', 'Gildenmagier', 'Goblinzauberinnen', 'Kristallomanten'],
    increaseFactor: IncreaseFactor.B,
  },
  {
    name: 'seelenwanderung',
    label: 'Seelenwanderung',
    check: ['MU', 'CH', 'KO'] as SpellCheck,
    trait: SpellTrait.Daemonisch,
    traditions: ['Druiden', 'Gildenmagier', 'Hexen', 'Kristallomanten'],
    increaseFactor: IncreaseFactor.D,
  },
  {
    name: 'standhafterWaechter',
    label: 'Standhafter Wächter',
    check: ['MU', 'IN', 'GE'] as SpellCheck,
    trait: SpellTrait.Heilung,
    traditions: ['Elfen'],
    increaseFactor: IncreaseFactor.B,
  },
  {
    name: 'staubWandle',
    label: 'Staub wandle',
    check: ['MU', 'KL', 'CH'] as SpellCheck,
    trait: SpellTrait.Elementar,
    traditions: ['Gildenmagier'],
    increaseFactor: IncreaseFactor.C,
  },
  {
    name: 'steinWandle',
    label: 'Stein wandle',
    check: ['MU', 'KL', 'CH'] as SpellCheck,
    trait: SpellTrait.Daemonisch,
    traditions: ['Borbaradianer', 'Gildenmagier'],
    increaseFactor: IncreaseFactor.C,
  },
  {
    name: 'totesHandle',
    label: 'Totes handle',
    check: ['MU', 'KL', 'CH'] as SpellCheck,
    trait: SpellTrait.Daemonisch,
    traditions: ['Borbaradianer', 'Gildenmagier', 'Kristallomanten'],
    increaseFactor: IncreaseFactor.C,
  },
  {
    name: 'transformatio',
    label: 'Transformatio',
    check: ['KL', 'KO', 'FF'] as SpellCheck,
    trait: SpellTrait.Objekt,
    traditions: ['Geoden', 'Gildenmagier', 'Kristallomanten'],
    increaseFactor: IncreaseFactor.D,
  },
  {
    name: 'transmutare',
    label: 'Transmutare',
    check: ['IN', 'CH', 'KO'] as SpellCheck,
    trait: SpellTrait.Verwandlung,
    traditions: ['Hexen'],
    increaseFactor: IncreaseFactor.C,
  },
  {
    name: 'traumgestalt',
    label: 'Traumgestalt',
    check: ['MU', 'IN', 'CH'] as SpellCheck,
    trait: SpellTrait.Einfluss,
    traditions: ['Druiden', 'Elfen', 'Geoden', 'Goblinzauberinnen', 'Hexen'],
    increaseFactor: IncreaseFactor.C,
  },
  {
    name: 'ueberlegenerKrieger',
    label: 'Überlegener Krieger',
    check: ['MU', 'IN', 'GE'] as SpellCheck,
    trait: SpellTrait.Heilung,
    traditions: ['Elfen'],
    increaseFactor: IncreaseFactor.B,
  },
  {
    name: 'unberuehrtVonSatinav',
    label: 'Unberührt von Satinav',
    check: ['KL', 'IN', 'FF'] as SpellCheck,
    trait: SpellTrait.Temporal,
    traditions: ['Elfen', 'Kristallomanten'],
    increaseFactor: IncreaseFactor.B,
  },
  {
    name: 'weichesErstarre',
    label: 'Weiches erstarre',
    check: ['MU', 'KL', 'KK'] as SpellCheck,
    trait: SpellTrait.Objekt,
    traditions: ['Borbaradianer', 'Gildenmagier'],
    increaseFactor: IncreaseFactor.B,
  },
  {
    name: 'weisheitDerBaeume',
    label: 'Weisheit der Bäume',
    check: ['MU', 'IN', 'KO'] as SpellCheck,
    trait: SpellTrait.Elementar,
    traditions: ['Druiden', 'Elfen', 'Geoden', 'Hexen'],
    increaseFactor: IncreaseFactor.C,
  },
  {
    name: 'widerwille',
    label: 'Widerwille',
    check: ['IN', 'CH', 'GE'] as SpellCheck,
    trait: SpellTrait.Einfluss,
    traditions: ['Gildenmagier', 'Scharlatane'],
    increaseFactor: IncreaseFactor.B,
  },
  {
    name: 'wirbelform',
    label: 'Wirbelform',
    check: ['KL', 'FF', 'KK'] as SpellCheck,
    trait: SpellTrait.Elementar,
    traditions: ['Elfen'],
    increaseFactor: IncreaseFactor.B,
  },
  {
    name: 'wogenform',
    label: 'Wogenform',
    check: ['KL', 'FF', 'KK'] as SpellCheck,
    trait: SpellTrait.Elementar,
    traditions: ['Druiden', 'Elfen', 'Gildenmagier', 'Kristallomanten'],
    increaseFactor: IncreaseFactor.B,
  },
  {
    name: 'xenographus',
    label: 'Xenographus',
    check: ['MU', 'KL', 'IN'] as SpellCheck,
    trait: SpellTrait.Hellsicht,
    traditions: ['Gildenmagier', 'Scharlatane'],
    increaseFactor: IncreaseFactor.A,
  },
  {
    name: 'zauberklingeGeisterspeer',
    label: 'Zauberklinge Geisterspeer',
    check: ['KL', 'IN', 'FF'] as SpellCheck,
    trait: SpellTrait.Objekt,
    traditions: ['Allgemein'],
    increaseFactor: IncreaseFactor.C,
  },
  {
    name: 'zaubernahrung',
    label: 'Zaubernahrung',
    check: ['MU', 'IN', 'KO'] as SpellCheck,
    trait: SpellTrait.Heilung,
    traditions: ['Elfen'],
    increaseFactor: IncreaseFactor.B,
  },
  {
    name: 'zauberschnurren',
    label: 'Zauberschnurren',
    check: ['MU', 'IN', 'CH'] as SpellCheck,
    trait: SpellTrait.Heilung,
    traditions: ['Goblinzauberinnen', 'Hexen'],
    increaseFactor: IncreaseFactor.C,
  },
  {
    name: 'zauberwesenDerNatur',
    label: 'Zauberwesen der Natur',
    check: ['MU', 'CH', 'KO'] as SpellCheck,
    trait: SpellTrait.Sphaeren,
    traditions: ['Elfen'],
    increaseFactor: IncreaseFactor.B,
  },
  {
    name: 'zauberzwang',
    label: 'Zauberzwang',
    check: ['MU', 'KL', 'CH'] as SpellCheck,
    trait: SpellTrait.Einfluss,
    traditions: ['Hexen', 'Kristallomanten'],
    increaseFactor: IncreaseFactor.C,
  },
];
