import { SpecialAbility, SpecialAbilityCategory } from '../models/special-ability.model';

// â”€â”€â”€ Profane Sonderfertigkeiten â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
// Source: DSA 5 Regelwiki â€“ Profane Sonderfertigkeiten
// Cost = 0 means AP cost not yet populated (expansion book content)
// Parameterized SF use naming: {baseName}_{qualifier}

// â”€â”€â”€ Allgemeine Sonderfertigkeiten â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
export const GENERAL_SPECIAL_ABILITIES: SpecialAbility[] = [
  // â”€â”€ Regelwerk â”€â”€
  {
    name: 'abrollen',
    label: 'Abrollen',
    cost: 8,
    category: SpecialAbilityCategory.General,
    prerequisite: [{ name: 'korperbeherrschung', required: true, minLvl: 4 }],
    url: 'https://dsa.ulisses-regelwiki.de/sf_Abrollen.html',
  },
  {
    name: 'analytiker',
    label: 'Analytiker',
    cost: 5,
    category: SpecialAbilityCategory.General,
    prerequisite: [{ name: 'magiekunde', required: true, minLvl: 4 }],
    url: 'https://dsa.ulisses-regelwiki.de/sf_Analytiker.html',
  },
  { name: 'anfuhrer', label: 'Anführer', cost: 0, category: SpecialAbilityCategory.General, prerequisite: [], url: 'https://dsa.ulisses-regelwiki.de/sf_Anfuehrer.html' },
  {
    name: 'athlet',
    label: 'Athlet',
    cost: 20,
    category: SpecialAbilityCategory.General,
    prerequisite: [
      { name: 'korperbeherrschung', required: true, minLvl: 4 },
      { name: 'kraftakt', required: true, minLvl: 4 },
      { name: 'behabig', required: false },
      { name: 'fettleibig', required: false },
    ],
    url: 'https://dsa.ulisses-regelwiki.de/sf_Athlet.html',
  },
  {
    name: 'bauchreden',
    label: 'Bauchreden',
    cost: 5,
    category: SpecialAbilityCategory.General,
    prerequisite: [
      { name: 'gaukeleien', required: true, minLvl: 8 },
      { name: 'korperbeherrschung', required: true, minLvl: 4 },
    ],
    url: 'https://dsa.ulisses-regelwiki.de/sf_Bauchreden.html',
  },
  {
    name: 'drohgebarden',
    label: 'Drohgebärden',
    cost: 10,
    category: SpecialAbilityCategory.General,
    prerequisite: [{ name: 'einschuchtern', required: true, minLvl: 4 }],
    url: 'https://dsa.ulisses-regelwiki.de/sf_Drohgebaerden.html',
  },
  {
    name: 'eisernerWille',
    label: 'Eiserner Wille I-II',
    cost: 15,
    category: SpecialAbilityCategory.General,
    lvl: 1,
    maxLvl: 2,
    prerequisite: [],
    url: 'https://dsa.ulisses-regelwiki.de/sf_Eiserner_Wille_I-II.html',
  },
  {
    name: 'entfesselungskunstler',
    label: 'Entfesselungskünstler',
    cost: 8,
    category: SpecialAbilityCategory.General,
    prerequisite: [{ name: 'korperbeherrschung', required: true, minLvl: 10 }],
    url: 'https://dsa.ulisses-regelwiki.de/sf_Entfesselungskuenstler.html',
  },
  {
    name: 'falschspielen',
    label: 'Falschspielen',
    cost: 5,
    category: SpecialAbilityCategory.General,
    prerequisite: [{ name: 'brettUndGlucksspiel', required: true, minLvl: 8 }],
    url: 'https://dsa.ulisses-regelwiki.de/sf_Falschspielen.html',
  },
  {
    name: 'fertigkeitsspezialisierung',
    label: 'Fertigkeitsspezialisierung (Talente)',
    cost: 1,
    category: SpecialAbilityCategory.General,
    prerequisite: [],
    url: 'https://dsa.ulisses-regelwiki.de/sf_Fertigkeitsspezialisierung_Talente.html',
  },
  {
    name: 'freiklettern',
    label: 'Freiklettern',
    cost: 6,
    category: SpecialAbilityCategory.General,
    prerequisite: [{ name: 'klettern', required: true, minLvl: 8 }],
    url: 'https://dsa.ulisses-regelwiki.de/sf_Freiklettern.html',
  },
  { name: 'fuchsisch', label: 'Füchsisch', cost: 0, category: SpecialAbilityCategory.General, prerequisite: [], url: 'https://dsa.ulisses-regelwiki.de/sf_Fuechsisch.html' },
  { name: 'gelandekunde', label: 'Geländekunde', cost: 15, category: SpecialAbilityCategory.General, prerequisite: [], url: 'https://dsa.ulisses-regelwiki.de/sf_Gelaendekunde.html' },
  {
    name: 'geruchtekoch',
    label: 'Gerüchtekoch I-III',
    cost: 0,
    category: SpecialAbilityCategory.General,
    lvl: 1,
    maxLvl: 3,
    prerequisite: [],
    url: 'https://dsa.ulisses-regelwiki.de/sf_Geruechtekoch_I-III.html',
  },
  {
    name: 'gestalterWille',
    label: 'Gestählter Wille',
    cost: 5,
    category: SpecialAbilityCategory.General,
    prerequisite: [{ name: 'willenskraft', required: true, minLvl: 8 }],
    url: 'https://dsa.ulisses-regelwiki.de/sf_Gestaelter_Wille.html',
  },
  {
    name: 'jager',
    label: 'Jäger',
    cost: 5,
    category: SpecialAbilityCategory.General,
    prerequisite: [
      { name: 'fahrtensuchen', required: true, minLvl: 4 },
      { name: 'tierkunde', required: true, minLvl: 4 },
      { name: 'verbergen', required: true, minLvl: 4 },
    ],
    url: 'https://dsa.ulisses-regelwiki.de/sf_Jaeger.html',
  },
  {
    name: 'kampftrinker',
    label: 'Kampftrinker I-IV',
    cost: 2,
    category: SpecialAbilityCategory.General,
    lvl: 1,
    maxLvl: 4,
    prerequisite: [],
    url: 'https://dsa.ulisses-regelwiki.de/sf_Kampftrinker_I-IV.html',
  },
  {
    name: 'kunstreiten',
    label: 'Kunstreiten',
    cost: 3,
    category: SpecialAbilityCategory.General,
    prerequisite: [{ name: 'reiten', required: true, minLvl: 8 }],
    url: 'https://dsa.ulisses-regelwiki.de/sf_Kunstreiten.html',
  },
  {
    name: 'lehrer',
    label: 'Lehrer I-III',
    cost: 3,
    category: SpecialAbilityCategory.General,
    lvl: 1,
    maxLvl: 3,
    prerequisite: [],
    url: 'https://dsa.ulisses-regelwiki.de/sf_Lehrer_I-III.html',
  },
  {
    name: 'lippenlesen',
    label: 'Lippenlesen',
    cost: 10,
    category: SpecialAbilityCategory.General,
    prerequisite: [
      { name: 'sinnescharfe', required: true, minLvl: 4 },
      { name: 'blind', required: false },
    ],
    url: 'https://dsa.ulisses-regelwiki.de/sf_Lippenlesen.html',
  },
  {
    name: 'navigation',
    label: 'Navigation',
    cost: 10,
    category: SpecialAbilityCategory.General,
    prerequisite: [
      { name: 'booteUndSchiffe', required: true, minLvl: 8 },
      { name: 'rechnen', required: true, minLvl: 8 },
      { name: 'sternkunde', required: true, minLvl: 8 },
    ],
    url: 'https://dsa.ulisses-regelwiki.de/sf_Navigation.html',
  },
  {
    name: 'nervenAusStahl',
    label: 'Nerven aus Stahl',
    cost: 5,
    category: SpecialAbilityCategory.General,
    prerequisite: [
      { name: 'menschenkenntnis', required: true, minLvl: 4 },
      { name: 'willenskraft', required: true, minLvl: 8 },
    ],
    url: 'https://dsa.ulisses-regelwiki.de/sf_Nerven_aus_Stahl.html',
  },
  { name: 'ortskenntnis', label: 'Ortskenntnis', cost: 2, category: SpecialAbilityCategory.General, prerequisite: [], url: 'https://dsa.ulisses-regelwiki.de/sf_Ortskenntnis.html' },
  {
    name: 'provozieren',
    label: 'Provozieren',
    cost: 12,
    category: SpecialAbilityCategory.General,
    prerequisite: [
      { name: 'einschuchtern', required: true, minLvl: 8 },
      { name: 'uberreden', required: true, minLvl: 8 },
    ],
    url: 'https://dsa.ulisses-regelwiki.de/sf_Provozieren.html',
  },
  {
    name: 'sammler',
    label: 'Sammler',
    cost: 2,
    category: SpecialAbilityCategory.General,
    prerequisite: [
      { name: 'pflanzenkunde', required: true, minLvl: 4 },
      { name: 'wildnisleben', required: true, minLvl: 4 },
    ],
    url: 'https://dsa.ulisses-regelwiki.de/sf_Sammler.html',
  },
  {
    name: 'schmerzenUnterdrucken',
    label: 'Schmerzen unterdrücken',
    cost: 20,
    category: SpecialAbilityCategory.General,
    prerequisite: [{ name: 'selbstbeherrschung', required: true, minLvl: 4 }],
    url: 'https://dsa.ulisses-regelwiki.de/sf_Schmerzen_unterdruecken.html',
  },
  {
    name: 'selbstbewusstesAuftreten',
    label: 'Selbstbewusstes Auftreten',
    cost: 10,
    category: SpecialAbilityCategory.General,
    prerequisite: [{ name: 'etikette', required: true, minLvl: 8 }],
    url: 'https://dsa.ulisses-regelwiki.de/sf_Selbstbewusstes_Auftreten.html',
  },
  {
    name: 'skifahren',
    label: 'Skifahren',
    cost: 4,
    category: SpecialAbilityCategory.General,
    prerequisite: [{ name: 'korperbeherrschung', required: true, minLvl: 4 }],
    url: 'https://dsa.ulisses-regelwiki.de/sf_Skifahren.html',
  },
  {
    name: 'tierstimmenImitieren',
    label: 'Tierstimmen imitieren',
    cost: 5,
    category: SpecialAbilityCategory.General,
    prerequisite: [{ name: 'tierkunde', required: true, minLvl: 4 }],
    url: 'https://dsa.ulisses-regelwiki.de/sf_Tierstimmen_imitieren.html',
  },
  {
    name: 'verfuhrungskunst',
    label: 'Verführungskunst',
    cost: 5,
    category: SpecialAbilityCategory.General,
    prerequisite: [
      { name: 'betoren', required: true, minLvl: 10 },
      { name: 'etikette', required: true, minLvl: 4 },
    ],
    url: 'https://dsa.ulisses-regelwiki.de/sf_Verfuehrungskunst.html',
  },
  {
    name: 'wettervorhersage',
    label: 'Wettervorhersage',
    cost: 2,
    category: SpecialAbilityCategory.General,
    prerequisite: [{ name: 'wildnisleben', required: true, minLvl: 4 }],
    url: 'https://dsa.ulisses-regelwiki.de/sf_Wettervorhersage.html',
  },
  // â”€â”€ Expansion: Weitere Allgemeine SF â”€â”€
  { name: 'abrichter', label: 'Abrichter', cost: 0, category: SpecialAbilityCategory.General, prerequisite: [], url: 'https://dsa.ulisses-regelwiki.de/sf_Abrichter.html' },
  { name: 'ackerbau', label: 'Ackerbau', cost: 0, category: SpecialAbilityCategory.General, prerequisite: [], url: 'https://dsa.ulisses-regelwiki.de/sf_Ackerbau.html' },
  {
    name: 'alchimiezirkel',
    label: 'Alchimiezirkel I-III',
    cost: 0,
    category: SpecialAbilityCategory.General,
    lvl: 1,
    maxLvl: 3,
    prerequisite: [],
    url: 'https://dsa.ulisses-regelwiki.de/sf_Alchimiezirkel_I-III.html',
  },
  {
    name: 'alchimischeAquivalenzlehre',
    label: 'Alchimistische Äquivalenzlehre',
    cost: 0,
    category: SpecialAbilityCategory.General,
    prerequisite: [],
    url: 'https://dsa.ulisses-regelwiki.de/sf_Alchimistische_Aequivalenzlehre.html',
  },
  { name: 'anpeitscher', label: 'Anpeitscher', cost: 0, category: SpecialAbilityCategory.General, prerequisite: [], url: 'https://dsa.ulisses-regelwiki.de/sf_Anpeitscher.html' },
  { name: 'architekt', label: 'Architekt', cost: 0, category: SpecialAbilityCategory.General, prerequisite: [], url: 'https://dsa.ulisses-regelwiki.de/sf_Architekt.html' },
  { name: 'archivar', label: 'Archivar', cost: 0, category: SpecialAbilityCategory.General, prerequisite: [], url: 'https://dsa.ulisses-regelwiki.de/sf_Archivar.html' },
  { name: 'bastler', label: 'Bastler', cost: 0, category: SpecialAbilityCategory.General, prerequisite: [], url: 'https://dsa.ulisses-regelwiki.de/sf_Bastler.html' },
  {
    name: 'beeindruckendeVorstellung',
    label: 'Beeindruckende Vorstellung',
    cost: 0,
    category: SpecialAbilityCategory.General,
    prerequisite: [],
    url: 'https://dsa.ulisses-regelwiki.de/sf_Beeindruckende_Vorstellung.html',
  },
  { name: 'bergbau', label: 'Bergbau', cost: 0, category: SpecialAbilityCategory.General, prerequisite: [], url: 'https://dsa.ulisses-regelwiki.de/sf_Bergbau.html' },
  {
    name: 'bernsteinErhitzen',
    label: 'Bernstein erhitzen',
    cost: 0,
    category: SpecialAbilityCategory.General,
    prerequisite: [],
    url: 'https://dsa.ulisses-regelwiki.de/sf_Bernstein_erhitzen.html',
  },
  {
    name: 'berufsgeheimnisse',
    label: 'Berufsgeheimnisse',
    cost: 0,
    category: SpecialAbilityCategory.General,
    prerequisite: [],
    url: 'https://dsa.ulisses-regelwiki.de/sf_Berufsgeheimnisse.html',
  },
  { name: 'bierbrauerei', label: 'Bierbrauerei', cost: 0, category: SpecialAbilityCategory.General, prerequisite: [], url: 'https://dsa.ulisses-regelwiki.de/sf_Bierbrauerei.html' },
  { name: 'bildhauerei', label: 'Bildhauerei', cost: 0, category: SpecialAbilityCategory.General, prerequisite: [], url: 'https://dsa.ulisses-regelwiki.de/sf_Bildhauerei.html' },
  { name: 'bineMaschores', label: 'Bine Maschores', cost: 0, category: SpecialAbilityCategory.General, prerequisite: [], url: 'https://dsa.ulisses-regelwiki.de/sf_Bine_Maschores.html' },
  { name: 'bootsbauer', label: 'Bootsbauer', cost: 0, category: SpecialAbilityCategory.General, prerequisite: [], url: 'https://dsa.ulisses-regelwiki.de/sf_Bootsbauer.html' },
  { name: 'buchdrucker', label: 'Buchdrucker', cost: 0, category: SpecialAbilityCategory.General, prerequisite: [], url: 'https://dsa.ulisses-regelwiki.de/sf_Buchdrucker.html' },
  { name: 'buchherstellung', label: 'Buchherstellung', cost: 0, category: SpecialAbilityCategory.General, prerequisite: [], url: 'https://dsa.ulisses-regelwiki.de/sf_Buchherstellung.html' },
  { name: 'deichbauer', label: 'Deichbauer', cost: 0, category: SpecialAbilityCategory.General, prerequisite: [], url: 'https://dsa.ulisses-regelwiki.de/sf_Deichbauer.html' },
  { name: 'diener', label: 'Diener', cost: 0, category: SpecialAbilityCategory.General, prerequisite: [], url: 'https://dsa.ulisses-regelwiki.de/sf_Diener.html' },
  {
    name: 'dokumentfalscher',
    label: 'Dokumentfälscher',
    cost: 0,
    category: SpecialAbilityCategory.General,
    prerequisite: [],
    url: 'https://dsa.ulisses-regelwiki.de/sf_Dokumentfaelscher.html',
  },
  {
    name: 'edelsteinschleifen',
    label: 'Edelsteinschleifen',
    cost: 0,
    category: SpecialAbilityCategory.General,
    prerequisite: [],
    url: 'https://dsa.ulisses-regelwiki.de/sf_Edelsteinschleifen.html',
  },
  { name: 'eleganeFrisur', label: 'Elegante Frisur', cost: 0, category: SpecialAbilityCategory.General, prerequisite: [], url: 'https://dsa.ulisses-regelwiki.de/sf_Elegante_Frisur.html' },
  {
    name: 'entfernungenSchatzen',
    label: 'Entfernungen schätzen',
    cost: 0,
    category: SpecialAbilityCategory.General,
    prerequisite: [],
    url: 'https://dsa.ulisses-regelwiki.de/sf_Entfernungen_schaetzen.html',
  },
  { name: 'erholsamesBad', label: 'Erholsames Bad', cost: 0, category: SpecialAbilityCategory.General, prerequisite: [], url: 'https://dsa.ulisses-regelwiki.de/sf_Erholsames_Bad.html' },
  {
    name: 'ermutigenderGesang',
    label: 'Ermutigender Gesang',
    cost: 0,
    category: SpecialAbilityCategory.General,
    prerequisite: [],
    url: 'https://dsa.ulisses-regelwiki.de/sf_Ermutigender_Gesang.html',
  },
  {
    name: 'fallenEntscharfen',
    label: 'Fallen entschärfen',
    cost: 0,
    category: SpecialAbilityCategory.General,
    prerequisite: [],
    url: 'https://dsa.ulisses-regelwiki.de/sf_Fallen_entscharfen.html',
  },
  {
    name: 'fallenWiederScharfmachen',
    label: 'Fallen wieder scharfmachen',
    cost: 0,
    category: SpecialAbilityCategory.General,
    prerequisite: [],
    url: 'https://dsa.ulisses-regelwiki.de/sf_Fallen_wieder_scharfmachen.html',
  },
  {
    name: 'fallenbaumeisterin',
    label: 'Fallenbaumeisterin',
    cost: 0,
    category: SpecialAbilityCategory.General,
    prerequisite: [],
    url: 'https://dsa.ulisses-regelwiki.de/sf_Fallenbaumeisterin.html',
  },
  { name: 'fallentarnung', label: 'Fallentarnung', cost: 0, category: SpecialAbilityCategory.General, prerequisite: [], url: 'https://dsa.ulisses-regelwiki.de/sf_Fallentarnung.html' },
  {
    name: 'faszinierender Gesang',
    label: 'Faszinierender Gesang',
    cost: 0,
    category: SpecialAbilityCategory.General,
    prerequisite: [],
    url: 'https://dsa.ulisses-regelwiki.de/sf_Faszinierender_Gesang.html',
  },
  { name: 'feuerschlucker', label: 'Feuerschlucker', cost: 0, category: SpecialAbilityCategory.General, prerequisite: [], url: 'https://dsa.ulisses-regelwiki.de/sf_Feuerschlucker.html' },
  { name: 'fischer', label: 'Fischer', cost: 0, category: SpecialAbilityCategory.General, prerequisite: [], url: 'https://dsa.ulisses-regelwiki.de/sf_Fischer.html' },
  { name: 'facherspache', label: 'Fächersprache', cost: 0, category: SpecialAbilityCategory.General, prerequisite: [], url: 'https://dsa.ulisses-regelwiki.de/sf_Faechersprache.html' },
  { name: 'galanterie', label: 'Galanterie', cost: 0, category: SpecialAbilityCategory.General, prerequisite: [], url: 'https://dsa.ulisses-regelwiki.de/sf_Galanterie.html' },
  {
    name: 'geschosshersteller',
    label: 'Geschosshersteller',
    cost: 0,
    category: SpecialAbilityCategory.General,
    prerequisite: [],
    url: 'https://dsa.ulisses-regelwiki.de/sf_Geschosshersteller.html',
  },
  {
    name: 'gespurFurHimmelsrichtungen',
    label: 'Gespür für Himmelsrichtungen',
    cost: 0,
    category: SpecialAbilityCategory.General,
    prerequisite: [],
    url: 'https://dsa.ulisses-regelwiki.de/sf_Gespur_fuer_Himmelsrichtungen.html',
  },
  {
    name: 'giftMelkenLand',
    label: 'Gift melken (Land- und Lufttiere)',
    cost: 0,
    category: SpecialAbilityCategory.General,
    prerequisite: [],
    url: 'https://dsa.ulisses-regelwiki.de/sf_Gift_melken_Landtiere.html',
  },
  {
    name: 'giftMelkenWasser',
    label: 'Gift melken (Wassertiere)',
    cost: 0,
    category: SpecialAbilityCategory.General,
    prerequisite: [],
    url: 'https://dsa.ulisses-regelwiki.de/sf_Gift_melken_Wassertiere.html',
  },
  {
    name: 'giftverstarkung',
    label: 'Giftverstärkung (Giftart)',
    cost: 0,
    category: SpecialAbilityCategory.General,
    prerequisite: [],
    url: 'https://dsa.ulisses-regelwiki.de/sf_Giftverstaerkung.html',
  },
  { name: 'gildenrecht', label: 'Gildenrecht', cost: 0, category: SpecialAbilityCategory.General, prerequisite: [], url: 'https://dsa.ulisses-regelwiki.de/sf_Gildenrecht.html' },
  { name: 'glasblaserei', label: 'Glasbläserei', cost: 0, category: SpecialAbilityCategory.General, prerequisite: [], url: 'https://dsa.ulisses-regelwiki.de/sf_Glasblaeserei.html' },
  {
    name: 'guterGardistBoserGardist',
    label: 'Guter Gardist, böser Gardist',
    cost: 0,
    category: SpecialAbilityCategory.General,
    prerequisite: [],
    url: 'https://dsa.ulisses-regelwiki.de/sf_Guter_Gardist_boeser_Gardist.html',
  },
  { name: 'hauswirtschaft', label: 'Hauswirtschaft', cost: 0, category: SpecialAbilityCategory.General, prerequisite: [], url: 'https://dsa.ulisses-regelwiki.de/sf_Hauswirtschaft.html' },
  { name: 'hehlerei', label: 'Hehlerei', cost: 0, category: SpecialAbilityCategory.General, prerequisite: [], url: 'https://dsa.ulisses-regelwiki.de/sf_Hehlerei.html' },
  {
    name: 'heilungsspezialgebiet',
    label: 'Heilungsspezialgebiet (Anwendungsgebiet)',
    cost: 0,
    category: SpecialAbilityCategory.General,
    prerequisite: [],
    url: 'https://dsa.ulisses-regelwiki.de/sf_Heilungsspezialgebiet.html',
  },
  { name: 'heraldik', label: 'Heraldik', cost: 0, category: SpecialAbilityCategory.General, prerequisite: [], url: 'https://dsa.ulisses-regelwiki.de/sf_Heraldik.html' },
  {
    name: 'heraldikspezialist',
    label: 'Heraldikspezialist',
    cost: 0,
    category: SpecialAbilityCategory.General,
    prerequisite: [],
    url: 'https://dsa.ulisses-regelwiki.de/sf_Heraldikspezialist.html',
  },
  {
    name: 'hinterhaltsspezialist',
    label: 'Hinterhaltsspezialist',
    cost: 0,
    category: SpecialAbilityCategory.General,
    prerequisite: [],
    url: 'https://dsa.ulisses-regelwiki.de/sf_Hinterhaltsspezialist.html',
  },
  { name: 'hofzeremoniell', label: 'Hofzeremoniell', cost: 0, category: SpecialAbilityCategory.General, prerequisite: [], url: 'https://dsa.ulisses-regelwiki.de/sf_Hofzeremoniell.html' },
  { name: 'holzkenntnis', label: 'Holzkenntnis', cost: 0, category: SpecialAbilityCategory.General, prerequisite: [], url: 'https://dsa.ulisses-regelwiki.de/sf_Holzkenntnis.html' },
  { name: 'iglubau', label: 'Iglubau', cost: 0, category: SpecialAbilityCategory.General, prerequisite: [], url: 'https://dsa.ulisses-regelwiki.de/sf_Iglubau.html' },
  { name: 'ingenieurin', label: 'Ingenieurin', cost: 0, category: SpecialAbilityCategory.General, prerequisite: [], url: 'https://dsa.ulisses-regelwiki.de/sf_Ingenieurin.html' },
  {
    name: 'instrumenteBauen',
    label: 'Instrumente bauen',
    cost: 0,
    category: SpecialAbilityCategory.General,
    prerequisite: [],
    url: 'https://dsa.ulisses-regelwiki.de/sf_Instrumente_bauen.html',
  },
  { name: 'kalligraphie', label: 'Kalligraphie', cost: 0, category: SpecialAbilityCategory.General, prerequisite: [], url: 'https://dsa.ulisses-regelwiki.de/sf_Kalligraphie.html' },
  { name: 'kapellmeister', label: 'Kapellmeister', cost: 0, category: SpecialAbilityCategory.General, prerequisite: [], url: 'https://dsa.ulisses-regelwiki.de/sf_Kapellmeister.html' },
  { name: 'kartographie', label: 'Kartographie', cost: 0, category: SpecialAbilityCategory.General, prerequisite: [], url: 'https://dsa.ulisses-regelwiki.de/sf_Kartographie.html' },
  { name: 'kohlezeichnungen', label: 'Kohlezeichnungen', cost: 0, category: SpecialAbilityCategory.General, prerequisite: [], url: 'https://dsa.ulisses-regelwiki.de/sf_Kohlezeichnungen.html' },
  { name: 'konditor', label: 'Konditor', cost: 0, category: SpecialAbilityCategory.General, prerequisite: [], url: 'https://dsa.ulisses-regelwiki.de/sf_Konditor.html' },
  { name: 'kristallzucht', label: 'Kristallzucht', cost: 0, category: SpecialAbilityCategory.General, prerequisite: [], url: 'https://dsa.ulisses-regelwiki.de/sf_Kristallzucht.html' },
  { name: 'kryptographie', label: 'Kryptographie', cost: 0, category: SpecialAbilityCategory.General, prerequisite: [], url: 'https://dsa.ulisses-regelwiki.de/sf_Kryptographie.html' },
  { name: 'krautermischung', label: 'Kräutermischung', cost: 0, category: SpecialAbilityCategory.General, prerequisite: [], url: 'https://dsa.ulisses-regelwiki.de/sf_Kraeutermischung.html' },
  { name: 'kunstflug', label: 'Kunstflug', cost: 0, category: SpecialAbilityCategory.General, prerequisite: [], url: 'https://dsa.ulisses-regelwiki.de/sf_Kunstflug.html' },
  { name: 'kupferstich', label: 'Kupferstich', cost: 0, category: SpecialAbilityCategory.General, prerequisite: [], url: 'https://dsa.ulisses-regelwiki.de/sf_Kupferstich.html' },
  { name: 'kurzschrift', label: 'Kurzschrift', cost: 0, category: SpecialAbilityCategory.General, prerequisite: [], url: 'https://dsa.ulisses-regelwiki.de/sf_Kurzschrift.html' },
  { name: 'kutschenbauer', label: 'Kutschenbauer', cost: 0, category: SpecialAbilityCategory.General, prerequisite: [], url: 'https://dsa.ulisses-regelwiki.de/sf_Kutschenbauer.html' },
  { name: 'legGaLeg', label: 'Leg-ga-leg', cost: 0, category: SpecialAbilityCategory.General, prerequisite: [], url: 'https://dsa.ulisses-regelwiki.de/sf_Leg-ga-leg.html' },
  { name: 'leibdiener', label: 'Leibdiener', cost: 0, category: SpecialAbilityCategory.General, prerequisite: [], url: 'https://dsa.ulisses-regelwiki.de/sf_Leibdiener.html' },
  {
    name: 'lieblingDerMassen',
    label: 'Liebling der Massen',
    cost: 0,
    category: SpecialAbilityCategory.General,
    prerequisite: [],
    url: 'https://dsa.ulisses-regelwiki.de/sf_Liebling_der_Massen.html',
  },
  { name: 'masseur', label: 'Masseur/in', cost: 0, category: SpecialAbilityCategory.General, prerequisite: [], url: 'https://dsa.ulisses-regelwiki.de/sf_Masseur.html' },
  {
    name: 'meisterDerImprovisation',
    label: 'Meister der Improvisation',
    cost: 0,
    category: SpecialAbilityCategory.General,
    prerequisite: [],
    url: 'https://dsa.ulisses-regelwiki.de/sf_Meister_der_Improvisation.html',
  },
  {
    name: 'menschenstimmenImitieren',
    label: 'Menschenstimmen imitieren',
    cost: 0,
    category: SpecialAbilityCategory.General,
    prerequisite: [],
    url: 'https://dsa.ulisses-regelwiki.de/sf_Menschenstimmen_imitieren.html',
  },
  {
    name: 'meteoreisenVerarbeiten',
    label: 'Meteoreisen verarbeiten I-III',
    cost: 0,
    category: SpecialAbilityCategory.General,
    lvl: 1,
    maxLvl: 3,
    prerequisite: [],
    url: 'https://dsa.ulisses-regelwiki.de/sf_Meteoreisen_verarbeiten_I-III.html',
  },
  { name: 'mobelHerstellen', label: 'Möbel herstellen', cost: 0, category: SpecialAbilityCategory.General, prerequisite: [], url: 'https://dsa.ulisses-regelwiki.de/sf_Moebel_herstellen.html' },
  {
    name: 'namensschmeichler',
    label: 'Namensschmeichler',
    cost: 0,
    category: SpecialAbilityCategory.General,
    prerequisite: [],
    url: 'https://dsa.ulisses-regelwiki.de/sf_Namensschmeichler.html',
  },
  {
    name: 'niederhollischerSchmied',
    label: 'Niederhöllischer Schmied',
    cost: 0,
    category: SpecialAbilityCategory.General,
    prerequisite: [],
    url: 'https://dsa.ulisses-regelwiki.de/sf_Niederhoellischer_Schmied.html',
  },
  { name: 'opernsanger', label: 'Opernsänger', cost: 0, category: SpecialAbilityCategory.General, prerequisite: [], url: 'https://dsa.ulisses-regelwiki.de/sf_Opernsaenger.html' },
  {
    name: 'orientierungUnterTage',
    label: 'Orientierung unter Tage',
    cost: 0,
    category: SpecialAbilityCategory.General,
    prerequisite: [],
    url: 'https://dsa.ulisses-regelwiki.de/sf_Orientierung_unter_Tage.html',
  },
  { name: 'palenkelubung', label: 'Palenkelübung', cost: 0, category: SpecialAbilityCategory.General, prerequisite: [], url: 'https://dsa.ulisses-regelwiki.de/sf_Palenkeluebung.html' },
  {
    name: 'pflanzenErhalten',
    label: 'Pflanzen erhalten',
    cost: 0,
    category: SpecialAbilityCategory.General,
    prerequisite: [],
    url: 'https://dsa.ulisses-regelwiki.de/sf_Pflanzen_erhalten.html',
  },
  {
    name: 'porzellanarbeiten',
    label: 'Porzellanarbeiten',
    cost: 0,
    category: SpecialAbilityCategory.General,
    prerequisite: [],
    url: 'https://dsa.ulisses-regelwiki.de/sf_Porzellanarbeiten.html',
  },
  {
    name: 'prunkkleidungHerstellen',
    label: 'Prunkkleidung herstellen',
    cost: 0,
    category: SpecialAbilityCategory.General,
    prerequisite: [],
    url: 'https://dsa.ulisses-regelwiki.de/sf_Prunkkleidung_herstellen.html',
  },
  { name: 'pyromantiker', label: 'Pyromantiker', cost: 0, category: SpecialAbilityCategory.General, prerequisite: [], url: 'https://dsa.ulisses-regelwiki.de/sf_Pyromantiker.html' },
  {
    name: 'rahjasutraKenntnisse',
    label: 'Rahjasutra-Kenntnisse',
    cost: 0,
    category: SpecialAbilityCategory.General,
    prerequisite: [],
    url: 'https://dsa.ulisses-regelwiki.de/sf_Rahjasutra_Kenntnisse.html',
  },
  { name: 'rosstauscher', label: 'Rosstäuscher', cost: 0, category: SpecialAbilityCategory.General, prerequisite: [], url: 'https://dsa.ulisses-regelwiki.de/sf_Rosstaeuscher.html' },
  { name: 'rustungsbau', label: 'Rüstungsbau', cost: 0, category: SpecialAbilityCategory.General, prerequisite: [], url: 'https://dsa.ulisses-regelwiki.de/sf_Ruestungsbau.html' },
  { name: 'schiffsbauer', label: 'Schiffsbauer', cost: 0, category: SpecialAbilityCategory.General, prerequisite: [], url: 'https://dsa.ulisses-regelwiki.de/sf_Schiffsbauer.html' },
  { name: 'schleiertanz', label: 'Schleiertanz', cost: 0, category: SpecialAbilityCategory.General, prerequisite: [], url: 'https://dsa.ulisses-regelwiki.de/sf_Schleiertanz.html' },
  {
    name: 'schmuckHerstellen',
    label: 'Schmuck herstellen',
    cost: 0,
    category: SpecialAbilityCategory.General,
    prerequisite: [],
    url: 'https://dsa.ulisses-regelwiki.de/sf_Schmuck_herstellen.html',
  },
  { name: 'schnapsbrennerei', label: 'Schnapsbrennerei', cost: 0, category: SpecialAbilityCategory.General, prerequisite: [], url: 'https://dsa.ulisses-regelwiki.de/sf_Schnapsbrennerei.html' },
  { name: 'schnellschreiber', label: 'Schnellschreiber', cost: 0, category: SpecialAbilityCategory.General, prerequisite: [], url: 'https://dsa.ulisses-regelwiki.de/sf_Schnellschreiber.html' },
  { name: 'schriftstellerei', label: 'Schriftstellerei', cost: 0, category: SpecialAbilityCategory.General, prerequisite: [], url: 'https://dsa.ulisses-regelwiki.de/sf_Schriftstellerei.html' },
  { name: 'seileHerstellen', label: 'Seile herstellen', cost: 0, category: SpecialAbilityCategory.General, prerequisite: [], url: 'https://dsa.ulisses-regelwiki.de/sf_Seile_herstellen.html' },
  { name: 'silberguss', label: 'Silberguss', cost: 0, category: SpecialAbilityCategory.General, prerequisite: [], url: 'https://dsa.ulisses-regelwiki.de/sf_Silberguss.html' },
  { name: 'sinnlicherTanz', label: 'Sinnlicher Tanz', cost: 0, category: SpecialAbilityCategory.General, prerequisite: [], url: 'https://dsa.ulisses-regelwiki.de/sf_Sinnlicher_Tanz.html' },
  { name: 'smutje', label: 'Smutje', cost: 0, category: SpecialAbilityCategory.General, prerequisite: [], url: 'https://dsa.ulisses-regelwiki.de/sf_Smutje.html' },
  {
    name: 'spracheDerBlumen',
    label: 'Sprache der Blumen',
    cost: 0,
    category: SpecialAbilityCategory.General,
    prerequisite: [],
    url: 'https://dsa.ulisses-regelwiki.de/sf_Sprache_der_Blumen.html',
  },
  { name: 'staatskunst', label: 'Staatskunst', cost: 0, category: SpecialAbilityCategory.General, prerequisite: [], url: 'https://dsa.ulisses-regelwiki.de/sf_Staatskunst.html' },
  { name: 'stechenderBlick', label: 'Stechender Blick', cost: 0, category: SpecialAbilityCategory.General, prerequisite: [], url: 'https://dsa.ulisses-regelwiki.de/sf_Stechender_Blick.html' },
  { name: 'stellmacherei', label: 'Stellmacherei', cost: 0, category: SpecialAbilityCategory.General, prerequisite: [], url: 'https://dsa.ulisses-regelwiki.de/sf_Stellmacherei.html' },
  { name: 'turnierkenntnis', label: 'Turnierkenntnis', cost: 0, category: SpecialAbilityCategory.General, prerequisite: [], url: 'https://dsa.ulisses-regelwiki.de/sf_Turnierkenntnis.html' },
  { name: 'tatowierer', label: 'Tätowierer', cost: 0, category: SpecialAbilityCategory.General, prerequisite: [], url: 'https://dsa.ulisses-regelwiki.de/sf_Taetowierer.html' },
  { name: 'topferei', label: 'Töpferei', cost: 0, category: SpecialAbilityCategory.General, prerequisite: [], url: 'https://dsa.ulisses-regelwiki.de/sf_Toepferei.html' },
  { name: 'unterminieren', label: 'Unterminieren', cost: 0, category: SpecialAbilityCategory.General, prerequisite: [], url: 'https://dsa.ulisses-regelwiki.de/sf_Unterminieren.html' },
  {
    name: 'unterschlupfFinden',
    label: 'Unterschlupf finden',
    cost: 0,
    category: SpecialAbilityCategory.General,
    prerequisite: [],
    url: 'https://dsa.ulisses-regelwiki.de/sf_Unterschlupf_finden.html',
  },
  { name: 'versteckeFinden', label: 'Verstecke finden', cost: 0, category: SpecialAbilityCategory.General, prerequisite: [], url: 'https://dsa.ulisses-regelwiki.de/sf_Verstecke_finden.html' },
  { name: 'viehzucht', label: 'Viehzucht', cost: 0, category: SpecialAbilityCategory.General, prerequisite: [], url: 'https://dsa.ulisses-regelwiki.de/sf_Viehzucht.html' },
  { name: 'waffenbau', label: 'Waffenbau', cost: 0, category: SpecialAbilityCategory.General, prerequisite: [], url: 'https://dsa.ulisses-regelwiki.de/sf_Waffenbau.html' },
  { name: 'wandmalerei', label: 'Wandmalerei', cost: 0, category: SpecialAbilityCategory.General, prerequisite: [], url: 'https://dsa.ulisses-regelwiki.de/sf_Wandmalerei.html' },
  {
    name: 'wegabkurzungenKennen',
    label: 'Wegabkürzungen kennen',
    cost: 0,
    category: SpecialAbilityCategory.General,
    prerequisite: [],
    url: 'https://dsa.ulisses-regelwiki.de/sf_Wegabkuerzungen_kennen.html',
  },
  { name: 'wegkenntnis', label: 'Wegkenntnis', cost: 0, category: SpecialAbilityCategory.General, prerequisite: [], url: 'https://dsa.ulisses-regelwiki.de/sf_Wegkenntnis.html' },
  { name: 'werteSchatzen', label: 'Werte schätzen', cost: 0, category: SpecialAbilityCategory.General, prerequisite: [], url: 'https://dsa.ulisses-regelwiki.de/sf_Werte_schaetzen.html' },
  { name: 'winzerei', label: 'Winzerei', cost: 0, category: SpecialAbilityCategory.General, prerequisite: [], url: 'https://dsa.ulisses-regelwiki.de/sf_Winzerei.html' },
  { name: 'zahlenmystik', label: 'Zahlenmystik', cost: 0, category: SpecialAbilityCategory.General, prerequisite: [], url: 'https://dsa.ulisses-regelwiki.de/sf_Zahlenmystik.html' },
  { name: 'zyklopenschmied', label: 'Zyklopenschmied', cost: 0, category: SpecialAbilityCategory.General, prerequisite: [], url: 'https://dsa.ulisses-regelwiki.de/sf_Zyklopenschmied.html' },
  { name: 'olmalerei', label: 'Ölmalerei', cost: 0, category: SpecialAbilityCategory.General, prerequisite: [], url: 'https://dsa.ulisses-regelwiki.de/sf_Oelmalerei.html' },
];

// â”€â”€â”€ Kampfsonderfertigkeiten â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
export const COMBAT_SPECIAL_ABILITIES: SpecialAbility[] = [
  {
    name: 'armbrustUberdrehen',
    label: 'Armbrust überdrehen',
    cost: 0,
    category: SpecialAbilityCategory.Combat,
    prerequisite: [],
    url: 'https://dsa.ulisses-regelwiki.de/ksf_Armbrust_ueberdrehen.html',
  },
  {
    name: 'aufDistanzHalten',
    label: 'Auf Distanz halten I-II',
    cost: 15,
    category: SpecialAbilityCategory.Combat,
    lvl: 1,
    maxLvl: 2,
    prerequisite: [],
    attributeRequirement: [{ attribute: 'GE', minValue: 13 }],
    url: 'https://dsa.ulisses-regelwiki.de/ksf_Auf_Distanz_halten_I-II.html',
  },
  { name: 'auflaufen', label: 'Auflaufen', cost: 0, category: SpecialAbilityCategory.Combat, prerequisite: [], url: 'https://dsa.ulisses-regelwiki.de/ksf_Auflaufen.html' },
  {
    name: 'aufmerksamkeit',
    label: 'Aufmerksamkeit',
    cost: 15,
    category: SpecialAbilityCategory.Combat,
    prerequisite: [],
    attributeRequirement: [{ attribute: 'IN', minValue: 13 }],
    url: 'https://dsa.ulisses-regelwiki.de/ksf_Aufmerksamkeit.html',
  },
  {
    name: 'ausfall',
    label: 'Ausfall I-II',
    cost: 15,
    category: SpecialAbilityCategory.Combat,
    lvl: 1,
    maxLvl: 2,
    prerequisite: [],
    attributeRequirement: [{ attribute: 'GE', minValue: 15 }],
    url: 'https://dsa.ulisses-regelwiki.de/ksf_Ausfall_I-II.html',
  },
  {
    name: 'ballistischerSchuss',
    label: 'Ballistischer Schuss',
    cost: 0,
    category: SpecialAbilityCategory.Combat,
    prerequisite: [],
    url: 'https://dsa.ulisses-regelwiki.de/ksf_Ballistischer_Schuss.html',
  },
  {
    name: 'beidhandigerKampf',
    label: 'Beidhändiger Kampf I-II',
    cost: 20,
    category: SpecialAbilityCategory.Combat,
    lvl: 1,
    maxLvl: 2,
    prerequisite: [],
    attributeRequirement: [{ attribute: 'GE', minValue: 13 }],
    url: 'https://dsa.ulisses-regelwiki.de/ksf_Beidhaendiger_Kampf_I-II.html',
  },
  {
    name: 'belastungsgewohnung',
    label: 'Belastungsgewöhnung I-II',
    cost: 20,
    category: SpecialAbilityCategory.Combat,
    lvl: 1,
    maxLvl: 2,
    prerequisite: [],
    attributeRequirement: [{ attribute: 'KO', minValue: 13 }],
    url: 'https://dsa.ulisses-regelwiki.de/ksf_Belastungsgewohnung_I-II.html',
  },
  {
    name: 'berittenerKampf',
    label: 'Berittener Kampf',
    cost: 20,
    category: SpecialAbilityCategory.Combat,
    prerequisite: [{ name: 'reiten', required: true, minLvl: 4 }],
    url: 'https://dsa.ulisses-regelwiki.de/ksf_Berittener_Kampf.html',
  },
  {
    name: 'berittenerSchutze',
    label: 'Berittener Schütze',
    cost: 10,
    category: SpecialAbilityCategory.Combat,
    prerequisite: [{ name: 'berittenerKampf', required: true }],
    url: 'https://dsa.ulisses-regelwiki.de/ksf_Berittener_Schuetze.html',
  },
  { name: 'beschutzer', label: 'Beschützer', cost: 0, category: SpecialAbilityCategory.Combat, prerequisite: [], url: 'https://dsa.ulisses-regelwiki.de/ksf_Beschuetzer.html' },
  {
    name: 'betaubungsschlag',
    label: 'Betäubungsschlag',
    cost: 15,
    category: SpecialAbilityCategory.Combat,
    prerequisite: [],
    attributeRequirement: [{ attribute: 'KK', minValue: 13 }],
    url: 'https://dsa.ulisses-regelwiki.de/ksf_Betaeubungsschlag.html',
  },
  {
    name: 'blindkampf',
    label: 'Blindkampf I-II',
    cost: 15,
    category: SpecialAbilityCategory.Combat,
    lvl: 1,
    maxLvl: 2,
    prerequisite: [],
    attributeRequirement: [{ attribute: 'IN', minValue: 13 }],
    url: 'https://dsa.ulisses-regelwiki.de/ksf_Blindkampf_I-II.html',
  },
  {
    name: 'doppelangriff',
    label: 'Doppelangriff',
    cost: 25,
    category: SpecialAbilityCategory.Combat,
    prerequisite: [{ name: 'beidhandigerKampf', required: true }],
    attributeRequirement: [{ attribute: 'GE', minValue: 15 }],
    url: 'https://dsa.ulisses-regelwiki.de/ksf_Doppelangriff.html',
  },
  {
    name: 'einhandigerKampf',
    label: 'Einhändiger Kampf',
    cost: 10,
    category: SpecialAbilityCategory.Combat,
    prerequisite: [],
    attributeRequirement: [{ attribute: 'GE', minValue: 13 }],
    url: 'https://dsa.ulisses-regelwiki.de/ksf_Einhaendiger_Kampf.html',
  },
  {
    name: 'entwaffnen',
    label: 'Entwaffnen',
    cost: 40,
    category: SpecialAbilityCategory.Combat,
    prerequisite: [],
    attributeRequirement: [{ attribute: 'GE', minValue: 15 }],
    url: 'https://dsa.ulisses-regelwiki.de/ksf_Entwaffnen.html',
  },
  {
    name: 'feindgespur',
    label: 'Feindgespür',
    cost: 10,
    category: SpecialAbilityCategory.Combat,
    prerequisite: [],
    attributeRequirement: [{ attribute: 'IN', minValue: 15 }],
    url: 'https://dsa.ulisses-regelwiki.de/ksf_Feindgespur.html',
  },
  { name: 'festnageln', label: 'Festnageln', cost: 20, category: SpecialAbilityCategory.Combat, prerequisite: [], url: 'https://dsa.ulisses-regelwiki.de/ksf_Festnageln.html' },
  {
    name: 'finte',
    label: 'Finte I-III',
    cost: 15,
    category: SpecialAbilityCategory.Combat,
    lvl: 1,
    maxLvl: 3,
    prerequisite: [],
    attributeRequirement: [{ attribute: 'GE', minValue: 13 }],
    url: 'https://dsa.ulisses-regelwiki.de/ksf_Finte_I-III.html',
  },
  {
    name: 'formation',
    label: 'Formation',
    cost: 20,
    category: SpecialAbilityCategory.Combat,
    prerequisite: [{ name: 'kriegskunst', required: true, minLvl: 6 }],
    url: 'https://dsa.ulisses-regelwiki.de/ksf_Formation.html',
  },
  {
    name: 'geschossabwehr',
    label: 'Geschossabwehr I-III',
    cost: 5,
    category: SpecialAbilityCategory.Combat,
    lvl: 1,
    maxLvl: 3,
    prerequisite: [],
    attributeRequirement: [{ attribute: 'FF', minValue: 13 }],
    url: 'https://dsa.ulisses-regelwiki.de/ksf_Geschossabwehr_I-III.html',
  },
  {
    name: 'gezielterAngriff',
    label: 'Gezielter Angriff',
    cost: 10,
    category: SpecialAbilityCategory.Combat,
    prerequisite: [],
    attributeRequirement: [{ attribute: 'GE', minValue: 13 }],
    url: 'https://dsa.ulisses-regelwiki.de/ksf_Gezielter_Angriff.html',
  },
  {
    name: 'gezielterSchuss',
    label: 'Gezielter Schuss',
    cost: 10,
    category: SpecialAbilityCategory.Combat,
    prerequisite: [],
    attributeRequirement: [{ attribute: 'FF', minValue: 13 }],
    url: 'https://dsa.ulisses-regelwiki.de/ksf_Gezielter_Schuss.html',
  },
  {
    name: 'hammerschlag',
    label: 'Hammerschlag',
    cost: 25,
    category: SpecialAbilityCategory.Combat,
    prerequisite: [{ name: 'wuchtschlag', required: true, minLvl: 3 }],
    attributeRequirement: [{ attribute: 'MU', minValue: 15 }],
    url: 'https://dsa.ulisses-regelwiki.de/ksf_Hammerschlag.html',
  },
  {
    name: 'kampfreflexe',
    label: 'Kampfreflexe I-III',
    cost: 10,
    category: SpecialAbilityCategory.Combat,
    lvl: 1,
    maxLvl: 3,
    prerequisite: [],
    attributeRequirement: [{ attribute: 'IN', minValue: 13 }],
    url: 'https://dsa.ulisses-regelwiki.de/ksf_Kampfreflexe_I-III.html',
  },
  {
    name: 'klingensturm',
    label: 'Klingensturm',
    cost: 30,
    category: SpecialAbilityCategory.Combat,
    prerequisite: [],
    attributeRequirement: [{ attribute: 'GE', minValue: 15 }],
    url: 'https://dsa.ulisses-regelwiki.de/ksf_Klingensturm.html',
  },
  {
    name: 'meisterlichesAusweichen',
    label: 'Meisterliches Ausweichen',
    cost: 15,
    category: SpecialAbilityCategory.Combat,
    prerequisite: [{ name: 'verbesserteAusweichen', required: true, minLvl: 2 }],
    attributeRequirement: [{ attribute: 'IN', minValue: 13 }],
    url: 'https://dsa.ulisses-regelwiki.de/ksf_Meisterliches_Ausweichen.html',
  },
  { name: 'meisterparade', label: 'Meisterparade', cost: 25, category: SpecialAbilityCategory.Combat, prerequisite: [], url: 'https://dsa.ulisses-regelwiki.de/ksf_Meisterparade.html' },
  {
    name: 'praeziserSchussWurf',
    label: 'Präziser Schuss/Wurf I-III',
    cost: 15,
    category: SpecialAbilityCategory.Combat,
    lvl: 1,
    maxLvl: 3,
    prerequisite: [],
    attributeRequirement: [{ attribute: 'IN', minValue: 13 }],
    url: 'https://dsa.ulisses-regelwiki.de/ksf_Praeziser_Schuss_Wurf_I-III.html',
  },
  {
    name: 'riposte',
    label: 'Riposte',
    cost: 20,
    category: SpecialAbilityCategory.Combat,
    prerequisite: [],
    attributeRequirement: [{ attribute: 'GE', minValue: 15 }],
    url: 'https://dsa.ulisses-regelwiki.de/ksf_Riposte.html',
  },
  {
    name: 'rundumschlag',
    label: 'Rundumschlag I-II',
    cost: 25,
    category: SpecialAbilityCategory.Combat,
    lvl: 1,
    maxLvl: 2,
    prerequisite: [],
    attributeRequirement: [{ attribute: 'GE', minValue: 15 }],
    url: 'https://dsa.ulisses-regelwiki.de/ksf_Rundumschlag_I-II.html',
  },
  {
    name: 'scharfschutze',
    label: 'Scharfschütze I-II',
    cost: 15,
    category: SpecialAbilityCategory.Combat,
    lvl: 1,
    maxLvl: 2,
    prerequisite: [{ name: 'praeziserSchussWurf', required: true }],
    attributeRequirement: [{ attribute: 'IN', minValue: 15 }],
    url: 'https://dsa.ulisses-regelwiki.de/ksf_Scharfschuetze_I-II.html',
  },
  {
    name: 'schildspalter',
    label: 'Schildspalter',
    cost: 15,
    category: SpecialAbilityCategory.Combat,
    prerequisite: [{ name: 'wuchtschlag', required: true }],
    attributeRequirement: [{ attribute: 'KK', minValue: 13 }],
    url: 'https://dsa.ulisses-regelwiki.de/ksf_Schildspalter.html',
  },
  {
    name: 'schnellladen',
    label: 'Schnellladen (Kampftechnik)',
    cost: 5,
    category: SpecialAbilityCategory.Combat,
    prerequisite: [],
    attributeRequirement: [{ attribute: 'FF', minValue: 13 }],
    url: 'https://dsa.ulisses-regelwiki.de/ksf_Schnellladen.html',
  },
  {
    name: 'schnellziehen',
    label: 'Schnellziehen',
    cost: 10,
    category: SpecialAbilityCategory.Combat,
    prerequisite: [],
    attributeRequirement: [{ attribute: 'FF', minValue: 13 }],
    url: 'https://dsa.ulisses-regelwiki.de/ksf_Schnellziehen.html',
  },
  {
    name: 'sturmangriff',
    label: 'Sturmangriff',
    cost: 25,
    category: SpecialAbilityCategory.Combat,
    prerequisite: [{ name: 'wuchtschlag', required: true }],
    attributeRequirement: [{ attribute: 'MU', minValue: 13 }],
    url: 'https://dsa.ulisses-regelwiki.de/ksf_Sturmangriff.html',
  },
  {
    name: 'todesstoss',
    label: 'Todesstoß',
    cost: 30,
    category: SpecialAbilityCategory.Combat,
    prerequisite: [{ name: 'praeziserStich', required: true, minLvl: 3 }],
    attributeRequirement: [{ attribute: 'MU', minValue: 15 }],
    url: 'https://dsa.ulisses-regelwiki.de/ksf_Todesstoss.html',
  },
  {
    name: 'unterlaufen',
    label: 'Unterlaufen I-II',
    cost: 10,
    category: SpecialAbilityCategory.Combat,
    lvl: 1,
    maxLvl: 2,
    prerequisite: [],
    attributeRequirement: [{ attribute: 'GE', minValue: 13 }],
    url: 'https://dsa.ulisses-regelwiki.de/ksf_Unterlaufen_I-II.html',
  },
  {
    name: 'verbesserteAusweichen',
    label: 'Verbessertes Ausweichen I-III',
    cost: 15,
    category: SpecialAbilityCategory.Combat,
    lvl: 1,
    maxLvl: 3,
    prerequisite: [{ name: 'korperbeherrschung', required: true, minLvl: 4 }],
    url: 'https://dsa.ulisses-regelwiki.de/ksf_Verbessertes_Ausweichen_I-III.html',
  },
  {
    name: 'verteidigungshaltung',
    label: 'Verteidigungshaltung',
    cost: 10,
    category: SpecialAbilityCategory.Combat,
    prerequisite: [],
    attributeRequirement: [{ attribute: 'IN', minValue: 13 }],
    url: 'https://dsa.ulisses-regelwiki.de/ksf_Verteidigungshaltung.html',
  },
  {
    name: 'wirbelangriff',
    label: 'Wirbelangriff I-II',
    cost: 20,
    category: SpecialAbilityCategory.Combat,
    lvl: 1,
    maxLvl: 2,
    prerequisite: [],
    attributeRequirement: [{ attribute: 'GE', minValue: 15 }],
    url: 'https://dsa.ulisses-regelwiki.de/ksf_Wirbelangriff_I-II.html',
  },
  {
    name: 'wuchtschlag',
    label: 'Wuchtschlag I-III',
    cost: 15,
    category: SpecialAbilityCategory.Combat,
    lvl: 1,
    maxLvl: 3,
    prerequisite: [],
    attributeRequirement: [{ attribute: 'KK', minValue: 13 }],
    url: 'https://dsa.ulisses-regelwiki.de/ksf_Wuchtschlag_I-III.html',
  },
  {
    name: 'zuFallBringen',
    label: 'Zu Fall bringen',
    cost: 20,
    category: SpecialAbilityCategory.Combat,
    prerequisite: [],
    attributeRequirement: [{ attribute: 'KK', minValue: 13 }],
    url: 'https://dsa.ulisses-regelwiki.de/ksf_Zu_Fall_bringen.html',
  },
  // â”€â”€ Weitere Kampf-SF â”€â”€
  {
    name: 'berittenerFlugkampf',
    label: 'Berittener Flugkampf',
    cost: 0,
    category: SpecialAbilityCategory.Combat,
    prerequisite: [{ name: 'berittenerKampf', required: true }],
    url: 'https://dsa.ulisses-regelwiki.de/ksf_Berittener_Flugkampf.html',
  },
  {
    name: 'beritteneLanzenformation',
    label: 'Berittene Lanzenformation',
    cost: 0,
    category: SpecialAbilityCategory.Combat,
    prerequisite: [],
    url: 'https://dsa.ulisses-regelwiki.de/ksf_Berittene_Lanzenformation.html',
  },
  { name: 'betaubungswurf', label: 'Betäubungswurf', cost: 0, category: SpecialAbilityCategory.Combat, prerequisite: [], url: 'https://dsa.ulisses-regelwiki.de/ksf_Betaeubungswurf.html' },
  { name: 'blutgratsche', label: 'Blutgrätsche', cost: 0, category: SpecialAbilityCategory.Combat, prerequisite: [], url: 'https://dsa.ulisses-regelwiki.de/ksf_Blutgraetsche.html' },
  {
    name: 'drachenkampfTaktik',
    label: 'Drachenkampf-Taktik',
    cost: 0,
    category: SpecialAbilityCategory.Combat,
    prerequisite: [],
    url: 'https://dsa.ulisses-regelwiki.de/ksf_Drachenkampf-Taktik.html',
  },
  {
    name: 'durchgezogenerTritt',
    label: 'Durchgezogener Tritt I-III',
    cost: 0,
    category: SpecialAbilityCategory.Combat,
    lvl: 1,
    maxLvl: 3,
    prerequisite: [],
    url: 'https://dsa.ulisses-regelwiki.de/ksf_Durchgezogener_Tritt_I-III.html',
  },
  {
    name: 'eisenhagel',
    label: 'Eisenhagel I-II',
    cost: 0,
    category: SpecialAbilityCategory.Combat,
    lvl: 1,
    maxLvl: 2,
    prerequisite: [],
    url: 'https://dsa.ulisses-regelwiki.de/ksf_Eisenhagel_I-II.html',
  },
  {
    name: 'ellbogenangriff',
    label: 'Ellbogenangriff I-III',
    cost: 0,
    category: SpecialAbilityCategory.Combat,
    lvl: 1,
    maxLvl: 3,
    prerequisite: [],
    url: 'https://dsa.ulisses-regelwiki.de/ksf_Ellbogenangriff_I-III.html',
  },
  {
    name: 'gefechtsformation',
    label: 'Gefechtsformation',
    cost: 0,
    category: SpecialAbilityCategory.Combat,
    prerequisite: [],
    url: 'https://dsa.ulisses-regelwiki.de/ksf_Gefechtsformation.html',
  },
  { name: 'gegenhalten', label: 'Gegenhalten', cost: 0, category: SpecialAbilityCategory.Combat, prerequisite: [], url: 'https://dsa.ulisses-regelwiki.de/ksf_Gegenhalten.html' },
  {
    name: 'geschutzeBedienen',
    label: 'Geschütze bedienen',
    cost: 0,
    category: SpecialAbilityCategory.Combat,
    prerequisite: [],
    url: 'https://dsa.ulisses-regelwiki.de/ksf_Geschuetze_bedienen.html',
  },
  { name: 'gratsche', label: 'Grätsche', cost: 0, category: SpecialAbilityCategory.Combat, prerequisite: [], url: 'https://dsa.ulisses-regelwiki.de/ksf_Graetsche.html' },
  { name: 'haltegriff', label: 'Haltegriff', cost: 0, category: SpecialAbilityCategory.Combat, prerequisite: [], url: 'https://dsa.ulisses-regelwiki.de/ksf_Haltegriff.html' },
  { name: 'harpunieren', label: 'Harpunieren', cost: 0, category: SpecialAbilityCategory.Combat, prerequisite: [], url: 'https://dsa.ulisses-regelwiki.de/ksf_Harpunieren.html' },
  { name: 'herunterstossen', label: 'Herunterstoßen', cost: 0, category: SpecialAbilityCategory.Combat, prerequisite: [], url: 'https://dsa.ulisses-regelwiki.de/ksf_Herunterstossen.html' },
  { name: 'kampfImWasser', label: 'Kampf im Wasser', cost: 0, category: SpecialAbilityCategory.Combat, prerequisite: [], url: 'https://dsa.ulisses-regelwiki.de/ksf_Kampf_im_Wasser.html' },
  {
    name: 'kampfstilKombination',
    label: 'Kampfstil-Kombination',
    cost: 0,
    category: SpecialAbilityCategory.Combat,
    prerequisite: [],
    url: 'https://dsa.ulisses-regelwiki.de/ksf_Kampfstil-Kombination.html',
  },
  {
    name: 'kernschuss',
    label: 'Kernschuss I-III',
    cost: 0,
    category: SpecialAbilityCategory.Combat,
    lvl: 1,
    maxLvl: 3,
    prerequisite: [],
    url: 'https://dsa.ulisses-regelwiki.de/ksf_Kernschuss_I-III.html',
  },
  { name: 'kettenkugelkampf', label: 'Kettenkugelkampf', cost: 0, category: SpecialAbilityCategory.Combat, prerequisite: [], url: 'https://dsa.ulisses-regelwiki.de/ksf_Kettenkugelkampf.html' },
  { name: 'klingeDrehen', label: 'Klinge drehen', cost: 0, category: SpecialAbilityCategory.Combat, prerequisite: [], url: 'https://dsa.ulisses-regelwiki.de/ksf_Klinge_drehen.html' },
  { name: 'klingenfanger', label: 'Klingenfänger', cost: 0, category: SpecialAbilityCategory.Combat, prerequisite: [], url: 'https://dsa.ulisses-regelwiki.de/ksf_Klingenfaenger.html' },
  { name: 'klingentatzer', label: 'Klingentänzer', cost: 0, category: SpecialAbilityCategory.Combat, prerequisite: [], url: 'https://dsa.ulisses-regelwiki.de/ksf_Klingentaenzer.html' },
  {
    name: 'kraftvollerSpeerwurf',
    label: 'Kraftvoller Speerwurf',
    cost: 0,
    category: SpecialAbilityCategory.Combat,
    prerequisite: [],
    url: 'https://dsa.ulisses-regelwiki.de/ksf_Kraftvoller_Speerwurf.html',
  },
  { name: 'kreuzblock', label: 'Kreuzblock', cost: 0, category: SpecialAbilityCategory.Combat, prerequisite: [], url: 'https://dsa.ulisses-regelwiki.de/ksf_Kreuzblock.html' },
  { name: 'lanzenangriff', label: 'Lanzenangriff', cost: 0, category: SpecialAbilityCategory.Combat, prerequisite: [], url: 'https://dsa.ulisses-regelwiki.de/ksf_Lanzenangriff.html' },
  { name: 'lanzenfuhrung', label: 'Lanzenführung', cost: 0, category: SpecialAbilityCategory.Combat, prerequisite: [], url: 'https://dsa.ulisses-regelwiki.de/ksf_Lanzenfuehrung.html' },
  {
    name: 'machtvolleMeisterparade',
    label: 'Machtvolle Meisterparade',
    cost: 0,
    category: SpecialAbilityCategory.Combat,
    prerequisite: [{ name: 'meisterparade', required: true }],
    url: 'https://dsa.ulisses-regelwiki.de/ksf_Machtvolle_Meisterparade.html',
  },
  {
    name: 'meisterDerImprovisiertenWaffen',
    label: 'Meister der improvisierten Waffen',
    cost: 0,
    category: SpecialAbilityCategory.Combat,
    prerequisite: [],
    url: 'https://dsa.ulisses-regelwiki.de/ksf_Meister_der_improvisierten_Waffen.html',
  },
  {
    name: 'meisterlicheGeschossabwehr',
    label: 'Meisterliche Geschossabwehr I-III',
    cost: 0,
    category: SpecialAbilityCategory.Combat,
    lvl: 1,
    maxLvl: 3,
    prerequisite: [{ name: 'geschossabwehr', required: true, minLvl: 3 }],
    url: 'https://dsa.ulisses-regelwiki.de/ksf_Meisterliche_Geschossabwehr_I-III.html',
  },
  {
    name: 'meisterlicheKlingentatzer',
    label: 'Meisterlicher Klingentänzer',
    cost: 0,
    category: SpecialAbilityCategory.Combat,
    prerequisite: [{ name: 'klingentatzer', required: true }],
    url: 'https://dsa.ulisses-regelwiki.de/ksf_Meisterlicher_Klingentaenzer.html',
  },
  { name: 'pikenwall', label: 'Pikenwall', cost: 0, category: SpecialAbilityCategory.Combat, prerequisite: [], url: 'https://dsa.ulisses-regelwiki.de/ksf_Pikenwall.html' },
  {
    name: 'praeziserStich',
    label: 'Präziser Stich I-III',
    cost: 0,
    category: SpecialAbilityCategory.Combat,
    lvl: 1,
    maxLvl: 3,
    prerequisite: [],
    url: 'https://dsa.ulisses-regelwiki.de/ksf_Praeziser_Stich_I-III.html',
  },
  {
    name: 'querschuss',
    label: 'Querschuss I-III',
    cost: 0,
    category: SpecialAbilityCategory.Combat,
    lvl: 1,
    maxLvl: 3,
    prerequisite: [],
    url: 'https://dsa.ulisses-regelwiki.de/ksf_Querschuss_I-III.html',
  },
  { name: 'reissangriff', label: 'Reißangriff', cost: 0, category: SpecialAbilityCategory.Combat, prerequisite: [], url: 'https://dsa.ulisses-regelwiki.de/ksf_Reissangriff.html' },
  { name: 'schildschlag', label: 'Schildschlag', cost: 0, category: SpecialAbilityCategory.Combat, prerequisite: [], url: 'https://dsa.ulisses-regelwiki.de/ksf_Schildschlag.html' },
  { name: 'schildwall', label: 'Schildwall', cost: 0, category: SpecialAbilityCategory.Combat, prerequisite: [], url: 'https://dsa.ulisses-regelwiki.de/ksf_Schildwall.html' },
  { name: 'schwitzkasten', label: 'Schwitzkasten', cost: 0, category: SpecialAbilityCategory.Combat, prerequisite: [], url: 'https://dsa.ulisses-regelwiki.de/ksf_Schwitzkasten.html' },
  { name: 'spiessgespann', label: 'Spießgespann', cost: 0, category: SpecialAbilityCategory.Combat, prerequisite: [], url: 'https://dsa.ulisses-regelwiki.de/ksf_Spiessgespann.html' },
  {
    name: 'turnierreiterei',
    label: 'Turnierreiterei',
    cost: 0,
    category: SpecialAbilityCategory.Combat,
    prerequisite: [{ name: 'berittenerKampf', required: true }],
    url: 'https://dsa.ulisses-regelwiki.de/ksf_Turnierreiterei.html',
  },
  { name: 'umrennen', label: 'Umrennen', cost: 0, category: SpecialAbilityCategory.Combat, prerequisite: [], url: 'https://dsa.ulisses-regelwiki.de/ksf_Umrennen.html' },
  { name: 'umwickeln', label: 'Umwickeln', cost: 0, category: SpecialAbilityCategory.Combat, prerequisite: [], url: 'https://dsa.ulisses-regelwiki.de/ksf_Umwickeln.html' },
  { name: 'unterwasserkampf', label: 'Unterwasserkampf', cost: 0, category: SpecialAbilityCategory.Combat, prerequisite: [], url: 'https://dsa.ulisses-regelwiki.de/ksf_Unterwasserkampf.html' },
  {
    name: 'verbesserteUnterlaufen',
    label: 'Verbessertes Unterlaufen',
    cost: 0,
    category: SpecialAbilityCategory.Combat,
    prerequisite: [{ name: 'unterlaufen', required: true, minLvl: 2 }],
    url: 'https://dsa.ulisses-regelwiki.de/ksf_Verbessertes_Unterlaufen.html',
  },
  {
    name: 'verteilterEisenhagel',
    label: 'Verteilter Eisenhagel',
    cost: 0,
    category: SpecialAbilityCategory.Combat,
    prerequisite: [{ name: 'eisenhagel', required: true }],
    url: 'https://dsa.ulisses-regelwiki.de/ksf_Verteilter_Eisenhagel.html',
  },
  { name: 'vorstoss', label: 'Vorstoß', cost: 0, category: SpecialAbilityCategory.Combat, prerequisite: [], url: 'https://dsa.ulisses-regelwiki.de/ksf_Vorstoss.html' },
  { name: 'weitwurf', label: 'Weitwurf', cost: 0, category: SpecialAbilityCategory.Combat, prerequisite: [], url: 'https://dsa.ulisses-regelwiki.de/ksf_Weitwurf.html' },
  { name: 'wurf', label: 'Wurf', cost: 0, category: SpecialAbilityCategory.Combat, prerequisite: [], url: 'https://dsa.ulisses-regelwiki.de/ksf_Wurf.html' },
  {
    name: 'zweihandwaffenDoppelschlag',
    label: 'Zweihandwaffen-Doppelschlag',
    cost: 0,
    category: SpecialAbilityCategory.Combat,
    prerequisite: [],
    url: 'https://dsa.ulisses-regelwiki.de/ksf_Zweihandwaffen-Doppelschlag.html',
  },
  {
    name: 'zweihandwaffenKampf',
    label: 'Zweihandwaffen-Kampf',
    cost: 0,
    category: SpecialAbilityCategory.Combat,
    prerequisite: [],
    url: 'https://dsa.ulisses-regelwiki.de/ksf_Zweihandwaffen-Kampf.html',
  },
  {
    name: 'zweihandigerReiterkampf',
    label: 'Zweihändiger Reiterkampf',
    cost: 0,
    category: SpecialAbilityCategory.Combat,
    prerequisite: [{ name: 'berittenerKampf', required: true }],
    url: 'https://dsa.ulisses-regelwiki.de/ksf_Zweihaendiger_Reiterkampf.html',
  },
  { name: 'khaFormation', label: 'Kha-Formation', cost: 0, category: SpecialAbilityCategory.Combat, prerequisite: [], url: 'https://dsa.ulisses-regelwiki.de/ksf_Kha-Formation.html' },
  {
    name: 'planklerFormation',
    label: 'Plänkler-Formation',
    cost: 0,
    category: SpecialAbilityCategory.Combat,
    prerequisite: [],
    url: 'https://dsa.ulisses-regelwiki.de/ksf_Plaenkler-Formation.html',
  },
];

// â”€â”€â”€ Kampfstilsonderfertigkeiten (Combat Styles) â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
// AP cost varies by style; typically 15â€“25 AP
export const COMBAT_STYLE_SPECIAL_ABILITIES: SpecialAbility[] = [
  // â”€â”€ Bewaffnete Kampfstile â”€â”€
  {
    name: 'achazschleicherStil',
    label: 'Achazschleicher-Stil',
    cost: 0,
    category: SpecialAbilityCategory.CombatStyle,
    prerequisite: [],
    url: 'https://dsa.ulisses-regelwiki.de/ksf_Achazschleicher-Stil.html',
  },
  { name: 'adersinStil', label: 'Adersin-Stil', cost: 0, category: SpecialAbilityCategory.CombatStyle, prerequisite: [], url: 'https://dsa.ulisses-regelwiki.de/ksf_Adersin-Stil.html' },
  { name: 'adoruStil', label: 'Adoru-Stil', cost: 0, category: SpecialAbilityCategory.CombatStyle, prerequisite: [], url: 'https://dsa.ulisses-regelwiki.de/ksf_Adoru-Stil.html' },
  {
    name: 'alterAdersinStil',
    label: 'Alter Adersin-Stil',
    cost: 0,
    category: SpecialAbilityCategory.CombatStyle,
    prerequisite: [],
    url: 'https://dsa.ulisses-regelwiki.de/ksf_Alter_Adersin-Stil.html',
  },
  {
    name: 'alDrakorhimStil',
    label: "Al'Drakorhim-Stil",
    cost: 0,
    category: SpecialAbilityCategory.CombatStyle,
    prerequisite: [],
    url: 'https://dsa.ulisses-regelwiki.de/ksf_AlDrakorhim-Stil.html',
  },
  { name: 'amazonenStil', label: 'Amazonen-Stil', cost: 0, category: SpecialAbilityCategory.CombatStyle, prerequisite: [], url: 'https://dsa.ulisses-regelwiki.de/ksf_Amazonen-Stil.html' },
  { name: 'garethStil', label: 'Gareth-Stil', cost: 0, category: SpecialAbilityCategory.CombatStyle, prerequisite: [], url: 'https://dsa.ulisses-regelwiki.de/ksf_Gareth-Stil.html' },
  { name: 'gardistenStil', label: 'Gardisten-Stil', cost: 0, category: SpecialAbilityCategory.CombatStyle, prerequisite: [], url: 'https://dsa.ulisses-regelwiki.de/ksf_Gardisten-Stil.html' },
  {
    name: 'golgaritenstil',
    label: 'Golgariten-Stil',
    cost: 0,
    category: SpecialAbilityCategory.CombatStyle,
    prerequisite: [],
    url: 'https://dsa.ulisses-regelwiki.de/ksf_Golgariten-Stil.html',
  },
  { name: 'soldatenStil', label: 'Soldaten-Stil', cost: 0, category: SpecialAbilityCategory.CombatStyle, prerequisite: [], url: 'https://dsa.ulisses-regelwiki.de/ksf_Soldaten-Stil.html' },
  { name: 'soldnerStil', label: 'Söldner-Stil', cost: 0, category: SpecialAbilityCategory.CombatStyle, prerequisite: [], url: 'https://dsa.ulisses-regelwiki.de/ksf_Soeldner-Stil.html' },
  { name: 'thorwalStil', label: 'Thorwal-Stil', cost: 0, category: SpecialAbilityCategory.CombatStyle, prerequisite: [], url: 'https://dsa.ulisses-regelwiki.de/ksf_Thorwal-Stil.html' },
  { name: 'xorloschStil', label: 'Xorlosch-Stil', cost: 0, category: SpecialAbilityCategory.CombatStyle, prerequisite: [], url: 'https://dsa.ulisses-regelwiki.de/ksf_Xorlosch-Stil.html' },
  // â”€â”€ Unbewaffnete Kampfstile â”€â”€
  {
    name: 'bornlandischesRaufen',
    label: 'Bornländisches Raufen',
    cost: 0,
    category: SpecialAbilityCategory.CombatStyle,
    prerequisite: [],
    url: 'https://dsa.ulisses-regelwiki.de/ksf_Bornlaendisches_Raufen.html',
  },
  { name: 'boxerStil', label: 'Boxer-Stil', cost: 0, category: SpecialAbilityCategory.CombatStyle, prerequisite: [], url: 'https://dsa.ulisses-regelwiki.de/ksf_Boxer-Stil.html' },
  {
    name: 'gladiatorenStil',
    label: 'Gladiatoren-Stil',
    cost: 0,
    category: SpecialAbilityCategory.CombatStyle,
    prerequisite: [],
    url: 'https://dsa.ulisses-regelwiki.de/ksf_Gladiatoren-Stil.html',
  },
  {
    name: 'hammerfaustStil',
    label: 'Hammerfaust-Stil',
    cost: 0,
    category: SpecialAbilityCategory.CombatStyle,
    prerequisite: [],
    url: 'https://dsa.ulisses-regelwiki.de/ksf_Hammerfaust-Stil.html',
  },
  { name: 'unauerSchule', label: 'Unauer Schule', cost: 0, category: SpecialAbilityCategory.CombatStyle, prerequisite: [], url: 'https://dsa.ulisses-regelwiki.de/ksf_Unauer_Schule.html' },
  {
    name: 'zyklopaischesRingen',
    label: 'Zyklopäisches Ringen',
    cost: 0,
    category: SpecialAbilityCategory.CombatStyle,
    prerequisite: [],
    url: 'https://dsa.ulisses-regelwiki.de/ksf_Zyklopaeisches_Ringen.html',
  },
];

// â”€â”€â”€ Befehlssonderfertigkeiten (Command SF) â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
export const COMMAND_SPECIAL_ABILITIES: SpecialAbility[] = [
  {
    name: 'befehlFlugangriff',
    label: 'Befehl Flugangriff',
    cost: 0,
    category: SpecialAbilityCategory.Command,
    prerequisite: [],
    url: 'https://dsa.ulisses-regelwiki.de/sf_Befehl_Flugangriff.html',
  },
  {
    name: 'befehlKlammerangriff',
    label: 'Befehl Klammerangriff',
    cost: 0,
    category: SpecialAbilityCategory.Command,
    prerequisite: [],
    url: 'https://dsa.ulisses-regelwiki.de/sf_Befehl_Klammerangriff.html',
  },
  {
    name: 'befehlMachtigerSchlag',
    label: 'Befehl Mächtiger Schlag',
    cost: 0,
    category: SpecialAbilityCategory.Command,
    prerequisite: [],
    url: 'https://dsa.ulisses-regelwiki.de/sf_Befehl_Maechtiger_Schlag.html',
  },
  {
    name: 'befehlSichelangriff',
    label: 'Befehl Sichelangriff',
    cost: 0,
    category: SpecialAbilityCategory.Command,
    prerequisite: [],
    url: 'https://dsa.ulisses-regelwiki.de/sf_Befehl_Sichelangriff.html',
  },
  { name: 'befehlTrampeln', label: 'Befehl Trampeln', cost: 0, category: SpecialAbilityCategory.Command, prerequisite: [], url: 'https://dsa.ulisses-regelwiki.de/sf_Befehl_Trampeln.html' },
  {
    name: 'befehlUberrennen',
    label: 'Befehl Überrennen',
    cost: 0,
    category: SpecialAbilityCategory.Command,
    prerequisite: [],
    url: 'https://dsa.ulisses-regelwiki.de/sf_Befehl_Ueberrennen.html',
  },
];

// â”€â”€â”€ Schicksalspunkte-Sonderfertigkeiten (Fate Point SF) â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
export const FATE_POINT_SPECIAL_ABILITIES: SpecialAbility[] = [
  {
    name: 'attackeVerbessern',
    label: 'Attacke verbessern',
    cost: 5,
    category: SpecialAbilityCategory.FatePoint,
    prerequisite: [],
    url: 'https://dsa.ulisses-regelwiki.de/SF_Attacke_verbessern.html',
  },
  {
    name: 'ausweichenVerbessern',
    label: 'Ausweichen verbessern',
    cost: 5,
    category: SpecialAbilityCategory.FatePoint,
    prerequisite: [],
    url: 'https://dsa.ulisses-regelwiki.de/SF_Ausweichen_verbessern.html',
  },
  {
    name: 'beistandDerGotter',
    label: 'Beistand der Götter I-II',
    cost: 0,
    category: SpecialAbilityCategory.FatePoint,
    lvl: 1,
    maxLvl: 2,
    prerequisite: [],
    url: 'https://dsa.ulisses-regelwiki.de/SF_Beistand_der_Goetter_I-II.html',
  },
  {
    name: 'eigenschaftVerbessern',
    label: 'Eigenschaft verbessern',
    cost: 5,
    category: SpecialAbilityCategory.FatePoint,
    prerequisite: [],
    url: 'https://dsa.ulisses-regelwiki.de/SF_Eigenschaft_verbessern.html',
  },
  {
    name: 'elementarrettung',
    label: 'Elementarrettung I-III',
    cost: 0,
    category: SpecialAbilityCategory.FatePoint,
    lvl: 1,
    maxLvl: 3,
    prerequisite: [],
    url: 'https://dsa.ulisses-regelwiki.de/SF_Elementarrettung_I-III.html',
  },
  { name: 'empathie', label: 'Empathie', cost: 0, category: SpecialAbilityCategory.FatePoint, prerequisite: [], url: 'https://dsa.ulisses-regelwiki.de/SF_Empathie.html' },
  {
    name: 'erholsameRegeneration',
    label: 'Erholsame Regeneration',
    cost: 0,
    category: SpecialAbilityCategory.FatePoint,
    prerequisite: [],
    url: 'https://dsa.ulisses-regelwiki.de/SF_Erholsame_Regeneration.html',
  },
  { name: 'feenrettung', label: 'Feenrettung', cost: 0, category: SpecialAbilityCategory.FatePoint, prerequisite: [], url: 'https://dsa.ulisses-regelwiki.de/SF_Feenrettung.html' },
  {
    name: 'fernkampfVerbessern',
    label: 'Fernkampf verbessern',
    cost: 5,
    category: SpecialAbilityCategory.FatePoint,
    prerequisite: [],
    url: 'https://dsa.ulisses-regelwiki.de/SF_Fernkampf_verbessern.html',
  },
  { name: 'fleischwunde', label: 'Fleischwunde', cost: 0, category: SpecialAbilityCategory.FatePoint, prerequisite: [], url: 'https://dsa.ulisses-regelwiki.de/SF_Fleischwunde.html' },
  {
    name: 'freundVonFreunden',
    label: 'Freund von Freunden',
    cost: 0,
    category: SpecialAbilityCategory.FatePoint,
    prerequisite: [],
    url: 'https://dsa.ulisses-regelwiki.de/SF_Freund_von_Freunden.html',
  },
  {
    name: 'gespurFurDasBose',
    label: 'Gespür für das Böse',
    cost: 0,
    category: SpecialAbilityCategory.FatePoint,
    prerequisite: [],
    url: 'https://dsa.ulisses-regelwiki.de/SF_Gespur_fuer_das_Boese.html',
  },
  { name: 'haltetDurch', label: 'Haltet durch!', cost: 0, category: SpecialAbilityCategory.FatePoint, prerequisite: [], url: 'https://dsa.ulisses-regelwiki.de/SF_Haltet_durch.html' },
  {
    name: 'heilkraft',
    label: 'Heilkraft I-III',
    cost: 0,
    category: SpecialAbilityCategory.FatePoint,
    lvl: 1,
    maxLvl: 3,
    prerequisite: [],
    url: 'https://dsa.ulisses-regelwiki.de/SF_Heilkraft_I-III.html',
  },
  { name: 'letzteReserve', label: 'Letzte Reserve', cost: 0, category: SpecialAbilityCategory.FatePoint, prerequisite: [], url: 'https://dsa.ulisses-regelwiki.de/SF_Letzte_Reserve.html' },
  { name: 'magiegespur', label: 'Magiegespür', cost: 0, category: SpecialAbilityCategory.FatePoint, prerequisite: [], url: 'https://dsa.ulisses-regelwiki.de/SF_Magiegespur.html' },
  {
    name: 'paradeVerbessern',
    label: 'Parade verbessern',
    cost: 5,
    category: SpecialAbilityCategory.FatePoint,
    prerequisite: [],
    url: 'https://dsa.ulisses-regelwiki.de/SF_Parade_verbessern.html',
  },
  { name: 'prophezeiung', label: 'Prophezeiung', cost: 0, category: SpecialAbilityCategory.FatePoint, prerequisite: [], url: 'https://dsa.ulisses-regelwiki.de/SF_Prophezeiung.html' },
  { name: 'schicksalsmacht', label: 'Schicksalsmacht', cost: 15, category: SpecialAbilityCategory.FatePoint, prerequisite: [], url: 'https://dsa.ulisses-regelwiki.de/SF_Schicksalsmacht.html' },
  { name: 'wachsamkeit', label: 'Wachsamkeit', cost: 0, category: SpecialAbilityCategory.FatePoint, prerequisite: [], url: 'https://dsa.ulisses-regelwiki.de/SF_Wachsamkeit.html' },
  {
    name: 'winkDesSchicksals',
    label: 'Wink des Schicksals',
    cost: 12,
    category: SpecialAbilityCategory.FatePoint,
    prerequisite: [],
    url: 'https://dsa.ulisses-regelwiki.de/SF_Wink_des_Schicksals.html',
  },
  {
    name: 'zeichenDesSchicksals',
    label: 'Zeichen des Schicksals',
    cost: 0,
    category: SpecialAbilityCategory.FatePoint,
    prerequisite: [],
    url: 'https://dsa.ulisses-regelwiki.de/SF_Zeichen_des_Schicksals.html',
  },
];

// â”€â”€â”€ Prügel-Sonderfertigkeiten (Brawling SF) â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
export const BRAWLING_SPECIAL_ABILITIES: SpecialAbility[] = [
  {
    name: 'backpfeifenSturm',
    label: 'Backpfeifen-Sturm',
    cost: 0,
    category: SpecialAbilityCategory.Brawling,
    prerequisite: [],
    url: 'https://dsa.ulisses-regelwiki.de/SF_Backpfeifen-Sturm.html',
  },
  { name: 'durchDieWand', label: 'Durch die Wand', cost: 0, category: SpecialAbilityCategory.Brawling, prerequisite: [], url: 'https://dsa.ulisses-regelwiki.de/SF_Durch_die_Wand.html' },
  {
    name: 'hoseHerunterziehen',
    label: 'Hose Herunterziehen/Hemd Hochziehen',
    cost: 0,
    category: SpecialAbilityCategory.Brawling,
    prerequisite: [],
    url: 'https://dsa.ulisses-regelwiki.de/SF_Hose_Herunterziehen.html',
  },
  {
    name: 'kneipenBlutgratsche',
    label: 'Kneipen-Blutgrätsche',
    cost: 0,
    category: SpecialAbilityCategory.Brawling,
    prerequisite: [],
    url: 'https://dsa.ulisses-regelwiki.de/SF_Kneipen-Blutgraetsche.html',
  },
  {
    name: 'kneipenGeschossabwehr',
    label: 'Kneipen-Geschossabwehr',
    cost: 0,
    category: SpecialAbilityCategory.Brawling,
    prerequisite: [],
    url: 'https://dsa.ulisses-regelwiki.de/SF_Kneipen-Geschossabwehr.html',
  },
  {
    name: 'kneipenKopfstoss',
    label: 'Kneipen-Kopfstoß',
    cost: 0,
    category: SpecialAbilityCategory.Brawling,
    prerequisite: [],
    url: 'https://dsa.ulisses-regelwiki.de/SF_Kneipen-Kopfstoss.html',
  },
  {
    name: 'kopfeAneinanderschlagen',
    label: 'Köpfe Aneinanderschlagen',
    cost: 0,
    category: SpecialAbilityCategory.Brawling,
    prerequisite: [],
    url: 'https://dsa.ulisses-regelwiki.de/SF_Koepfe_Aneinanderschlagen.html',
  },
  {
    name: 'schlagAufDenKopf',
    label: 'Schlag auf den Kopf',
    cost: 0,
    category: SpecialAbilityCategory.Brawling,
    prerequisite: [],
    url: 'https://dsa.ulisses-regelwiki.de/SF_Schlag_auf_den_Kopf.html',
  },
  {
    name: 'turGegenDenKopfKnallen',
    label: 'Tür gegen den Kopf Knallen',
    cost: 0,
    category: SpecialAbilityCategory.Brawling,
    prerequisite: [],
    url: 'https://dsa.ulisses-regelwiki.de/SF_Tuer_gegen_den_Kopf_Knallen.html',
  },
];

// â”€â”€â”€ Sprachen (Languages) â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
// Languages cost 2 AP per level (I-III), some restricted to max II
export const LANGUAGE_SPECIAL_ABILITIES: SpecialAbility[] = [
  {
    name: 'sprache_garethi',
    label: 'Sprache: Garethi',
    cost: 2,
    category: SpecialAbilityCategory.Language,
    lvl: 1,
    maxLvl: 3,
    prerequisite: [],
    url: 'https://dsa.ulisses-regelwiki.de/Sprachen.html',
  },
  {
    name: 'sprache_tulamidya',
    label: 'Sprache: Tulamidya',
    cost: 2,
    category: SpecialAbilityCategory.Language,
    lvl: 1,
    maxLvl: 3,
    prerequisite: [],
    url: 'https://dsa.ulisses-regelwiki.de/Sprachen.html',
  },
  {
    name: 'sprache_thorwalsch',
    label: 'Sprache: Thorwalsch',
    cost: 2,
    category: SpecialAbilityCategory.Language,
    lvl: 1,
    maxLvl: 3,
    prerequisite: [],
    url: 'https://dsa.ulisses-regelwiki.de/Sprachen.html',
  },
  {
    name: 'sprache_bosparano',
    label: 'Sprache: Bosparano',
    cost: 2,
    category: SpecialAbilityCategory.Language,
    lvl: 1,
    maxLvl: 3,
    prerequisite: [],
    url: 'https://dsa.ulisses-regelwiki.de/Sprachen.html',
  },
  {
    name: 'sprache_isdira',
    label: 'Sprache: Isdira',
    cost: 2,
    category: SpecialAbilityCategory.Language,
    lvl: 1,
    maxLvl: 3,
    prerequisite: [],
    url: 'https://dsa.ulisses-regelwiki.de/Sprachen.html',
  },
  {
    name: 'sprache_asdharia',
    label: 'Sprache: Asdharia',
    cost: 2,
    category: SpecialAbilityCategory.Language,
    lvl: 1,
    maxLvl: 3,
    prerequisite: [],
    url: 'https://dsa.ulisses-regelwiki.de/Sprachen.html',
  },
  {
    name: 'sprache_rogolan',
    label: 'Sprache: Rogolan',
    cost: 2,
    category: SpecialAbilityCategory.Language,
    lvl: 1,
    maxLvl: 3,
    prerequisite: [],
    url: 'https://dsa.ulisses-regelwiki.de/Sprachen.html',
  },
  {
    name: 'sprache_rssahh',
    label: 'Sprache: Rssahh',
    cost: 2,
    category: SpecialAbilityCategory.Language,
    lvl: 1,
    maxLvl: 3,
    prerequisite: [],
    url: 'https://dsa.ulisses-regelwiki.de/Sprachen.html',
  },
  {
    name: 'sprache_alaani',
    label: 'Sprache: Alaani',
    cost: 2,
    category: SpecialAbilityCategory.Language,
    lvl: 1,
    maxLvl: 3,
    prerequisite: [],
    url: 'https://dsa.ulisses-regelwiki.de/Sprachen.html',
  },
  {
    name: 'sprache_atak',
    label: 'Sprache: Atak',
    cost: 2,
    category: SpecialAbilityCategory.Language,
    lvl: 1,
    maxLvl: 3,
    prerequisite: [],
    url: 'https://dsa.ulisses-regelwiki.de/Sprachen.html',
  },
  {
    name: 'sprache_aureliani',
    label: 'Sprache: Aureliani',
    cost: 2,
    category: SpecialAbilityCategory.Language,
    lvl: 1,
    maxLvl: 3,
    prerequisite: [],
    url: 'https://dsa.ulisses-regelwiki.de/Sprachen.html',
  },
  {
    name: 'sprache_fjarningsch',
    label: 'Sprache: Fjarningsch',
    cost: 2,
    category: SpecialAbilityCategory.Language,
    lvl: 1,
    maxLvl: 3,
    prerequisite: [],
    url: 'https://dsa.ulisses-regelwiki.de/Sprachen.html',
  },
  {
    name: 'sprache_goblinisch',
    label: 'Sprache: Goblinisch',
    cost: 2,
    category: SpecialAbilityCategory.Language,
    lvl: 1,
    maxLvl: 3,
    prerequisite: [],
    url: 'https://dsa.ulisses-regelwiki.de/Sprachen.html',
  },
  {
    name: 'sprache_gjalskisch',
    label: 'Sprache: Gjalskisch',
    cost: 2,
    category: SpecialAbilityCategory.Language,
    lvl: 1,
    maxLvl: 3,
    prerequisite: [],
    url: 'https://dsa.ulisses-regelwiki.de/Sprachen.html',
  },
  {
    name: 'sprache_nujuka',
    label: 'Sprache: Nujuka',
    cost: 2,
    category: SpecialAbilityCategory.Language,
    lvl: 1,
    maxLvl: 3,
    prerequisite: [],
    url: 'https://dsa.ulisses-regelwiki.de/Sprachen.html',
  },
  {
    name: 'sprache_ologhaijan',
    label: 'Sprache: Ologhaijan',
    cost: 2,
    category: SpecialAbilityCategory.Language,
    lvl: 1,
    maxLvl: 3,
    prerequisite: [],
    url: 'https://dsa.ulisses-regelwiki.de/Sprachen.html',
  },
  {
    name: 'sprache_oloarkh',
    label: 'Sprache: Oloarkh',
    cost: 2,
    category: SpecialAbilityCategory.Language,
    lvl: 1,
    maxLvl: 2,
    prerequisite: [],
    url: 'https://dsa.ulisses-regelwiki.de/Sprachen.html',
  },
  {
    name: 'sprache_tahaya',
    label: 'Sprache: Tahaya',
    cost: 2,
    category: SpecialAbilityCategory.Language,
    lvl: 1,
    maxLvl: 3,
    prerequisite: [],
    url: 'https://dsa.ulisses-regelwiki.de/Sprachen.html',
  },
  {
    name: 'sprache_urTulamidya',
    label: 'Sprache: Ur-Tulamidya',
    cost: 2,
    category: SpecialAbilityCategory.Language,
    lvl: 1,
    maxLvl: 3,
    prerequisite: [],
    url: 'https://dsa.ulisses-regelwiki.de/Sprachen.html',
  },
  {
    name: 'sprache_zhayad',
    label: 'Sprache: Zhayad',
    cost: 2,
    category: SpecialAbilityCategory.Language,
    lvl: 1,
    maxLvl: 3,
    prerequisite: [],
    url: 'https://dsa.ulisses-regelwiki.de/Sprachen.html',
  },
  {
    name: 'sprache_angram',
    label: 'Sprache: Angram',
    cost: 2,
    category: SpecialAbilityCategory.Language,
    lvl: 1,
    maxLvl: 3,
    prerequisite: [],
    url: 'https://dsa.ulisses-regelwiki.de/Sprachen.html',
  },
  {
    name: 'sprache_sagaThorwalsch',
    label: 'Sprache: Saga-Thorwalsch',
    cost: 2,
    category: SpecialAbilityCategory.Language,
    lvl: 1,
    maxLvl: 3,
    prerequisite: [],
    url: 'https://dsa.ulisses-regelwiki.de/Sprachen.html',
  },
  {
    name: 'sprache_ferkina',
    label: 'Sprache: Ferkina',
    cost: 2,
    category: SpecialAbilityCategory.Language,
    lvl: 1,
    maxLvl: 3,
    prerequisite: [],
    url: 'https://dsa.ulisses-regelwiki.de/Sprachen.html',
  },
  {
    name: 'sprache_ruuz',
    label: 'Sprache: Ruuz',
    cost: 2,
    category: SpecialAbilityCategory.Language,
    lvl: 1,
    maxLvl: 3,
    prerequisite: [],
    url: 'https://dsa.ulisses-regelwiki.de/Sprachen.html',
  },
  {
    name: 'sprache_zelemja',
    label: 'Sprache: Zelemja',
    cost: 2,
    category: SpecialAbilityCategory.Language,
    lvl: 1,
    maxLvl: 3,
    prerequisite: [],
    url: 'https://dsa.ulisses-regelwiki.de/Sprachen.html',
  },
  {
    name: 'sprache_trollisch',
    label: 'Sprache: Trollisch',
    cost: 2,
    category: SpecialAbilityCategory.Language,
    lvl: 1,
    maxLvl: 3,
    prerequisite: [],
    url: 'https://dsa.ulisses-regelwiki.de/Sprachen.html',
  },
  {
    name: 'sprache_rabensprache',
    label: 'Sprache: Rabensprache',
    cost: 2,
    category: SpecialAbilityCategory.Language,
    lvl: 1,
    maxLvl: 3,
    prerequisite: [],
    url: 'https://dsa.ulisses-regelwiki.de/Sprachen.html',
  },
  {
    name: 'sprache_zyklopaeisch',
    label: 'Sprache: Zyklopäisch',
    cost: 2,
    category: SpecialAbilityCategory.Language,
    lvl: 1,
    maxLvl: 3,
    prerequisite: [],
    url: 'https://dsa.ulisses-regelwiki.de/Sprachen.html',
  },
  {
    name: 'sprache_adorunu',
    label: 'Sprache: Adorunu',
    cost: 2,
    category: SpecialAbilityCategory.Language,
    lvl: 1,
    maxLvl: 3,
    prerequisite: [],
    url: 'https://dsa.ulisses-regelwiki.de/Sprachen.html',
  },
  {
    name: 'sprache_amuurak',
    label: 'Sprache: Amuurak',
    cost: 2,
    category: SpecialAbilityCategory.Language,
    lvl: 1,
    maxLvl: 2,
    prerequisite: [],
    url: 'https://dsa.ulisses-regelwiki.de/Sprachen.html',
  },
  {
    name: 'sprache_krakonisch',
    label: 'Sprache: Krakonisch',
    cost: 2,
    category: SpecialAbilityCategory.Language,
    lvl: 1,
    maxLvl: 3,
    prerequisite: [],
    url: 'https://dsa.ulisses-regelwiki.de/Sprachen.html',
  },
  {
    name: 'sprache_rissoal',
    label: 'Sprache: Rissoal',
    cost: 2,
    category: SpecialAbilityCategory.Language,
    lvl: 1,
    maxLvl: 3,
    prerequisite: [],
    url: 'https://dsa.ulisses-regelwiki.de/Sprachen.html',
  },
  {
    name: 'sprache_tiefzwergisch',
    label: 'Sprache: Tiefzwergisch',
    cost: 2,
    category: SpecialAbilityCategory.Language,
    lvl: 1,
    maxLvl: 2,
    prerequisite: [],
    url: 'https://dsa.ulisses-regelwiki.de/Sprachen.html',
  },
  {
    name: 'sprache_ogrisch',
    label: 'Sprache: Ogrisch',
    cost: 2,
    category: SpecialAbilityCategory.Language,
    lvl: 1,
    maxLvl: 2,
    prerequisite: [],
    url: 'https://dsa.ulisses-regelwiki.de/Sprachen.html',
  },
  {
    name: 'sprache_molochisch',
    label: 'Sprache: Molochisch',
    cost: 2,
    category: SpecialAbilityCategory.Language,
    lvl: 1,
    maxLvl: 3,
    prerequisite: [],
    url: 'https://dsa.ulisses-regelwiki.de/Sprachen.html',
  },
  {
    name: 'sprache_bukanisch',
    label: 'Sprache: Bukanisch',
    cost: 2,
    category: SpecialAbilityCategory.Language,
    lvl: 1,
    maxLvl: 3,
    prerequisite: [],
    url: 'https://dsa.ulisses-regelwiki.de/Sprachen.html',
  },
  {
    name: 'sprache_grolmisch',
    label: 'Sprache: Grolmisch',
    cost: 2,
    category: SpecialAbilityCategory.Language,
    lvl: 1,
    maxLvl: 3,
    prerequisite: [],
    url: 'https://dsa.ulisses-regelwiki.de/Sprachen.html',
  },
  {
    name: 'sprache_golp',
    label: 'Sprache: Golp',
    cost: 2,
    category: SpecialAbilityCategory.Language,
    lvl: 1,
    maxLvl: 2,
    prerequisite: [],
    url: 'https://dsa.ulisses-regelwiki.de/Sprachen.html',
  },
  {
    name: 'sprache_yetan',
    label: 'Sprache: Yetan',
    cost: 2,
    category: SpecialAbilityCategory.Language,
    lvl: 1,
    maxLvl: 3,
    prerequisite: [],
    url: 'https://dsa.ulisses-regelwiki.de/Sprachen.html',
  },
  {
    name: 'sprache_zhulchammaqra',
    label: 'Sprache: Zhulchammaqra',
    cost: 2,
    category: SpecialAbilityCategory.Language,
    lvl: 1,
    maxLvl: 3,
    prerequisite: [],
    url: 'https://dsa.ulisses-regelwiki.de/Sprachen.html',
  },
];

// â”€â”€â”€ Schriften (Scripts) â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
// Cost values are per the Regelwiki Sprachen page
export const SCRIPT_SPECIAL_ABILITIES: SpecialAbility[] = [
  {
    name: 'schrift_kuslikerZeichen',
    label: 'Schrift: Kusliker Zeichen',
    cost: 2,
    category: SpecialAbilityCategory.Script,
    prerequisite: [],
    url: 'https://dsa.ulisses-regelwiki.de/Sprachen.html',
  },
  {
    name: 'schrift_tulamidyaZeichen',
    label: 'Schrift: Tulamidya-Zeichen',
    cost: 2,
    category: SpecialAbilityCategory.Script,
    prerequisite: [],
    url: 'https://dsa.ulisses-regelwiki.de/Sprachen.html',
  },
  {
    name: 'schrift_thorwalscheRunen',
    label: 'Schrift: Thorwalsche Runen',
    cost: 2,
    category: SpecialAbilityCategory.Script,
    prerequisite: [],
    url: 'https://dsa.ulisses-regelwiki.de/Sprachen.html',
  },
  {
    name: 'schrift_imperialeZeichen',
    label: 'Schrift: Imperiale Zeichen',
    cost: 2,
    category: SpecialAbilityCategory.Script,
    prerequisite: [],
    url: 'https://dsa.ulisses-regelwiki.de/Sprachen.html',
  },
  {
    name: 'schrift_isdiraZeichen',
    label: 'Schrift: Isdira-/Asdharia-Zeichen',
    cost: 2,
    category: SpecialAbilityCategory.Script,
    prerequisite: [],
    url: 'https://dsa.ulisses-regelwiki.de/Sprachen.html',
  },
  { name: 'schrift_rogolanRunen', label: 'Schrift: Rogolan-Runen', cost: 2, category: SpecialAbilityCategory.Script, prerequisite: [], url: 'https://dsa.ulisses-regelwiki.de/Sprachen.html' },
  { name: 'schrift_chrmk', label: 'Schrift: Chrmk', cost: 4, category: SpecialAbilityCategory.Script, prerequisite: [], url: 'https://dsa.ulisses-regelwiki.de/Sprachen.html' },
  {
    name: 'schrift_hjaldingscheRunen',
    label: 'Schrift: Hjaldingsche Runen',
    cost: 2,
    category: SpecialAbilityCategory.Script,
    prerequisite: [],
    url: 'https://dsa.ulisses-regelwiki.de/Sprachen.html',
  },
  {
    name: 'schrift_nanduriazZeichen',
    label: 'Schrift: Nanduria-Zeichen',
    cost: 2,
    category: SpecialAbilityCategory.Script,
    prerequisite: [],
    url: 'https://dsa.ulisses-regelwiki.de/Sprachen.html',
  },
  {
    name: 'schrift_adorunuZeichen',
    label: 'Schrift: Adorunu-Zeichen',
    cost: 2,
    category: SpecialAbilityCategory.Script,
    prerequisite: [],
    url: 'https://dsa.ulisses-regelwiki.de/Sprachen.html',
  },
  {
    name: 'schrift_angramBilderschrift',
    label: 'Schrift: Angram-Bilderschrift',
    cost: 4,
    category: SpecialAbilityCategory.Script,
    prerequisite: [],
    url: 'https://dsa.ulisses-regelwiki.de/Sprachen.html',
  },
  { name: 'schrift_gimaril', label: 'Schrift: Gimaril', cost: 4, category: SpecialAbilityCategory.Script, prerequisite: [], url: 'https://dsa.ulisses-regelwiki.de/Sprachen.html' },
  { name: 'schrift_gjalskerRunen', label: 'Schrift: Gjalsker Runen', cost: 4, category: SpecialAbilityCategory.Script, prerequisite: [], url: 'https://dsa.ulisses-regelwiki.de/Sprachen.html' },
  { name: 'schrift_drakhardZinke', label: 'Schrift: Drakhard-Zinke', cost: 4, category: SpecialAbilityCategory.Script, prerequisite: [], url: 'https://dsa.ulisses-regelwiki.de/Sprachen.html' },
  {
    name: 'schrift_geheiligteGlyphenVonUnau',
    label: 'Schrift: Geheiligte Glyphen von Unau',
    cost: 2,
    category: SpecialAbilityCategory.Script,
    prerequisite: [],
    url: 'https://dsa.ulisses-regelwiki.de/Sprachen.html',
  },
  {
    name: 'schrift_urTulamidyaZeichen',
    label: 'Schrift: Ur-Tulamidya-Zeichen',
    cost: 2,
    category: SpecialAbilityCategory.Script,
    prerequisite: [],
    url: 'https://dsa.ulisses-regelwiki.de/Sprachen.html',
  },
  {
    name: 'schrift_zhayadzZeichen',
    label: 'Schrift: Zhayad-Zeichen',
    cost: 2,
    category: SpecialAbilityCategory.Script,
    prerequisite: [],
    url: 'https://dsa.ulisses-regelwiki.de/Sprachen.html',
  },
  {
    name: 'schrift_amulashtraGlyphenAlt',
    label: 'Schrift: Amulashtra-Glyphen, alt',
    cost: 6,
    category: SpecialAbilityCategory.Script,
    prerequisite: [],
    url: 'https://dsa.ulisses-regelwiki.de/Sprachen.html',
  },
  {
    name: 'schrift_amulashtraGlyphenModern',
    label: 'Schrift: Amulashtra-Glyphen, modern',
    cost: 4,
    category: SpecialAbilityCategory.Script,
    prerequisite: [],
    url: 'https://dsa.ulisses-regelwiki.de/Sprachen.html',
  },
  { name: 'schrift_altesAlaani', label: 'Schrift: Altes Alaani', cost: 4, category: SpecialAbilityCategory.Script, prerequisite: [], url: 'https://dsa.ulisses-regelwiki.de/Sprachen.html' },
  { name: 'schrift_chuchas', label: 'Schrift: Chuchas', cost: 6, category: SpecialAbilityCategory.Script, prerequisite: [], url: 'https://dsa.ulisses-regelwiki.de/Sprachen.html' },
  {
    name: 'schrift_trollischeRaumbilderschrift',
    label: 'Schrift: Trollische Raumbilderschrift',
    cost: 6,
    category: SpecialAbilityCategory.Script,
    prerequisite: [],
    url: 'https://dsa.ulisses-regelwiki.de/Sprachen.html',
  },
  { name: 'schrift_kemiSymbole', label: 'Schrift: Kemi-Symbole', cost: 6, category: SpecialAbilityCategory.Script, prerequisite: [], url: 'https://dsa.ulisses-regelwiki.de/Sprachen.html' },
  {
    name: 'schrift_mahrischeGlyphen',
    label: 'Schrift: Mahrische Glyphen',
    cost: 6,
    category: SpecialAbilityCategory.Script,
    prerequisite: [],
    url: 'https://dsa.ulisses-regelwiki.de/Sprachen.html',
  },
  { name: 'schrift_arkanil', label: 'Schrift: Arkanil', cost: 8, category: SpecialAbilityCategory.Script, prerequisite: [], url: 'https://dsa.ulisses-regelwiki.de/Sprachen.html' },
  {
    name: 'schrift_draknedGlyphen',
    label: 'Schrift: Drakned-Glyphen',
    cost: 6,
    category: SpecialAbilityCategory.Script,
    prerequisite: [],
    url: 'https://dsa.ulisses-regelwiki.de/Sprachen.html',
  },
];

// â”€â”€â”€ Alle profanen Sonderfertigkeiten zusammengefasst â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
export const ALL_PROFANE_SPECIAL_ABILITIES: SpecialAbility[] = [
  ...GENERAL_SPECIAL_ABILITIES,
  ...COMBAT_SPECIAL_ABILITIES,
  ...COMBAT_STYLE_SPECIAL_ABILITIES,
  ...COMMAND_SPECIAL_ABILITIES,
  ...FATE_POINT_SPECIAL_ABILITIES,
  ...BRAWLING_SPECIAL_ABILITIES,
  ...LANGUAGE_SPECIAL_ABILITIES,
  ...SCRIPT_SPECIAL_ABILITIES,
];
