import { Species, SpeciesType } from '../models/species.model';

export const ALL_SPECIES: Species[] = [
  // ── Mensch ── RW 88
  {
    type: SpeciesType.Human,
    name: SpeciesType.Human,
    label: 'Mensch',
    image: 'spezies_mensch',
    apCost: 0,
    baseStats: { le: 5, sk: -5, zk: -5, gs: 8 },
    attributeMods: [{ type: 'choice', selectionOptions: ['MU', 'KL', 'IN', 'CH', 'FF', 'GE', 'KO', 'KK'], modifier: 1 }],
    autoAdvantages: [],
    autoDisadvantages: [],
    recommendedAdvantages: [],
    recommendedDisadvantages: [],
    typicalAdvantages: [
      { group: 'Nivesen', advantages: ['entfernungssinn', 'kalteresistenz'] },
      { group: 'Thorwaler', advantages: ['hoheZahigkeit', 'zaherHund'] },
      { group: 'Tulamiden', advantages: ['hitzeresistenz'] },
      {
        group: 'Waldmenschen & Utulus',
        advantages: ['angenehmerGeruch', 'hitzeresistenz', { name: 'immunitatGift', option: 'wurara' }, { name: 'immunitatKrankheit', option: 'flinkerdifar' }, { name: 'immunitatKrankheit', option: 'brabakerschweiss' }],
      },
    ],
    typicalDisadvantages: [
      { group: 'Nivesen', advantages: ['hitzeempfindlich'] },
      { group: 'Thorwaler', advantages: ['blutrausch', 'niedrigeSeelenkraft'] },
      { group: 'Tulamiden, Waldmenschen & Utulus', advantages: ['kalteempfindlich'] },
    ],
    atypicalAdvantages: [],
    atypicalDisadvantages: [],
  },
  // ── Elf ── RW 90
  {
    type: SpeciesType.Elf,
    name: SpeciesType.Elf,
    label: 'Elf',
    image: 'spezies_elf',
    apCost: 18,
    baseStats: { le: 2, sk: -4, zk: -6, gs: 8 },
    attributeMods: [
      { type: 'fixed', attribute: 'IN', modifier: 1 },
      { type: 'fixed', attribute: 'GE', modifier: 1 },
      { type: 'choice', selectionOptions: ['KL', 'KK'], modifier: -2 },
    ],
    autoAdvantages: ['zauberer', 'zweistimmigerGesang'],
    autoDisadvantages: [],
    recommendedAdvantages: ['altersresistenz', 'dunkelsicht', 'nichtschlafer'],
    recommendedDisadvantages: ['sensiblerGeruchssinn', { name: 'unfahig', option: 'zechen' }],
    typicalAdvantages: [
      {
        advantages: [
          { name: 'begabung', option: 'singen' },
          { name: 'begabung', option: 'musizieren' },
          'beidhandig',
          { name: 'dunkelsicht', lvl: 2 },
          'flink',
          { name: 'giftresistenz', lvl: 2 },
          { name: 'gutaussehend', lvl: 2 },
          { name: 'herausragenderSinn', option: 'gehoer' },
          { name: 'herausragenderSinn', option: 'sicht' },
          { name: 'immunitatKrankheit', option: 'schwarzewut' },
          { name: 'immunitatKrankheit', option: 'tollwut' },
          { name: 'immunitatKrankheit', option: 'lykanthropieueb' },
          { name: 'krankheitsresistenz', lvl: 2 },
          'richtungssinn',
          'schlangenmensch',
          { name: 'verbesserteRegenerationAsp', lvl: 3 },
          'wohlklang',
        ],
      },
    ],
    typicalDisadvantages: [{ advantages: ['korpergebundeneKraft', 'lastigeMindergeister', 'wahrerName'] }],
    atypicalAdvantages: ['hitzeresistenz', 'schwerZuVerzaubern', 'zwergennase'],
    atypicalDisadvantages: ['blutrausch', 'eingeschrankterSinn', 'fettleibig', 'nachtblind'],
  },
  // ── Halbelf ── RW 92
  {
    type: SpeciesType.HalfElf,
    name: SpeciesType.HalfElf,
    label: 'Halbelf',
    image: 'spezies_halbelf',
    apCost: 0,
    baseStats: { le: 5, sk: -4, zk: -6, gs: 8 },
    attributeMods: [{ type: 'choice', selectionOptions: ['MU', 'KL', 'IN', 'CH', 'FF', 'GE', 'KO', 'KK'], modifier: 1 }],
    autoAdvantages: [],
    autoDisadvantages: [],
    recommendedAdvantages: [],
    recommendedDisadvantages: [],
    typicalAdvantages: [
      {
        advantages: [
          { name: 'begabung', option: 'singen' },
          { name: 'begabung', option: 'musizieren' },
          'beidhandig',
          { name: 'dunkelsicht', lvl: 1 },
          'flink',
          { name: 'gutaussehend', lvl: 2 },
          { name: 'herausragenderSinn', option: 'gehoer' },
          { name: 'herausragenderSinn', option: 'sicht' },
          'schlangenmensch',
          'wohlklang',
          'zauberer',
          'zweistimmigerGesang',
        ],
      },
    ],
    typicalDisadvantages: [{ advantages: ['sensiblerGeruchssinn', 'wahrerName'] }],
    atypicalAdvantages: ['schwerZuVerzaubern', 'zwergennase'],
    atypicalDisadvantages: ['blutrausch', 'fettleibig', { name: 'krankheitsanfallig', lvl: 2 }],
  },
  // ── Zwerg ── RW 93
  {
    type: SpeciesType.Dwarf,
    name: SpeciesType.Dwarf,
    label: 'Zwerg',
    image: 'spezies_zwerg',
    apCost: 61,
    baseStats: { le: 8, sk: -4, zk: -4, gs: 6 },
    attributeMods: [
      { type: 'fixed', attribute: 'KO', modifier: 1 },
      { type: 'fixed', attribute: 'KK', modifier: 1 },
      { type: 'choice', selectionOptions: ['CH', 'GE'], modifier: -2 },
    ],
    autoAdvantages: [],
    autoDisadvantages: [],
    recommendedAdvantages: ['dunkelsicht', { name: 'immunitatGift', option: 'tulmadron' }],
    recommendedDisadvantages: [{ name: 'unfahig', option: 'schwimmen' }],
    typicalAdvantages: [
      {
        advantages: [
          { name: 'dunkelsicht', lvl: 2 },
          'hitzeresistenz',
          'hoheZahigkeit',
          { name: 'krankheitsresistenz', lvl: 2 },
          'richtungssinn',
          'schwerZuVerzaubern',
          'zaherHund',
          'zwergennase',
        ],
      },
    ],
    typicalDisadvantages: [{ advantages: ['blutrausch'] }],
    atypicalAdvantages: ['schlangenmensch', 'wohlklang', 'zauberer'],
    atypicalDisadvantages: ['hitzeempfindlich', 'nachtblind', 'niedrigeSeelenkraft', 'niedrigeZahigkeit', 'zerbrechlich'],
  },
  // ── Achaz ── Achaz – Schuppenkleid & Lange Zungen S. 18
  {
    type: SpeciesType.Achaz,
    name: SpeciesType.Achaz,
    label: 'Achaz',
    image: 'spezies_achaz',
    apCost: 25,
    baseStats: { le: 5, sk: -4, zk: -5, gs: 8 },
    attributeMods: [
      { type: 'fixed', attribute: 'IN', modifier: 1 },
      { type: 'fixed', attribute: 'KO', modifier: 1 },
      { type: 'choice', selectionOptions: ['MU', 'KK'], modifier: -1 },
    ],
    autoAdvantages: ['dunkelsicht', { name: 'zusatzlicheGliedmasse', option: 'schwanz' }],
    autoDisadvantages: ['kaltestarre'],
    recommendedAdvantages: [
      { name: 'begabung', option: 'schwimmen' },
      { name: 'herausragenderSinn', option: 'geruch' },
      { name: 'natuerlichwaffewaffe', option: 'biss' },
      { name: 'natuerlichwaffewaffe', option: 'schwanz' },
      'naturlicherRustungsschutz',
      'richtungssinn',
    ],
    recommendedDisadvantages: [{ name: 'angstVor', option: 'dunkelheit' }, { name: 'eingeschrankterSinn', option: 'gehoer' }, { name: 'unfahig', option: 'musizieren' }, { name: 'unfahig', option: 'singen' }],
    typicalAdvantages: [{ advantages: ['greifschwanz', 'hauttasche', 'hoheZahigkeit', 'schlangenmensch', 'zeitgefuhl'] }],
    typicalDisadvantages: [{ advantages: ['nachtblind'] }],
    atypicalAdvantages: ['angenehmerGeruch', 'wohlklang'],
    atypicalDisadvantages: ['blutrausch', 'zerbrechlich'],
  },
  // ── Goblin ── Kodex der Helden S. 34
  {
    type: SpeciesType.Goblin,
    name: SpeciesType.Goblin,
    label: 'Goblin',
    image: 'spezies_goblin',
    apCost: 5,
    baseStats: { le: 3, sk: -6, zk: -5, gs: 8 },
    attributeMods: [
      { type: 'fixed', attribute: 'FF', modifier: 1 },
      { type: 'fixed', attribute: 'GE', modifier: 1 },
      { type: 'choice', selectionOptions: ['MU', 'KL'], modifier: -1 },
    ],
    autoAdvantages: ['dunkelsicht', { name: 'herausragenderSinn', option: 'gehoer' }, { name: 'herausragenderSinn', option: 'geruch' }, 'krankheitsresistenz'],
    autoDisadvantages: [],
    recommendedAdvantages: ['biss', 'flink', 'kalteresistenz', { name: 'natuerlichwaffewaffe', option: 'biss' }, 'naturlicherRustungsschutz'],
    recommendedDisadvantages: [{ name: 'schlechteEigenschaft', option: 'aberglaube' }, { name: 'schlechteEigenschaft', option: 'neugier' }],
    typicalAdvantages: [{ advantages: [{ name: 'dunkelsicht', lvl: 2 }, 'richtungssinn'] }],
    typicalDisadvantages: [{ advantages: ['niedrigeSeelenkraft'] }],
    atypicalAdvantages: [{ name: 'adel', lvl: 3 }, 'zauberer'],
    atypicalDisadvantages: ['nachtblind', 'niedrigeZahigkeit'],
  },
  // ── Halbork ── Orks – Hauer & Schwarzer Pelz S. 17
  {
    type: SpeciesType.Halforc,
    name: SpeciesType.Halforc,
    label: 'Halbork',
    image: 'spezies_halbork',
    apCost: 1,
    baseStats: { le: 6, sk: -6, zk: -5, gs: 8 },
    attributeMods: [
      { type: 'fixed', attribute: 'KO', modifier: 1 },
      { type: 'fixed', attribute: 'CH', modifier: -1 },
    ],
    autoAdvantages: ['zaherHund'],
    autoDisadvantages: [],
    recommendedAdvantages: ['biss', 'dunkelsicht', 'kalteresistenz'],
    recommendedDisadvantages: ['niedrigeSeelenkraft'],
    typicalAdvantages: [{ advantages: [{ name: 'dunkelsicht', lvl: 2 }, 'hoheZahigkeit', 'richtungssinn'] }],
    typicalDisadvantages: [{ advantages: ['blutrausch', 'niedrigeSeelenkraft', 'stechenderOrkgeruch'] }],
    atypicalAdvantages: ['angenehmerGeruch', 'wohlklang'],
    atypicalDisadvantages: ['nachtblind', 'niedrigeZahigkeit', 'zerbrechlich'],
  },
  // ── Holberker ── Orks – Hauer & Schwarzer Pelz S. 19
  {
    type: SpeciesType.Holberker,
    name: SpeciesType.Holberker,
    label: 'Holberker',
    image: 'spezies_holberker',
    apCost: 1,
    baseStats: { le: 6, sk: -6, zk: -5, gs: 8 },
    attributeMods: [
      { type: 'fixed', attribute: 'KL', modifier: -1 },
      { type: 'fixed', attribute: 'KO', modifier: 1 },
    ],
    autoAdvantages: ['zaherHund'],
    autoDisadvantages: [],
    recommendedAdvantages: [],
    recommendedDisadvantages: [],
    typicalAdvantages: [{ advantages: [{ name: 'dunkelsicht', lvl: 1 }, 'hoheZahigkeit', 'richtungssinn', 'zauberer'] }],
    typicalDisadvantages: [{ advantages: ['niedrigeSeelenkraft'] }],
    atypicalAdvantages: ['angenehmerGeruch', 'wohlklang'],
    atypicalDisadvantages: ['nachtblind', 'niedrigeZahigkeit', 'zerbrechlich'],
  },
  // ── Ork ── Orks – Hauer & Schwarzer Pelz S. 18
  {
    type: SpeciesType.Orc,
    name: SpeciesType.Orc,
    label: 'Ork',
    image: 'spezies_ork',
    apCost: 18,
    baseStats: { le: 8, sk: -6, zk: -4, gs: 8 },
    attributeMods: [
      { type: 'fixed', attribute: 'MU', modifier: 1 },
      { type: 'fixed', attribute: 'KO', modifier: 1 },
      { type: 'choice', selectionOptions: ['KL', 'CH'], modifier: -1 },
    ],
    autoAdvantages: [],
    autoDisadvantages: [],
    recommendedAdvantages: ['biss', 'dunkelsicht', 'kalteresistenz', { name: 'natuerlichwaffewaffe', option: 'biss' }, 'naturlicherRustungsschutz', 'zaherHund'],
    recommendedDisadvantages: ['niedrigeSeelenkraft', { name: 'schlechteEigenschaft', option: 'aberglaube' }, { name: 'schlechteEigenschaft', option: 'jaehzorn' }],
    typicalAdvantages: [{ advantages: [{ name: 'dunkelsicht', lvl: 2 }, 'hoheZahigkeit', 'richtungssinn'] }],
    typicalDisadvantages: [{ advantages: ['blutrausch', 'stechenderOrkgeruch'] }],
    atypicalAdvantages: ['angenehmerGeruch', 'wohlklang'],
    atypicalDisadvantages: ['nachtblind', 'niedrigeZahigkeit', 'zerbrechlich'],
  },
  // ── Nachtalb ── Helden des Wolfsfrosts S. 25
  {
    type: SpeciesType.Nachtalb,
    name: SpeciesType.Nachtalb,
    label: 'Nachtalb',
    image: 'spezies_nachtalb',
    apCost: 18,
    baseStats: { le: 2, sk: -4, zk: -6, gs: 8 },
    attributeMods: [
      { type: 'fixed', attribute: 'IN', modifier: 1 },
      { type: 'fixed', attribute: 'GE', modifier: 1 },
      { type: 'choice', selectionOptions: ['KL', 'KK'], modifier: -2 },
    ],
    autoAdvantages: ['zauberer', 'zweistimmigerGesang'],
    autoDisadvantages: [],
    recommendedAdvantages: ['altersresistenz', 'dunkelsicht', 'nichtschlafer'],
    recommendedDisadvantages: ['sensiblerGeruchssinn', { name: 'unfahig', option: 'zechen' }],
    typicalAdvantages: [
      {
        advantages: [
          'beidhandig',
          { name: 'dunkelsicht', lvl: 2 },
          'flink',
          { name: 'giftresistenz', lvl: 2 },
          { name: 'gutaussehend', lvl: 2 },
          { name: 'herausragenderSinn', option: 'gehoer' },
          { name: 'herausragenderSinn', option: 'sicht' },
          { name: 'immunitatKrankheit', option: 'schwarzewut' },
          { name: 'immunitatKrankheit', option: 'tollwut' },
          { name: 'immunitatKrankheit', option: 'lykanthropieueb' },
          { name: 'krankheitsresistenz', lvl: 2 },
          'richtungssinn',
          'schlangenmensch',
          { name: 'verbesserteRegenerationAsp', lvl: 3 },
          'wohlklang',
        ],
      },
    ],
    typicalDisadvantages: [
      {
        advantages: [
          'blutrausch',
          { name: 'empfindlichkeitunedlemetalle' },
          'hitzeempfindlich',
          'korpergebundeneKraft',
          'lichtempfindlich',
          'raubtiergeruch',
          'wahrerName',
        ],
      },
    ],
    atypicalAdvantages: [],
    atypicalDisadvantages: [],
  },
];
