import { SpecialAbility, SpecialAbilityCategory } from '../models/special-ability.model';

// â”€â”€â”€ Magische Sonderfertigkeiten â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
// Source: DSA 5 Regelwiki â€“ Magische Sonderfertigkeiten
// Cost = 0 means AP cost not yet populated (expansion book content)
// Prerequisite { name: 'zauberer', required: true } = Vorteil Zauberer required

// â”€â”€â”€ Allgemeine magische Sonderfertigkeiten â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
export const MAGIC_GENERAL_SPECIAL_ABILITIES: SpecialAbility[] = [
  // â”€â”€ Regelwerk core â”€â”€
  {
    name: 'fernzaubern',
    label: 'Fernzaubern',
    cost: 15,
    category: SpecialAbilityCategory.MagicGeneral,
    prerequisite: [{ name: 'zauberer', required: true }],
    attributeRequirement: [{ attribute: 'KL', minValue: 15 }],
    url: 'https://dsa.ulisses-regelwiki.de/msf_Fernzaubern.html',
  },
  {
    name: 'gedankenschutz',
    label: 'Gedankenschutz',
    cost: 10,
    category: SpecialAbilityCategory.MagicGeneral,
    prerequisite: [{ name: 'zauberer', required: true }],
    attributeRequirement: [{ attribute: 'MU', minValue: 13 }],
    url: 'https://dsa.ulisses-regelwiki.de/msf_Gedankenschutz.html',
  },
  {
    name: 'konzentrationstarke',
    label: 'Konzentrationsstärke',
    cost: 8,
    category: SpecialAbilityCategory.MagicGeneral,
    prerequisite: [{ name: 'zauberer', required: true }],
    attributeRequirement: [{ attribute: 'MU', minValue: 13 }],
    url: 'https://dsa.ulisses-regelwiki.de/msf_Konzentrationstaerke.html',
  },
  {
    name: 'kleineKraftkontrolle',
    label: 'Kleine Kraftkontrolle',
    cost: 10,
    category: SpecialAbilityCategory.MagicGeneral,
    prerequisite: [{ name: 'zauberer', required: true }],
    url: 'https://dsa.ulisses-regelwiki.de/msf_Kleine_Kraftkontrolle.html',
  },
  {
    name: 'kraftkontrolle',
    label: 'Kraftkontrolle',
    cost: 20,
    category: SpecialAbilityCategory.MagicGeneral,
    prerequisite: [
      { name: 'zauberer', required: true },
      { name: 'kleineKraftkontrolle', required: true },
    ],
    url: 'https://dsa.ulisses-regelwiki.de/msf_Kraftkontrolle.html',
  },
  {
    name: 'lieblingszauber',
    label: 'Lieblingszauber',
    cost: 3,
    category: SpecialAbilityCategory.MagicGeneral,
    prerequisite: [{ name: 'zauberer', required: true }],
    url: 'https://dsa.ulisses-regelwiki.de/msf_Lieblingszauber.html',
  },
  {
    name: 'lockeresZaubern',
    label: 'Lockeres Zaubern',
    cost: 15,
    category: SpecialAbilityCategory.MagicGeneral,
    prerequisite: [{ name: 'zauberer', required: true }],
    url: 'https://dsa.ulisses-regelwiki.de/msf_Lockeres_Zaubern.html',
  },
  {
    name: 'magischeRegeneration',
    label: 'Magische Regeneration I-II',
    cost: 12,
    category: SpecialAbilityCategory.MagicGeneral,
    lvl: 1,
    maxLvl: 2,
    prerequisite: [{ name: 'zauberer', required: true }],
    url: 'https://dsa.ulisses-regelwiki.de/msf_Magische_Regeneration_I-II.html',
  },
  {
    name: 'meisterlicheRegeneration',
    label: 'Meisterliche Regeneration',
    cost: 10,
    category: SpecialAbilityCategory.MagicGeneral,
    prerequisite: [{ name: 'zauberer', required: true }],
    url: 'https://dsa.ulisses-regelwiki.de/msf_Meisterliche_Regeneration.html',
  },
  {
    name: 'parallelzauberei',
    label: 'Parallelzauberei',
    cost: 15,
    category: SpecialAbilityCategory.MagicGeneral,
    prerequisite: [{ name: 'zauberer', required: true }],
    url: 'https://dsa.ulisses-regelwiki.de/msf_Parallelzauberei.html',
  },
  {
    name: 'routinierteZauberwiederholung',
    label: 'Routinierte Zauberwiederholung',
    cost: 10,
    category: SpecialAbilityCategory.MagicGeneral,
    prerequisite: [{ name: 'zauberer', required: true }],
    attributeRequirement: [{ attribute: 'KL', minValue: 13 }],
    url: 'https://dsa.ulisses-regelwiki.de/msf_Routinierte_Zauberwiederholung.html',
  },
  {
    name: 'reversalis',
    label: 'Reversalis I-II (Zauber)',
    cost: 4,
    category: SpecialAbilityCategory.MagicGeneral,
    lvl: 1,
    maxLvl: 2,
    prerequisite: [{ name: 'zauberer', required: true }],
    url: 'https://dsa.ulisses-regelwiki.de/msf_Reversalis_I-II.html',
  },
  {
    name: 'starkeZaubertricks',
    label: 'Starke Zaubertricks',
    cost: 2,
    category: SpecialAbilityCategory.MagicGeneral,
    prerequisite: [{ name: 'zauberer', required: true }],
    url: 'https://dsa.ulisses-regelwiki.de/msf_Starke_Zaubertricks.html',
  },
  {
    name: 'zauberAbbrechen',
    label: 'Zauber abbrechen',
    cost: 12,
    category: SpecialAbilityCategory.MagicGeneral,
    prerequisite: [{ name: 'zauberer', required: true }],
    url: 'https://dsa.ulisses-regelwiki.de/msf_Zauber_abbrechen.html',
  },
  {
    name: 'zauberUnterbrechen',
    label: 'Zauber unterbrechen',
    cost: 20,
    category: SpecialAbilityCategory.MagicGeneral,
    prerequisite: [
      { name: 'zauberer', required: true },
      { name: 'zauberAbbrechen', required: true },
    ],
    url: 'https://dsa.ulisses-regelwiki.de/msf_Zauber_unterbrechen.html',
  },
  {
    name: 'zauberBereithalten',
    label: 'Zauber bereithalten',
    cost: 20,
    category: SpecialAbilityCategory.MagicGeneral,
    prerequisite: [
      { name: 'zauberer', required: true },
      { name: 'zauberUnterbrechen', required: true },
    ],
    url: 'https://dsa.ulisses-regelwiki.de/msf_Zauber_bereithalten.html',
  },
  {
    name: 'zauberBundeln',
    label: 'Zauber bündeln I-II',
    cost: 15,
    category: SpecialAbilityCategory.MagicGeneral,
    lvl: 1,
    maxLvl: 2,
    prerequisite: [{ name: 'zauberer', required: true }],
    url: 'https://dsa.ulisses-regelwiki.de/msf_Zauber_buendeln_I-II.html',
  },
  // â”€â”€ Weitere allgemeine magische SF â”€â”€
  {
    name: 'abgeschwachterZauber',
    label: 'Abgeschwächter Zauber',
    cost: 0,
    category: SpecialAbilityCategory.MagicGeneral,
    prerequisite: [{ name: 'zauberer', required: true }],
    url: 'https://dsa.ulisses-regelwiki.de/msf_Abgeschwachter_Zauber.html',
  },
  {
    name: 'adaption',
    label: 'Adaption (Zauber)',
    cost: 0,
    category: SpecialAbilityCategory.MagicGeneral,
    prerequisite: [{ name: 'zauberer', required: true }],
    url: 'https://dsa.ulisses-regelwiki.de/msf_Adaption.html',
  },
  {
    name: 'alchimieverstarkung',
    label: 'Alchimieverstärkung',
    cost: 0,
    category: SpecialAbilityCategory.MagicGeneral,
    prerequisite: [{ name: 'zauberer', required: true }],
    url: 'https://dsa.ulisses-regelwiki.de/msf_Alchimieverstarkung.html',
  },
  {
    name: 'bindungDamonen',
    label: 'Bindung (Dämonen)',
    cost: 0,
    category: SpecialAbilityCategory.MagicGeneral,
    prerequisite: [{ name: 'zauberer', required: true }],
    url: 'https://dsa.ulisses-regelwiki.de/msf_Bindung_Daemonen.html',
  },
  {
    name: 'bindungElementare',
    label: 'Bindung (Elementare)',
    cost: 0,
    category: SpecialAbilityCategory.MagicGeneral,
    prerequisite: [{ name: 'zauberer', required: true }],
    url: 'https://dsa.ulisses-regelwiki.de/msf_Bindung_Elementare.html',
  },
  {
    name: 'bindungFeen',
    label: 'Bindung (Feen)',
    cost: 0,
    category: SpecialAbilityCategory.MagicGeneral,
    prerequisite: [{ name: 'zauberer', required: true }],
    url: 'https://dsa.ulisses-regelwiki.de/msf_Bindung_Feen.html',
  },
  {
    name: 'blutmagieFremdopfer',
    label: 'Blutmagie (Fremdopfer)',
    cost: 0,
    category: SpecialAbilityCategory.MagicGeneral,
    prerequisite: [{ name: 'zauberer', required: true }],
    url: 'https://dsa.ulisses-regelwiki.de/msf_Blutmagie_Fremdopfer.html',
  },
  {
    name: 'blutmagieSelbstopfer',
    label: 'Blutmagie (Selbstopfer)',
    cost: 0,
    category: SpecialAbilityCategory.MagicGeneral,
    prerequisite: [{ name: 'zauberer', required: true }],
    url: 'https://dsa.ulisses-regelwiki.de/msf_Blutmagie_Selbstopfer.html',
  },
  {
    name: 'entschwurungDamonen',
    label: 'Entschwörung (Dämonen)',
    cost: 0,
    category: SpecialAbilityCategory.MagicGeneral,
    prerequisite: [{ name: 'zauberer', required: true }],
    url: 'https://dsa.ulisses-regelwiki.de/msf_Entschwoerung_Daemonen.html',
  },
  {
    name: 'entschwurungElementare',
    label: 'Entschwörung (Elementare)',
    cost: 0,
    category: SpecialAbilityCategory.MagicGeneral,
    prerequisite: [{ name: 'zauberer', required: true }],
    url: 'https://dsa.ulisses-regelwiki.de/msf_Entschwoerung_Elementare.html',
  },
  {
    name: 'entschwurungFeen',
    label: 'Entschwörung (Feen)',
    cost: 0,
    category: SpecialAbilityCategory.MagicGeneral,
    prerequisite: [{ name: 'zauberer', required: true }],
    url: 'https://dsa.ulisses-regelwiki.de/msf_Entschwoerung_Feen.html',
  },
  {
    name: 'entschwurungGeister',
    label: 'Entschwörung (Geister)',
    cost: 0,
    category: SpecialAbilityCategory.MagicGeneral,
    prerequisite: [{ name: 'zauberer', required: true }],
    url: 'https://dsa.ulisses-regelwiki.de/msf_Entschwoerung_Geister.html',
  },
  {
    name: 'flugsalbe',
    label: 'Flugsalbe',
    cost: 0,
    category: SpecialAbilityCategory.MagicGeneral,
    prerequisite: [{ name: 'zauberer', required: true }],
    url: 'https://dsa.ulisses-regelwiki.de/msf_Flugsalbe.html',
  },
  {
    name: 'gefahrlicheTraume',
    label: 'Gefährliche Träume I-III',
    cost: 0,
    category: SpecialAbilityCategory.MagicGeneral,
    lvl: 1,
    maxLvl: 3,
    prerequisite: [{ name: 'zauberer', required: true }],
    url: 'https://dsa.ulisses-regelwiki.de/msf_Gefaehrliche_Traeume_I-III.html',
  },
  {
    name: 'gefassDerMacht',
    label: 'Gefäß der Macht',
    cost: 0,
    category: SpecialAbilityCategory.MagicGeneral,
    prerequisite: [{ name: 'zauberer', required: true }],
    url: 'https://dsa.ulisses-regelwiki.de/msf_Gefaess_der_Macht.html',
  },
  {
    name: 'hexentanz',
    label: 'Hexentanz',
    cost: 0,
    category: SpecialAbilityCategory.MagicGeneral,
    prerequisite: [{ name: 'zauberer', required: true }],
    url: 'https://dsa.ulisses-regelwiki.de/msf_Hexentanz.html',
  },
  {
    name: 'homunculusbindung',
    label: 'Homunculusbindung',
    cost: 0,
    category: SpecialAbilityCategory.MagicGeneral,
    prerequisite: [{ name: 'zauberer', required: true }],
    url: 'https://dsa.ulisses-regelwiki.de/msf_Homunculusbindung.html',
  },
  {
    name: 'imitationszauberei',
    label: 'Imitationszauberei I-V',
    cost: 0,
    category: SpecialAbilityCategory.MagicGeneral,
    lvl: 1,
    maxLvl: 5,
    prerequisite: [{ name: 'zauberer', required: true }],
    url: 'https://dsa.ulisses-regelwiki.de/msf_Imitationszauberei_I-V.html',
  },
  {
    name: 'improvisationszaubereiFormel',
    label: 'Improvisationszauberei (Formel)',
    cost: 0,
    category: SpecialAbilityCategory.MagicGeneral,
    prerequisite: [{ name: 'zauberer', required: true }],
    url: 'https://dsa.ulisses-regelwiki.de/msf_Improvisationszauberei_Formel.html',
  },
  {
    name: 'improvisationszaubereiGesten',
    label: 'Improvisationszauberei (Gesten)',
    cost: 0,
    category: SpecialAbilityCategory.MagicGeneral,
    prerequisite: [{ name: 'zauberer', required: true }],
    url: 'https://dsa.ulisses-regelwiki.de/msf_Improvisationszauberei_Gesten.html',
  },
  {
    name: 'nekromant',
    label: 'Nekromant',
    cost: 0,
    category: SpecialAbilityCategory.MagicGeneral,
    prerequisite: [{ name: 'zauberer', required: true }],
    url: 'https://dsa.ulisses-regelwiki.de/msf_Nekromant.html',
  },
  {
    name: 'ritualArtefakt',
    label: 'Ritual-Artefakt',
    cost: 0,
    category: SpecialAbilityCategory.MagicGeneral,
    prerequisite: [{ name: 'zauberer', required: true }],
    url: 'https://dsa.ulisses-regelwiki.de/msf_Ritual-Artefakt.html',
  },
  {
    name: 'signaturkenntnis',
    label: 'Signaturkenntnis',
    cost: 0,
    category: SpecialAbilityCategory.MagicGeneral,
    prerequisite: [{ name: 'zauberer', required: true }],
    url: 'https://dsa.ulisses-regelwiki.de/msf_Signaturkenntnis.html',
  },
  {
    name: 'tanzDerMada',
    label: 'Tanz der Mada',
    cost: 0,
    category: SpecialAbilityCategory.MagicGeneral,
    prerequisite: [{ name: 'zauberer', required: true }],
    url: 'https://dsa.ulisses-regelwiki.de/msf_Tanz_der_Mada.html',
  },
  {
    name: 'traumzauberei',
    label: 'Traumzauberei I-III',
    cost: 0,
    category: SpecialAbilityCategory.MagicGeneral,
    lvl: 1,
    maxLvl: 3,
    prerequisite: [{ name: 'zauberer', required: true }],
    url: 'https://dsa.ulisses-regelwiki.de/msf_Traumzauberei_I-III.html',
  },
  {
    name: 'verbotene Pforten',
    label: 'Verbotene Pforten',
    cost: 0,
    category: SpecialAbilityCategory.MagicGeneral,
    prerequisite: [{ name: 'zauberer', required: true }],
    url: 'https://dsa.ulisses-regelwiki.de/msf_Verbotene_Pforten.html',
  },
  {
    name: 'zweiteRegeneration',
    label: 'Zweite Regeneration',
    cost: 0,
    category: SpecialAbilityCategory.MagicGeneral,
    prerequisite: [{ name: 'zauberer', required: true }],
    url: 'https://dsa.ulisses-regelwiki.de/msf_Zweite_Regeneration.html',
  },
];

// â”€â”€â”€ Magische Traditionen â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
export const MAGIC_TRADITION_SPECIAL_ABILITIES: SpecialAbility[] = [
  {
    name: 'traditionGildenmagier',
    label: 'Tradition (Gildenmagier)',
    cost: 155,
    category: SpecialAbilityCategory.MagicTradition,
    prerequisite: [{ name: 'zauberer', required: true }],
    url: 'https://dsa.ulisses-regelwiki.de/tradition_Gildenmagier.html',
  },
  {
    name: 'traditionHexen',
    label: 'Tradition (Hexen)',
    cost: 130,
    category: SpecialAbilityCategory.MagicTradition,
    prerequisite: [{ name: 'zauberer', required: true }],
    url: 'https://dsa.ulisses-regelwiki.de/tradition_Hexen.html',
  },
  {
    name: 'traditionElfen',
    label: 'Tradition (Elfen)',
    cost: 125,
    category: SpecialAbilityCategory.MagicTradition,
    prerequisite: [{ name: 'zauberer', required: true }],
    url: 'https://dsa.ulisses-regelwiki.de/tradition_Elfen.html',
  },
  {
    name: 'traditionDruiden',
    label: 'Tradition (Druiden)',
    cost: 0,
    category: SpecialAbilityCategory.MagicTradition,
    prerequisite: [{ name: 'zauberer', required: true }],
    url: 'https://dsa.ulisses-regelwiki.de/tradition_Druiden.html',
  },
  {
    name: 'traditionScharlatane',
    label: 'Tradition (Scharlatane)',
    cost: 0,
    category: SpecialAbilityCategory.MagicTradition,
    prerequisite: [{ name: 'zauberer', required: true }],
    url: 'https://dsa.ulisses-regelwiki.de/tradition_Scharlatane.html',
  },
  {
    name: 'traditionZauberbarden',
    label: 'Tradition (Zauberbarden)',
    cost: 0,
    category: SpecialAbilityCategory.MagicTradition,
    prerequisite: [{ name: 'zauberer', required: true }],
    url: 'https://dsa.ulisses-regelwiki.de/tradition_Zauberbarden.html',
  },
  {
    name: 'traditionZaubertanzer',
    label: 'Tradition (Zaubertänzer)',
    cost: 0,
    category: SpecialAbilityCategory.MagicTradition,
    prerequisite: [{ name: 'zauberer', required: true }],
    url: 'https://dsa.ulisses-regelwiki.de/tradition_Zaubertaenzer.html',
  },
  {
    name: 'traditionIntuitiveZauberer',
    label: 'Tradition (Intuitive Zauberer)',
    cost: 0,
    category: SpecialAbilityCategory.MagicTradition,
    prerequisite: [{ name: 'zauberer', required: true }],
    url: 'https://dsa.ulisses-regelwiki.de/tradition_Intuitive_Zauberer.html',
  },
  {
    name: 'traditionSchelme',
    label: 'Tradition (Schelme)',
    cost: 0,
    category: SpecialAbilityCategory.MagicTradition,
    prerequisite: [{ name: 'zauberer', required: true }],
    url: 'https://dsa.ulisses-regelwiki.de/tradition_Schelme.html',
  },
  {
    name: 'traditionGeoden',
    label: 'Tradition (Geoden)',
    cost: 0,
    category: SpecialAbilityCategory.MagicTradition,
    prerequisite: [{ name: 'zauberer', required: true }],
    url: 'https://dsa.ulisses-regelwiki.de/tradition_Geoden.html',
  },
  {
    name: 'traditionAnimisten',
    label: 'Tradition (Animisten)',
    cost: 0,
    category: SpecialAbilityCategory.MagicTradition,
    prerequisite: [{ name: 'zauberer', required: true }],
    url: 'https://dsa.ulisses-regelwiki.de/tradition_Animisten.html',
  },
  {
    name: 'traditionZauberalchimisten',
    label: 'Tradition (Zauberalchimisten)',
    cost: 0,
    category: SpecialAbilityCategory.MagicTradition,
    prerequisite: [{ name: 'zauberer', required: true }],
    url: 'https://dsa.ulisses-regelwiki.de/tradition_Zauberalchimisten.html',
  },
  {
    name: 'traditionBannzeichner',
    label: 'Tradition (Bannzeichner)',
    cost: 0,
    category: SpecialAbilityCategory.MagicTradition,
    prerequisite: [{ name: 'zauberer', required: true }],
    url: 'https://dsa.ulisses-regelwiki.de/tradition_Bannzeichner.html',
  },
  {
    name: 'traditionKristallomanten',
    label: 'Tradition (Kristallomanten)',
    cost: 0,
    category: SpecialAbilityCategory.MagicTradition,
    prerequisite: [{ name: 'zauberer', required: true }],
    url: 'https://dsa.ulisses-regelwiki.de/tradition_Kristallomanten.html',
  },
  {
    name: 'traditionBorbaradianer',
    label: 'Tradition (Borbaradianer)',
    cost: 0,
    category: SpecialAbilityCategory.MagicTradition,
    prerequisite: [{ name: 'zauberer', required: true }],
    url: 'https://dsa.ulisses-regelwiki.de/tradition_Borbaradianer.html',
  },
  {
    name: 'traditionRunenschopfer',
    label: 'Tradition (Runenschöpfer)',
    cost: 0,
    category: SpecialAbilityCategory.MagicTradition,
    prerequisite: [{ name: 'zauberer', required: true }],
    url: 'https://dsa.ulisses-regelwiki.de/tradition_Runenschoepfer.html',
  },
  {
    name: 'traditionGoblinzauberinnen',
    label: 'Tradition (Goblinzauberinnen)',
    cost: 0,
    category: SpecialAbilityCategory.MagicTradition,
    prerequisite: [{ name: 'zauberer', required: true }],
    url: 'https://dsa.ulisses-regelwiki.de/tradition_Goblinzauberinnen.html',
  },
  {
    name: 'traditionMeistertalentierte',
    label: 'Tradition (Meistertalentierte)',
    cost: 0,
    category: SpecialAbilityCategory.MagicTradition,
    prerequisite: [{ name: 'zauberer', required: true }],
    url: 'https://dsa.ulisses-regelwiki.de/tradition_Meistertalentierte.html',
  },
  {
    name: 'traditionNachtalben',
    label: 'Tradition (Nachtalben)',
    cost: 0,
    category: SpecialAbilityCategory.MagicTradition,
    prerequisite: [{ name: 'zauberer', required: true }],
    url: 'https://dsa.ulisses-regelwiki.de/tradition_Nachtalben.html',
  },
  {
    name: 'traditionQabalyamagier',
    label: 'Tradition (Qabalyamagier)',
    cost: 0,
    category: SpecialAbilityCategory.MagicTradition,
    prerequisite: [{ name: 'zauberer', required: true }],
    url: 'https://dsa.ulisses-regelwiki.de/tradition_Qabalyamagier.html',
  },
  {
    name: 'traditionBrobimGeoden',
    label: 'Tradition (Brobim-Geoden)',
    cost: 0,
    category: SpecialAbilityCategory.MagicTradition,
    prerequisite: [{ name: 'zauberer', required: true }],
    url: 'https://dsa.ulisses-regelwiki.de/tradition_Brobim-Geoden.html',
  },
  {
    name: 'traditionPetromantierer',
    label: 'Tradition (Petromantierer)',
    cost: 0,
    category: SpecialAbilityCategory.MagicTradition,
    prerequisite: [{ name: 'zauberer', required: true }],
    url: 'https://dsa.ulisses-regelwiki.de/tradition_Petromantierer.html',
  },
  {
    name: 'traditionAdoruMagier',
    label: 'Tradition (Adoru-Magier)',
    cost: 0,
    category: SpecialAbilityCategory.MagicTradition,
    prerequisite: [{ name: 'zauberer', required: true }],
    url: 'https://dsa.ulisses-regelwiki.de/tradition_Adoru-Magier.html',
  },
  {
    name: 'traditionKarfunkelElfen',
    label: 'Tradition (Karfunkel-Elfen)',
    cost: 0,
    category: SpecialAbilityCategory.MagicTradition,
    prerequisite: [{ name: 'zauberer', required: true }],
    url: 'https://dsa.ulisses-regelwiki.de/tradition_Karfunkel-Elfen.html',
  },
  {
    name: 'traditionDarna',
    label: 'Tradition (Darna)',
    cost: 0,
    category: SpecialAbilityCategory.MagicTradition,
    prerequisite: [{ name: 'zauberer', required: true }],
    url: 'https://dsa.ulisses-regelwiki.de/tradition_Darna.html',
  },
  {
    name: 'traditionTsatuaraAnhangerinnen',
    label: 'Tradition (Tsatuara-Anhängerinnen)',
    cost: 0,
    category: SpecialAbilityCategory.MagicTradition,
    prerequisite: [{ name: 'zauberer', required: true }],
    url: 'https://dsa.ulisses-regelwiki.de/tradition_Tsatuara.html',
  },
  {
    name: 'traditionKristalloide',
    label: 'Tradition (Kristalloide)',
    cost: 0,
    category: SpecialAbilityCategory.MagicTradition,
    prerequisite: [{ name: 'zauberer', required: true }],
    url: 'https://dsa.ulisses-regelwiki.de/tradition_Kristalloide.html',
  },
  {
    name: 'traditionGraumotten',
    label: 'Tradition (Graumotten)',
    cost: 0,
    category: SpecialAbilityCategory.MagicTradition,
    prerequisite: [{ name: 'zauberer', required: true }],
    url: 'https://dsa.ulisses-regelwiki.de/tradition_Graumotten.html',
  },
  {
    name: 'traditionZibilja',
    label: 'Tradition (Zibilja)',
    cost: 0,
    category: SpecialAbilityCategory.MagicTradition,
    prerequisite: [{ name: 'zauberer', required: true }],
    url: 'https://dsa.ulisses-regelwiki.de/tradition_Zibilja.html',
  },
];

// â”€â”€â”€ Alle magischen Sonderfertigkeiten zusammengefasst â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
export const ALL_MAGIC_SPECIAL_ABILITIES: SpecialAbility[] = [...MAGIC_GENERAL_SPECIAL_ABILITIES, ...MAGIC_TRADITION_SPECIAL_ABILITIES];
