import { Species, SpeciesType } from '../models/species.model';

export const ALL_SPECIES: Species[] = [
  // ── Mensch ── RW 88
  {
    type: SpeciesType.Human,
    name: SpeciesType.Human,
    label: 'Mensch',
    image: 'spezies_mensch',
    apCost: 0,
    baseStats: { le: 5, sk: -5, zk: -5, gs: 8 },
    attributeMods: [{ type: 'choice', selectionOptions: ['MU', 'KL', 'IN', 'CH', 'FF', 'GE', 'KO', 'KK'], modifier: 1 }],
    autoAdvantages: [],
    autoDisadvantages: [],
    recommendedAdvantages: [],
    recommendedDisadvantages: [],
    typicalAdvantages: [
      { group: 'Nivesen', advantages: ['entfernungssinn', 'kalteresistenz'] },
      { group: 'Thorwaler', advantages: ['hoheZahigkeit', 'zaherHund'] },
      { group: 'Tulamiden', advantages: ['hitzeresistenz'] },
      {
        group: 'Waldmenschen & Utulus',
        advantages: ['angenehmerGeruch', 'hitzeresistenz', 'immunitatGift_wurara', 'immunitatKrankheit_flinkerDifar', 'immunitatKrankheit_brabakerSchweiss'],
      },
    ],
    typicalDisadvantages: [
      { group: 'Nivesen', advantages: ['hitzeempfindlich'] },
      { group: 'Thorwaler', advantages: ['blutrausch', 'niedrigeSeelenkraft'] },
      { group: 'Tulamiden, Waldmenschen & Utulus', advantages: ['kalteempfindlich'] },
    ],
  },
  // ── Elf ── RW 90
  {
    type: SpeciesType.Elf,
    name: SpeciesType.Elf,
    label: 'Elf',
    image: 'spezies_elf',
    apCost: 18,
    baseStats: { le: 2, sk: -4, zk: -6, gs: 8 },
    attributeMods: [
      { type: 'fixed', attribute: 'IN', modifier: 1 },
      { type: 'fixed', attribute: 'GE', modifier: 1 },
      { type: 'choice', selectionOptions: ['KL', 'KK'], modifier: -2 },
    ],
    autoAdvantages: ['zauberer', 'zweistimmigerGesang'],
    autoDisadvantages: [],
    recommendedAdvantages: ['altersresistenz', 'dunkelsicht', 'nichtschlafer'],
    recommendedDisadvantages: ['sensiblerGeruchssinn', 'unfahig_zechen'],
    typicalAdvantages: [
      {
        advantages: [
          'begabung_singen',
          'begabung_musizieren',
          'beidhandig',
          'dunkelsicht',
          'flink',
          'giftresistenz',
          'gutaussehend',
          'herausragenderSinn_gehor',
          'herausragenderSinn_sicht',
          'immunitatKrankheit_schwarzeWut',
          'immunitatKrankheit_tollwut',
          'immunitatKrankheit_lykanthropie',
          'krankheitsresistenz',
          'richtungssinn',
          'schlangenmensch',
          'verbesserteRegenerationAsp',
          'wohlklang',
        ],
      },
    ],
    typicalDisadvantages: [{ advantages: ['korpergebundeneKraft', 'lastigeMindergeister', 'wahrerName'] }],
  },
  // ── Halbelf ── RW 92
  {
    type: SpeciesType.HalfElf,
    name: SpeciesType.HalfElf,
    label: 'Halbelf',
    image: 'spezies_halbelf',
    apCost: 0,
    baseStats: { le: 5, sk: -4, zk: -6, gs: 8 },
    attributeMods: [{ type: 'choice', selectionOptions: ['MU', 'KL', 'IN', 'CH', 'FF', 'GE', 'KO', 'KK'], modifier: 1 }],
    autoAdvantages: [],
    autoDisadvantages: [],
    recommendedAdvantages: [],
    recommendedDisadvantages: [],
    typicalAdvantages: [
      {
        advantages: [
          'begabung_singen',
          'begabung_musizieren',
          'beidhandig',
          'dunkelsicht',
          'flink',
          'gutaussehend',
          'herausragenderSinn_gehor',
          'herausragenderSinn_sicht',
          'schlangenmensch',
          'wohlklang',
          'zauberer',
          'zweistimmigerGesang',
        ],
      },
    ],
    typicalDisadvantages: [{ advantages: ['sensiblerGeruchssinn', 'wahrerName'] }],
  },
  // ── Zwerg ── RW 93
  {
    type: SpeciesType.Dwarf,
    name: SpeciesType.Dwarf,
    label: 'Zwerg',
    image: 'spezies_zwerg',
    apCost: 61,
    baseStats: { le: 8, sk: -4, zk: -4, gs: 6 },
    attributeMods: [
      { type: 'fixed', attribute: 'KO', modifier: 1 },
      { type: 'fixed', attribute: 'KK', modifier: 1 },
      { type: 'choice', selectionOptions: ['CH', 'GE'], modifier: -2 },
    ],
    autoAdvantages: [],
    autoDisadvantages: [],
    recommendedAdvantages: ['dunkelsicht', 'immunitatGift_tulmadron'],
    recommendedDisadvantages: ['unfahig_schwimmen'],
    typicalAdvantages: [
      {
        advantages: [
          'dunkelsicht',
          'hitzeresistenz',
          'hoheZahigkeit',
          'krankheitsresistenz',
          'richtungssinn',
          'schwerZuVerzaubern',
          'zaherHund',
          'zwergennase',
        ],
      },
    ],
    typicalDisadvantages: [{ advantages: ['blutrausch'] }],
  },
  // ── Achaz ── Achaz – Schuppenkleid & Lange Zungen S. 18
  {
    type: SpeciesType.Achaz,
    name: SpeciesType.Achaz,
    label: 'Achaz',
    image: 'spezies_achaz',
    apCost: 25,
    baseStats: { le: 5, sk: -4, zk: -5, gs: 8 },
    attributeMods: [
      { type: 'fixed', attribute: 'IN', modifier: 1 },
      { type: 'fixed', attribute: 'KO', modifier: 1 },
      { type: 'choice', selectionOptions: ['MU', 'KK'], modifier: -1 },
    ],
    autoAdvantages: ['dunkelsicht', 'zusatzlicheGliedmasse_schwanz'],
    autoDisadvantages: ['kaltestarre'],
    recommendedAdvantages: [
      'begabung_schwimmen',
      'herausragenderSinn_geruch',
      'naturlicheWaffe_biss',
      'naturlicheWaffe_schwanz',
      'naturlicherRustungsschutz',
      'richtungssinn',
    ],
    recommendedDisadvantages: ['angstVor_dunkelheit', 'eingeschrankterSinn_gehor', 'unfahig_musizieren', 'unfahig_singen'],
    typicalAdvantages: [{ advantages: ['greifschwanz', 'hauttasche', 'hoheZahigkeit', 'schlangenmensch', 'zeitgefuhl'] }],
    typicalDisadvantages: [{ advantages: ['nachtblind'] }],
  },
  // ── Goblin ── Kodex der Helden S. 34
  {
    type: SpeciesType.Goblin,
    name: SpeciesType.Goblin,
    label: 'Goblin',
    image: 'spezies_goblin',
    apCost: 5,
    baseStats: { le: 3, sk: -6, zk: -5, gs: 8 },
    attributeMods: [
      { type: 'fixed', attribute: 'FF', modifier: 1 },
      { type: 'fixed', attribute: 'GE', modifier: 1 },
      { type: 'choice', selectionOptions: ['MU', 'KL'], modifier: -1 },
    ],
    autoAdvantages: ['dunkelsicht', 'herausragenderSinn_gehor', 'herausragenderSinn_geruch', 'krankheitsresistenz'],
    autoDisadvantages: [],
    recommendedAdvantages: ['biss', 'flink', 'kalteresistenz', 'naturlicheWaffe_biss', 'naturlicherRustungsschutz'],
    recommendedDisadvantages: ['schlechteEigenschaft_aberglaube', 'schlechteEigenschaft_neugier'],
    typicalAdvantages: [{ advantages: ['dunkelsicht', 'richtungssinn'] }],
    typicalDisadvantages: [{ advantages: ['niedrigeSeelenkraft'] }],
  },
  // ── Halbork ── Orks – Hauer & Schwarzer Pelz S. 17
  {
    type: SpeciesType.Halforc,
    name: SpeciesType.Halforc,
    label: 'Halbork',
    image: 'spezies_halbork',
    apCost: 1,
    baseStats: { le: 6, sk: -6, zk: -5, gs: 8 },
    attributeMods: [
      { type: 'fixed', attribute: 'KO', modifier: 1 },
      { type: 'fixed', attribute: 'CH', modifier: -1 },
    ],
    autoAdvantages: ['zaherHund'],
    autoDisadvantages: [],
    recommendedAdvantages: ['biss', 'dunkelsicht', 'kalteresistenz'],
    recommendedDisadvantages: ['niedrigeSeelenkraft'],
    typicalAdvantages: [{ advantages: ['dunkelsicht', 'hoheZahigkeit', 'richtungssinn'] }],
    typicalDisadvantages: [{ advantages: ['blutrausch', 'niedrigeSeelenkraft', 'stechenderOrkgeruch'] }],
  },
  // ── Holberker ── Orks – Hauer & Schwarzer Pelz S. 19
  {
    type: SpeciesType.Holberker,
    name: SpeciesType.Holberker,
    label: 'Holberker',
    image: 'spezies_holberker',
    apCost: 1,
    baseStats: { le: 6, sk: -6, zk: -5, gs: 8 },
    attributeMods: [
      { type: 'fixed', attribute: 'KL', modifier: -1 },
      { type: 'fixed', attribute: 'KO', modifier: 1 },
    ],
    autoAdvantages: ['zaherHund'],
    autoDisadvantages: [],
    recommendedAdvantages: [],
    recommendedDisadvantages: [],
    typicalAdvantages: [{ advantages: ['dunkelsicht', 'hoheZahigkeit', 'richtungssinn', 'zauberer'] }],
    typicalDisadvantages: [{ advantages: ['niedrigeSeelenkraft'] }],
  },
  // ── Ork ── Orks – Hauer & Schwarzer Pelz S. 18
  {
    type: SpeciesType.Orc,
    name: SpeciesType.Orc,
    label: 'Ork',
    image: 'spezies_ork',
    apCost: 18,
    baseStats: { le: 8, sk: -6, zk: -4, gs: 8 },
    attributeMods: [
      { type: 'fixed', attribute: 'MU', modifier: 1 },
      { type: 'fixed', attribute: 'KO', modifier: 1 },
      { type: 'choice', selectionOptions: ['KL', 'CH'], modifier: -1 },
    ],
    autoAdvantages: [],
    autoDisadvantages: [],
    recommendedAdvantages: ['biss', 'dunkelsicht', 'kalteresistenz', 'naturlicheWaffe_biss', 'naturlicherRustungsschutz', 'zaherHund'],
    recommendedDisadvantages: ['niedrigeSeelenkraft', 'schlechteEigenschaft_aberglaube', 'schlechteEigenschaft_jahzorn'],
    typicalAdvantages: [{ advantages: ['dunkelsicht', 'hoheZahigkeit', 'richtungssinn'] }],
    typicalDisadvantages: [{ advantages: ['blutrausch', 'stechenderOrkgeruch'] }],
  },
  // ── Nachtalb ── Helden des Wolfsfrosts S. 25
  {
    type: SpeciesType.Nachtalb,
    name: SpeciesType.Nachtalb,
    label: 'Nachtalb',
    image: 'spezies_nachtalb',
    apCost: 18,
    baseStats: { le: 2, sk: -4, zk: -6, gs: 8 },
    attributeMods: [
      { type: 'fixed', attribute: 'IN', modifier: 1 },
      { type: 'fixed', attribute: 'GE', modifier: 1 },
      { type: 'choice', selectionOptions: ['KL', 'KK'], modifier: -2 },
    ],
    autoAdvantages: ['zauberer', 'zweistimmigerGesang'],
    autoDisadvantages: [],
    recommendedAdvantages: ['altersresistenz', 'dunkelsicht', 'nichtschlafer'],
    recommendedDisadvantages: ['sensiblerGeruchssinn', 'unfahig_zechen'],
    typicalAdvantages: [
      {
        advantages: [
          'beidhandig',
          'dunkelsicht',
          'flink',
          'giftresistenz',
          'gutaussehend',
          'herausragenderSinn_gehor',
          'herausragenderSinn_sicht',
          'immunitatKrankheit_schwarzeWut',
          'immunitatKrankheit_tollwut',
          'immunitatKrankheit_lykanthropie',
          'krankheitsresistenz',
          'richtungssinn',
          'schlangenmensch',
          'verbesserteRegenerationAsp',
          'wohlklang',
        ],
      },
    ],
    typicalDisadvantages: [
      {
        advantages: [
          'blutrausch',
          'empfindlichkeit_unedleMetalle',
          'hitzeempfindlich',
          'korpergebundeneKraft',
          'lichtempfindlich',
          'raubtiergeruch',
          'wahrerName',
        ],
      },
    ],
  },
];
