import { SpecialAbility, SpecialAbilityCategory } from '../models/special-ability.model';

// â”€â”€â”€ Karmale Sonderfertigkeiten â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
// Source: DSA 5 Regelwiki â€“ Karmale Sonderfertigkeiten
// Cost = 0 means AP cost not yet populated (expansion book content)
// Prerequisite { name: 'geweihter', required: true } = Vorteil Geweihter required

// â”€â”€â”€ Allgemeine karmale Sonderfertigkeiten â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
export const KARMAL_GENERAL_SPECIAL_ABILITIES: SpecialAbility[] = [
  // â”€â”€ Regelwerk core â”€â”€
  {
    name: 'aspektkenntnis',
    label: 'Aspektkenntnis',
    cost: 15,
    category: SpecialAbilityCategory.KarmalGeneral,
    prerequisite: [{ name: 'geweihter', required: true }],
    url: 'https://dsa.ulisses-regelwiki.de/ksf_Aspektkenntnis.html',
  },
  {
    name: 'fokussierung',
    label: 'Fokussierung',
    cost: 8,
    category: SpecialAbilityCategory.KarmalGeneral,
    prerequisite: [],
    attributeRequirement: [{ attribute: 'MU', minValue: 13 }],
    url: 'https://dsa.ulisses-regelwiki.de/ksf_Fokussierung.html',
  },
  {
    name: 'karmaleMeditation',
    label: 'Karmale Meditation',
    cost: 15,
    category: SpecialAbilityCategory.KarmalGeneral,
    prerequisite: [{ name: 'geweihter', required: true }],
    url: 'https://dsa.ulisses-regelwiki.de/ksf_Karmale_Meditation.html',
  },
  {
    name: 'karmaleRegeneration',
    label: 'Karmale Regeneration I-II',
    cost: 12,
    category: SpecialAbilityCategory.KarmalGeneral,
    lvl: 1,
    maxLvl: 2,
    prerequisite: [{ name: 'geweihter', required: true }],
    url: 'https://dsa.ulisses-regelwiki.de/ksf_Karmale_Regeneration_I-II.html',
  },
  {
    name: 'lieblingsliturgie',
    label: 'Lieblingsliturgie',
    cost: 3,
    category: SpecialAbilityCategory.KarmalGeneral,
    prerequisite: [{ name: 'geweihter', required: true }],
    url: 'https://dsa.ulisses-regelwiki.de/ksf_Lieblingsliturgie.html',
  },
  {
    name: 'liturgieAbbrechen',
    label: 'Liturgie abbrechen',
    cost: 8,
    category: SpecialAbilityCategory.KarmalGeneral,
    prerequisite: [{ name: 'geweihter', required: true }],
    url: 'https://dsa.ulisses-regelwiki.de/ksf_Liturgie_abbrechen.html',
  },
  {
    name: 'liturgieVereinen',
    label: 'Liturgie vereinen I-II',
    cost: 15,
    category: SpecialAbilityCategory.KarmalGeneral,
    lvl: 1,
    maxLvl: 2,
    prerequisite: [{ name: 'geweihter', required: true }],
    url: 'https://dsa.ulisses-regelwiki.de/ksf_Liturgie_vereinen_I-II.html',
  },
  {
    name: 'routinierteLiturgiewiederholung',
    label: 'Routinierte Liturgiewiederholung',
    cost: 10,
    category: SpecialAbilityCategory.KarmalGeneral,
    prerequisite: [{ name: 'geweihter', required: true }],
    attributeRequirement: [{ attribute: 'KL', minValue: 13 }],
    url: 'https://dsa.ulisses-regelwiki.de/ksf_Routinierte_Liturgiewiederholung.html',
  },
  {
    name: 'segnungsbruch',
    label: 'Segnungsbruch',
    cost: 2,
    category: SpecialAbilityCategory.KarmalGeneral,
    prerequisite: [{ name: 'geweihter', required: true }],
    url: 'https://dsa.ulisses-regelwiki.de/ksf_Segnungsbruch.html',
  },
  {
    name: 'starkeSegnungen',
    label: 'Starke Segnungen',
    cost: 2,
    category: SpecialAbilityCategory.KarmalGeneral,
    prerequisite: [{ name: 'geweihter', required: true }],
    url: 'https://dsa.ulisses-regelwiki.de/ksf_Starke_Segnungen.html',
  },
  // â”€â”€ Weitere allgemeine karmale SF â”€â”€
  {
    name: 'abgeschwachteLiturgie',
    label: 'Abgeschwächte Liturgie',
    cost: 0,
    category: SpecialAbilityCategory.KarmalGeneral,
    prerequisite: [{ name: 'geweihter', required: true }],
    url: 'https://dsa.ulisses-regelwiki.de/ksf_Abgeschwachte_Liturgie.html',
  },
  {
    name: 'blutpfand',
    label: 'Blutpfand',
    cost: 0,
    category: SpecialAbilityCategory.KarmalGeneral,
    prerequisite: [{ name: 'geweihter', required: true }],
    url: 'https://dsa.ulisses-regelwiki.de/ksf_Blutpfand.html',
  },
  {
    name: 'chimarenschreck',
    label: 'Chimärenschreck',
    cost: 0,
    category: SpecialAbilityCategory.KarmalGeneral,
    prerequisite: [{ name: 'geweihter', required: true }],
    url: 'https://dsa.ulisses-regelwiki.de/ksf_Chimaerenschreck.html',
  },
  {
    name: 'daimonidenschreck',
    label: 'Daimonidenschreck',
    cost: 0,
    category: SpecialAbilityCategory.KarmalGeneral,
    prerequisite: [{ name: 'geweihter', required: true }],
    url: 'https://dsa.ulisses-regelwiki.de/ksf_Daimonidenschreck.html',
  },
  {
    name: 'entruckungsmeditation',
    label: 'Entrückungsmeditation',
    cost: 0,
    category: SpecialAbilityCategory.KarmalGeneral,
    prerequisite: [{ name: 'geweihter', required: true }],
    url: 'https://dsa.ulisses-regelwiki.de/ksf_Entruckungsmeditation.html',
  },
  {
    name: 'extremStarkeSegnungen',
    label: 'Extrem starke Segnungen',
    cost: 0,
    category: SpecialAbilityCategory.KarmalGeneral,
    prerequisite: [
      { name: 'geweihter', required: true },
      { name: 'starkeSegnungen', required: true },
    ],
    url: 'https://dsa.ulisses-regelwiki.de/ksf_Extrem_starke_Segnungen.html',
  },
  {
    name: 'extremStarkerSegnungsbruch',
    label: 'Extrem starker Segnungsbruch',
    cost: 0,
    category: SpecialAbilityCategory.KarmalGeneral,
    prerequisite: [
      { name: 'geweihter', required: true },
      { name: 'segnungsbruch', required: true },
    ],
    url: 'https://dsa.ulisses-regelwiki.de/ksf_Extrem_starker_Segnungsbruch.html',
  },
  {
    name: 'furchtNehmen',
    label: 'Furcht nehmen',
    cost: 0,
    category: SpecialAbilityCategory.KarmalGeneral,
    prerequisite: [{ name: 'geweihter', required: true }],
    url: 'https://dsa.ulisses-regelwiki.de/ksf_Furcht_nehmen.html',
  },
  {
    name: 'gefestigterZeremonieablauf',
    label: 'Gefestigter Zeremonieablauf',
    cost: 0,
    category: SpecialAbilityCategory.KarmalGeneral,
    prerequisite: [{ name: 'geweihter', required: true }],
    url: 'https://dsa.ulisses-regelwiki.de/ksf_Gefestigter_Zeremonieablauf.html',
  },
  {
    name: 'geisterschreck',
    label: 'Geisterschreck',
    cost: 0,
    category: SpecialAbilityCategory.KarmalGeneral,
    prerequisite: [{ name: 'geweihter', required: true }],
    url: 'https://dsa.ulisses-regelwiki.de/ksf_Geisterschreck.html',
  },
  {
    name: 'geweihterKarmalleib',
    label: 'Geweihter Karmalleib',
    cost: 0,
    category: SpecialAbilityCategory.KarmalGeneral,
    prerequisite: [{ name: 'geweihter', required: true }],
    url: 'https://dsa.ulisses-regelwiki.de/ksf_Geweihter_Karmalleib.html',
  },
  {
    name: 'golemschreck',
    label: 'Golemschreck',
    cost: 0,
    category: SpecialAbilityCategory.KarmalGeneral,
    prerequisite: [{ name: 'geweihter', required: true }],
    url: 'https://dsa.ulisses-regelwiki.de/ksf_Golemschreck.html',
  },
  {
    name: 'gottlicherSchutz',
    label: 'Göttlicher Schutz I-II',
    cost: 0,
    category: SpecialAbilityCategory.KarmalGeneral,
    lvl: 1,
    maxLvl: 2,
    prerequisite: [{ name: 'geweihter', required: true }],
    url: 'https://dsa.ulisses-regelwiki.de/ksf_Goettlicher_Schutz_I-II.html',
  },
  {
    name: 'hauptsegnung',
    label: 'Hauptsegnung I-III',
    cost: 0,
    category: SpecialAbilityCategory.KarmalGeneral,
    lvl: 1,
    maxLvl: 3,
    prerequisite: [{ name: 'geweihter', required: true }],
    url: 'https://dsa.ulisses-regelwiki.de/ksf_Hauptsegnung_I-III.html',
  },
  {
    name: 'heiligerKarmalleib',
    label: 'Heiliger Karmalleib',
    cost: 0,
    category: SpecialAbilityCategory.KarmalGeneral,
    prerequisite: [
      { name: 'geweihter', required: true },
      { name: 'geweihterKarmalleib', required: true },
    ],
    url: 'https://dsa.ulisses-regelwiki.de/ksf_Heiliger_Karmalleib.html',
  },
  {
    name: 'hoheWeihe',
    label: 'Hohe Weihe I-III',
    cost: 0,
    category: SpecialAbilityCategory.KarmalGeneral,
    lvl: 1,
    maxLvl: 3,
    prerequisite: [{ name: 'geweihter', required: true }],
    url: 'https://dsa.ulisses-regelwiki.de/ksf_Hohe_Weihe_I-III.html',
  },
  {
    name: 'improvisierteLiburgieGebet',
    label: 'Improvisierte Liturgie (Gebet)',
    cost: 0,
    category: SpecialAbilityCategory.KarmalGeneral,
    prerequisite: [{ name: 'geweihter', required: true }],
    url: 'https://dsa.ulisses-regelwiki.de/ksf_Improvisierte_Liturgie_Gebet.html',
  },
  {
    name: 'improvisierteLiburgieGesten',
    label: 'Improvisierte Liturgie (Gesten)',
    cost: 0,
    category: SpecialAbilityCategory.KarmalGeneral,
    prerequisite: [{ name: 'geweihter', required: true }],
    url: 'https://dsa.ulisses-regelwiki.de/ksf_Improvisierte_Liturgie_Gesten.html',
  },
  {
    name: 'klarerBlick',
    label: 'Klarer Blick',
    cost: 0,
    category: SpecialAbilityCategory.KarmalGeneral,
    prerequisite: [{ name: 'geweihter', required: true }],
    url: 'https://dsa.ulisses-regelwiki.de/ksf_Klarer_Blick.html',
  },
  {
    name: 'kontrolleDesKarmalkorpers',
    label: 'Kontrolle des Karmalkörpers',
    cost: 0,
    category: SpecialAbilityCategory.KarmalGeneral,
    prerequisite: [{ name: 'geweihter', required: true }],
    url: 'https://dsa.ulisses-regelwiki.de/ksf_Kontrolle_des_Karmalkoerpers.html',
  },
  {
    name: 'liturgiebindung',
    label: 'Liturgiebindung',
    cost: 0,
    category: SpecialAbilityCategory.KarmalGeneral,
    prerequisite: [{ name: 'geweihter', required: true }],
    url: 'https://dsa.ulisses-regelwiki.de/ksf_Liturgiebindung.html',
  },
  {
    name: 'machtigeKontrolleDesKarmalkorpers',
    label: 'Mächtige Kontrolle des Karmalkörpers',
    cost: 0,
    category: SpecialAbilityCategory.KarmalGeneral,
    prerequisite: [
      { name: 'geweihter', required: true },
      { name: 'kontrolleDesKarmalkorpers', required: true },
    ],
    url: 'https://dsa.ulisses-regelwiki.de/ksf_Maechtige_Kontrolle_des_Karmalkoerpers.html',
  },
  {
    name: 'mauerDesGeistes',
    label: 'Mauer des Geistes',
    cost: 0,
    category: SpecialAbilityCategory.KarmalGeneral,
    prerequisite: [{ name: 'geweihter', required: true }],
    url: 'https://dsa.ulisses-regelwiki.de/ksf_Mauer_des_Geistes.html',
  },
  {
    name: 'mirakelmacht',
    label: 'Mirakelmacht',
    cost: 0,
    category: SpecialAbilityCategory.KarmalGeneral,
    prerequisite: [{ name: 'geweihter', required: true }],
    url: 'https://dsa.ulisses-regelwiki.de/ksf_Mirakelmacht.html',
  },
  {
    name: 'stabileRegeneration',
    label: 'Stabile Regeneration',
    cost: 0,
    category: SpecialAbilityCategory.KarmalGeneral,
    prerequisite: [{ name: 'geweihter', required: true }],
    url: 'https://dsa.ulisses-regelwiki.de/ksf_Stabile_Regeneration.html',
  },
  {
    name: 'starkeDesGlaubens',
    label: 'Stärke des Glaubens',
    cost: 0,
    category: SpecialAbilityCategory.KarmalGeneral,
    prerequisite: [{ name: 'geweihter', required: true }],
    url: 'https://dsa.ulisses-regelwiki.de/ksf_Staerke_des_Glaubens.html',
  },
  {
    name: 'starkerSegnungsbruch',
    label: 'Starker Segnungsbruch',
    cost: 0,
    category: SpecialAbilityCategory.KarmalGeneral,
    prerequisite: [
      { name: 'geweihter', required: true },
      { name: 'segnungsbruch', required: true },
    ],
    url: 'https://dsa.ulisses-regelwiki.de/ksf_Starker_Segnungsbruch.html',
  },
  {
    name: 'schildDesGlaubens',
    label: 'Schild des Glaubens',
    cost: 0,
    category: SpecialAbilityCategory.KarmalGeneral,
    prerequisite: [{ name: 'geweihter', required: true }],
    url: 'https://dsa.ulisses-regelwiki.de/ksf_Schild_des_Glaubens.html',
  },
  {
    name: 'traumweber',
    label: 'Traumweber I-III',
    cost: 0,
    category: SpecialAbilityCategory.KarmalGeneral,
    lvl: 1,
    maxLvl: 3,
    prerequisite: [{ name: 'geweihter', required: true }],
    url: 'https://dsa.ulisses-regelwiki.de/ksf_Traumweber_I-III.html',
  },
  {
    name: 'untotenschreck',
    label: 'Untotenschreck',
    cost: 0,
    category: SpecialAbilityCategory.KarmalGeneral,
    prerequisite: [{ name: 'geweihter', required: true }],
    url: 'https://dsa.ulisses-regelwiki.de/ksf_Untotenschreck.html',
  },
  {
    name: 'wahreStarkeDesGlaubens',
    label: 'Wahre Stärke des Glaubens',
    cost: 0,
    category: SpecialAbilityCategory.KarmalGeneral,
    prerequisite: [
      { name: 'geweihter', required: true },
      { name: 'starkeDesGlaubens', required: true },
    ],
    url: 'https://dsa.ulisses-regelwiki.de/ksf_Wahre_Staerke_des_Glaubens.html',
  },
  {
    name: 'wahrerGlaube',
    label: 'Wahrer Glaube',
    cost: 0,
    category: SpecialAbilityCategory.KarmalGeneral,
    prerequisite: [{ name: 'geweihter', required: true }],
    url: 'https://dsa.ulisses-regelwiki.de/ksf_Wahrer_Glaube.html',
  },
  {
    name: 'zeremonialgegenstandeHerstellen',
    label: 'Zeremonialgegenstände herstellen',
    cost: 0,
    category: SpecialAbilityCategory.KarmalGeneral,
    prerequisite: [{ name: 'geweihter', required: true }],
    url: 'https://dsa.ulisses-regelwiki.de/ksf_Zeremonialgegenstaende_herstellen.html',
  },
  {
    name: 'zuruckInDieNiederhollen',
    label: 'Zurück in die Niederhöllen',
    cost: 0,
    category: SpecialAbilityCategory.KarmalGeneral,
    prerequisite: [{ name: 'geweihter', required: true }],
    url: 'https://dsa.ulisses-regelwiki.de/ksf_Zurueck_in_die_Niederhoellen.html',
  },
  {
    name: 'zweiSegnungenGleichzeitig',
    label: 'Zwei Segnungen gleichzeitig',
    cost: 0,
    category: SpecialAbilityCategory.KarmalGeneral,
    prerequisite: [{ name: 'geweihter', required: true }],
    url: 'https://dsa.ulisses-regelwiki.de/ksf_Zwei_Segnungen_gleichzeitig.html',
  },
  {
    name: 'zweifachgeweihterKarmalleib',
    label: 'Zweifachgeweihter Karmalleib',
    cost: 0,
    category: SpecialAbilityCategory.KarmalGeneral,
    prerequisite: [
      { name: 'geweihter', required: true },
      { name: 'geweihterKarmalleib', required: true },
    ],
    url: 'https://dsa.ulisses-regelwiki.de/ksf_Zweifachgeweihter_Karmalleib.html',
  },
];

// â”€â”€â”€ Karmale Traditionen â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
export const KARMAL_TRADITION_SPECIAL_ABILITIES: SpecialAbility[] = [
  {
    name: 'traditionPraioskirche',
    label: 'Tradition (Praioskirche)',
    cost: 0,
    category: SpecialAbilityCategory.KarmalTradition,
    prerequisite: [{ name: 'geweihter', required: true }],
    url: 'https://dsa.ulisses-regelwiki.de/tradition_Praioskirche.html',
  },
  {
    name: 'traditionRondrageweihte',
    label: 'Tradition (Rondrageweihte)',
    cost: 0,
    category: SpecialAbilityCategory.KarmalTradition,
    prerequisite: [{ name: 'geweihter', required: true }],
    url: 'https://dsa.ulisses-regelwiki.de/tradition_Rondrageweihte.html',
  },
  {
    name: 'traditionEfferdkirche',
    label: 'Tradition (Efferdkirche)',
    cost: 0,
    category: SpecialAbilityCategory.KarmalTradition,
    prerequisite: [{ name: 'geweihter', required: true }],
    url: 'https://dsa.ulisses-regelwiki.de/tradition_Efferdkirche.html',
  },
  {
    name: 'traditionTraviaKirche',
    label: 'Tradition (Travia-Kirche)',
    cost: 0,
    category: SpecialAbilityCategory.KarmalTradition,
    prerequisite: [{ name: 'geweihter', required: true }],
    url: 'https://dsa.ulisses-regelwiki.de/tradition_Travia-Kirche.html',
  },
  {
    name: 'traditionBoronkirche',
    label: 'Tradition (Boronkirche)',
    cost: 0,
    category: SpecialAbilityCategory.KarmalTradition,
    prerequisite: [{ name: 'geweihter', required: true }],
    url: 'https://dsa.ulisses-regelwiki.de/tradition_Boronkirche.html',
  },
  {
    name: 'traditionHesindkirche',
    label: 'Tradition (Hesindkirche)',
    cost: 0,
    category: SpecialAbilityCategory.KarmalTradition,
    prerequisite: [{ name: 'geweihter', required: true }],
    url: 'https://dsa.ulisses-regelwiki.de/tradition_Hesindkirche.html',
  },
  {
    name: 'traditionFirunkirche',
    label: 'Tradition (Firunkirche)',
    cost: 0,
    category: SpecialAbilityCategory.KarmalTradition,
    prerequisite: [{ name: 'geweihter', required: true }],
    url: 'https://dsa.ulisses-regelwiki.de/tradition_Firunkirche.html',
  },
  {
    name: 'traditionTsaKirche',
    label: 'Tradition (Tsa-Kirche)',
    cost: 0,
    category: SpecialAbilityCategory.KarmalTradition,
    prerequisite: [{ name: 'geweihter', required: true }],
    url: 'https://dsa.ulisses-regelwiki.de/tradition_Tsa-Kirche.html',
  },
  {
    name: 'traditionPhexkirche',
    label: 'Tradition (Phexkirche)',
    cost: 0,
    category: SpecialAbilityCategory.KarmalTradition,
    prerequisite: [{ name: 'geweihter', required: true }],
    url: 'https://dsa.ulisses-regelwiki.de/tradition_Phexkirche.html',
  },
  {
    name: 'traditionPerainekirche',
    label: 'Tradition (Perainekirche)',
    cost: 0,
    category: SpecialAbilityCategory.KarmalTradition,
    prerequisite: [{ name: 'geweihter', required: true }],
    url: 'https://dsa.ulisses-regelwiki.de/tradition_Perainekirche.html',
  },
  {
    name: 'traditionIngerimmkirche',
    label: 'Tradition (Ingerimmkirche)',
    cost: 0,
    category: SpecialAbilityCategory.KarmalTradition,
    prerequisite: [{ name: 'geweihter', required: true }],
    url: 'https://dsa.ulisses-regelwiki.de/tradition_Ingerimmkirche.html',
  },
  {
    name: 'traditionRahjakirche',
    label: 'Tradition (Rahjakirche)',
    cost: 0,
    category: SpecialAbilityCategory.KarmalTradition,
    prerequisite: [{ name: 'geweihter', required: true }],
    url: 'https://dsa.ulisses-regelwiki.de/tradition_Rahjakirche.html',
  },
  {
    name: 'traditionAngroschkirche',
    label: 'Tradition (Angroschkirche)',
    cost: 0,
    category: SpecialAbilityCategory.KarmalTradition,
    prerequisite: [{ name: 'geweihter', required: true }],
    url: 'https://dsa.ulisses-regelwiki.de/tradition_Angroschkirche.html',
  },
  {
    name: 'traditionNanduskirche',
    label: 'Tradition (Nanduskirche)',
    cost: 0,
    category: SpecialAbilityCategory.KarmalTradition,
    prerequisite: [{ name: 'geweihter', required: true }],
    url: 'https://dsa.ulisses-regelwiki.de/tradition_Nanduskirche.html',
  },
  {
    name: 'traditionKorkirche',
    label: 'Tradition (Korkirche)',
    cost: 0,
    category: SpecialAbilityCategory.KarmalTradition,
    prerequisite: [{ name: 'geweihter', required: true }],
    url: 'https://dsa.ulisses-regelwiki.de/tradition_Korkirche.html',
  },
  {
    name: 'traditionIfirnskirche',
    label: 'Tradition (Ifirnskirche)',
    cost: 0,
    category: SpecialAbilityCategory.KarmalTradition,
    prerequisite: [{ name: 'geweihter', required: true }],
    url: 'https://dsa.ulisses-regelwiki.de/tradition_Ifirnskirche.html',
  },
  {
    name: 'traditionSwafnirkirche',
    label: 'Tradition (Swafnirkirche)',
    cost: 0,
    category: SpecialAbilityCategory.KarmalTradition,
    prerequisite: [{ name: 'geweihter', required: true }],
    url: 'https://dsa.ulisses-regelwiki.de/tradition_Swafnirkirche.html',
  },
  {
    name: 'traditionAveskirche',
    label: 'Tradition (Aveskirche)',
    cost: 0,
    category: SpecialAbilityCategory.KarmalTradition,
    prerequisite: [{ name: 'geweihter', required: true }],
    url: 'https://dsa.ulisses-regelwiki.de/tradition_Aveskirche.html',
  },
  {
    name: 'traditionGraveshkirche',
    label: 'Tradition (Graveshkirche)',
    cost: 0,
    category: SpecialAbilityCategory.KarmalTradition,
    prerequisite: [{ name: 'geweihter', required: true }],
    url: 'https://dsa.ulisses-regelwiki.de/tradition_Graveshkirche.html',
  },
  {
    name: 'traditionMarbokirche',
    label: 'Tradition (Marbokirche)',
    cost: 0,
    category: SpecialAbilityCategory.KarmalTradition,
    prerequisite: [{ name: 'geweihter', required: true }],
    url: 'https://dsa.ulisses-regelwiki.de/tradition_Marbokirche.html',
  },
  {
    name: 'traditionNamenloserKult',
    label: 'Tradition (Namenloser Kult)',
    cost: 0,
    category: SpecialAbilityCategory.KarmalTradition,
    prerequisite: [{ name: 'geweihter', required: true }],
    url: 'https://dsa.ulisses-regelwiki.de/tradition_Namenloser_Kult.html',
  },
  {
    name: 'traditionNivesenschamanen',
    label: 'Tradition (Nivesenschamanen)',
    cost: 0,
    category: SpecialAbilityCategory.KarmalTradition,
    prerequisite: [{ name: 'geweihter', required: true }],
    url: 'https://dsa.ulisses-regelwiki.de/tradition_Nivesenschamanen.html',
  },
  {
    name: 'traditionFerkinaschamanen',
    label: 'Tradition (Ferkinaschamanen)',
    cost: 0,
    category: SpecialAbilityCategory.KarmalTradition,
    prerequisite: [{ name: 'geweihter', required: true }],
    url: 'https://dsa.ulisses-regelwiki.de/tradition_Ferkinaschamanen.html',
  },
  {
    name: 'traditionFjarningerschamanen',
    label: 'Tradition (Fjarningerschamanen)',
    cost: 0,
    category: SpecialAbilityCategory.KarmalTradition,
    prerequisite: [{ name: 'geweihter', required: true }],
    url: 'https://dsa.ulisses-regelwiki.de/tradition_Fjarningerschamanen.html',
  },
  {
    name: 'traditionGjalskerTierkrieger',
    label: 'Tradition (Gjalskerländer Tierkrieger)',
    cost: 0,
    category: SpecialAbilityCategory.KarmalTradition,
    prerequisite: [{ name: 'geweihter', required: true }],
    url: 'https://dsa.ulisses-regelwiki.de/tradition_Gjalskerlaender_Tierkrieger.html',
  },
  {
    name: 'traditionTrollzackerSchamanen',
    label: 'Tradition (Trollzacker-Schamanen)',
    cost: 0,
    category: SpecialAbilityCategory.KarmalTradition,
    prerequisite: [{ name: 'geweihter', required: true }],
    url: 'https://dsa.ulisses-regelwiki.de/tradition_Trollzacker-Schamanen.html',
  },
  {
    name: 'traditionAchazschamanen',
    label: 'Tradition (Achazschamanen)',
    cost: 0,
    category: SpecialAbilityCategory.KarmalTradition,
    prerequisite: [{ name: 'geweihter', required: true }],
    url: 'https://dsa.ulisses-regelwiki.de/tradition_Achazschamanen.html',
  },
  {
    name: 'traditionChrSsirSsrKult',
    label: "Tradition (Chr'Ssir'Ssr-Kult)",
    cost: 0,
    category: SpecialAbilityCategory.KarmalTradition,
    prerequisite: [{ name: 'geweihter', required: true }],
    url: 'https://dsa.ulisses-regelwiki.de/tradition_ChrSsirSsr-Kult.html',
  },
  {
    name: 'traditionHSzintKult',
    label: "Tradition (H'Szint-Kult)",
    cost: 0,
    category: SpecialAbilityCategory.KarmalTradition,
    prerequisite: [{ name: 'geweihter', required: true }],
    url: 'https://dsa.ulisses-regelwiki.de/tradition_HSzint-Kult.html',
  },
  {
    name: 'traditionNuminoruKult',
    label: 'Tradition (Numinoru-Kult)',
    cost: 0,
    category: SpecialAbilityCategory.KarmalTradition,
    prerequisite: [{ name: 'geweihter', required: true }],
    url: 'https://dsa.ulisses-regelwiki.de/tradition_Numinoru-Kult.html',
  },
  {
    name: 'traditionShinxirKult',
    label: 'Tradition (Shinxir-Kult)',
    cost: 0,
    category: SpecialAbilityCategory.KarmalTradition,
    prerequisite: [{ name: 'geweihter', required: true }],
    url: 'https://dsa.ulisses-regelwiki.de/tradition_Shinxir-Kult.html',
  },
  {
    name: 'traditionTairachKult',
    label: 'Tradition (Tairach-Kult)',
    cost: 0,
    category: SpecialAbilityCategory.KarmalTradition,
    prerequisite: [{ name: 'geweihter', required: true }],
    url: 'https://dsa.ulisses-regelwiki.de/tradition_Tairach-Kult.html',
  },
  {
    name: 'traditionZsahhKult',
    label: 'Tradition (Zsahh-Kult)',
    cost: 0,
    category: SpecialAbilityCategory.KarmalTradition,
    prerequisite: [{ name: 'geweihter', required: true }],
    url: 'https://dsa.ulisses-regelwiki.de/tradition_Zsahh-Kult.html',
  },
  {
    name: 'traditionRadschaKult',
    label: 'Tradition (Radscha-Kult)',
    cost: 0,
    category: SpecialAbilityCategory.KarmalTradition,
    prerequisite: [{ name: 'geweihter', required: true }],
    url: 'https://dsa.ulisses-regelwiki.de/tradition_Radscha-Kult.html',
  },
  {
    name: 'traditionTahaya',
    label: 'Tradition (Tahaya)',
    cost: 0,
    category: SpecialAbilityCategory.KarmalTradition,
    prerequisite: [{ name: 'geweihter', required: true }],
    url: 'https://dsa.ulisses-regelwiki.de/tradition_Tahaya.html',
  },
];

// â”€â”€â”€ Predigt-Sonderfertigkeiten â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
export const KARMAL_SERMON_SPECIAL_ABILITIES: SpecialAbility[] = [
  {
    name: 'predigtDerGemeinschaft',
    label: 'Predigt der Gemeinschaft',
    cost: 0,
    category: SpecialAbilityCategory.KarmalSermon,
    prerequisite: [{ name: 'geweihter', required: true }],
    url: 'https://dsa.ulisses-regelwiki.de/predigt_Gemeinschaft.html',
  },
  {
    name: 'predigtDerZuversicht',
    label: 'Predigt der Zuversicht',
    cost: 0,
    category: SpecialAbilityCategory.KarmalSermon,
    prerequisite: [{ name: 'geweihter', required: true }],
    url: 'https://dsa.ulisses-regelwiki.de/predigt_Zuversicht.html',
  },
  {
    name: 'predigtDesGottvertrauens',
    label: 'Predigt des Gottvertrauens',
    cost: 0,
    category: SpecialAbilityCategory.KarmalSermon,
    prerequisite: [{ name: 'geweihter', required: true }],
    url: 'https://dsa.ulisses-regelwiki.de/predigt_Gottvertrauens.html',
  },
  {
    name: 'predigtDesWohlgefallens',
    label: 'Predigt des Wohlgefallens',
    cost: 0,
    category: SpecialAbilityCategory.KarmalSermon,
    prerequisite: [{ name: 'geweihter', required: true }],
    url: 'https://dsa.ulisses-regelwiki.de/predigt_Wohlgefallens.html',
  },
  {
    name: 'predigtWiderMissgeschicke',
    label: 'Predigt wider Missgeschicke',
    cost: 0,
    category: SpecialAbilityCategory.KarmalSermon,
    prerequisite: [{ name: 'geweihter', required: true }],
    url: 'https://dsa.ulisses-regelwiki.de/predigt_wider_Missgeschicke.html',
  },
];

// â”€â”€â”€ Vision-Sonderfertigkeiten â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
export const KARMAL_VISION_SPECIAL_ABILITIES: SpecialAbility[] = [
  {
    name: 'visionDerBestimmung',
    label: 'Vision der Bestimmung',
    cost: 0,
    category: SpecialAbilityCategory.KarmalVision,
    prerequisite: [{ name: 'geweihter', required: true }],
    url: 'https://dsa.ulisses-regelwiki.de/vision_Bestimmung.html',
  },
  {
    name: 'visionDerEntruckung',
    label: 'Vision der Entrückung',
    cost: 0,
    category: SpecialAbilityCategory.KarmalVision,
    prerequisite: [{ name: 'geweihter', required: true }],
    url: 'https://dsa.ulisses-regelwiki.de/vision_Entrueckung.html',
  },
  {
    name: 'visionDerGottheit',
    label: 'Vision der Gottheit',
    cost: 0,
    category: SpecialAbilityCategory.KarmalVision,
    prerequisite: [{ name: 'geweihter', required: true }],
    url: 'https://dsa.ulisses-regelwiki.de/vision_Gottheit.html',
  },
  {
    name: 'visionDesSchicksals',
    label: 'Vision des Schicksals',
    cost: 0,
    category: SpecialAbilityCategory.KarmalVision,
    prerequisite: [{ name: 'geweihter', required: true }],
    url: 'https://dsa.ulisses-regelwiki.de/vision_Schicksals.html',
  },
  {
    name: 'visionDesWahrenGlaubens',
    label: 'Vision des Wahren Glaubens',
    cost: 0,
    category: SpecialAbilityCategory.KarmalVision,
    prerequisite: [{ name: 'geweihter', required: true }],
    url: 'https://dsa.ulisses-regelwiki.de/vision_Wahren_Glaubens.html',
  },
];

// â”€â”€â”€ Alle karmalen Sonderfertigkeiten zusammengefasst â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
export const ALL_KARMAL_SPECIAL_ABILITIES: SpecialAbility[] = [
  ...KARMAL_GENERAL_SPECIAL_ABILITIES,
  ...KARMAL_TRADITION_SPECIAL_ABILITIES,
  ...KARMAL_SERMON_SPECIAL_ABILITIES,
  ...KARMAL_VISION_SPECIAL_ABILITIES,
];
