import { Spell, SpellCheck, SpellTrait, IncreaseFactor } from '../models/magic.model';

// ─── Zaubersprüche (Spells) ───────────────────────────────────────────────────
// Source: DSA 5 Regelwiki – https://dsa.ulisses-regelwiki.de/zauberauswahl.html
// Total: 263 spells, alphabetically ordered

export const ALL_SPELLS: Spell[] = [
  {
    name: 'ablativum',
    label: 'Ablativum',
    check: ['MU', 'KL', 'CH'] as SpellCheck,
    trait: SpellTrait.Antimagie,
    traditions: ['Gildenmagier'],
    increaseFactor: IncreaseFactor.D,
  },
  {
    name: 'abvenenum',
    label: 'Abvenenum',
    check: ['KL', 'IN', 'FF'] as SpellCheck,
    trait: SpellTrait.Objekt,
    traditions: ['Druiden', 'Elfen', 'Gildenmagier', 'Goblinzauberinnen', 'Kristallomanten'],
    increaseFactor: IncreaseFactor.A,
  },
  {
    name: 'adlerauge',
    label: 'Adlerauge',
    check: ['KL', 'IN', 'FF'] as SpellCheck,
    trait: SpellTrait.Heilung,
    traditions: ['Druiden', 'Elfen', 'Goblinzauberinnen', 'Kristallomanten', 'Nachtalben'],
    increaseFactor: IncreaseFactor.B,
  },
  {
    name: 'adlerschwinge',
    label: 'Adlerschwinge',
    check: ['MU', 'IN', 'GE'] as SpellCheck,
    trait: SpellTrait.Verwandlung,
    traditions: ['Allgemein'],
    increaseFactor: IncreaseFactor.C,
  },
  {
    name: 'aeolito',
    label: 'Aeolito',
    check: ['KL', 'CH', 'KO'] as SpellCheck,
    trait: SpellTrait.Elementar,
    traditions: ['Allgemein'],
    increaseFactor: IncreaseFactor.B,
  },
  {
    name: 'aerofugo',
    label: 'Aerofugo',
    check: ['MU', 'KO', 'KK'] as SpellCheck,
    trait: SpellTrait.Elementar,
    traditions: ['Elfen', 'Gildenmagier'],
    increaseFactor: IncreaseFactor.C,
  },
  {
    name: 'affenarme',
    label: 'Affenarme',
    check: ['MU', 'KL', 'CH'] as SpellCheck,
    trait: SpellTrait.Verwandlung,
    traditions: ['Goblinzauberinnen', 'Hexen'],
    increaseFactor: IncreaseFactor.A,
  },
  {
    name: 'affenruf',
    label: 'Affenruf',
    check: ['MU', 'CH', 'CH'] as SpellCheck,
    trait: SpellTrait.Daemonisch,
    traditions: ['Hexen'],
    increaseFactor: IncreaseFactor.C,
  },
  {
    name: 'alpgestalt',
    label: 'Alpgestalt',
    check: ['MU', 'CH', 'GE'] as SpellCheck,
    trait: SpellTrait.Einfluss,
    traditions: ['Druiden', 'Hexen', 'Scharlatane'],
    increaseFactor: IncreaseFactor.A,
  },
  {
    name: 'altisonus',
    label: 'Altisonus',
    check: ['MU', 'CH', 'KO'] as SpellCheck,
    trait: SpellTrait.Heilung,
    traditions: ['Scharlatane'],
    increaseFactor: IncreaseFactor.A,
  },
  {
    name: 'analysArkanstruktur',
    label: 'Analys Arkanstruktur',
    check: ['KL', 'KL', 'IN'] as SpellCheck,
    trait: SpellTrait.Hellsicht,
    traditions: ['Allgemein'],
    increaseFactor: IncreaseFactor.C,
  },
  {
    name: 'angstAusloesen',
    label: 'Angst auslösen',
    check: ['MU', 'CH', 'GE'] as SpellCheck,
    trait: SpellTrait.Daemonisch,
    traditions: ['Gildenmagier'],
    increaseFactor: IncreaseFactor.C,
  },
  {
    name: 'aquafaxius',
    label: 'Aquafaxius',
    check: ['MU', 'KL', 'CH'] as SpellCheck,
    trait: SpellTrait.Elementar,
    traditions: ['Druiden', 'Geoden', 'Gildenmagier', 'Kristallomanten', 'Nachtalben'],
    increaseFactor: IncreaseFactor.C,
  },
  {
    name: 'aquaqueris',
    label: 'Aquaqueris',
    check: ['IN', 'CH', 'KO'] as SpellCheck,
    trait: SpellTrait.Elementar,
    traditions: ['Druiden', 'Gildenmagier'],
    increaseFactor: IncreaseFactor.B,
  },
  {
    name: 'aquasphaero',
    label: 'Aquasphaero',
    check: ['MU', 'KL', 'KO'] as SpellCheck,
    trait: SpellTrait.Elementar,
    traditions: ['Druiden', 'Geoden', 'Gildenmagier', 'Kristallomanten'],
    increaseFactor: IncreaseFactor.D,
  },
  {
    name: 'arachnea',
    label: 'Arachnea',
    check: ['MU', 'IN', 'CH'] as SpellCheck,
    trait: SpellTrait.Einfluss,
    traditions: ['Hexen', 'Kristallomanten'],
    increaseFactor: IncreaseFactor.C,
  },
  {
    name: 'archofaxius',
    label: 'Archofaxius',
    check: ['MU', 'KL', 'CH'] as SpellCheck,
    trait: SpellTrait.Elementar,
    traditions: ['Druiden', 'Geoden', 'Gildenmagier', 'Kristallomanten'],
    increaseFactor: IncreaseFactor.C,
  },
  {
    name: 'archosphaero',
    label: 'Archosphaero',
    check: ['MU', 'KL', 'KO'] as SpellCheck,
    trait: SpellTrait.Elementar,
    traditions: ['Druiden', 'Geoden', 'Gildenmagier', 'Kristallomanten'],
    increaseFactor: IncreaseFactor.D,
  },
  {
    name: 'armatrutz',
    label: 'Armatrutz',
    check: ['KL', 'IN', 'FF'] as SpellCheck,
    trait: SpellTrait.Heilung,
    traditions: ['Allgemein'],
    increaseFactor: IncreaseFactor.C,
  },
  {
    name: 'aromatisIllusionis',
    label: 'Aromatis Illusionis',
    check: ['KL', 'IN', 'CH'] as SpellCheck,
    trait: SpellTrait.Illusion,
    traditions: ['Scharlatane'],
    increaseFactor: IncreaseFactor.A,
  },
  {
    name: 'atemnot',
    label: 'Atemnot',
    check: ['KL', 'CH', 'KO'] as SpellCheck,
    trait: SpellTrait.Einfluss,
    traditions: ['Druiden'],
    increaseFactor: IncreaseFactor.A,
  },
  {
    name: 'attributoCharisma',
    label: 'Attributo (Charisma)',
    check: ['KL', 'IN', 'CH'] as SpellCheck,
    trait: SpellTrait.Heilung,
    traditions: ['Goblinzauberinnen', 'Hexen', 'Scharlatane'],
    increaseFactor: IncreaseFactor.B,
  },
  {
    name: 'attributoFingerfertigkeit',
    label: 'Attributo (Fingerfertigkeit)',
    check: ['KL', 'IN', 'FF'] as SpellCheck,
    trait: SpellTrait.Heilung,
    traditions: ['Goblinzauberinnen', 'Scharlatane'],
    increaseFactor: IncreaseFactor.B,
  },
  {
    name: 'attributoGewandtheit',
    label: 'Attributo (Gewandtheit)',
    check: ['KL', 'IN', 'GE'] as SpellCheck,
    trait: SpellTrait.Heilung,
    traditions: ['Elfen', 'Kristallomanten'],
    increaseFactor: IncreaseFactor.B,
  },
  {
    name: 'attributoIntuition',
    label: 'Attributo (Intuition)',
    check: ['KL', 'IN', 'IN'] as SpellCheck,
    trait: SpellTrait.Heilung,
    traditions: ['Elfen', 'Goblinzauberinnen', 'Hexen'],
    increaseFactor: IncreaseFactor.B,
  },
  {
    name: 'attributoKlugheit',
    label: 'Attributo (Klugheit)',
    check: ['KL', 'KL', 'IN'] as SpellCheck,
    trait: SpellTrait.Heilung,
    traditions: ['Druiden', 'Gildenmagier'],
    increaseFactor: IncreaseFactor.B,
  },
  {
    name: 'attributoKonstitution',
    label: 'Attributo (Konstitution)',
    check: ['KL', 'IN', 'KO'] as SpellCheck,
    trait: SpellTrait.Heilung,
    traditions: ['Elfen', 'Kristallomanten'],
    increaseFactor: IncreaseFactor.B,
  },
  {
    name: 'attributoKoerperkraft',
    label: 'Attributo (Körperkraft)',
    check: ['KL', 'IN', 'KK'] as SpellCheck,
    trait: SpellTrait.Heilung,
    traditions: ['Gildenmagier', 'Kristallomanten', 'Nachtalben', 'Scharlatane'],
    increaseFactor: IncreaseFactor.B,
  },
  {
    name: 'attributoMut',
    label: 'Attributo (Mut)',
    check: ['MU', 'KL', 'IN'] as SpellCheck,
    trait: SpellTrait.Heilung,
    traditions: ['Gildenmagier'],
    increaseFactor: IncreaseFactor.B,
  },
  {
    name: 'aufwecken',
    label: 'Aufwecken',
    check: ['MU', 'IN', 'CH'] as SpellCheck,
    trait: SpellTrait.Heilung,
    traditions: ['Elfen', 'Gildenmagier', 'Hexen'],
    increaseFactor: IncreaseFactor.A,
  },
  {
    name: 'augeDesLimbus',
    label: 'Auge des Limbus',
    check: ['MU', 'IN', 'KK'] as SpellCheck,
    trait: SpellTrait.Sphaeren,
    traditions: ['Gildenmagier', 'Kristallomanten'],
    increaseFactor: IncreaseFactor.D,
  },
  {
    name: 'auraDerErschoepfung',
    label: 'Aura der Erschöpfung',
    check: ['MU', 'KL', 'CH'] as SpellCheck,
    trait: SpellTrait.Heilung,
    traditions: ['Gildenmagier', 'Goblinzauberinnen', 'Hexen'],
    increaseFactor: IncreaseFactor.B,
  },
  {
    name: 'aureolus',
    label: 'Aureolus',
    check: ['IN', 'CH', 'FF'] as SpellCheck,
    trait: SpellTrait.Illusion,
    traditions: ['Scharlatane'],
    increaseFactor: IncreaseFactor.A,
  },
  {
    name: 'aurisIllusionis',
    label: 'Auris Illusionis',
    check: ['KL', 'IN', 'CH'] as SpellCheck,
    trait: SpellTrait.Illusion,
    traditions: ['Gildenmagier', 'Scharlatane'],
    increaseFactor: IncreaseFactor.B,
  },
  {
    name: 'avilea',
    label: 'Avilea',
    check: ['MU', 'IN', 'CH'] as SpellCheck,
    trait: SpellTrait.Einfluss,
    traditions: ['Elfen', 'Hexen'],
    increaseFactor: IncreaseFactor.C,
  },
  {
    name: 'axxeleratus',
    label: 'Axxeleratus',
    check: ['KL', 'IN', 'FF'] as SpellCheck,
    trait: SpellTrait.Heilung,
    traditions: ['Elfen', 'Kristallomanten', 'Nachtalben'],
    increaseFactor: IncreaseFactor.B,
  },
  {
    name: 'aengsteLindern',
    label: 'Ängste Lindern',
    check: ['MU', 'IN', 'CH'] as SpellCheck,
    trait: SpellTrait.Einfluss,
    traditions: ['Geoden', 'Goblinzauberinnen', 'Hexen'],
    increaseFactor: IncreaseFactor.B,
  },
  {
    name: 'balsamSalabunde',
    label: 'Balsam Salabunde',
    check: ['KL', 'IN', 'FF'] as SpellCheck,
    trait: SpellTrait.Heilung,
    traditions: ['Allgemein'],
    increaseFactor: IncreaseFactor.B,
  },
  {
    name: 'bandUndFessel',
    label: 'Band und Fessel',
    check: ['KL', 'CH', 'KK'] as SpellCheck,
    trait: SpellTrait.Einfluss,
    traditions: ['Druiden', 'Elfen', 'Goblinzauberinnen', 'Hexen', 'Kristallomanten', 'Nachtalben'],
    increaseFactor: IncreaseFactor.B,
  },
  {
    name: 'bannbaladin',
    label: 'Bannbaladin',
    check: ['MU', 'IN', 'CH'] as SpellCheck,
    trait: SpellTrait.Einfluss,
    traditions: ['Allgemein'],
    increaseFactor: IncreaseFactor.B,
  },
  {
    name: 'basaltleib',
    label: 'Basaltleib',
    check: ['MU', 'KL', 'KK'] as SpellCheck,
    trait: SpellTrait.Elementar,
    traditions: ['Druiden', 'Elfen'],
    increaseFactor: IncreaseFactor.B,
  },
  {
    name: 'blickAufsWesen',
    label: 'Blick aufs Wesen',
    check: ['KL', 'IN', 'CH'] as SpellCheck,
    trait: SpellTrait.Hellsicht,
    traditions: ['Elfen', 'Kristallomanten', 'Scharlatane'],
    increaseFactor: IncreaseFactor.A,
  },
  {
    name: 'blickInDieGedanken',
    label: 'Blick in die Gedanken',
    check: ['MU', 'KL', 'IN'] as SpellCheck,
    trait: SpellTrait.Hellsicht,
    traditions: ['Allgemein'],
    increaseFactor: IncreaseFactor.C,
  },
  {
    name: 'blindheit',
    label: 'Blindheit',
    check: ['KL', 'IN', 'CH'] as SpellCheck,
    trait: SpellTrait.Einfluss,
    traditions: ['Hexen', 'Scharlatane'],
    increaseFactor: IncreaseFactor.C,
  },
  {
    name: 'blitzDichFind',
    label: 'Blitz dich find',
    check: ['MU', 'IN', 'CH'] as SpellCheck,
    trait: SpellTrait.Einfluss,
    traditions: ['Allgemein'],
    increaseFactor: IncreaseFactor.A,
  },
  {
    name: 'blitzball',
    label: 'Blitzball',
    check: ['MU', 'KL', 'KO'] as SpellCheck,
    trait: SpellTrait.Elementar,
    traditions: ['Gildenmagier'],
    increaseFactor: IncreaseFactor.D,
  },
  {
    name: 'boeserBlick',
    label: 'Böser Blick',
    check: ['MU', 'IN', 'CH'] as SpellCheck,
    trait: SpellTrait.Einfluss,
    traditions: ['Druiden', 'Kristallomanten'],
    increaseFactor: IncreaseFactor.C,
  },
  {
    name: 'brandungsleib',
    label: 'Brandungsleib',
    check: ['MU', 'IN', 'GE'] as SpellCheck,
    trait: SpellTrait.Elementar,
    traditions: ['Elfen'],
    increaseFactor: IncreaseFactor.B,
  },
  {
    name: 'brennenderHass',
    label: 'Brennender Hass',
    check: ['MU', 'IN', 'CH'] as SpellCheck,
    trait: SpellTrait.Einfluss,
    traditions: ['Hexen'],
    increaseFactor: IncreaseFactor.C,
  },
  {
    name: 'chamaelioni',
    label: 'Chamaelioni',
    check: ['IN', 'CH', 'GE'] as SpellCheck,
    trait: SpellTrait.Illusion,
    traditions: ['Elfen', 'Nachtalben', 'Scharlatane'],
    increaseFactor: IncreaseFactor.B,
  },
  {
    name: 'claudibus',
    label: 'Claudibus',
    check: ['KL', 'IN', 'FF'] as SpellCheck,
    trait: SpellTrait.Objekt,
    traditions: ['Gildenmagier', 'Hexen', 'Scharlatane'],
    increaseFactor: IncreaseFactor.B,
  },
  {
    name: 'corpofesso',
    label: 'Corpofesso',
    check: ['KL', 'IN', 'KO'] as SpellCheck,
    trait: SpellTrait.Verwandlung,
    traditions: ['Gildenmagier', 'Nachtalben'],
    increaseFactor: IncreaseFactor.C,
  },
  {
    name: 'corpofrigo',
    label: 'Corpofrigo',
    check: ['KL', 'CH', 'KO'] as SpellCheck,
    trait: SpellTrait.Elementar,
    traditions: ['Gildenmagier', 'Kristallomanten', 'Nachtalben'],
    increaseFactor: IncreaseFactor.B,
  },
  {
    name: 'cryptographo',
    label: 'Cryptographo',
    check: ['KL', 'KL', 'IN'] as SpellCheck,
    trait: SpellTrait.Objekt,
    traditions: ['Gildenmagier', 'Kristallomanten'],
    increaseFactor: IncreaseFactor.B,
  },
  {
    name: 'daemonenbann',
    label: 'Dämonenbann',
    check: ['MU', 'CH', 'KO'] as SpellCheck,
    trait: SpellTrait.Antimagie,
    traditions: ['Gildenmagier', 'Hexen'],
    increaseFactor: IncreaseFactor.B,
  },
  {
    name: 'daemonenschild',
    label: 'Dämonenschild',
    check: ['MU', 'KL', 'CH'] as SpellCheck,
    trait: SpellTrait.Antimagie,
    traditions: ['Gildenmagier'],
    increaseFactor: IncreaseFactor.B,
  },
  {
    name: 'daemonischesVergessen',
    label: 'Dämonisches Vergessen',
    check: ['MU', 'KL', 'IN'] as SpellCheck,
    trait: SpellTrait.Daemonisch,
    traditions: ['Borbaradianer', 'Gildenmagier', 'Hexen'],
    increaseFactor: IncreaseFactor.C,
  },
  {
    name: 'debilitatio',
    label: 'Debilitatio',
    check: ['MU', 'KL', 'CH'] as SpellCheck,
    trait: SpellTrait.Sphaeren,
    traditions: ['Gildenmagier'],
    increaseFactor: IncreaseFactor.B,
  },
  {
    name: 'desintegratus',
    label: 'Desintegratus',
    check: ['KL', 'CH', 'KK'] as SpellCheck,
    trait: SpellTrait.Objekt,
    traditions: ['Gildenmagier'],
    increaseFactor: IncreaseFactor.B,
  },
  {
    name: 'disruptivo',
    label: 'Disruptivo',
    check: ['MU', 'KL', 'CH'] as SpellCheck,
    trait: SpellTrait.Antimagie,
    traditions: ['Allgemein'],
    increaseFactor: IncreaseFactor.B,
  },
  {
    name: 'dornenwand',
    label: 'Dornenwand',
    check: ['MU', 'KL', 'CH'] as SpellCheck,
    trait: SpellTrait.Elementar,
    traditions: ['Druiden', 'Geoden'],
    increaseFactor: IncreaseFactor.B,
  },
  {
    name: 'drachenleib',
    label: 'Drachenleib',
    check: ['MU', 'KL', 'GE'] as SpellCheck,
    trait: SpellTrait.Elementar,
    traditions: ['Elfen'],
    increaseFactor: IncreaseFactor.B,
  },
  {
    name: 'dunkelheit',
    label: 'Dunkelheit',
    check: ['MU', 'KL', 'CH'] as SpellCheck,
    trait: SpellTrait.Elementar,
    traditions: ['Druiden', 'Geoden', 'Gildenmagier', 'Scharlatane'],
    increaseFactor: IncreaseFactor.B,
  },
  {
    name: 'duplicatus',
    label: 'Duplicatus',
    check: ['KL', 'IN', 'CH'] as SpellCheck,
    trait: SpellTrait.Illusion,
    traditions: ['Gildenmagier', 'Scharlatane'],
    increaseFactor: IncreaseFactor.C,
  },
  {
    name: 'ecliptifactus',
    label: 'Ecliptifactus',
    check: ['MU', 'IN', 'CH'] as SpellCheck,
    trait: SpellTrait.Daemonisch,
    traditions: ['Borbaradianer', 'Gildenmagier', 'Nachtalben'],
    increaseFactor: IncreaseFactor.C,
  },
  {
    name: 'eichenleib',
    label: 'Eichenleib',
    check: ['MU', 'KL', 'KK'] as SpellCheck,
    trait: SpellTrait.Elementar,
    traditions: ['Elfen'],
    increaseFactor: IncreaseFactor.B,
  },
  {
    name: 'eigeneAengste',
    label: 'Eigene Ängste',
    check: ['MU', 'IN', 'CH'] as SpellCheck,
    trait: SpellTrait.Einfluss,
    traditions: ['Borbaradianer', 'Gildenmagier', 'Hexen'],
    increaseFactor: IncreaseFactor.B,
  },
  {
    name: 'eigeneDummheit',
    label: 'Eigene Dummheit',
    check: ['MU', 'IN', 'CH'] as SpellCheck,
    trait: SpellTrait.Einfluss,
    traditions: ['Gildenmagier', 'Hexen'],
    increaseFactor: IncreaseFactor.B,
  },
  {
    name: 'einflussbann',
    label: 'Einflussbann',
    check: ['KL', 'IN', 'CH'] as SpellCheck,
    trait: SpellTrait.Antimagie,
    traditions: ['Druiden', 'Gildenmagier', 'Hexen', 'Scharlatane'],
    increaseFactor: IncreaseFactor.B,
  },
  {
    name: 'eisenrost',
    label: 'Eisenrost',
    check: ['KL', 'CH', 'GE'] as SpellCheck,
    trait: SpellTrait.Objekt,
    traditions: ['Gildenmagier', 'Hexen'],
    increaseFactor: IncreaseFactor.C,
  },
  {
    name: 'eiseskaelteKaempferherz',
    label: 'Eiseskälte Kämpferherz',
    check: ['MU', 'IN', 'KO'] as SpellCheck,
    trait: SpellTrait.Heilung,
    traditions: ['Elfen', 'Kristallomanten'],
    increaseFactor: IncreaseFactor.C,
  },
  {
    name: 'eispfeil',
    label: 'Eispfeil',
    check: ['IN', 'CH', 'FF'] as SpellCheck,
    trait: SpellTrait.Elementar,
    traditions: ['Elfen'],
    increaseFactor: IncreaseFactor.A,
  },
  {
    name: 'eiswand',
    label: 'Eiswand',
    check: ['MU', 'KL', 'CH'] as SpellCheck,
    trait: SpellTrait.Elementar,
    traditions: ['Gildenmagier', 'Nachtalben'],
    increaseFactor: IncreaseFactor.B,
  },
  {
    name: 'elementarbann',
    label: 'Elementarbann',
    check: ['IN', 'CH', 'KO'] as SpellCheck,
    trait: SpellTrait.Antimagie,
    traditions: ['Druiden', 'Geoden', 'Gildenmagier'],
    increaseFactor: IncreaseFactor.B,
  },
  {
    name: 'elfenstimme',
    label: 'Elfenstimme',
    check: ['IN', 'CH', 'KO'] as SpellCheck,
    trait: SpellTrait.Einfluss,
    traditions: ['Elfen'],
    increaseFactor: IncreaseFactor.A,
  },
  {
    name: 'erinnerungVerlasseDich',
    label: 'Erinnerung verlasse dich',
    check: ['MU', 'IN', 'CH'] as SpellCheck,
    trait: SpellTrait.Einfluss,
    traditions: ['Borbaradianer', 'Druiden', 'Gildenmagier'],
    increaseFactor: IncreaseFactor.B,
  },
  {
    name: 'erschoepfungenLindern',
    label: 'Erschöpfungen lindern',
    check: ['MU', 'IN', 'CH'] as SpellCheck,
    trait: SpellTrait.Heilung,
    traditions: ['Geoden', 'Hexen'],
    increaseFactor: IncreaseFactor.B,
  },
  {
    name: 'erzpfeil',
    label: 'Erzpfeil',
    check: ['IN', 'CH', 'FF'] as SpellCheck,
    trait: SpellTrait.Elementar,
    traditions: ['Elfen'],
    increaseFactor: IncreaseFactor.A,
  },
  {
    name: 'eulenruf',
    label: 'Eulenruf',
    check: ['MU', 'CH', 'CH'] as SpellCheck,
    trait: SpellTrait.Daemonisch,
    traditions: ['Hexen'],
    increaseFactor: IncreaseFactor.C,
  },
  {
    name: 'exposami',
    label: 'Exposami',
    check: ['KL', 'IN', 'CH'] as SpellCheck,
    trait: SpellTrait.Hellsicht,
    traditions: ['Druiden', 'Elfen', 'Kristallomanten', 'Nachtalben'],
    increaseFactor: IncreaseFactor.A,
  },
  {
    name: 'falkenauge',
    label: 'Falkenauge',
    check: ['MU', 'KL', 'IN'] as SpellCheck,
    trait: SpellTrait.Hellsicht,
    traditions: ['Elfen', 'Nachtalben'],
    increaseFactor: IncreaseFactor.B,
  },
  {
    name: 'favilludo',
    label: 'Favilludo',
    check: ['IN', 'FF', 'CH'] as SpellCheck,
    trait: SpellTrait.Elementar,
    traditions: ['Gildenmagier', 'Scharlatane'],
    increaseFactor: IncreaseFactor.A,
  },
  {
    name: 'federleib',
    label: 'Federleib',
    check: ['MU', 'IN', 'GE'] as SpellCheck,
    trait: SpellTrait.Elementar,
    traditions: ['Elfen'],
    increaseFactor: IncreaseFactor.B,
  },
  {
    name: 'feenstaub',
    label: 'Feenstaub',
    check: ['MU', 'KL', 'CH'] as SpellCheck,
    trait: SpellTrait.Sphaeren,
    traditions: ['Allgemein'],
    increaseFactor: IncreaseFactor.A,
  },
  {
    name: 'fesselfeld',
    label: 'Fesselfeld',
    check: ['KL', 'CH', 'KO'] as SpellCheck,
    trait: SpellTrait.Elementar,
    traditions: ['Geoden'],
    increaseFactor: IncreaseFactor.C,
  },
  {
    name: 'feuerpfeil',
    label: 'Feuerpfeil',
    check: ['IN', 'CH', 'FF'] as SpellCheck,
    trait: SpellTrait.Elementar,
    traditions: ['Elfen'],
    increaseFactor: IncreaseFactor.A,
  },
  {
    name: 'firnlauf',
    label: 'Firnlauf',
    check: ['MU', 'KL', 'GE'] as SpellCheck,
    trait: SpellTrait.Elementar,
    traditions: ['Elfen'],
    increaseFactor: IncreaseFactor.B,
  },
  {
    name: 'fischflosse',
    label: 'Fischflosse',
    check: ['MU', 'IN', 'GE'] as SpellCheck,
    trait: SpellTrait.Verwandlung,
    traditions: ['Allgemein'],
    increaseFactor: IncreaseFactor.C,
  },
  {
    name: 'flammenwand',
    label: 'Flammenwand',
    check: ['MU', 'KL', 'CH'] as SpellCheck,
    trait: SpellTrait.Elementar,
    traditions: ['Gildenmagier'],
    increaseFactor: IncreaseFactor.B,
  },
  {
    name: 'fledermausruf',
    label: 'Fledermausruf',
    check: ['MU', 'CH', 'CH'] as SpellCheck,
    trait: SpellTrait.Daemonisch,
    traditions: ['Hexen'],
    increaseFactor: IncreaseFactor.B,
  },
  {
    name: 'flimFlam',
    label: 'Flim Flam',
    check: ['MU', 'KL', 'CH'] as SpellCheck,
    trait: SpellTrait.Elementar,
    traditions: ['Allgemein'],
    increaseFactor: IncreaseFactor.A,
  },
  {
    name: 'foramen',
    label: 'Foramen',
    check: ['KL', 'IN', 'FF'] as SpellCheck,
    trait: SpellTrait.Objekt,
    traditions: ['Gildenmagier', 'Hexen', 'Scharlatane'],
    increaseFactor: IncreaseFactor.C,
  },
  {
    name: 'fortifex',
    label: 'Fortifex',
    check: ['MU', 'IN', 'KO'] as SpellCheck,
    trait: SpellTrait.Telekinese,
    traditions: ['Gildenmagier', 'Scharlatane'],
    increaseFactor: IncreaseFactor.B,
  },
  {
    name: 'frigifaxius',
    label: 'Frigifaxius',
    check: ['MU', 'KL', 'CH'] as SpellCheck,
    trait: SpellTrait.Elementar,
    traditions: ['Gildenmagier', 'Kristallomanten', 'Nachtalben'],
    increaseFactor: IncreaseFactor.C,
  },
  {
    name: 'frigisphaero',
    label: 'Frigisphaero',
    check: ['MU', 'KL', 'KO'] as SpellCheck,
    trait: SpellTrait.Elementar,
    traditions: ['Gildenmagier', 'Kristallomanten'],
    increaseFactor: IncreaseFactor.D,
  },
  {
    name: 'frostleib',
    label: 'Frostleib',
    check: ['MU', 'KL', 'GE'] as SpellCheck,
    trait: SpellTrait.Elementar,
    traditions: ['Elfen', 'Nachtalben'],
    increaseFactor: IncreaseFactor.B,
  },
  {
    name: 'fulminictus',
    label: 'Fulminictus',
    check: ['KL', 'IN', 'KO'] as SpellCheck,
    trait: SpellTrait.Verwandlung,
    traditions: ['Elfen', 'Nachtalben'],
    increaseFactor: IncreaseFactor.C,
  },
  {
    name: 'gardianum',
    label: 'Gardianum',
    check: ['MU', 'KL', 'CH'] as SpellCheck,
    trait: SpellTrait.Antimagie,
    traditions: ['Druiden', 'Geoden', 'Gildenmagier'],
    increaseFactor: IncreaseFactor.B,
  },
  {
    name: 'gedankenbilder',
    label: 'Gedankenbilder',
    check: ['IN', 'CH', 'KO'] as SpellCheck,
    trait: SpellTrait.Einfluss,
    traditions: ['Elfen'],
    increaseFactor: IncreaseFactor.A,
  },
  {
    name: 'gefunden',
    label: 'Gefunden',
    check: ['KL', 'IN', 'GE'] as SpellCheck,
    trait: SpellTrait.Hellsicht,
    traditions: ['Hexen', 'Scharlatane'],
    increaseFactor: IncreaseFactor.A,
  },
  {
    name: 'geisteressenz',
    label: 'Geisteressenz',
    check: ['MU', 'KL', 'CH'] as SpellCheck,
    trait: SpellTrait.Sphaeren,
    traditions: ['Allgemein'],
    increaseFactor: IncreaseFactor.A,
  },
  {
    name: 'gifthaut',
    label: 'Gifthaut',
    check: ['MU', 'IN', 'KO'] as SpellCheck,
    trait: SpellTrait.Verwandlung,
    traditions: ['Hexen', 'Kristallomanten'],
    increaseFactor: IncreaseFactor.B,
  },
  {
    name: 'glutlauf',
    label: 'Glutlauf',
    check: ['MU', 'KL', 'GE'] as SpellCheck,
    trait: SpellTrait.Elementar,
    traditions: ['Elfen'],
    increaseFactor: IncreaseFactor.B,
  },
  {
    name: 'granitUndMarmor',
    label: 'Granit und Marmor',
    check: ['CH', 'KL', 'IN'] as SpellCheck,
    trait: SpellTrait.Daemonisch,
    traditions: ['Borbaradianer', 'Gildenmagier'],
    increaseFactor: IncreaseFactor.D,
  },
  {
    name: 'grosseGier',
    label: 'Große Gier',
    check: ['MU', 'IN', 'CH'] as SpellCheck,
    trait: SpellTrait.Einfluss,
    traditions: ['Druiden', 'Hexen'],
    increaseFactor: IncreaseFactor.B,
  },
  {
    name: 'grosseVerwirrung',
    label: 'Große Verwirrung',
    check: ['MU', 'KL', 'CH'] as SpellCheck,
    trait: SpellTrait.Einfluss,
    traditions: ['Druiden', 'Goblinzauberinnen'],
    increaseFactor: IncreaseFactor.B,
  },
  {
    name: 'halluzination',
    label: 'Halluzination',
    check: ['KL', 'IN', 'CH'] as SpellCheck,
    trait: SpellTrait.Einfluss,
    traditions: ['Druiden', 'Goblinzauberinnen'],
    increaseFactor: IncreaseFactor.C,
  },
  {
    name: 'harmloseGestalt',
    label: 'Harmlose Gestalt',
    check: ['KL', 'IN', 'CH'] as SpellCheck,
    trait: SpellTrait.Illusion,
    traditions: ['Hexen', 'Kristallomanten'],
    increaseFactor: IncreaseFactor.B,
  },
  {
    name: 'haselbusch',
    label: 'Haselbusch',
    check: ['IN', 'CH', 'FF'] as SpellCheck,
    trait: SpellTrait.Elementar,
    traditions: ['Elfen', 'Geoden', 'Goblinzauberinnen'],
    increaseFactor: IncreaseFactor.B,
  },
  {
    name: 'heilungsbann',
    label: 'Heilungsbann',
    check: ['KL', 'CH', 'FF'] as SpellCheck,
    trait: SpellTrait.Antimagie,
    traditions: ['Borbaradianer', 'Gildenmagier', 'Hexen'],
    increaseFactor: IncreaseFactor.B,
  },
  {
    name: 'hellsichtbann',
    label: 'Hellsichtbann',
    check: ['KL', 'IN', 'CH'] as SpellCheck,
    trait: SpellTrait.Antimagie,
    traditions: ['Druiden', 'Gildenmagier', 'Hexen', 'Kristallomanten', 'Scharlatane'],
    increaseFactor: IncreaseFactor.B,
  },
  {
    name: 'heptagramma',
    label: 'Heptagramma',
    check: ['MU', 'KL', 'CH'] as SpellCheck,
    trait: SpellTrait.Antimagie,
    traditions: ['Allgemein'],
    increaseFactor: IncreaseFactor.B,
  },
  {
    name: 'herrUeberDasTierreich',
    label: 'Herr über das Tierreich',
    check: ['MU', 'IN', 'CH'] as SpellCheck,
    trait: SpellTrait.Einfluss,
    traditions: ['Druiden', 'Geoden', 'Goblinzauberinnen', 'Kristallomanten'],
    increaseFactor: IncreaseFactor.C,
  },
  {
    name: 'herzschlagRuhe',
    label: 'Herzschlag ruhe',
    check: ['MU', 'CH', 'KK'] as SpellCheck,
    trait: SpellTrait.Daemonisch,
    traditions: ['Borbaradianer', 'Gildenmagier', 'Hexen'],
    increaseFactor: IncreaseFactor.C,
  },
  {
    name: 'hexagramma',
    label: 'Hexagramma',
    check: ['MU', 'KL', 'CH'] as SpellCheck,
    trait: SpellTrait.Antimagie,
    traditions: ['Druiden', 'Gildenmagier'],
    increaseFactor: IncreaseFactor.C,
  },
  {
    name: 'hexengalle',
    label: 'Hexengalle',
    check: ['KL', 'IN', 'KO'] as SpellCheck,
    trait: SpellTrait.Verwandlung,
    traditions: ['Geoden', 'Goblinzauberinnen', 'Hexen'],
    increaseFactor: IncreaseFactor.B,
  },
  {
    name: 'hexenholz',
    label: 'Hexenholz',
    check: ['KL', 'FF', 'KK'] as SpellCheck,
    trait: SpellTrait.Telekinese,
    traditions: ['Hexen'],
    increaseFactor: IncreaseFactor.B,
  },
  {
    name: 'hexenknoten',
    label: 'Hexenknoten',
    check: ['MU', 'IN', 'CH'] as SpellCheck,
    trait: SpellTrait.Einfluss,
    traditions: ['Hexen'],
    increaseFactor: IncreaseFactor.C,
  },
  {
    name: 'hexenkrallen',
    label: 'Hexenkrallen',
    check: ['KL', 'IN', 'KO'] as SpellCheck,
    trait: SpellTrait.Verwandlung,
    traditions: ['Hexen'],
    increaseFactor: IncreaseFactor.A,
  },
  {
    name: 'hexenspeichel',
    label: 'Hexenspeichel',
    check: ['IN', 'CH', 'FF'] as SpellCheck,
    trait: SpellTrait.Heilung,
    traditions: ['Goblinzauberinnen', 'Hexen'],
    increaseFactor: IncreaseFactor.B,
  },
  {
    name: 'hilfreichePfote',
    label: 'Hilfreiche Pfote',
    check: ['MU', 'IN', 'CH'] as SpellCheck,
    trait: SpellTrait.Einfluss,
    traditions: ['Elfen', 'Goblinzauberinnen'],
    increaseFactor: IncreaseFactor.A,
  },
  {
    name: 'hilfreicheSchwinge',
    label: 'Hilfreiche Schwinge',
    check: ['MU', 'IN', 'CH'] as SpellCheck,
    trait: SpellTrait.Einfluss,
    traditions: ['Elfen', 'Goblinzauberinnen'],
    increaseFactor: IncreaseFactor.A,
  },
  {
    name: 'hilfreicheTatze',
    label: 'Hilfreiche Tatze',
    check: ['MU', 'IN', 'CH'] as SpellCheck,
    trait: SpellTrait.Einfluss,
    traditions: ['Elfen', 'Goblinzauberinnen'],
    increaseFactor: IncreaseFactor.C,
  },
  {
    name: 'himmelslauf',
    label: 'Himmelslauf',
    check: ['MU', 'KL', 'GE'] as SpellCheck,
    trait: SpellTrait.Elementar,
    traditions: ['Elfen'],
    increaseFactor: IncreaseFactor.B,
  },
  {
    name: 'hoellenpein',
    label: 'Höllenpein',
    check: ['MU', 'IN', 'CH'] as SpellCheck,
    trait: SpellTrait.Einfluss,
    traditions: ['Borbaradianer', 'Gildenmagier', 'Nachtalben'],
    increaseFactor: IncreaseFactor.B,
  },
  {
    name: 'hornissenruf',
    label: 'Hornissenruf',
    check: ['MU', 'CH', 'CH'] as SpellCheck,
    trait: SpellTrait.Daemonisch,
    traditions: ['Hexen'],
    increaseFactor: IncreaseFactor.C,
  },
  {
    name: 'horriphobus',
    label: 'Horriphobus',
    check: ['MU', 'IN', 'CH'] as SpellCheck,
    trait: SpellTrait.Einfluss,
    traditions: ['Borbaradianer', 'Gildenmagier', 'Nachtalben'],
    increaseFactor: IncreaseFactor.B,
  },
  {
    name: 'humofaxius',
    label: 'Humofaxius',
    check: ['MU', 'KL', 'CH'] as SpellCheck,
    trait: SpellTrait.Elementar,
    traditions: ['Druiden', 'Geoden', 'Gildenmagier', 'Kristallomanten'],
    increaseFactor: IncreaseFactor.C,
  },
  {
    name: 'humosphaero',
    label: 'Humosphaero',
    check: ['MU', 'KL', 'KO'] as SpellCheck,
    trait: SpellTrait.Elementar,
    traditions: ['Druiden', 'Geoden', 'Gildenmagier', 'Kristallomanten'],
    increaseFactor: IncreaseFactor.D,
  },
  {
    name: 'humuspfeil',
    label: 'Humuspfeil',
    check: ['IN', 'CH', 'FF'] as SpellCheck,
    trait: SpellTrait.Elementar,
    traditions: ['Elfen'],
    increaseFactor: IncreaseFactor.A,
  },
  {
    name: 'ignifaxius',
    label: 'Ignifaxius',
    check: ['MU', 'KL', 'CH'] as SpellCheck,
    trait: SpellTrait.Elementar,
    traditions: ['Druiden', 'Geoden', 'Gildenmagier'],
    increaseFactor: IncreaseFactor.C,
  },
  {
    name: 'ignisphaero',
    label: 'Ignisphaero',
    check: ['MU', 'KL', 'KO'] as SpellCheck,
    trait: SpellTrait.Elementar,
    traditions: ['Druiden', 'Geoden', 'Gildenmagier'],
    increaseFactor: IncreaseFactor.D,
  },
  {
    name: 'ignorantia',
    label: 'Ignorantia',
    check: ['IN', 'CH', 'GE'] as SpellCheck,
    trait: SpellTrait.Einfluss,
    traditions: ['Scharlatane'],
    increaseFactor: IncreaseFactor.B,
  },
  {
    name: 'illusionsbann',
    label: 'Illusionsbann',
    check: ['KL', 'IN', 'CH'] as SpellCheck,
    trait: SpellTrait.Antimagie,
    traditions: ['Gildenmagier', 'Scharlatane'],
    increaseFactor: IncreaseFactor.B,
  },
  {
    name: 'imperavi',
    label: 'Imperavi',
    check: ['MU', 'KL', 'CH'] as SpellCheck,
    trait: SpellTrait.Einfluss,
    traditions: ['Druiden', 'Gildenmagier'],
    increaseFactor: IncreaseFactor.C,
  },
  {
    name: 'impersona',
    label: 'Impersona',
    check: ['IN', 'CH', 'FF'] as SpellCheck,
    trait: SpellTrait.Illusion,
    traditions: ['Scharlatane'],
    increaseFactor: IncreaseFactor.B,
  },
  {
    name: 'incendio',
    label: 'Incendio',
    check: ['KL', 'CH', 'KO'] as SpellCheck,
    trait: SpellTrait.Elementar,
    traditions: ['Borbaradianer', 'Gildenmagier', 'Kristallomanten', 'Scharlatane'],
    increaseFactor: IncreaseFactor.B,
  },
  {
    name: 'invercano',
    label: 'Invercano',
    check: ['MU', 'IN', 'FF'] as SpellCheck,
    trait: SpellTrait.Antimagie,
    traditions: ['Gildenmagier'],
    increaseFactor: IncreaseFactor.C,
  },
  {
    name: 'invinculo',
    label: 'Invinculo',
    check: ['KL', 'CH', 'KO'] as SpellCheck,
    trait: SpellTrait.Elementar,
    traditions: ['Geoden'],
    increaseFactor: IncreaseFactor.B,
  },
  {
    name: 'invocatioMinima',
    label: 'Invocatio Minima',
    check: ['MU', 'CH', 'KO'] as SpellCheck,
    trait: SpellTrait.Sphaeren,
    traditions: ['Borbaradianer', 'Gildenmagier', 'Hexen', 'Nachtalben'],
    increaseFactor: IncreaseFactor.A,
  },
  {
    name: 'karnifilo',
    label: 'Karnifilo',
    check: ['MU', 'IN', 'CH'] as SpellCheck,
    trait: SpellTrait.Einfluss,
    traditions: ['Gildenmagier', 'Kristallomanten', 'Nachtalben'],
    increaseFactor: IncreaseFactor.B,
  },
  {
    name: 'katzenaugen',
    label: 'Katzenaugen',
    check: ['KL', 'IN', 'KO'] as SpellCheck,
    trait: SpellTrait.Verwandlung,
    traditions: ['Hexen'],
    increaseFactor: IncreaseFactor.A,
  },
  {
    name: 'katzenruf',
    label: 'Katzenruf',
    check: ['MU', 'CH', 'CH'] as SpellCheck,
    trait: SpellTrait.Daemonisch,
    traditions: ['Hexen'],
    increaseFactor: IncreaseFactor.C,
  },
  {
    name: 'klarumPurum',
    label: 'Klarum Purum',
    check: ['KL', 'IN', 'CH'] as SpellCheck,
    trait: SpellTrait.Heilung,
    traditions: ['Allgemein'],
    increaseFactor: IncreaseFactor.B,
  },
  {
    name: 'krabbelnderSchrecken',
    label: 'Krabbelnder Schrecken',
    check: ['MU', 'CH', 'FF'] as SpellCheck,
    trait: SpellTrait.Daemonisch,
    traditions: ['Hexen'],
    increaseFactor: IncreaseFactor.C,
  },
  {
    name: 'kraftDesHumus',
    label: 'Kraft des Humus',
    check: ['IN', 'CH', 'KO'] as SpellCheck,
    trait: SpellTrait.Elementar,
    traditions: ['Druiden', 'Elfen', 'Geoden', 'Hexen', 'Kristallomanten'],
    increaseFactor: IncreaseFactor.A,
  },
  {
    name: 'kraftDesTieres',
    label: 'Kraft des Tieres',
    check: ['MU', 'IN', 'KO'] as SpellCheck,
    trait: SpellTrait.Verwandlung,
    traditions: ['Goblinzauberinnen', 'Hexen'],
    increaseFactor: IncreaseFactor.A,
  },
  {
    name: 'kraehenruf',
    label: 'Krähenruf',
    check: ['MU', 'CH', 'CH'] as SpellCheck,
    trait: SpellTrait.Daemonisch,
    traditions: ['Hexen'],
    increaseFactor: IncreaseFactor.C,
  },
  {
    name: 'kroetenruf',
    label: 'Krötenruf',
    check: ['MU', 'CH', 'CH'] as SpellCheck,
    trait: SpellTrait.Daemonisch,
    traditions: ['Hexen'],
    increaseFactor: IncreaseFactor.C,
  },
  {
    name: 'kroetensprung',
    label: 'Krötensprung',
    check: ['KL', 'IN', 'KO'] as SpellCheck,
    trait: SpellTrait.Verwandlung,
    traditions: ['Hexen'],
    increaseFactor: IncreaseFactor.A,
  },
  {
    name: 'kulminatio',
    label: 'Kulminatio',
    check: ['MU', 'IN', 'KO'] as SpellCheck,
    trait: SpellTrait.Elementar,
    traditions: ['Gildenmagier'],
    increaseFactor: IncreaseFactor.C,
  },
  {
    name: 'kusch',
    label: 'Kusch',
    check: ['MU', 'IN', 'CH'] as SpellCheck,
    trait: SpellTrait.Einfluss,
    traditions: ['Druiden', 'Goblinzauberinnen', 'Scharlatane'],
    increaseFactor: IncreaseFactor.A,
  },
  {
    name: 'lastDesAlters',
    label: 'Last des Alters',
    check: ['IN', 'CH', 'KO'] as SpellCheck,
    trait: SpellTrait.Daemonisch,
    traditions: ['Borbaradianer', 'Gildenmagier', 'Hexen'],
    increaseFactor: IncreaseFactor.C,
  },
  {
    name: 'levthansFeuer',
    label: 'Levthans Feuer',
    check: ['MU', 'IN', 'CH'] as SpellCheck,
    trait: SpellTrait.Einfluss,
    traditions: ['Hexen'],
    increaseFactor: IncreaseFactor.B,
  },
  {
    name: 'luftpfeil',
    label: 'Luftpfeil',
    check: ['IN', 'CH', 'FF'] as SpellCheck,
    trait: SpellTrait.Elementar,
    traditions: ['Elfen'],
    increaseFactor: IncreaseFactor.A,
  },
  {
    name: 'lungeDesLeviatan',
    label: 'Lunge des Leviatan',
    check: ['MU', 'IN', 'KO'] as SpellCheck,
    trait: SpellTrait.Heilung,
    traditions: ['Elfen', 'Gildenmagier'],
    increaseFactor: IncreaseFactor.A,
  },
  {
    name: 'malDerErschoepfung',
    label: 'Mal der Erschöpfung',
    check: ['MU', 'IN', 'CH'] as SpellCheck,
    trait: SpellTrait.Einfluss,
    traditions: ['Elfen', 'Hexen'],
    increaseFactor: IncreaseFactor.B,
  },
  {
    name: 'malDerSchwaeche',
    label: 'Mal der Schwäche',
    check: ['MU', 'IN', 'CH'] as SpellCheck,
    trait: SpellTrait.Einfluss,
    traditions: ['Elfen', 'Gildenmagier', 'Hexen'],
    increaseFactor: IncreaseFactor.B,
  },
  {
    name: 'manifesto',
    label: 'Manifesto',
    check: ['MU', 'KL', 'CH'] as SpellCheck,
    trait: SpellTrait.Sphaeren,
    traditions: ['Allgemein'],
    increaseFactor: IncreaseFactor.A,
  },
  {
    name: 'manusIllusionis',
    label: 'Manus Illusionis',
    check: ['KL', 'IN', 'CH'] as SpellCheck,
    trait: SpellTrait.Illusion,
    traditions: ['Gildenmagier', 'Scharlatane'],
    increaseFactor: IncreaseFactor.A,
  },
  {
    name: 'manusMiracula',
    label: 'Manus Miracula',
    check: ['KL', 'FF', 'KK'] as SpellCheck,
    trait: SpellTrait.Telekinese,
    traditions: ['Allgemein'],
    increaseFactor: IncreaseFactor.A,
  },
  {
    name: 'memorans',
    label: 'Memorans',
    check: ['KL', 'KL', 'IN'] as SpellCheck,
    trait: SpellTrait.Verwandlung,
    traditions: ['Druiden', 'Gildenmagier', 'Scharlatane'],
    increaseFactor: IncreaseFactor.A,
  },
  {
    name: 'menetekel',
    label: 'Menetekel',
    check: ['KL', 'CH', 'FF'] as SpellCheck,
    trait: SpellTrait.Illusion,
    traditions: ['Gildenmagier', 'Scharlatane'],
    increaseFactor: IncreaseFactor.A,
  },
  {
    name: 'minimusReductibus',
    label: 'Minimus Reductibus',
    check: ['KL', 'CH', 'GE'] as SpellCheck,
    trait: SpellTrait.Objekt,
    traditions: ['Gildenmagier'],
    increaseFactor: IncreaseFactor.D,
  },
  {
    name: 'motoricus',
    label: 'Motoricus',
    check: ['KL', 'FF', 'KK'] as SpellCheck,
    trait: SpellTrait.Telekinese,
    traditions: ['Allgemein'],
    increaseFactor: IncreaseFactor.B,
  },
  {
    name: 'nebelform',
    label: 'Nebelform',
    check: ['MU', 'IN', 'KO'] as SpellCheck,
    trait: SpellTrait.Verwandlung,
    traditions: ['Druiden'],
    increaseFactor: IncreaseFactor.C,
  },
  {
    name: 'nebelwand',
    label: 'Nebelwand',
    check: ['MU', 'KL', 'CH'] as SpellCheck,
    trait: SpellTrait.Elementar,
    traditions: ['Druiden', 'Elfen', 'Geoden', 'Kristallomanten', 'Nachtalben'],
    increaseFactor: IncreaseFactor.C,
  },
  {
    name: 'nuntiovolo',
    label: 'Nuntiovolo',
    check: ['MU', 'KL', 'CH'] as SpellCheck,
    trait: SpellTrait.Sphaeren,
    traditions: ['Gildenmagier', 'Hexen'],
    increaseFactor: IncreaseFactor.B,
  },
  {
    name: 'objectobscuro',
    label: 'Objectobscuro',
    check: ['KL', 'FF', 'KO'] as SpellCheck,
    trait: SpellTrait.Objekt,
    traditions: ['Kristallomanten', 'Scharlatane'],
    increaseFactor: IncreaseFactor.B,
  },
  {
    name: 'objectofixo',
    label: 'Objectofixo',
    check: ['MU', 'KL', 'KK'] as SpellCheck,
    trait: SpellTrait.Objekt,
    traditions: ['Kristallomanten', 'Scharlatane'],
    increaseFactor: IncreaseFactor.A,
  },
  {
    name: 'objectovoco',
    label: 'Objectovoco',
    check: ['KL', 'IN', 'CH'] as SpellCheck,
    trait: SpellTrait.Objekt,
    traditions: ['Elfen'],
    increaseFactor: IncreaseFactor.B,
  },
  {
    name: 'objektbann',
    label: 'Objektbann',
    check: ['KL', 'IN', 'FF'] as SpellCheck,
    trait: SpellTrait.Antimagie,
    traditions: ['Gildenmagier', 'Kristallomanten'],
    increaseFactor: IncreaseFactor.B,
  },
  {
    name: 'oculusAstralis',
    label: 'Oculus Astralis',
    check: ['KL', 'IN', 'CH'] as SpellCheck,
    trait: SpellTrait.Hellsicht,
    traditions: ['Allgemein'],
    increaseFactor: IncreaseFactor.B,
  },
  {
    name: 'oculusIllusionis',
    label: 'Oculus Illusionis',
    check: ['KL', 'IN', 'CH'] as SpellCheck,
    trait: SpellTrait.Illusion,
    traditions: ['Gildenmagier', 'Scharlatane'],
    increaseFactor: IncreaseFactor.B,
  },
  {
    name: 'odemArcanum',
    label: 'Odem Arcanum',
    check: ['KL', 'IN', 'IN'] as SpellCheck,
    trait: SpellTrait.Hellsicht,
    traditions: ['Allgemein'],
    increaseFactor: IncreaseFactor.A,
  },
  {
    name: 'oktagramma',
    label: 'Oktagramma',
    check: ['MU', 'KL', 'CH'] as SpellCheck,
    trait: SpellTrait.Antimagie,
    traditions: ['Allgemein'],
    increaseFactor: IncreaseFactor.B,
  },
  {
    name: 'orcanofaxius',
    label: 'Orcanofaxius',
    check: ['MU', 'KL', 'CH'] as SpellCheck,
    trait: SpellTrait.Elementar,
    traditions: ['Druiden', 'Geoden', 'Gildenmagier'],
    increaseFactor: IncreaseFactor.C,
  },
  {
    name: 'orcanosphaero',
    label: 'Orcanosphaero',
    check: ['MU', 'KL', 'KO'] as SpellCheck,
    trait: SpellTrait.Elementar,
    traditions: ['Druiden', 'Geoden', 'Gildenmagier'],
    increaseFactor: IncreaseFactor.D,
  },
  {
    name: 'pandaemonium',
    label: 'Pandaemonium',
    check: ['MU', 'CH', 'KK'] as SpellCheck,
    trait: SpellTrait.Daemonisch,
    traditions: ['Borbaradianer', 'Hexen', 'Nachtalben'],
    increaseFactor: IncreaseFactor.D,
  },
  {
    name: 'panikUeberkommeEuch',
    label: 'Panik überkomme euch',
    check: ['MU', 'KL', 'CH'] as SpellCheck,
    trait: SpellTrait.Einfluss,
    traditions: ['Borbaradianer', 'Druiden', 'Gildenmagier'],
    increaseFactor: IncreaseFactor.B,
  },
  {
    name: 'papageienruf',
    label: 'Papageienruf',
    check: ['MU', 'CH', 'CH'] as SpellCheck,
    trait: SpellTrait.Daemonisch,
    traditions: ['Hexen'],
    increaseFactor: IncreaseFactor.C,
  },
  {
    name: 'paralysis',
    label: 'Paralysis',
    check: ['KL', 'IN', 'KO'] as SpellCheck,
    trait: SpellTrait.Verwandlung,
    traditions: ['Druiden', 'Gildenmagier', 'Nachtalben'],
    increaseFactor: IncreaseFactor.B,
  },
  {
    name: 'penetrizzel',
    label: 'Penetrizzel',
    check: ['MU', 'KL', 'IN'] as SpellCheck,
    trait: SpellTrait.Hellsicht,
    traditions: ['Gildenmagier', 'Scharlatane'],
    increaseFactor: IncreaseFactor.B,
  },
  {
    name: 'pentagramma',
    label: 'Pentagramma',
    check: ['MU', 'KL', 'CH'] as SpellCheck,
    trait: SpellTrait.Antimagie,
    traditions: ['Gildenmagier', 'Hexen'],
    increaseFactor: IncreaseFactor.C,
  },
  {
    name: 'pestilenzErspueren',
    label: 'Pestilenz erspüren',
    check: ['MU', 'KL', 'IN'] as SpellCheck,
    trait: SpellTrait.Hellsicht,
    traditions: ['Druiden', 'Goblinzauberinnen'],
    increaseFactor: IncreaseFactor.A,
  },
  {
    name: 'pestodem',
    label: 'Pestodem',
    check: ['MU', 'IN', 'KO'] as SpellCheck,
    trait: SpellTrait.Daemonisch,
    traditions: ['Borbaradianer', 'Goblinzauberinnen', 'Hexen'],
    increaseFactor: IncreaseFactor.B,
  },
  {
    name: 'physiostabilis',
    label: 'Physiostabilis',
    check: ['KL', 'IN', 'FF'] as SpellCheck,
    trait: SpellTrait.Heilung,
    traditions: ['Gildenmagier'],
    increaseFactor: IncreaseFactor.B,
  },
  {
    name: 'plumbumbarum',
    label: 'Plumbumbarum',
    check: ['MU', 'CH', 'GE'] as SpellCheck,
    trait: SpellTrait.Einfluss,
    traditions: ['Druiden', 'Gildenmagier', 'Goblinzauberinnen', 'Kristallomanten', 'Scharlatane'],
    increaseFactor: IncreaseFactor.B,
  },
  {
    name: 'projectimago',
    label: 'Projectimago',
    check: ['MU', 'IN', 'CH'] as SpellCheck,
    trait: SpellTrait.Illusion,
    traditions: ['Scharlatane'],
    increaseFactor: IncreaseFactor.B,
  },
  {
    name: 'protectionis',
    label: 'Protectionis',
    check: ['KL', 'KO', 'CH'] as SpellCheck,
    trait: SpellTrait.Antimagie,
    traditions: ['Borbaradianer', 'Gildenmagier'],
    increaseFactor: IncreaseFactor.C,
  },
  {
    name: 'psychostabilis',
    label: 'Psychostabilis',
    check: ['KL', 'IN', 'FF'] as SpellCheck,
    trait: SpellTrait.Heilung,
    traditions: ['Allgemein'],
    increaseFactor: IncreaseFactor.B,
  },
  {
    name: 'radau',
    label: 'Radau',
    check: ['KL', 'FF', 'KK'] as SpellCheck,
    trait: SpellTrait.Telekinese,
    traditions: ['Hexen'],
    increaseFactor: IncreaseFactor.B,
  },
  {
    name: 'reflectimago',
    label: 'Reflectimago',
    check: ['KL', 'CH', 'FF'] as SpellCheck,
    trait: SpellTrait.Illusion,
    traditions: ['Scharlatane'],
    increaseFactor: IncreaseFactor.A,
  },
  {
    name: 'regeneratio',
    label: 'Regeneratio',
    check: ['IN', 'CH', 'KO'] as SpellCheck,
    trait: SpellTrait.Heilung,
    traditions: ['Elfen', 'Kristallomanten'],
    increaseFactor: IncreaseFactor.D,
  },
  {
    name: 'reptilea',
    label: 'Reptilea',
    check: ['MU', 'IN', 'CH'] as SpellCheck,
    trait: SpellTrait.Einfluss,
    traditions: ['Hexen', 'Kristallomanten'],
    increaseFactor: IncreaseFactor.C,
  },
  {
    name: 'respondami',
    label: 'Respondami',
    check: ['MU', 'IN', 'CH'] as SpellCheck,
    trait: SpellTrait.Einfluss,
    traditions: ['Druiden', 'Gildenmagier', 'Nachtalben'],
    increaseFactor: IncreaseFactor.B,
  },
  {
    name: 'salander',
    label: 'Salander',
    check: ['KL', 'IN', 'KO'] as SpellCheck,
    trait: SpellTrait.Verwandlung,
    traditions: ['Gildenmagier', 'Goblinzauberinnen', 'Kristallomanten'],
    increaseFactor: IncreaseFactor.C,
  },
  {
    name: 'sanfterFall',
    label: 'Sanfter Fall',
    check: ['MU', 'IN', 'GE'] as SpellCheck,
    trait: SpellTrait.Telekinese,
    traditions: ['Elfen'],
    increaseFactor: IncreaseFactor.A,
  },
  {
    name: 'sanftmut',
    label: 'Sanftmut',
    check: ['MU', 'IN', 'CH'] as SpellCheck,
    trait: SpellTrait.Einfluss,
    traditions: ['Druiden', 'Elfen', 'Geoden', 'Goblinzauberinnen', 'Hexen'],
    increaseFactor: IncreaseFactor.A,
  },
  {
    name: 'sapefacta',
    label: 'Sapefacta',
    check: ['KL', 'CH', 'FF'] as SpellCheck,
    trait: SpellTrait.Telekinese,
    traditions: ['Scharlatane'],
    increaseFactor: IncreaseFactor.A,
  },
  {
    name: 'satuariasHerrlichkeit',
    label: 'Satuarias Herrlichkeit',
    check: ['KL', 'IN', 'KO'] as SpellCheck,
    trait: SpellTrait.Verwandlung,
    traditions: ['Hexen'],
    increaseFactor: IncreaseFactor.B,
  },
  {
    name: 'schimmernderSchild',
    label: 'Schimmernder Schild',
    check: ['MU', 'IN', 'KO'] as SpellCheck,
    trait: SpellTrait.Telekinese,
    traditions: ['Gildenmagier'],
    increaseFactor: IncreaseFactor.A,
  },
  {
    name: 'schlangenruf',
    label: 'Schlangenruf',
    check: ['MU', 'CH', 'CH'] as SpellCheck,
    trait: SpellTrait.Daemonisch,
    traditions: ['Hexen'],
    increaseFactor: IncreaseFactor.C,
  },
  {
    name: 'schlechteAusstrahlung',
    label: 'Schlechte Ausstrahlung',
    check: ['MU', 'IN', 'CH'] as SpellCheck,
    trait: SpellTrait.Einfluss,
    traditions: ['Gildenmagier', 'Hexen'],
    increaseFactor: IncreaseFactor.B,
  },
  {
    name: 'schleierDerUnwissenheit',
    label: 'Schleier der Unwissenheit',
    check: ['MU', 'IN', 'CH'] as SpellCheck,
    trait: SpellTrait.Antimagie,
    traditions: ['Hexen'],
    increaseFactor: IncreaseFactor.B,
  },
  {
    name: 'schmerzenLindern',
    label: 'Schmerzen lindern',
    check: ['MU', 'IN', 'CH'] as SpellCheck,
    trait: SpellTrait.Heilung,
    traditions: ['Elfen', 'Gildenmagier'],
    increaseFactor: IncreaseFactor.B,
  },
  {
    name: 'schuppenhaut',
    label: 'Schuppenhaut',
    check: ['MU', 'IN', 'GE'] as SpellCheck,
    trait: SpellTrait.Verwandlung,
    traditions: ['Gildenmagier', 'Hexen'],
    increaseFactor: IncreaseFactor.C,
  },
  {
    name: 'schwarzUndRot',
    label: 'Schwarz und Rot',
    check: ['MU', 'CH', 'KO'] as SpellCheck,
    trait: SpellTrait.Verwandlung,
    traditions: ['Borbaradianer', 'Gildenmagier', 'Hexen'],
    increaseFactor: IncreaseFactor.C,
  },
  {
    name: 'schwarzerSchrecken',
    label: 'Schwarzer Schrecken',
    check: ['MU', 'IN', 'CH'] as SpellCheck,
    trait: SpellTrait.Einfluss,
    traditions: ['Borbaradianer', 'Druiden', 'Nachtalben'],
    increaseFactor: IncreaseFactor.A,
  },
  {
    name: 'seelentierErkennen',
    label: 'Seelentier erkennen',
    check: ['MU', 'IN', 'CH'] as SpellCheck,
    trait: SpellTrait.Hellsicht,
    traditions: ['Elfen', 'Hexen'],
    increaseFactor: IncreaseFactor.B,
  },
  {
    name: 'seidenzunge',
    label: 'Seidenzunge',
    check: ['KL', 'IN', 'CH'] as SpellCheck,
    trait: SpellTrait.Einfluss,
    traditions: ['Elfen'],
    increaseFactor: IncreaseFactor.A,
  },
  {
    name: 'sensattacco',
    label: 'Sensattacco',
    check: ['MU', 'IN', 'GE'] as SpellCheck,
    trait: SpellTrait.Einfluss,
    traditions: ['Gildenmagier'],
    increaseFactor: IncreaseFactor.C,
  },
  {
    name: 'sensibar',
    label: 'Sensibar',
    check: ['MU', 'IN', 'CH'] as SpellCheck,
    trait: SpellTrait.Hellsicht,
    traditions: ['Allgemein'],
    increaseFactor: IncreaseFactor.B,
  },
  {
    name: 'serpentialis',
    label: 'Serpentialis',
    check: ['MU', 'CH', 'GE'] as SpellCheck,
    trait: SpellTrait.Verwandlung,
    traditions: ['Hexen', 'Kristallomanten'],
    increaseFactor: IncreaseFactor.B,
  },
  {
    name: 'silentium',
    label: 'Silentium',
    check: ['KL', 'FF', 'KK'] as SpellCheck,
    trait: SpellTrait.Telekinese,
    traditions: ['Elfen'],
    increaseFactor: IncreaseFactor.B,
  },
  {
    name: 'sinesigil',
    label: 'Sinesigil',
    check: ['KL', 'IN', 'FF'] as SpellCheck,
    trait: SpellTrait.Illusion,
    traditions: ['Gildenmagier', 'Hexen'],
    increaseFactor: IncreaseFactor.A,
  },
  {
    name: 'skelettarius',
    label: 'Skelettarius',
    check: ['MU', 'KL', 'CH'] as SpellCheck,
    trait: SpellTrait.Daemonisch,
    traditions: ['Borbaradianer', 'Gildenmagier'],
    increaseFactor: IncreaseFactor.B,
  },
  {
    name: 'solidirid',
    label: 'Solidirid',
    check: ['MU', 'IN', 'KO'] as SpellCheck,
    trait: SpellTrait.Telekinese,
    traditions: ['Elfen'],
    increaseFactor: IncreaseFactor.C,
  },
  {
    name: 'somnigravis',
    label: 'Somnigravis',
    check: ['MU', 'IN', 'CH'] as SpellCheck,
    trait: SpellTrait.Einfluss,
    traditions: ['Druiden', 'Elfen', 'Goblinzauberinnen', 'Kristallomanten'],
    increaseFactor: IncreaseFactor.B,
  },
  {
    name: 'sphaerenbann',
    label: 'Sphärenbann',
    check: ['MU', 'IN', 'CH'] as SpellCheck,
    trait: SpellTrait.Antimagie,
    traditions: ['Gildenmagier'],
    increaseFactor: IncreaseFactor.B,
  },
  {
    name: 'spinnenlauf',
    label: 'Spinnenlauf',
    check: ['KL', 'IN', 'KO'] as SpellCheck,
    trait: SpellTrait.Verwandlung,
    traditions: ['Hexen', 'Nachtalben'],
    increaseFactor: IncreaseFactor.A,
  },
  {
    name: 'spinnenruf',
    label: 'Spinnenruf',
    check: ['MU', 'CH', 'CH'] as SpellCheck,
    trait: SpellTrait.Daemonisch,
    traditions: ['Hexen'],
    increaseFactor: IncreaseFactor.C,
  },
  {
    name: 'spurlos',
    label: 'Spurlos',
    check: ['KL', 'FF', 'KK'] as SpellCheck,
    trait: SpellTrait.Telekinese,
    traditions: ['Elfen', 'Nachtalben'],
    increaseFactor: IncreaseFactor.B,
  },
  {
    name: 'standfest',
    label: 'Standfest',
    check: ['MU', 'IN', 'GE'] as SpellCheck,
    trait: SpellTrait.Heilung,
    traditions: ['Elfen'],
    increaseFactor: IncreaseFactor.A,
  },
  {
    name: 'steinwand',
    label: 'Steinwand',
    check: ['MU', 'KL', 'CH'] as SpellCheck,
    trait: SpellTrait.Elementar,
    traditions: ['Druiden', 'Geoden', 'Gildenmagier'],
    increaseFactor: IncreaseFactor.B,
  },
  {
    name: 'stillstand',
    label: 'Stillstand',
    check: ['MU', 'IN', 'KO'] as SpellCheck,
    trait: SpellTrait.Elementar,
    traditions: ['Druiden', 'Geoden', 'Gildenmagier', 'Kristallomanten', 'Nachtalben'],
    increaseFactor: IncreaseFactor.C,
  },
  {
    name: 'sturmDerVerunsicherung',
    label: 'Sturm der Verunsicherung',
    check: ['MU', 'KL', 'CH'] as SpellCheck,
    trait: SpellTrait.Einfluss,
    traditions: ['Druiden', 'Geoden', 'Hexen'],
    increaseFactor: IncreaseFactor.B,
  },
  {
    name: 'sturmwand',
    label: 'Sturmwand',
    check: ['MU', 'KL', 'CH'] as SpellCheck,
    trait: SpellTrait.Elementar,
    traditions: ['Druiden', 'Geoden'],
    increaseFactor: IncreaseFactor.B,
  },
  {
    name: 'sumpfstrudel',
    label: 'Sumpfstrudel',
    check: ['KL', 'IN', 'IN'] as SpellCheck,
    trait: SpellTrait.Elementar,
    traditions: ['Druiden', 'Elfen', 'Geoden', 'Gildenmagier', 'Hexen'],
    increaseFactor: IncreaseFactor.B,
  },
  {
    name: 'sumusElixiere',
    label: 'Sumus Elixiere',
    check: ['KL', 'IN', 'IN'] as SpellCheck,
    trait: SpellTrait.Objekt,
    traditions: ['Druiden'],
    increaseFactor: IncreaseFactor.A,
  },
  {
    name: 'taubheit',
    label: 'Taubheit',
    check: ['KL', 'IN', 'CH'] as SpellCheck,
    trait: SpellTrait.Einfluss,
    traditions: ['Goblinzauberinnen', 'Scharlatane'],
    increaseFactor: IncreaseFactor.B,
  },
  {
    name: 'telekinesebann',
    label: 'Telekinesebann',
    check: ['KL', 'IN', 'FF'] as SpellCheck,
    trait: SpellTrait.Antimagie,
    traditions: ['Gildenmagier', 'Kristallomanten', 'Scharlatane'],
    increaseFactor: IncreaseFactor.B,
  },
  {
    name: 'temporalbann',
    label: 'Temporalbann',
    check: ['MU', 'IN', 'CH'] as SpellCheck,
    trait: SpellTrait.Antimagie,
    traditions: ['Druiden', 'Geoden', 'Gildenmagier', 'Hexen', 'Kristallomanten'],
    increaseFactor: IncreaseFactor.B,
  },
  {
    name: 'tempusStasis',
    label: 'Tempus Stasis',
    check: ['MU', 'KL', 'KK'] as SpellCheck,
    trait: SpellTrait.Temporal,
    traditions: ['Gildenmagier', 'Kristallomanten'],
    increaseFactor: IncreaseFactor.C,
  },
  {
    name: 'tiereBesprechen',
    label: 'Tiere besprechen',
    check: ['MU', 'IN', 'CH'] as SpellCheck,
    trait: SpellTrait.Heilung,
    traditions: ['Geoden', 'Hexen'],
    increaseFactor: IncreaseFactor.A,
  },
  {
    name: 'tiergedanken',
    label: 'Tiergedanken',
    check: ['MU', 'IN', 'CH'] as SpellCheck,
    trait: SpellTrait.Hellsicht,
    traditions: ['Elfen', 'Geoden', 'Hexen', 'Kristallomanten'],
    increaseFactor: IncreaseFactor.A,
  },
  {
    name: 'transversalis',
    label: 'Transversalis',
    check: ['MU', 'CH', 'KO'] as SpellCheck,
    trait: SpellTrait.Sphaeren,
    traditions: ['Gildenmagier'],
    increaseFactor: IncreaseFactor.C,
  },
  {
    name: 'unentflammbarkeit',
    label: 'Unentflammbarkeit',
    check: ['MU', 'IN', 'KO'] as SpellCheck,
    trait: SpellTrait.Elementar,
    traditions: ['Hexen'],
    increaseFactor: IncreaseFactor.A,
  },
  {
    name: 'ungeschickt',
    label: 'Ungeschickt',
    check: ['MU', 'IN', 'CH'] as SpellCheck,
    trait: SpellTrait.Einfluss,
    traditions: ['Elfen', 'Hexen'],
    increaseFactor: IncreaseFactor.B,
  },
  {
    name: 'verunsicherung',
    label: 'Verunsicherung',
    check: ['MU', 'IN', 'CH'] as SpellCheck,
    trait: SpellTrait.Einfluss,
    traditions: ['Elfen'],
    increaseFactor: IncreaseFactor.B,
  },
  {
    name: 'verwandlungsbann',
    label: 'Verwandlungsbann',
    check: ['KL', 'CH', 'FF'] as SpellCheck,
    trait: SpellTrait.Antimagie,
    traditions: ['Gildenmagier', 'Hexen'],
    increaseFactor: IncreaseFactor.B,
  },
  {
    name: 'vipernblick',
    label: 'Vipernblick',
    check: ['MU', 'MU', 'CH'] as SpellCheck,
    trait: SpellTrait.Einfluss,
    traditions: ['Hexen', 'Kristallomanten'],
    increaseFactor: IncreaseFactor.C,
  },
  {
    name: 'visibili',
    label: 'Visibili',
    check: ['KL', 'IN', 'KO'] as SpellCheck,
    trait: SpellTrait.Verwandlung,
    traditions: ['Elfen', 'Nachtalben'],
    increaseFactor: IncreaseFactor.B,
  },
  {
    name: 'vogelzwitschern',
    label: 'Vogelzwitschern',
    check: ['MU', 'IN', 'GE'] as SpellCheck,
    trait: SpellTrait.Illusion,
    traditions: ['Scharlatane'],
    increaseFactor: IncreaseFactor.A,
  },
  {
    name: 'warmesGefriere',
    label: 'Warmes gefriere',
    check: ['KL', 'CH', 'GE'] as SpellCheck,
    trait: SpellTrait.Elementar,
    traditions: ['Gildenmagier'],
    increaseFactor: IncreaseFactor.A,
  },
  {
    name: 'wasseratem',
    label: 'Wasseratem',
    check: ['KL', 'IN', 'KO'] as SpellCheck,
    trait: SpellTrait.Verwandlung,
    traditions: ['Elfen', 'Geoden'],
    increaseFactor: IncreaseFactor.B,
  },
  {
    name: 'wasserpfeil',
    label: 'Wasserpfeil',
    check: ['IN', 'CH', 'FF'] as SpellCheck,
    trait: SpellTrait.Elementar,
    traditions: ['Elfen'],
    increaseFactor: IncreaseFactor.A,
  },
  {
    name: 'welleDerReinigung',
    label: 'Welle der Reinigung',
    check: ['MU', 'KL', 'KK'] as SpellCheck,
    trait: SpellTrait.Verwandlung,
    traditions: ['Gildenmagier'],
    increaseFactor: IncreaseFactor.B,
  },
  {
    name: 'welleDesSchmerzes',
    label: 'Welle des Schmerzes',
    check: ['MU', 'KL', 'KK'] as SpellCheck,
    trait: SpellTrait.Verwandlung,
    traditions: ['Gildenmagier', 'Hexen'],
    increaseFactor: IncreaseFactor.C,
  },
  {
    name: 'wellenlauf',
    label: 'Wellenlauf',
    check: ['MU', 'KL', 'GE'] as SpellCheck,
    trait: SpellTrait.Elementar,
    traditions: ['Elfen', 'Nachtalben'],
    increaseFactor: IncreaseFactor.B,
  },
  {
    name: 'wellenwand',
    label: 'Wellenwand',
    check: ['MU', 'KL', 'CH'] as SpellCheck,
    trait: SpellTrait.Elementar,
    traditions: ['Druiden', 'Geoden', 'Gildenmagier', 'Nachtalben'],
    increaseFactor: IncreaseFactor.B,
  },
  {
    name: 'windhose',
    label: 'Windhose',
    check: ['MU', 'IN', 'KK'] as SpellCheck,
    trait: SpellTrait.Elementar,
    traditions: ['Druiden', 'Geoden'],
    increaseFactor: IncreaseFactor.D,
  },
  {
    name: 'windstille',
    label: 'Windstille',
    check: ['MU', 'IN', 'CH'] as SpellCheck,
    trait: SpellTrait.Elementar,
    traditions: ['Druiden', 'Elfen', 'Gildenmagier'],
    increaseFactor: IncreaseFactor.A,
  },
  {
    name: 'wipfellauf',
    label: 'Wipfellauf',
    check: ['MU', 'KL', 'GE'] as SpellCheck,
    trait: SpellTrait.Elementar,
    traditions: ['Elfen'],
    increaseFactor: IncreaseFactor.B,
  },
  {
    name: 'wogeDerVersteinerung',
    label: 'Woge der Versteinerung',
    check: ['MU', 'KL', 'KO'] as SpellCheck,
    trait: SpellTrait.Verwandlung,
    traditions: ['Gildenmagier', 'Hexen'],
    increaseFactor: IncreaseFactor.B,
  },
  {
    name: 'wolfstatze',
    label: 'Wolfstatze',
    check: ['MU', 'IN', 'GE'] as SpellCheck,
    trait: SpellTrait.Verwandlung,
    traditions: ['Allgemein'],
    increaseFactor: IncreaseFactor.C,
  },
  {
    name: 'wuestenlauf',
    label: 'Wüstenlauf',
    check: ['MU', 'KL', 'GE'] as SpellCheck,
    trait: SpellTrait.Elementar,
    traditions: ['Elfen'],
    increaseFactor: IncreaseFactor.B,
  },
  {
    name: 'zauberpferdHerbeirufen',
    label: 'Zauberpferd herbeirufen',
    check: ['KL', 'IN', 'CH'] as SpellCheck,
    trait: SpellTrait.Sphaeren,
    traditions: ['Elfen'],
    increaseFactor: IncreaseFactor.B,
  },
  {
    name: 'zitterfinger',
    label: 'Zitterfinger',
    check: ['MU', 'IN', 'CH'] as SpellCheck,
    trait: SpellTrait.Einfluss,
    traditions: ['Gildenmagier', 'Hexen'],
    increaseFactor: IncreaseFactor.B,
  },
  {
    name: 'zornDerElemente',
    label: 'Zorn der Elemente',
    check: ['MU', 'KL', 'CH'] as SpellCheck,
    trait: SpellTrait.Elementar,
    traditions: ['Druiden', 'Geoden', 'Goblinzauberinnen', 'Kristallomanten'],
    increaseFactor: IncreaseFactor.B,
  },
  {
    name: 'zungeBetaeuben',
    label: 'Zunge betäuben',
    check: ['KL', 'IN', 'CH'] as SpellCheck,
    trait: SpellTrait.Einfluss,
    traditions: ['Druiden'],
    increaseFactor: IncreaseFactor.C,
  },
  {
    name: 'zweifelSchueren',
    label: 'Zweifel schüren',
    check: ['KL', 'IN', 'CH'] as SpellCheck,
    trait: SpellTrait.Einfluss,
    traditions: ['Druiden', 'Goblinzauberinnen'],
    increaseFactor: IncreaseFactor.B,
  },
  {
    name: 'zwingtanz',
    label: 'Zwingtanz',
    check: ['MU', 'KL', 'CH'] as SpellCheck,
    trait: SpellTrait.Einfluss,
    traditions: ['Druiden'],
    increaseFactor: IncreaseFactor.C,
  },
];
