// ─── AUTO-GENERATED by tools/extract-pdf-data.mjs (PDF *Modifikator / *Grundwert formulas). Do not edit by hand. ───
// Maps an advantage/special-ability slug → its effect on derived stats. perLevel scales with the entry's level
// (e.g. Hohe Lebenskraft III → +3); flat applies once. Energy base = 20 + round(factor × Leiteigenschaft).

export type DerivedStatKey =
  | 'lifePoints' | 'astralPoints' | 'karmaPoints' | 'spirit' | 'toughness'
  | 'dodge' | 'initiative' | 'movement' | 'woundThreshold' | 'fatePoints';

export interface StatModifier { stat: DerivedStatKey; perLevel?: number; flat?: number; }

export const STAT_MODIFIERS: Record<string, StatModifier[]> = {
  "behabig": [{ stat: "movement", flat: -1 }],
  "dschinnenblutahn": [{ stat: "initiative", flat: 2 }, { stat: "movement", flat: 1 }],
  "eisern": [{ stat: "woundThreshold", flat: 1 }],
  "feenblutahn": [{ stat: "dodge", flat: 1 }],
  "flink": [{ stat: "movement", flat: 1 }],
  "glaesern": [{ stat: "woundThreshold", flat: -1 }],
  "gluck": [{ stat: "fatePoints", perLevel: 1 }],
  "hoheAstralkraft": [{ stat: "astralPoints", perLevel: 1 }],
  "hoheKarmalkraft": [{ stat: "karmaPoints", perLevel: 1 }],
  "hoheLebenskraft": [{ stat: "lifePoints", perLevel: 1 }],
  "hoheSeelenkraft": [{ stat: "spirit", flat: 1 }],
  "hoheZahigkeit": [{ stat: "toughness", flat: 1 }],
  "kampfreflexe": [{ stat: "initiative", flat: 1 }],
  "niedrigeAstralkraft": [{ stat: "astralPoints", perLevel: -1 }],
  "niedrigeKarmalkraft": [{ stat: "karmaPoints", perLevel: -1 }],
  "niedrigeLebenskraft": [{ stat: "lifePoints", perLevel: -1 }],
  "niedrigeSeelenkraft": [{ stat: "spirit", flat: -1 }],
  "niedrigeZahigkeit": [{ stat: "toughness", flat: -1 }],
  "pech": [{ stat: "fatePoints", perLevel: -1 }],
  "verbesserteAusweichen": [{ stat: "dodge", flat: 1 }],
};

/** Caster energy base = CASTER_ENERGY_BASE + round(factor × Leiteigenschaft). Factor per tradition (default 1). */
export const CASTER_ENERGY_BASE = 20;

export const TRADITION_ENERGY_FACTOR: Record<string, { factor: number; leit?: string }> = {
  Animisten: {
    factor: 0.5,
    leit: "IN"
  },
  "Brobim-Geoden": {
    factor: 1,
    leit: "CH"
  },
  Geoden: {
    factor: 1,
    leit: "CH"
  },
  Hochelfen: {
    factor: 1
  },
  Zauberbarden: {
    factor: 0.5,
    leit: "CH"
  },
  "Zaubertänzer": {
    factor: 0.5,
    leit: "CH"
  },
  "Animisten: Anach-Nûr": {
    factor: 0.5,
    leit: "IN"
  },
  "Animisten: Bakaroghs": {
    factor: 0.5,
    leit: "IN"
  },
  "Animisten: Durro-Dûn": {
    factor: 0.5,
    leit: "IN"
  },
  "Animisten: Hadan-Harigastur": {
    factor: 0.5,
    leit: "IN"
  },
  "Animisten: Mudran…Nuriq": {
    factor: 0.5,
    leit: "IN"
  },
  "Animisten: Nipakau-kocanan": {
    factor: 0.5,
    leit: "IN"
  },
  "Animisten: Nuan": {
    factor: 0.5,
    leit: "IN"
  },
  Borbaradianer: {
    factor: 1,
    leit: "MU"
  },
  "Brobim-Geoden (Erz)": {
    factor: 1,
    leit: "CH"
  },
  "Brobim-Geoden (Feuer)": {
    factor: 1,
    leit: "CH"
  },
  "Brobim-Geoden (Luft)": {
    factor: 1,
    leit: "CH"
  },
  "Dämonen": {
    factor: 1,
    leit: "MU"
  },
  Darna: {
    factor: 0.5,
    leit: "IN"
  },
  Drachen: {
    factor: 1,
    leit: "MU"
  },
  Druiden: {
    factor: 1,
    leit: "KL"
  },
  "Einhörner": {
    factor: 1,
    leit: "IN"
  },
  Elementare: {
    factor: 1,
    leit: "CH"
  },
  Elfen: {
    factor: 1,
    leit: "IN"
  },
  Feen: {
    factor: 1,
    leit: "CH"
  },
  "Frühe Borbaradianer": {
    factor: 1,
    leit: "MU"
  },
  Geister: {
    factor: 1,
    leit: "IN"
  },
  "Geoden (Eis)": {
    factor: 1,
    leit: "CH"
  },
  "Geoden (Erz)": {
    factor: 1,
    leit: "CH"
  },
  "Geoden (Feuer)": {
    factor: 1,
    leit: "CH"
  },
  "Geoden (Humus)": {
    factor: 1,
    leit: "CH"
  },
  "Geoden (Luft)": {
    factor: 1,
    leit: "CH"
  },
  "Geoden (Wasser)": {
    factor: 1,
    leit: "CH"
  },
  Gildenmagier: {
    factor: 1,
    leit: "KL"
  },
  Goblinzauberinnen: {
    factor: 1,
    leit: "IN"
  },
  Graumotten: {
    factor: 1,
    leit: "IN"
  },
  Hexen: {
    factor: 1,
    leit: "CH"
  },
  "Himmelsrösser": {
    factor: 1,
    leit: "IN"
  },
  "Karfunkel-Elfen": {
    factor: 1,
    leit: "IN"
  },
  "Katzen-Träumer": {
    factor: 1,
    leit: "CH"
  },
  Kristalloide: {
    factor: 1,
    leit: "KL"
  },
  Kristallomanten: {
    factor: 1,
    leit: "KL"
  },
  Nachtalben: {
    factor: 1,
    leit: "MU"
  },
  Necker: {
    factor: 1,
    leit: "CH"
  },
  Petromantierer: {
    factor: 1,
    leit: "IN"
  },
  Qabalyamagier: {
    factor: 1,
    leit: "KL"
  },
  Scharlatane: {
    factor: 1,
    leit: "CH"
  },
  Schelme: {
    factor: 1,
    leit: "IN"
  },
  Sphingen: {
    factor: 1,
    leit: "IN"
  },
  "Tsatuara-Anhängerinnen": {
    factor: 1,
    leit: "CH"
  },
  Waldschrate: {
    factor: 1,
    leit: "IN"
  },
  Zauberalchimisten: {
    factor: 0.5,
    leit: "KL"
  },
  "Zauberbarden: Ceoladir": {
    factor: 0.5,
    leit: "CH"
  },
  "Zauberbarden: Derwische": {
    factor: 0.5,
    leit: "CH"
  },
  "Zauberbarden: Sangara": {
    factor: 0.5,
    leit: "CH"
  },
  "Zauberbarden: Satuduraki": {
    factor: 0.5,
    leit: "CH"
  },
  "Zaubertänzer: Hazaqi": {
    factor: 0.5,
    leit: "CH"
  },
  "Zaubertänzer: Majuna": {
    factor: 0.5,
    leit: "CH"
  },
  "Zaubertänzer: Rahkisa": {
    factor: 0.5,
    leit: "CH"
  },
  "Zaubertänzer: Sharisadim": {
    factor: 0.5,
    leit: "CH"
  },
  Zibiljas: {
    factor: 1,
    leit: "IN"
  }
};
