/** German display names for book-generator dropdown options and result lists. */

/** Book type filter options */
export const BOOK_TYPE_NAMES: Record<string, string> = {
  none:    'Alle Buchtypen',
  magic:   'Zauberbuch',
  divine:  'Religionswerk',
  profane: 'Profanes Buch',
};

/** Whether the generated book should have a special feature */
export const FEATURE_NAMES: Record<string, string> = {
  yes:    'Hat eine Besonderheit',
  random: 'Hat eventuell eine Besonderheit',
};

/** First part of a generated book title (e.g. "Handbuch ...") */
export const BOOK_NAMES_PART_ONE: Record<string, string> = {
  primer:       'Fibel ',
  basics:       'Das Einmaleins ',
  handbook:     'Handbuch ',
  vademecum:    'Vademecum ',
  compendium:   'Kompendium ',
  basicConcepts:'Grundbegriffe ',
  art:          'Die Kunst ',
  dangers:      'Von den Gefahren ',
  essence:      'Vom Wesen ',
  secrets:      'Geheimnisse ',
  book:         'Das Buch ',
  almanac:      'Almanach ',
  lexicon:      'Lexikon ',
  register:     'Register ',
  chronicle:    'Chronik ',
  history:      'Geschichte ',
  encyclopedia: 'Enzyklopädie ',
  codex:        'Kodex ',
  fundamentals: 'Grundlagen ',
  theory:       'Theorie ',
};

/** Second part of a generated book title (e.g. "... der Magie ...") */
export const BOOK_NAMES_PART_TWO: Record<string, string> = {
  unfathomable:     'des Unergründlichen ',
  whiteMagic:       'der Weißen Magie ',
  praioticOrder:    'der praiotischen Ordnung ',
  blackMagic:       'der Schwarzen Magie ',
  rondraBehavior:   'des rondragefälligen Verhaltens ',
  magicSleep:       'des magischen Schlafes ',
  seaGods:          'der Meeresgötter ',
  necromancy:       'der Nekromantie ',
  hospitality:      'der Gastfreundschaft ',
  domination:       'der Beherrschung ',
  silence:          'des Schweigens ',
  delusions:        'der Wahnbilder ',
  hesindeKnowledge: 'der hesindegefälligen Erkenntnis ',
  mindReading:      'des Gedankenlesens ',
  hunting:          'der Jagd ',
  curseMagic:       'der Fluchmagie ',
  rebirth:          'der Wiedergeburt ',
  exorcisms:        'der Exorzismen ',
  luck:             'des Glücks ',
  invocations:      'der Invokationen ',
  sowing:           'der Aussaat ',
  magicDestruction: 'der magischen Zerstörung ',
  ingerimmCraft:    'des ingerimmgefälligen Handwerks ',
  shapeShifting:    'der Formveränderung ',
  rahjanianBliss:   'der rahjanischen Wonne ',
  elementalMagic:   'der Elementarmagie ',
  adventureLust:    'der Abenteuerlust ',
  shapeChange:      'der Gestaltwandlung ',
  victoryAndGold:   'des Sieges und des Goldes ',
  objectMagic:      'der Objektmagie ',
  charity:          'der Mildtätigkeit ',
  clairvoyance:     'der Hellseherei ',
  marbiden:         'der Marbiden ',
  magicIllusions:   'der magischen Illusionen ',
  swafnirCult:      'des Swafnirkultes ',
  counterspells:    'der Gegenzauber ',
  mechanics:        'der Mechanik ',
  demonology:       'der Dämonologie ',
  urtulamidicGods:  'der urtulamidischen Götter ',
};

/** Third part of a generated book title (e.g. "... der Verwandlung") */
export const BOOK_NAMES_PART_THREE: Record<string, string> = {
  transformation:           'der Verwandlung',
  elvenMythology:           'der Sagenwelt der Elfen',
  artifactMagic:            'der Artefaktmagie',
  dwarvenLegends:           'der Zwergenlegenden',
  alchemy:                  'der Alchimie',
  dragons:                  'der Drachen',
  enchantments:             'der Verzauberungen',
  demons:                   'der Dämonen',
  weatherMagic:             'der Wettermagie',
  travel:                   'des Reisens',
  witchcraft:               'der Hexerei',
  history:                  'der Geschichte',
  magicalAnalysis:          'der magischen Analyse',
  novadis:                  'der Novadis',
  phantasmagoria:           'der Phantasmagorien',
  mathematics:              'der Mathematik',
  spiritSummoning:          'der Geisterbeschwörungen',
  healingArts:              'der Heilkunde',
  mentalInfluence:          'der geistigen Beeinflussung',
  castles:                  'der Schlösser',
  metamorphoses:            'der Metamorphosen',
  wilderness:               'der Wildnis',
  magicalAnimation:         'der magischen Belebung',
  mountains:                'der Berge',
  protectionAndUtilitySpells:'der Schutz- und Nutzzauber',
  theNameless:              'des Namenlosen',
  loveSpells:               'der Liebeszauber',
  creatures:                'der Kreaturen',
  invisibleReality:         'der unsichtbaren Wirklichkeit',
  tulamidLands:             'der Tulamidenlande',
  magicalHealing:           'der magischen Heilung',
  meridianas:               'Meridianas',
  translocations:           'der Translokationen',
  maraskans:                'Maraskans',
  oracles:                  'der Orakel',
  heroes:                   'der Helden',
  enchantedPlaces:          'der verzauberten Orte',
  villains:                 'der Schurken',
  limbus:                   'des Limbus\'',
  alveran:                  'Alverans',
};

/** Special feature descriptions for a book — displayed under the book title */
export const BOOK_FEATURE_NAMES: Record<string, string> = {
  format:        'Das Buch weist ein ungewöhnliches, von seiner üblichen Herstellung abweichendes Buchformat auf. Beispiele sind: Quer- statt Hochformat, ein fünfeckiges Buch oder ein Leporello, Pergament oder Papyrus anstelle von Papier, vielleicht sogar Menschen- oder Zwergenhaut, lebende Augen, Teile von Tieren, etwa Flügel, Federn oder Schwänze als Lesezeichen.',
  page:          'Zwischen den Buchseiten befindet sich eine weitere, lose Buchseite. Entweder ist es ein Stück Papier, das jemand dazwischen gelegt hat, oder die Seite aus einem anderen Buch.',
  gem:           'Das Buch ist in einem sehr guten Zustand und mit Edelsteinen verziert (+10 % des Preises).',
  signature:     'Der Autor hat seine Signatur hinterlassen (+20 % des Preises).',
  comments:      'Irgendjemand, möglicherweise ein vorheriger Besitzer des Buches, hat viele Kommentare und Querverweise auf andere Bücher in das Buch geschrieben.',
  dirty:         'Flecken und Schwärzungen haben einen Teil des Textes unleserlich gemacht (-20 % des Preises).',
  wax:           'Die Seiten des Buches sind wachsbehandelt, um es gegen Feuchtigkeit zu schützen (+20 % des Preises).',
  decoration:    'Das Buch weist zahlreiche Verzierungen auf (+10 % des Preises).',
  different:     'Der Buchdeckel stimmt nicht mit dem Inhalt des Buches überein. Vielleicht hat jemand versucht, ein verbotenes oder indiziertes Buch zu verstecken.',
  burned:        'Brandspuren verunstalten das Buch (-10 % des Preises).',
  missingPages:  '1W20 Seiten des Buches wurden entfernt (-30 % des Preises).',
  noBinding:     'Der Einband des Buches ist abhandengekommen (-10 % des Preises).',
  wet:           'Durch Nässe sind Löcher in den Seiten entstanden (-20 % des Preises).',
  lock:          'Das Buch weist ein (zwergisches) Schloss auf. Es kann ohne Schlüssel nur mit einer Probe auf Schlösserknacken (Bartschlösser) -2/-5 (normal/zwergisch) geöffnet werden (+10/30 % (normal/zwergisch) des Preises).',
  worms:         'Bücherwürmer haben Löcher ins Buch gefressen (-20 % des Preises).',
  noVowels:      'Die Verfasserin des Buches hat, möglicherweise um Tinte und Papier zu sparen oder sich einen Scherz zu erlauben, alle Vokale ausgelassen. Um das Buch zu verstehen, benötigt man 25 % länger als üblich.',
  encrypted:     'Das Buch wurde kryptographisch verschlüsselt. Würfle mit 1W6: 1-2 primitive Verschlüsselung, 3-4 einfache Verschlüsselung, 5-6 komplexe Verschlüsselung.',
  missingM:      'Auf jeder Seite des Buches fehlt der Buchstabe M oder er wurde gegen eine 12 ersetzt. M ist der 13. Buchstabe des Alphabets und deshalb für einige Leute unglückverheißend.',
  noIllustration:'Alle Illustrationen wurden entfernt oder Seiten herausgerissen. Vermutlich wollte jemand einige Details zensieren (-10 % des Preises).',
  poison:        'Die Seiten des Buches sind teilweise mit Gift verunreinigt (z. B. Kelmon).',
  open:          'Das Buch lässt sich nur zu einer bestimmten Tageszeit, z. B. nachts öffnen. Auf ihm liegt ein OBJECTOFIXO-artiger Zauber gildenmagischen Ursprungs aus der Zeit der Großen Magierzunft.',
  demon:         'An das Buch ist ein niederer Dämon gebunden.',
  ghost:         'An das Buch ist ein Geist gebunden.',
  schelm:        'Alle Buchstaben verlaufen und tauchen danach wieder auf. Einige wechseln ihre Position oder die Schrift leuchtet, oder einzelne Buchstaben springen aus dem Buch. Der Leser kann das Buch deshalb nicht lesen. Die Magie, die auf dem Buch liegt, scheint schelmischen Ursprungs zu sein.',
  reader:        'Ein Zaubertrick wirkt auf dem Buch, sodass jede aufgeschlagene Seite von einer angenehmen Stimme vorgelesen wird.',
  xenographus:   'Auf dem Buch wirkt ein XENOGRAPHUS, sodass das Buch von jedem Leser verstanden werden kann.',
  memorans:      'Auf dem Buch liegt ein MEMORANS, der dafür sorgen soll, dass sich der Leser den Inhalt einprägt.',
  cryptogrpho:   'Das Buch ist durch einen CRYPTOGRAPHO gesichert.',
  mirrowed:      'Ein Zaubertrick hat dafür gesorgt, dass die Schrift spiegelverkehrt ist.',
  fireResistent: 'Zauber lassen das Buch feuerresistent werden. Die Magie scheint gildenmagischen Ursprungs zu sein.',
  custodosigil:  'Ein CUSTODOSIGIL liegt auf dem Werk.',
  protected:     'Ein Schutzzauber wird beim Öffnen des Werkes ausgelöst (1W6, je FW 16): PARALYSIS (1), CORPOFESSO (2), HORRIPHOBUS (3), FULMINICTUS (4), SALANDER (5), IGNISPHAERO (6). Nur, wer das Lösungswort kennt, kann das Buch unbeschadet öffnen.',
  oneTime:       'Sobald ein Text gelesen wurde, verschwindet er für immer.',
  memory:        'Auf dem Buch liegt ein ERINNERUNG VERLASSE DICH.',
};
